import type { PoliteiTable } from "@/types/tables";

export const tablesMockData: PoliteiTable[] = [
  {
    id: "ds_encuestas_2026",
    workspaceId: "ws_espana_2026",
    name: "Encuestas Electorales — Febrero-Mayo 2026",
    kind: "polling",
    view: "table",
    createdAt: "2026-02-01T00:00:00Z",
    updatedAt: "2026-05-13T06:00:00Z",
    tags: ["sondeos", "elecciones"],
    relatedIssueIds: ["iss_004"],
    columns: [
      { id: "c1", key: "partido",      label: "Partido",    type: "actor" },
      { id: "c2", key: "febrero",      label: "Feb 26",     type: "percentage" },
      { id: "c3", key: "marzo",        label: "Mar 26",     type: "percentage" },
      { id: "c4", key: "abril",        label: "Abr 26",     type: "percentage" },
      { id: "c5", key: "mayo",         label: "May 26",     type: "percentage" },
      { id: "c6", key: "delta",        label: "Δ Feb-May",  type: "trend" },
      { id: "c7", key: "escanos_est",  label: "Escaños est.", type: "seats" },
    ],
    rows: [
      { id: "r1", partido: "PP",    febrero: 33.2, marzo: 34.1, abril: 33.8, mayo: 34.5, delta:  1.3, escanos_est: 142 },
      { id: "r2", partido: "PSOE",  febrero: 28.4, marzo: 27.9, abril: 28.2, mayo: 27.6, delta: -0.8, escanos_est: 112 },
      { id: "r3", partido: "Vox",   febrero: 12.1, marzo: 11.8, abril: 12.3, mayo: 11.9, delta: -0.2, escanos_est:  45 },
      { id: "r4", partido: "Sumar", febrero: 10.2, marzo: 10.5, abril:  9.8, mayo: 10.1, delta: -0.1, escanos_est:  36 },
      { id: "r5", partido: "Junts", febrero:  3.8, marzo:  3.9, abril:  4.1, mayo:  4.0, delta:  0.2, escanos_est:  14 },
      { id: "r6", partido: "ERC",   febrero:  2.9, marzo:  2.7, abril:  2.8, mayo:  2.6, delta: -0.3, escanos_est:   9 },
    ],
  },
  {
    id: "ds_actores_leg",
    workspaceId: "ws_espana_2026",
    name: "Actores Legislativos Clave",
    kind: "actors",
    view: "table",
    createdAt: "2026-05-01T00:00:00Z",
    updatedAt: "2026-05-12T00:00:00Z",
    tags: ["actores", "legislativo"],
    relatedIssueIds: ["iss_002"],
    columns: [
      { id: "c1", key: "nombre",          label: "Actor",      type: "actor" },
      { id: "c2", key: "partido",         label: "Partido",    type: "tag" },
      { id: "c3", key: "comision",        label: "Comisión",   type: "text" },
      { id: "c4", key: "pos_ley_vivienda",label: "Pos. Vivienda", type: "status" },
      { id: "c5", key: "influencia",      label: "Influencia", type: "percentage" },
      { id: "c6", key: "riesgo",          label: "Riesgo",     type: "severity" },
    ],
    rows: [
      { id: "r1", nombre: "Carmen Villanueva", partido: "PP",    comision: "Economía",    pos_ley_vivienda: "against",      influencia: 88, riesgo: "high" },
      { id: "r2", nombre: "Pedro Marín",        partido: "PSOE",  comision: "Vivienda",    pos_ley_vivienda: "strongly_for", influencia: 92, riesgo: "low" },
      { id: "r3", nombre: "Aitana Rius",        partido: "Junts", comision: "Constitucional", pos_ley_vivienda: "neutral",   influencia: 71, riesgo: "high" },
      { id: "r4", nombre: "Sergi Vinyets",      partido: "Sumar", comision: "Trabajo",     pos_ley_vivienda: "strongly_for", influencia: 65, riesgo: "low" },
      { id: "r5", nombre: "Luis Arnedo",        partido: "Vox",   comision: "Interior",    pos_ley_vivienda: "strongly_against", influencia: 58, riesgo: "high" },
      { id: "r6", nombre: "Mireia Sols",        partido: "ERC",   comision: "Educación",   pos_ley_vivienda: "for",          influencia: 60, riesgo: "medium" },
      { id: "r7", nombre: "Andoni Esnaola",     partido: "PNV",   comision: "Defensa",     pos_ley_vivienda: "neutral",      influencia: 64, riesgo: "medium" },
      { id: "r8", nombre: "Elsa Carrera",       partido: "PP",    comision: "Sanidad",     pos_ley_vivienda: "against",      influencia: 55, riesgo: "medium" },
      { id: "r9", nombre: "Iván Berzal",        partido: "PSOE",  comision: "Industria",   pos_ley_vivienda: "for",          influencia: 70, riesgo: "low" },
      { id: "r10", nombre: "Olalla Mosquera",   partido: "Sumar", comision: "Igualdad",    pos_ley_vivienda: "strongly_for", influencia: 50, riesgo: "low" },
    ],
  },
  {
    id: "ds_seguimiento_leg",
    workspaceId: "ws_espana_2026",
    name: "Seguimiento Legislativo — Congreso 2026",
    kind: "legislative",
    view: "table",
    createdAt: "2026-05-01T00:00:00Z",
    updatedAt: "2026-05-12T00:00:00Z",
    tags: ["leyes", "congreso"],
    relatedIssueIds: ["iss_002", "iss_003"],
    columns: [
      { id: "c1", key: "titulo",        label: "Título",          type: "text" },
      { id: "c2", key: "fase",          label: "Fase",            type: "status" },
      { id: "c3", key: "partido",       label: "Promotor",        type: "actor" },
      { id: "c4", key: "fecha",         label: "Fecha votación",  type: "date" },
      { id: "c5", key: "posicion",      label: "Pos. propia",     type: "status" },
      { id: "c6", key: "riesgo",        label: "Riesgo",          type: "severity" },
    ],
    rows: [
      { id: "r1", titulo: "Ley de Vivienda 2026", fase: "in_progress", partido: "PSOE", fecha: "2026-05-20", posicion: "strongly_for", riesgo: "critical" },
      { id: "r2", titulo: "Reforma fiscal Sumar",  fase: "draft",       partido: "Sumar", fecha: "2026-06-15", posicion: "neutral",       riesgo: "medium" },
      { id: "r3", titulo: "Amnistía técnica",      fase: "published",   partido: "PSOE", fecha: "2026-04-30", posicion: "for",            riesgo: "high" },
      { id: "r4", titulo: "Ley telecomunicaciones",fase: "review",      partido: "PP",   fecha: "2026-06-05", posicion: "against",        riesgo: "medium" },
      { id: "r5", titulo: "Plan IA España",        fase: "in_progress", partido: "Sumar", fecha: "2026-07-10", posicion: "for",           riesgo: "low" },
      { id: "r6", titulo: "Ley pensiones 2027",    fase: "draft",       partido: "PSOE", fecha: "2026-09-01", posicion: "strongly_for",   riesgo: "high" },
      { id: "r7", titulo: "Reforma laboral fase 3",fase: "review",      partido: "PSOE", fecha: "2026-06-22", posicion: "for",            riesgo: "medium" },
      { id: "r8", titulo: "Marco regulación X",    fase: "published",   partido: "Junts", fecha: "2026-05-30", posicion: "against",       riesgo: "low" },
    ],
  },
  {
    id: "ds_riesgo_sectorial",
    workspaceId: "ws_espana_2026",
    name: "Monitor de Riesgo Regulatorio",
    kind: "risk",
    view: "table",
    createdAt: "2026-05-01T00:00:00Z",
    updatedAt: "2026-05-11T00:00:00Z",
    tags: ["riesgo", "regulación"],
    relatedIssueIds: [],
    columns: [
      { id: "c1", key: "area",        label: "Área",                 type: "text" },
      { id: "c2", key: "nivel",       label: "Nivel riesgo",         type: "severity" },
      { id: "c3", key: "tendencia",   label: "Tendencia",            type: "trend" },
      { id: "c4", key: "issues_rel",  label: "Issues relacionados",  type: "number" },
      { id: "c5", key: "fecha_clave", label: "Próxima fecha",        type: "date" },
    ],
    rows: [
      { id: "r1", area: "Vivienda",          nivel: "critical", tendencia:  2.3, issues_rel: 2, fecha_clave: "2026-05-20" },
      { id: "r2", area: "Energía",           nivel: "high",     tendencia:  0.8, issues_rel: 1, fecha_clave: "2026-06-12" },
      { id: "r3", area: "Banca",             nivel: "medium",   tendencia: -0.5, issues_rel: 0, fecha_clave: "2026-07-01" },
      { id: "r4", area: "Telecomunicaciones",nivel: "medium",   tendencia:  1.2, issues_rel: 1, fecha_clave: "2026-06-05" },
      { id: "r5", area: "Sanidad",           nivel: "low",      tendencia: -1.1, issues_rel: 0, fecha_clave: "2026-08-15" },
      { id: "r6", area: "Defensa",           nivel: "high",     tendencia:  0.4, issues_rel: 1, fecha_clave: "2026-06-25" },
    ],
  },
];
