import type { IntelligenceFeedState } from '@/types/intelligence-feed';

export const MOCK_FEED: IntelligenceFeedState = {
  ultima_sync: new Date().toISOString(),
  total_monitorizados_24h: 1847,
  breaking_activos: 3,
  clusters: [
    { id: 'cl-01', nombre: 'Crisis de coalición PSOE-Sumar', descripcion: 'Tensión interna por presupuestos', items_count: 234, intensidad: 92, tendencia: 'creciendo', primera_deteccion: new Date(Date.now() - 86400000 * 3).toISOString(), actores_principales: ['Pedro Sánchez', 'Yolanda Díaz'], medios_principales: ['El País', 'El Mundo'] },
    { id: 'cl-02', nombre: 'Caso Koldo: nuevas imputaciones', descripcion: 'Expansión de la causa judicial', items_count: 187, intensidad: 88, tendencia: 'creciendo', primera_deteccion: new Date(Date.now() - 86400000 * 7).toISOString(), actores_principales: ['José Luis Ábalos'], medios_principales: ['El Mundo', 'ABC'] },
    { id: 'cl-03', nombre: 'Ley de Amnistía y Tribunal Constitucional', descripcion: 'Recursos de inconstitucionalidad pendientes', items_count: 143, intensidad: 71, tendencia: 'estable', primera_deteccion: new Date(Date.now() - 86400000 * 14).toISOString(), actores_principales: ['TC', 'Junts'], medios_principales: ['La Razón', 'El Confidencial'] },
    { id: 'cl-04', nombre: 'Crisis de vivienda: protestas nacionales', descripcion: 'Movilización ciudadana en aumento', items_count: 98, intensidad: 64, tendencia: 'creciendo', primera_deteccion: new Date(Date.now() - 86400000 * 5).toISOString(), actores_principales: ['Plataformas vivienda'], medios_principales: ['elDiario.es', 'Público'] },
    { id: 'cl-05', nombre: 'Huelga transporte: sector en paro parcial', descripcion: 'Negociación colectiva fracasada', items_count: 67, intensidad: 55, tendencia: 'estable', primera_deteccion: new Date(Date.now() - 86400000 * 2).toISOString(), actores_principales: ['CCOO', 'UGT'], medios_principales: ['El Economista'] },
  ],
  signals: [
    { id: 's-01', titulo: 'Yolanda Díaz anuncia "línea roja" presupuestaria frente al PSOE', resumen: 'La vicepresidenta segunda fija límites a la negociación presupuestaria al rechazar los recortes en gasto social propuestos por el ala económica del PSOE. Sumar amenaza con votar en contra si no hay acuerdo en 72 horas.', fuente: 'El País', fuente_tipo: 'prensa_nacional', url: '#', publicado_en: new Date(Date.now() - 1800000).toISOString(), relevancia: 'breaking', tono: 'negativo', temas: ['Presupuestos', 'Coalición', 'Gasto social'], actores: ['Yolanda Díaz', 'Sumar', 'PSOE'], score_relevancia: 96, es_breaking: true, cluster_narrativo: 'cl-01' },
    { id: 's-02', titulo: 'Juez imputa a tres altos cargos del Ministerio del Interior en el Caso Koldo', resumen: 'El juzgado central número 6 de la Audiencia Nacional amplía la investigación a cargos del Ministerio del Interior con vínculos al entramado de comisiones irregulares. Se esperan más detenciones en los próximos días.', fuente: 'El Mundo', fuente_tipo: 'prensa_nacional', url: '#', publicado_en: new Date(Date.now() - 3600000).toISOString(), relevancia: 'breaking', tono: 'negativo', temas: ['Caso Koldo', 'Corrupción', 'Interior'], actores: ['Audiencia Nacional', 'Ministerio Interior'], score_relevancia: 94, es_breaking: true, cluster_narrativo: 'cl-02' },
    { id: 's-03', titulo: 'El TC suspende cautelarmente dos artículos clave de la Ley de Amnistía', resumen: 'El Tribunal Constitucional admite a trámite el recurso del PP y suspende provisionalmente los artículos relativos a los delitos de terrorismo. La medida pone en jaque el calendario político pactado con Junts.', fuente: 'La Razón', fuente_tipo: 'prensa_nacional', url: '#', publicado_en: new Date(Date.now() - 5400000).toISOString(), relevancia: 'breaking', tono: 'negativo', temas: ['TC', 'Amnistía', 'Junts'], actores: ['TC', 'PP', 'Junts'], score_relevancia: 91, es_breaking: true, cluster_narrativo: 'cl-03' },
    { id: 's-04', titulo: 'INE confirma inflación en el 2,3% en abril: tensión en negociación salarial', resumen: 'El dato de inflación de abril sorprende al alza y complica las negociaciones del convenio colectivo del transporte. Los sindicatos exigen una cláusula de revisión salarial automática vinculada al IPC real.', fuente: 'El Economista', fuente_tipo: 'prensa_nacional', url: '#', publicado_en: new Date(Date.now() - 7200000).toISOString(), relevancia: 'alta', tono: 'neutro', temas: ['Economía', 'Inflación', 'Negociación'], actores: ['INE', 'CCOO', 'UGT'], score_relevancia: 78, es_breaking: false, cluster_narrativo: 'cl-05' },
    { id: 's-05', titulo: 'Feijóo presiona al Gobierno con moción en el Senado sobre financiación autonómica', resumen: 'El Partido Popular registra una moción en el Senado para debatir el sistema de financiación autonómica y la situación de Catalunya. La iniciativa busca capitalizar el desgaste del ejecutivo ante las comunidades gobernadas por el PP.', fuente: 'ABC', fuente_tipo: 'prensa_nacional', url: '#', publicado_en: new Date(Date.now() - 9000000).toISOString(), relevancia: 'alta', tono: 'negativo', temas: ['PP', 'Senado', 'Financiación'], actores: ['Alberto Núñez Feijóo', 'PP', 'Senado'], score_relevancia: 74, es_breaking: false },
    { id: 's-06', titulo: 'Manifestación en Madrid reúne 50.000 personas por el derecho a la vivienda', resumen: 'La Plataforma por la Vivienda Digna convoca la mayor manifestación del año en Madrid con participación de sindicatos y partidos de izquierda. Los organizadores exigen una ley de contención de alquileres de emergencia.', fuente: 'elDiario.es', fuente_tipo: 'prensa_nacional', url: '#', publicado_en: new Date(Date.now() - 10800000).toISOString(), relevancia: 'alta', tono: 'neutro', temas: ['Vivienda', 'Manifestación', 'Alquiler'], actores: ['Plataforma Vivienda'], score_relevancia: 71, es_breaking: false, cluster_narrativo: 'cl-04' },
    { id: 's-07', titulo: 'Gobierno aprueba decreto de medidas urgentes contra la sequía en Cataluña', resumen: 'El Consejo de Ministros aprueba un paquete de 240 millones para actuaciones de emergencia ante la sequía en la cuenca del Ebro, con restricciones al regadío y apoyo a comunidades afectadas.', fuente: 'La Vanguardia', fuente_tipo: 'prensa_regional', url: '#', publicado_en: new Date(Date.now() - 14400000).toISOString(), relevancia: 'media', tono: 'neutro', temas: ['Sequía', 'Decreto', 'Medioambiente'], actores: ['Gobierno', 'Cataluña'], score_relevancia: 62, es_breaking: false },
    { id: 's-08', titulo: 'El PSOE celebra primarias internas para renovar liderazgos territoriales', resumen: 'El partido socialista convoca procesos de elección interna en seis federaciones territoriales. El proceso busca revitalizar la militancia y afrontar con renovados liderazgos el ciclo electoral autonómico.', fuente: 'Cadena SER', fuente_tipo: 'prensa_nacional', url: '#', publicado_en: new Date(Date.now() - 18000000).toISOString(), relevancia: 'media', tono: 'positivo', temas: ['PSOE', 'Primarias', 'Interno'], actores: ['PSOE'], score_relevancia: 55, es_breaking: false },
  ],
};
