"""Catálogo de 350 fuentes de medios internacionales con coordenadas geográficas.

Organizado en 7 regiones: local_spain, regional_spain, europe, north_america,
latin_america, africa, asia — 50 fuentes cada una.
"""
from __future__ import annotations

MEDIA_SOURCES: dict[str, list[dict]] = {

    # ── 1. MEDIOS LOCALES ESPAÑA (50) ──────────────────────────────────────
    "local_spain": [
        {"name": "El País",         "url": "https://elpais.com",         "rss": "https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/portada",        "region": "local_spain", "country": "Spain", "lat": 40.4168, "lon": -3.7038},
        {"name": "El Mundo",        "url": "https://elmundo.es",         "rss": "https://e00-elmundo.uecdn.es/elmundo/rss/portada.xml",                    "region": "local_spain", "country": "Spain", "lat": 40.4168, "lon": -3.7038},
        {"name": "ABC",             "url": "https://abc.es",             "rss": "https://www.abc.es/rss/feeds/abc_EspanaEspana.xml",                       "region": "local_spain", "country": "Spain", "lat": 40.4168, "lon": -3.7038},
        {"name": "El Confidencial", "url": "https://elconfidencial.com", "rss": "https://rss.elconfidencial.com/espana/",                                  "region": "local_spain", "country": "Spain", "lat": 40.4168, "lon": -3.7038},
        {"name": "La Vanguardia",   "url": "https://lavanguardia.com",   "rss": "https://www.lavanguardia.com/mvc/feed/rss/home.xml",                      "region": "local_spain", "country": "Spain", "lat": 41.3851, "lon": 2.1734},
        {"name": "El Español",      "url": "https://elespanol.com",      "rss": "https://www.elespanol.com/rss/",                                          "region": "local_spain", "country": "Spain", "lat": 40.4168, "lon": -3.7038},
        {"name": "Público",         "url": "https://publico.es",         "rss": "https://www.publico.es/rss/",                                             "region": "local_spain", "country": "Spain", "lat": 40.4168, "lon": -3.7038},
        {"name": "infoLibre",       "url": "https://infolibre.es",       "rss": "https://www.infolibre.es/rss/",                                           "region": "local_spain", "country": "Spain", "lat": 40.4168, "lon": -3.7038},
        {"name": "20 Minutos",      "url": "https://20minutos.es",       "rss": "https://www.20minutos.es/rss/",                                           "region": "local_spain", "country": "Spain", "lat": 40.4168, "lon": -3.7038},
        {"name": "El Diario",       "url": "https://eldiario.es",        "rss": "https://www.eldiario.es/rss/",                                            "region": "local_spain", "country": "Spain", "lat": 40.4168, "lon": -3.7038},
        {"name": "Expansión",       "url": "https://expansion.com",      "rss": "https://e00-expansion.uecdn.es/rss/portada.xml",                          "region": "local_spain", "country": "Spain", "lat": 40.4168, "lon": -3.7038},
        {"name": "El Economista",   "url": "https://eleconomista.es",    "rss": "https://www.eleconomista.es/rss/rss-portada.php",                         "region": "local_spain", "country": "Spain", "lat": 40.4168, "lon": -3.7038},
        {"name": "Cinco Días",      "url": "https://cincodias.elpais.com","rss": "https://cincodias.elpais.com/rss/feeds/cincodias.xml",                   "region": "local_spain", "country": "Spain", "lat": 40.4168, "lon": -3.7038},
        {"name": "El HuffPost",     "url": "https://huffingtonpost.es",  "rss": "https://www.huffingtonpost.es/feeds/index.xml",                           "region": "local_spain", "country": "Spain", "lat": 40.4168, "lon": -3.7038},
        {"name": "Vozpópuli",       "url": "https://vozpopuli.com",      "rss": "https://vozpopuli.com/feed/",                                             "region": "local_spain", "country": "Spain", "lat": 40.4168, "lon": -3.7038},
        {"name": "OK Diario",       "url": "https://okdiario.com",       "rss": "https://okdiario.com/feed",                                               "region": "local_spain", "country": "Spain", "lat": 40.4168, "lon": -3.7038},
        {"name": "La Razón",        "url": "https://larazon.es",         "rss": "https://www.larazon.es/rss/",                                             "region": "local_spain", "country": "Spain", "lat": 40.4168, "lon": -3.7038},
        {"name": "Periodista Digital","url": "https://periodistadigital.com","rss": "https://www.periodistadigital.com/feed/",                             "region": "local_spain", "country": "Spain", "lat": 40.4168, "lon": -3.7038},
        {"name": "El Plural",       "url": "https://elplural.com",       "rss": "https://www.elplural.com/feed/",                                          "region": "local_spain", "country": "Spain", "lat": 40.4168, "lon": -3.7038},
        {"name": "Nueva Tribuna",   "url": "https://nuevatribuna.es",    "rss": "https://www.nuevatribuna.es/rss/",                                        "region": "local_spain", "country": "Spain", "lat": 40.4168, "lon": -3.7038},
        {"name": "Diario Libre",    "url": "https://diariolibre.com",    "rss": "https://diariolibre.com/feed/",                                           "region": "local_spain", "country": "Spain", "lat": 40.4168, "lon": -3.7038},
        {"name": "El Toro de Wall St.","url": "https://eltoro.com",      "rss": "https://eltoro.com/feed/",                                                "region": "local_spain", "country": "Spain", "lat": 40.4168, "lon": -3.7038},
        {"name": "Bolsamanía",      "url": "https://bolsamania.com",     "rss": "https://www.bolsamania.com/noticias/feed/",                               "region": "local_spain", "country": "Spain", "lat": 40.4168, "lon": -3.7038},
        {"name": "El Nacional",     "url": "https://elnacional.cat",     "rss": "https://www.elnacional.cat/feed/",                                        "region": "local_spain", "country": "Spain", "lat": 41.3851, "lon": 2.1734},
        {"name": "Nació Digital",   "url": "https://naciodigital.cat",   "rss": "https://www.naciodigital.cat/rss.xml",                                    "region": "local_spain", "country": "Spain", "lat": 41.3851, "lon": 2.1734},
        {"name": "VilaWeb",         "url": "https://vilaweb.cat",        "rss": "https://www.vilaweb.cat/rss.xml",                                         "region": "local_spain", "country": "Spain", "lat": 41.3851, "lon": 2.1734},
        {"name": "Crónica Global",  "url": "https://cronicaglobal.elespanol.com","rss": "https://cronicaglobal.elespanol.com/rss/",                        "region": "local_spain", "country": "Spain", "lat": 41.3851, "lon": 2.1734},
        {"name": "El Periódico",    "url": "https://elperiodico.com",    "rss": "https://www.elperiodico.com/es/rss/rss_portada.xml",                      "region": "local_spain", "country": "Spain", "lat": 41.3851, "lon": 2.1734},
        {"name": "Ara",             "url": "https://ara.cat",            "rss": "https://www.ara.cat/rss.xml",                                             "region": "local_spain", "country": "Spain", "lat": 41.3851, "lon": 2.1734},
        {"name": "El Correo",       "url": "https://elcorreo.com",       "rss": "https://www.elcorreo.com/rss/feeds/portada.xml",                          "region": "local_spain", "country": "Spain", "lat": 43.2627, "lon": -2.9253},
        {"name": "Deia",            "url": "https://deia.eus",           "rss": "https://www.deia.eus/rss/feeds/portada.xml",                              "region": "local_spain", "country": "Spain", "lat": 43.2627, "lon": -2.9253},
        {"name": "Noticias de Navarra","url": "https://noticiasdenavarra.com","rss": "https://www.noticiasdenavarra.com/rss/",                             "region": "local_spain", "country": "Spain", "lat": 42.6954, "lon": -1.6761},
        {"name": "El Diario Vasco", "url": "https://diariovasco.com",    "rss": "https://www.diariovasco.com/rss/feeds/portada.xml",                       "region": "local_spain", "country": "Spain", "lat": 43.3183, "lon": -1.9812},
        {"name": "La Nueva España", "url": "https://lne.es",             "rss": "https://www.lne.es/rss/feeds/portada.xml",                                "region": "local_spain", "country": "Spain", "lat": 43.3602, "lon": -5.8448},
        {"name": "El Comercio",     "url": "https://elcomercio.es",      "rss": "https://www.elcomercio.es/rss/feeds/portada.xml",                         "region": "local_spain", "country": "Spain", "lat": 43.5322, "lon": -5.6613},
        {"name": "La Voz de Galicia","url": "https://lavozdegalicia.es", "rss": "https://www.lavozdegalicia.es/rss/portada.xml",                           "region": "local_spain", "country": "Spain", "lat": 43.3623, "lon": -8.4115},
        {"name": "Faro de Vigo",    "url": "https://farodevigo.es",      "rss": "https://www.farodevigo.es/rss/feeds/portada.xml",                         "region": "local_spain", "country": "Spain", "lat": 42.2328, "lon": -8.7226},
        {"name": "Galicia Confidencial","url": "https://galiciaconfidencial.com","rss": "https://www.galiciaconfidencial.com/feed/",                       "region": "local_spain", "country": "Spain", "lat": 42.8782, "lon": -8.5448},
        {"name": "Hoy Extremadura", "url": "https://hoy.es",             "rss": "https://www.hoy.es/rss/feeds/portada.xml",                                "region": "local_spain", "country": "Spain", "lat": 38.9159, "lon": -6.3413},
        {"name": "El Día de Córdoba","url": "https://eldiadecordoba.es", "rss": "https://www.eldiadecordoba.es/rss/feeds/portada.xml",                     "region": "local_spain", "country": "Spain", "lat": 37.8882, "lon": -4.7794},
        {"name": "Málaga Hoy",      "url": "https://malagahoy.es",       "rss": "https://www.malagahoy.es/rss/feeds/portada.xml",                          "region": "local_spain", "country": "Spain", "lat": 36.7213, "lon": -4.4214},
        {"name": "Granada Hoy",     "url": "https://granadahoy.com",     "rss": "https://www.granadahoy.com/rss/feeds/portada.xml",                        "region": "local_spain", "country": "Spain", "lat": 37.1773, "lon": -3.5986},
        {"name": "Diario de Sevilla","url": "https://diariodesevilla.es","rss": "https://www.diariodesevilla.es/rss/feeds/portada.xml",                    "region": "local_spain", "country": "Spain", "lat": 37.3891, "lon": -5.9845},
        {"name": "Europa Sur",      "url": "https://europasur.es",       "rss": "https://www.europasur.es/rss/feeds/portada.xml",                          "region": "local_spain", "country": "Spain", "lat": 36.1408, "lon": -5.4530},
        {"name": "Las Provincias",  "url": "https://lasprovincias.es",   "rss": "https://www.lasprovincias.es/rss/feeds/portada.xml",                      "region": "local_spain", "country": "Spain", "lat": 39.4699, "lon": -0.3763},
        {"name": "Levante EMV",     "url": "https://levante-emv.com",    "rss": "https://www.levante-emv.com/rss/feeds/portada.xml",                       "region": "local_spain", "country": "Spain", "lat": 39.4699, "lon": -0.3763},
        {"name": "Información Alicante","url": "https://diarioinformacion.com","rss": "https://www.diarioinformacion.com/rss/feeds/portada.xml",           "region": "local_spain", "country": "Spain", "lat": 38.3452, "lon": -0.4810},
        {"name": "La Tribuna Albacete","url": "https://latribunadealbacete.es","rss": "https://www.latribunadealbacete.es/rss/feeds/portada.xml",          "region": "local_spain", "country": "Spain", "lat": 38.9942, "lon": -1.8564},
        {"name": "Heraldo de Aragón","url": "https://heraldo.es",        "rss": "https://www.heraldo.es/rss/portada.xml",                                  "region": "local_spain", "country": "Spain", "lat": 41.6488, "lon": -0.8891},
        {"name": "Diario de Mallorca","url": "https://diariodemallorca.es","rss": "https://www.diariodemallorca.es/rss/feeds/portada.xml",                 "region": "local_spain", "country": "Spain", "lat": 39.5696, "lon": 2.6502},
    ],

    # ── 2. MEDIOS REGIONALES / ESPECIALIZADOS ESPAÑA (50) ──────────────────
    "regional_spain": [
        {"name": "El Salto Diario",   "url": "https://elsaltodiario.com",  "rss": "https://www.elsaltodiario.com/feed/",                           "region": "regional_spain", "country": "Spain", "lat": 40.4168, "lon": -3.7038},
        {"name": "Ctxt Contexto",     "url": "https://ctxt.es",            "rss": "https://ctxt.es/rss",                                           "region": "regional_spain", "country": "Spain", "lat": 40.4168, "lon": -3.7038},
        {"name": "La Marea",          "url": "https://lamarea.com",        "rss": "https://www.lamarea.com/feed/",                                 "region": "regional_spain", "country": "Spain", "lat": 40.4168, "lon": -3.7038},
        {"name": "Climática",         "url": "https://climatica.coop",     "rss": "https://climatica.coop/feed/",                                  "region": "regional_spain", "country": "Spain", "lat": 40.4168, "lon": -3.7038},
        {"name": "Pikara Magazine",   "url": "https://pikaramagazine.com", "rss": "https://www.pikaramagazine.com/feed/",                          "region": "regional_spain", "country": "Spain", "lat": 43.2627, "lon": -2.9253},
        {"name": "Naiz",              "url": "https://naiz.eus",           "rss": "https://www.naiz.eus/eu/actualidad/rss",                        "region": "regional_spain", "country": "Spain", "lat": 43.2627, "lon": -2.9253},
        {"name": "Berria",            "url": "https://berria.eus",         "rss": "https://www.berria.eus/rss.xml",                                "region": "regional_spain", "country": "Spain", "lat": 43.2627, "lon": -2.9253},
        {"name": "Hordago",           "url": "https://hordago.eus",        "rss": "https://hordago.eus/feed/",                                     "region": "regional_spain", "country": "Spain", "lat": 43.2627, "lon": -2.9253},
        {"name": "Praza Pública",     "url": "https://praza.gal",          "rss": "https://praza.gal/feed/",                                       "region": "regional_spain", "country": "Spain", "lat": 42.8782, "lon": -8.5448},
        {"name": "GCiencia",          "url": "https://gciencia.gal",       "rss": "https://gciencia.gal/feed/",                                    "region": "regional_spain", "country": "Spain", "lat": 42.8782, "lon": -8.5448},
        {"name": "Diario de Ibiza",   "url": "https://diariodeibiza.es",   "rss": "https://www.diariodeibiza.es/rss/feeds/portada.xml",            "region": "regional_spain", "country": "Spain", "lat": 38.9067, "lon": 1.4206},
        {"name": "Diario de Menorca", "url": "https://menorca.info",       "rss": "https://www.menorca.info/rss/feeds/portada.xml",                "region": "regional_spain", "country": "Spain", "lat": 39.9494, "lon": 4.1200},
        {"name": "La Palma Ahora",    "url": "https://lapalmahora.es",     "rss": "https://lapalmahora.es/feed/",                                  "region": "regional_spain", "country": "Spain", "lat": 28.6835, "lon": -17.7642},
        {"name": "Canarias 7",        "url": "https://canarias7.es",       "rss": "https://www.canarias7.es/rss/feeds/portada.xml",                "region": "regional_spain", "country": "Spain", "lat": 28.1235, "lon": -15.4363},
        {"name": "El Día Canarias",   "url": "https://eldia.es",           "rss": "https://www.eldia.es/rss/feeds/portada.xml",                    "region": "regional_spain", "country": "Spain", "lat": 28.4636, "lon": -16.2518},
        {"name": "La Opinión Murcia", "url": "https://laopiniondemurcia.es","rss": "https://www.laopiniondemurcia.es/rss/feeds/portada.xml",       "region": "regional_spain", "country": "Spain", "lat": 37.9922, "lon": -1.1307},
        {"name": "La Verdad Murcia",  "url": "https://laverdad.es",        "rss": "https://www.laverdad.es/rss/feeds/portada.xml",                 "region": "regional_spain", "country": "Spain", "lat": 37.9922, "lon": -1.1307},
        {"name": "Ideal Granada",     "url": "https://ideal.es",           "rss": "https://www.ideal.es/rss/feeds/portada.xml",                    "region": "regional_spain", "country": "Spain", "lat": 37.1773, "lon": -3.5986},
        {"name": "Sur Málaga",        "url": "https://diariosur.es",       "rss": "https://www.diariosur.es/rss/feeds/portada.xml",                "region": "regional_spain", "country": "Spain", "lat": 36.7213, "lon": -4.4214},
        {"name": "ABC Sevilla",       "url": "https://sevilla.abc.es",     "rss": "https://sevilla.abc.es/rss/",                                   "region": "regional_spain", "country": "Spain", "lat": 37.3891, "lon": -5.9845},
        {"name": "Jornada Deportiva", "url": "https://jornada.es",         "rss": "https://www.jornada.es/feed/",                                  "region": "regional_spain", "country": "Spain", "lat": 40.4168, "lon": -3.7038},
        {"name": "Marca",             "url": "https://marca.com",          "rss": "https://e00-marca.uecdn.es/rss/portada.xml",                    "region": "regional_spain", "country": "Spain", "lat": 40.4168, "lon": -3.7038},
        {"name": "AS Deportes",       "url": "https://as.com",             "rss": "https://feeds.as.com/mrss-s/pages/as/site/as.com/portada/",     "region": "regional_spain", "country": "Spain", "lat": 40.4168, "lon": -3.7038},
        {"name": "Sport",             "url": "https://sport.es",           "rss": "https://www.sport.es/rss/portada.xml",                          "region": "regional_spain", "country": "Spain", "lat": 41.3851, "lon": 2.1734},
        {"name": "Mundo Deportivo",   "url": "https://mundodeportivo.com", "rss": "https://www.mundodeportivo.com/mvc/feed/rss/home.xml",          "region": "regional_spain", "country": "Spain", "lat": 41.3851, "lon": 2.1734},
        {"name": "Cuatro TV",         "url": "https://cuatro.com",         "rss": "https://www.cuatro.com/rss/",                                   "region": "regional_spain", "country": "Spain", "lat": 40.4168, "lon": -3.7038},
        {"name": "Antena 3 Noticias", "url": "https://antena3.com",        "rss": "https://www.antena3.com/rss/",                                  "region": "regional_spain", "country": "Spain", "lat": 40.4168, "lon": -3.7038},
        {"name": "RTVE Noticias",     "url": "https://rtve.es",            "rss": "https://api2.rtve.es/rss/temas/noticias.xml",                   "region": "regional_spain", "country": "Spain", "lat": 40.4168, "lon": -3.7038},
        {"name": "Cope",              "url": "https://cope.es",            "rss": "https://www.cope.es/rss",                                       "region": "regional_spain", "country": "Spain", "lat": 40.4168, "lon": -3.7038},
        {"name": "Cadena Ser",        "url": "https://cadenaser.com",      "rss": "https://cadenaser.com/rss/portada/",                            "region": "regional_spain", "country": "Spain", "lat": 40.4168, "lon": -3.7038},
        {"name": "Onda Cero",         "url": "https://ondacero.es",        "rss": "https://www.ondacero.es/rss/",                                  "region": "regional_spain", "country": "Spain", "lat": 40.4168, "lon": -3.7038},
        {"name": "EsRadio",           "url": "https://esradio.libertaddigital.com","rss": "https://esradio.libertaddigital.com/rss/",              "region": "regional_spain", "country": "Spain", "lat": 40.4168, "lon": -3.7038},
        {"name": "Libertad Digital",  "url": "https://libertaddigital.com","rss": "https://www.libertaddigital.com/rss/portada.xml",               "region": "regional_spain", "country": "Spain", "lat": 40.4168, "lon": -3.7038},
        {"name": "Hazte Oír",         "url": "https://hazteoir.org",       "rss": "https://hazteoir.org/feed/",                                    "region": "regional_spain", "country": "Spain", "lat": 40.4168, "lon": -3.7038},
        {"name": "Religión en Libertad","url": "https://religionenlibertad.com","rss": "https://www.religionenlibertad.com/feed/",                "region": "regional_spain", "country": "Spain", "lat": 40.4168, "lon": -3.7038},
        {"name": "El Debate",         "url": "https://eldebate.com",       "rss": "https://www.eldebate.com/rss/",                                 "region": "regional_spain", "country": "Spain", "lat": 40.4168, "lon": -3.7038},
        {"name": "Diario Crítico",    "url": "https://diariocritico.com",  "rss": "https://www.diariocritico.com/feed/",                           "region": "regional_spain", "country": "Spain", "lat": 40.4168, "lon": -3.7038},
        {"name": "Tercera Información","url": "https://tercerainformacion.es","rss": "https://www.tercerainformacion.es/feed/",                    "region": "regional_spain", "country": "Spain", "lat": 40.4168, "lon": -3.7038},
        {"name": "Kaos en la Red",    "url": "https://kaosenlared.net",    "rss": "https://kaosenlared.net/feed/",                                 "region": "regional_spain", "country": "Spain", "lat": 40.4168, "lon": -3.7038},
        {"name": "Rebelión",          "url": "https://rebelion.org",       "rss": "https://rebelion.org/feed/",                                    "region": "regional_spain", "country": "Spain", "lat": 40.4168, "lon": -3.7038},
        {"name": "Mundo Obrero",      "url": "https://mundoobrero.es",     "rss": "https://mundoobrero.es/feed/",                                  "region": "regional_spain", "country": "Spain", "lat": 40.4168, "lon": -3.7038},
        {"name": "Diagonal",          "url": "https://diagonalperiodico.net","rss": "https://diagonalperiodico.net/feed/",                        "region": "regional_spain", "country": "Spain", "lat": 40.4168, "lon": -3.7038},
        {"name": "Sin Permiso",       "url": "https://sinpermiso.info",    "rss": "https://sinpermiso.info/feed/",                                 "region": "regional_spain", "country": "Spain", "lat": 40.4168, "lon": -3.7038},
        {"name": "Fundación FAES",    "url": "https://fundacionfaes.org", "rss": "https://www.fundacionfaes.org/rss/",                            "region": "regional_spain", "country": "Spain", "lat": 40.4168, "lon": -3.7038},
        {"name": "El Mundo Financiero","url": "https://elmundofinanciero.com","rss": "https://www.elmundofinanciero.com/feed/",                   "region": "regional_spain", "country": "Spain", "lat": 40.4168, "lon": -3.7038},
        {"name": "Business Insider ES","url": "https://businessinsider.es","rss": "https://www.businessinsider.es/feed/",                         "region": "regional_spain", "country": "Spain", "lat": 40.4168, "lon": -3.7038},
        {"name": "Forbes España",     "url": "https://forbes.es",          "rss": "https://www.forbes.es/feed/",                                   "region": "regional_spain", "country": "Spain", "lat": 40.4168, "lon": -3.7038},
        {"name": "Xataka",            "url": "https://xataka.com",         "rss": "https://feeds.weblogssl.com/xataka/",                           "region": "regional_spain", "country": "Spain", "lat": 40.4168, "lon": -3.7038},
        {"name": "Maldita.es",        "url": "https://maldita.es",         "rss": "https://maldita.es/feed/",                                      "region": "regional_spain", "country": "Spain", "lat": 40.4168, "lon": -3.7038},
        {"name": "Newtral",           "url": "https://newtral.es",         "rss": "https://www.newtral.es/feed/",                                  "region": "regional_spain", "country": "Spain", "lat": 40.4168, "lon": -3.7038},
    ],

    # ── 3. MEDIOS EUROPEOS (50) ─────────────────────────────────────────────
    "europe": [
        {"name": "BBC News",          "url": "https://bbc.com/news",       "rss": "https://feeds.bbci.co.uk/news/rss.xml",                         "region": "europe", "country": "UK",      "lat": 51.5074, "lon": -0.1278},
        {"name": "The Guardian",      "url": "https://theguardian.com",    "rss": "https://www.theguardian.com/world/rss",                         "region": "europe", "country": "UK",      "lat": 51.5074, "lon": -0.1278},
        {"name": "The Times",         "url": "https://thetimes.co.uk",     "rss": "https://www.thetimes.co.uk/rss/",                               "region": "europe", "country": "UK",      "lat": 51.5074, "lon": -0.1278},
        {"name": "The Independent",   "url": "https://independent.co.uk",  "rss": "https://www.independent.co.uk/news/rss",                        "region": "europe", "country": "UK",      "lat": 51.5074, "lon": -0.1278},
        {"name": "Financial Times",   "url": "https://ft.com",             "rss": "https://www.ft.com/rss/home/uk",                                "region": "europe", "country": "UK",      "lat": 51.5074, "lon": -0.1278},
        {"name": "The Economist",     "url": "https://economist.com",      "rss": "https://www.economist.com/feeds/print-edition/",                "region": "europe", "country": "UK",      "lat": 51.5074, "lon": -0.1278},
        {"name": "Le Monde",          "url": "https://lemonde.fr",         "rss": "https://www.lemonde.fr/rss/une.xml",                            "region": "europe", "country": "France",  "lat": 48.8566, "lon": 2.3522},
        {"name": "Le Figaro",         "url": "https://lefigaro.fr",        "rss": "https://www.lefigaro.fr/rss/figaro_actualites.xml",             "region": "europe", "country": "France",  "lat": 48.8566, "lon": 2.3522},
        {"name": "Libération",        "url": "https://liberation.fr",      "rss": "https://www.liberation.fr/arc/outboundfeeds/rss/?outputType=xml","region": "europe", "country": "France",  "lat": 48.8566, "lon": 2.3522},
        {"name": "France 24",         "url": "https://france24.com",       "rss": "https://www.france24.com/es/rss",                               "region": "europe", "country": "France",  "lat": 48.8566, "lon": 2.3522},
        {"name": "Der Spiegel",       "url": "https://spiegel.de",         "rss": "https://www.spiegel.de/schlagzeilen/index.rss",                 "region": "europe", "country": "Germany", "lat": 52.5200, "lon": 13.4050},
        {"name": "Frankfurter Allgemeine","url": "https://faz.net",        "rss": "https://www.faz.net/rss/aktuell/",                              "region": "europe", "country": "Germany", "lat": 50.1109, "lon": 8.6821},
        {"name": "Die Zeit",          "url": "https://zeit.de",            "rss": "https://newsfeed.zeit.de/index",                                "region": "europe", "country": "Germany", "lat": 53.5753, "lon": 10.0153},
        {"name": "Deutsche Welle",    "url": "https://dw.com",             "rss": "https://rss.dw.com/xml/rss-en-all",                            "region": "europe", "country": "Germany", "lat": 50.7374, "lon": 7.0982},
        {"name": "Handelsblatt",      "url": "https://handelsblatt.com",   "rss": "https://www.handelsblatt.com/contentexport/feed/top-themen",   "region": "europe", "country": "Germany", "lat": 52.5200, "lon": 13.4050},
        {"name": "La Repubblica",     "url": "https://repubblica.it",      "rss": "https://www.repubblica.it/rss/homepage/rss2.0.xml",             "region": "europe", "country": "Italy",   "lat": 41.9028, "lon": 12.4964},
        {"name": "Corriere della Sera","url": "https://corriere.it",       "rss": "https://xml2.corriereobjects.it/rss/homepage.xml",              "region": "europe", "country": "Italy",   "lat": 45.4654, "lon": 9.1859},
        {"name": "Il Sole 24 Ore",    "url": "https://ilsole24ore.com",    "rss": "https://www.ilsole24ore.com/rss/mondo.xml",                     "region": "europe", "country": "Italy",   "lat": 45.4654, "lon": 9.1859},
        {"name": "Ansa",              "url": "https://ansa.it",            "rss": "https://www.ansa.it/sito/ansait_rss.xml",                       "region": "europe", "country": "Italy",   "lat": 41.9028, "lon": 12.4964},
        {"name": "El Corriere",       "url": "https://corriere.it",        "rss": "https://xml2.corriereobjects.it/rss/politica.xml",              "region": "europe", "country": "Italy",   "lat": 45.4654, "lon": 9.1859},
        {"name": "Politico Europe",   "url": "https://politico.eu",        "rss": "https://www.politico.eu/feed/",                                 "region": "europe", "country": "Belgium", "lat": 50.8503, "lon": 4.3517},
        {"name": "EUobserver",        "url": "https://euobserver.com",     "rss": "https://euobserver.com/rss.xml",                                "region": "europe", "country": "Belgium", "lat": 50.8503, "lon": 4.3517},
        {"name": "EURACTIV",          "url": "https://euractiv.com",       "rss": "https://www.euractiv.com/sections/eu-politics/feed/",           "region": "europe", "country": "Belgium", "lat": 50.8503, "lon": 4.3517},
        {"name": "De Morgen",         "url": "https://demorgen.be",        "rss": "https://www.demorgen.be/rss.xml",                               "region": "europe", "country": "Belgium", "lat": 50.8503, "lon": 4.3517},
        {"name": "NRC Handelsblad",   "url": "https://nrc.nl",             "rss": "https://www.nrc.nl/rss/",                                       "region": "europe", "country": "Netherlands","lat": 52.3676, "lon": 4.9041},
        {"name": "De Volkskrant",     "url": "https://volkskrant.nl",      "rss": "https://www.volkskrant.nl/rss.xml",                             "region": "europe", "country": "Netherlands","lat": 52.3676, "lon": 4.9041},
        {"name": "Público Portugal",  "url": "https://publico.pt",         "rss": "https://feeds.feedburner.com/PublicoPt",                        "region": "europe", "country": "Portugal","lat": 38.7223, "lon": -9.1393},
        {"name": "Expresso",          "url": "https://expresso.pt",        "rss": "https://expresso.pt/rss",                                       "region": "europe", "country": "Portugal","lat": 38.7223, "lon": -9.1393},
        {"name": "Observador",        "url": "https://observador.pt",      "rss": "https://observador.pt/feed/",                                   "region": "europe", "country": "Portugal","lat": 38.7223, "lon": -9.1393},
        {"name": "El Periódico Andorra","url": "https://elperiodicodeandorra.ad","rss": "https://www.elperiodicodeandorra.ad/rss/",                "region": "europe", "country": "Andorra", "lat": 42.5063, "lon": 1.5218},
        {"name": "SRF News",          "url": "https://srf.ch/news",        "rss": "https://www.srf.ch/news/bnf/rss/1646",                          "region": "europe", "country": "Switzerland","lat": 47.3769, "lon": 8.5417},
        {"name": "NZZ",               "url": "https://nzz.ch",             "rss": "https://www.nzz.ch/news.rss",                                   "region": "europe", "country": "Switzerland","lat": 47.3769, "lon": 8.5417},
        {"name": "APA Austria",       "url": "https://apa.at",             "rss": "https://www.apa.at/rss/",                                       "region": "europe", "country": "Austria", "lat": 48.2082, "lon": 16.3738},
        {"name": "Der Standard",      "url": "https://derstandard.at",     "rss": "https://derstandard.at/?page=rss&ressort=Inland",               "region": "europe", "country": "Austria", "lat": 48.2082, "lon": 16.3738},
        {"name": "Hospodářské noviny","url": "https://hn.cz",             "rss": "https://hn.cz/rss/",                                            "region": "europe", "country": "Czechia", "lat": 50.0755, "lon": 14.4378},
        {"name": "Gazeta Wyborcza",   "url": "https://wyborcza.pl",        "rss": "https://wyborcza.pl/rss/wyborcza.xml",                          "region": "europe", "country": "Poland",  "lat": 52.2297, "lon": 21.0122},
        {"name": "TVN24 Polska",      "url": "https://tvn24.pl",           "rss": "https://tvn24.pl/najnowsze.xml",                                "region": "europe", "country": "Poland",  "lat": 52.2297, "lon": 21.0122},
        {"name": "Magyar Narancs",    "url": "https://magyarnarancs.hu",   "rss": "https://magyarnarancs.hu/rss",                                  "region": "europe", "country": "Hungary", "lat": 47.4979, "lon": 19.0402},
        {"name": "Népszava",          "url": "https://nepszava.hu",        "rss": "https://nepszava.hu/rss",                                       "region": "europe", "country": "Hungary", "lat": 47.4979, "lon": 19.0402},
        {"name": "SME Slovakia",      "url": "https://sme.sk",             "rss": "https://www.sme.sk/rss",                                        "region": "europe", "country": "Slovakia","lat": 48.1486, "lon": 17.1077},
        {"name": "Aktuality SK",      "url": "https://aktuality.sk",       "rss": "https://www.aktuality.sk/rss/top/",                             "region": "europe", "country": "Slovakia","lat": 48.1486, "lon": 17.1077},
        {"name": "Aftonbladet",       "url": "https://aftonbladet.se",     "rss": "https://rss.aftonbladet.se/rss2/small/pages/sections/senastenytt/",  "region": "europe", "country": "Sweden",  "lat": 59.3293, "lon": 18.0686},
        {"name": "Expressen",         "url": "https://expressen.se",       "rss": "https://www.expressen.se/rss/",                                 "region": "europe", "country": "Sweden",  "lat": 59.3293, "lon": 18.0686},
        {"name": "VG Norge",          "url": "https://vg.no",              "rss": "https://www.vg.no/rss/feed/?categories=1068",                   "region": "europe", "country": "Norway",  "lat": 59.9139, "lon": 10.7522},
        {"name": "Dagbladet",         "url": "https://dagbladet.no",       "rss": "https://www.dagbladet.no/feed",                                 "region": "europe", "country": "Norway",  "lat": 59.9139, "lon": 10.7522},
        {"name": "Yle Finland",       "url": "https://yle.fi",             "rss": "https://feeds.yle.fi/uutiset/v1/recent.rss?publisherIds=YLE_UUTISET","region": "europe", "country": "Finland","lat": 60.1699, "lon": 24.9384},
        {"name": "Postimees",         "url": "https://postimees.ee",       "rss": "https://www.postimees.ee/rss",                                  "region": "europe", "country": "Estonia", "lat": 59.4370, "lon": 24.7536},
        {"name": "Delfi Lithuania",   "url": "https://delfi.lt",           "rss": "https://www.delfi.lt/rss/feeds/news.xml",                       "region": "europe", "country": "Lithuania","lat": 54.6872, "lon": 25.2797},
        {"name": "TVNET Latvia",      "url": "https://tvnet.lv",           "rss": "https://www.tvnet.lv/rss/latest",                               "region": "europe", "country": "Latvia",  "lat": 56.9496, "lon": 24.1052},
        {"name": "RFI France",        "url": "https://rfi.fr",             "rss": "https://www.rfi.fr/es/rss",                                     "region": "europe", "country": "France",  "lat": 48.8566, "lon": 2.3522},
    ],

    # ── 4. NORTEAMÉRICA (50) ────────────────────────────────────────────────
    "north_america": [
        {"name": "New York Times",    "url": "https://nytimes.com",        "rss": "https://rss.nytimes.com/services/xml/rss/nyt/World.xml",        "region": "north_america", "country": "USA",    "lat": 40.7128, "lon": -74.0060},
        {"name": "Washington Post",   "url": "https://washingtonpost.com", "rss": "https://feeds.washingtonpost.com/rss/world",                    "region": "north_america", "country": "USA",    "lat": 38.9072, "lon": -77.0369},
        {"name": "Wall Street Journal","url": "https://wsj.com",           "rss": "https://feeds.a.dj.com/rss/RSSWorldNews.xml",                   "region": "north_america", "country": "USA",    "lat": 40.7128, "lon": -74.0060},
        {"name": "CNN",               "url": "https://cnn.com",            "rss": "http://rss.cnn.com/rss/cnn_world.rss",                          "region": "north_america", "country": "USA",    "lat": 33.7490, "lon": -84.3880},
        {"name": "NPR",               "url": "https://npr.org",            "rss": "https://feeds.npr.org/1001/rss.xml",                            "region": "north_america", "country": "USA",    "lat": 38.8977, "lon": -77.0365},
        {"name": "The Atlantic",      "url": "https://theatlantic.com",    "rss": "https://www.theatlantic.com/feed/all/",                         "region": "north_america", "country": "USA",    "lat": 38.9072, "lon": -77.0369},
        {"name": "Politico",          "url": "https://politico.com",       "rss": "https://www.politico.com/rss/politicopicks.xml",                "region": "north_america", "country": "USA",    "lat": 38.8977, "lon": -77.0365},
        {"name": "The Hill",          "url": "https://thehill.com",        "rss": "https://thehill.com/news/feed/",                                "region": "north_america", "country": "USA",    "lat": 38.8977, "lon": -77.0365},
        {"name": "Bloomberg",         "url": "https://bloomberg.com",      "rss": "https://feeds.bloomberg.com/politics/news.rss",                 "region": "north_america", "country": "USA",    "lat": 40.7128, "lon": -74.0060},
        {"name": "Reuters",           "url": "https://reuters.com",        "rss": "https://feeds.reuters.com/reuters/worldNews",                   "region": "north_america", "country": "USA",    "lat": 40.7128, "lon": -74.0060},
        {"name": "AP News",           "url": "https://apnews.com",         "rss": "https://feeds.apnews.com/rss/apf-topnews",                      "region": "north_america", "country": "USA",    "lat": 40.7128, "lon": -74.0060},
        {"name": "Axios",             "url": "https://axios.com",          "rss": "https://api.axios.com/feed/",                                   "region": "north_america", "country": "USA",    "lat": 38.9072, "lon": -77.0369},
        {"name": "Vox",               "url": "https://vox.com",            "rss": "https://www.vox.com/rss/index.xml",                             "region": "north_america", "country": "USA",    "lat": 40.7128, "lon": -74.0060},
        {"name": "Slate",             "url": "https://slate.com",          "rss": "http://feeds.slate.com/slate/",                                 "region": "north_america", "country": "USA",    "lat": 40.7128, "lon": -74.0060},
        {"name": "The Nation",        "url": "https://thenation.com",      "rss": "https://www.thenation.com/feed/",                               "region": "north_america", "country": "USA",    "lat": 40.7128, "lon": -74.0060},
        {"name": "Mother Jones",      "url": "https://motherjones.com",    "rss": "https://www.motherjones.com/feed/",                             "region": "north_america", "country": "USA",    "lat": 37.7749, "lon": -122.4194},
        {"name": "The Intercept",     "url": "https://theintercept.com",   "rss": "https://theintercept.com/feed/?rss",                            "region": "north_america", "country": "USA",    "lat": 40.7128, "lon": -74.0060},
        {"name": "ProPublica",        "url": "https://propublica.org",     "rss": "https://feeds.propublica.org/propublica/main",                  "region": "north_america", "country": "USA",    "lat": 40.7128, "lon": -74.0060},
        {"name": "BuzzFeed News",     "url": "https://buzzfeednews.com",   "rss": "https://www.buzzfeed.com/world.xml",                            "region": "north_america", "country": "USA",    "lat": 40.7128, "lon": -74.0060},
        {"name": "Vice News",         "url": "https://vice.com/en/section/news","rss": "https://www.vice.com/en/rss/section/news",                "region": "north_america", "country": "USA",    "lat": 40.7128, "lon": -74.0060},
        {"name": "LA Times",          "url": "https://latimes.com",        "rss": "https://www.latimes.com/world/rss2.0.xml",                      "region": "north_america", "country": "USA",    "lat": 34.0522, "lon": -118.2437},
        {"name": "Chicago Tribune",   "url": "https://chicagotribune.com", "rss": "https://www.chicagotribune.com/arcio/rss/category/nation-world/","region": "north_america", "country": "USA",   "lat": 41.8781, "lon": -87.6298},
        {"name": "Boston Globe",      "url": "https://bostonglobe.com",    "rss": "https://www.bostonglobe.com/topstories/rss.xml",                "region": "north_america", "country": "USA",    "lat": 42.3601, "lon": -71.0589},
        {"name": "Miami Herald",      "url": "https://miamiherald.com",    "rss": "https://www.miamiherald.com/news/?widgetName=rssfeed&widgetContentId=812232","region": "north_america", "country": "USA", "lat": 25.7617, "lon": -80.1918},
        {"name": "Univision Noticias","url": "https://univision.com",      "rss": "https://feeds.univision.com/feeds/noticias",                    "region": "north_america", "country": "USA",    "lat": 33.9416, "lon": -118.4085},
        {"name": "Telemundo",         "url": "https://telemundo.com",      "rss": "https://www.telemundo.com/rss/noticias",                        "region": "north_america", "country": "USA",    "lat": 40.7128, "lon": -74.0060},
        {"name": "Globe and Mail",    "url": "https://theglobeandmail.com","rss": "https://www.theglobeandmail.com/arc/outboundfeeds/rss/category/politics/","region": "north_america", "country": "Canada", "lat": 43.6532, "lon": -79.3832},
        {"name": "Toronto Star",      "url": "https://thestar.com",        "rss": "https://www.thestar.com/content/thestar/feed.RSSManagerServlet.topstories.rss","region": "north_america", "country": "Canada", "lat": 43.6532, "lon": -79.3832},
        {"name": "CBC News",          "url": "https://cbc.ca/news",        "rss": "https://www.cbc.ca/cmlink/rss-topstories",                      "region": "north_america", "country": "Canada", "lat": 45.4215, "lon": -75.6972},
        {"name": "National Post",     "url": "https://nationalpost.com",   "rss": "https://nationalpost.com/feed/",                                "region": "north_america", "country": "Canada", "lat": 43.6532, "lon": -79.3832},
        {"name": "Le Devoir",         "url": "https://ledevoir.com",       "rss": "https://www.ledevoir.com/rss/manchettes.xml",                   "region": "north_america", "country": "Canada", "lat": 45.5017, "lon": -73.5673},
        {"name": "La Presse",         "url": "https://lapresse.ca",        "rss": "https://www.lapresse.ca/actualites.rss",                        "region": "north_america", "country": "Canada", "lat": 45.5017, "lon": -73.5673},
        {"name": "El Financiero MX",  "url": "https://elfinanciero.com.mx","rss": "https://www.elfinanciero.com.mx/feed/",                         "region": "north_america", "country": "Mexico", "lat": 19.4326, "lon": -99.1332},
        {"name": "El Universal MX",   "url": "https://eluniversal.com.mx", "rss": "https://www.eluniversal.com.mx/minuto-x-minuto.rss",            "region": "north_america", "country": "Mexico", "lat": 19.4326, "lon": -99.1332},
        {"name": "Reforma",           "url": "https://reforma.com",        "rss": "https://www.reforma.com/rss/portada.xml",                       "region": "north_america", "country": "Mexico", "lat": 25.6866, "lon": -100.3161},
        {"name": "Milenio",           "url": "https://milenio.com",        "rss": "https://www.milenio.com/rss",                                   "region": "north_america", "country": "Mexico", "lat": 19.4326, "lon": -99.1332},
        {"name": "Proceso México",    "url": "https://proceso.com.mx",     "rss": "https://www.proceso.com.mx/rss/feed/",                          "region": "north_america", "country": "Mexico", "lat": 19.4326, "lon": -99.1332},
        {"name": "Sin Embargo MX",    "url": "https://sinembargo.mx",      "rss": "https://www.sinembargo.mx/feed",                                "region": "north_america", "country": "Mexico", "lat": 19.4326, "lon": -99.1332},
        {"name": "Animal Político",   "url": "https://animalpolitico.com", "rss": "https://www.animalpolitico.com/feed/",                          "region": "north_america", "country": "Mexico", "lat": 19.4326, "lon": -99.1332},
        {"name": "Aristegui Noticias","url": "https://aristeguinoticias.com","rss": "https://aristeguinoticias.com/feed/",                         "region": "north_america", "country": "Mexico", "lat": 19.4326, "lon": -99.1332},
        {"name": "La Jornada",        "url": "https://jornada.com.mx",     "rss": "https://www.jornada.com.mx/rss/portada.xml",                    "region": "north_america", "country": "Mexico", "lat": 19.4326, "lon": -99.1332},
        {"name": "Excélsior",         "url": "https://excelsior.com.mx",   "rss": "https://www.excelsior.com.mx/rss.xml",                          "region": "north_america", "country": "Mexico", "lat": 19.4326, "lon": -99.1332},
        {"name": "La Razón MX",       "url": "https://razon.com.mx",       "rss": "https://www.razon.com.mx/feed/",                                "region": "north_america", "country": "Mexico", "lat": 19.4326, "lon": -99.1332},
        {"name": "WOLA",              "url": "https://wola.org",           "rss": "https://www.wola.org/feed/",                                    "region": "north_america", "country": "USA",    "lat": 38.8977, "lon": -77.0365},
        {"name": "Foreign Policy",    "url": "https://foreignpolicy.com",  "rss": "https://foreignpolicy.com/feed/",                               "region": "north_america", "country": "USA",    "lat": 38.8977, "lon": -77.0365},
        {"name": "Foreign Affairs",   "url": "https://foreignaffairs.com", "rss": "https://www.foreignaffairs.com/rss.xml",                        "region": "north_america", "country": "USA",    "lat": 40.7128, "lon": -74.0060},
        {"name": "Defense One",       "url": "https://defenseone.com",     "rss": "https://www.defenseone.com/rss/all/",                           "region": "north_america", "country": "USA",    "lat": 38.8977, "lon": -77.0365},
        {"name": "National Security Archive","url": "https://nsarchive.gwu.edu","rss": "https://nsarchive.gwu.edu/rss.xml",                       "region": "north_america", "country": "USA",    "lat": 38.8997, "lon": -77.0480},
        {"name": "The Diplomat",      "url": "https://thediplomat.com",    "rss": "https://thediplomat.com/feed/",                                 "region": "north_america", "country": "USA",    "lat": 38.9072, "lon": -77.0369},
        {"name": "Lawfare",           "url": "https://lawfaremedia.org",   "rss": "https://www.lawfaremedia.org/feed/",                            "region": "north_america", "country": "USA",    "lat": 38.9072, "lon": -77.0369},
    ],

    # ── 5. LATINOAMÉRICA (50) ───────────────────────────────────────────────
    "latin_america": [
        {"name": "Infobae",           "url": "https://infobae.com",        "rss": "https://www.infobae.com/feeds/rss/",                            "region": "latin_america", "country": "Argentina","lat": -34.6037, "lon": -58.3816},
        {"name": "La Nación AR",      "url": "https://lanacion.com.ar",    "rss": "https://www.lanacion.com.ar/arc/outboundfeeds/rss/?outputType=xml","region": "latin_america", "country": "Argentina","lat": -34.6037, "lon": -58.3816},
        {"name": "Clarín",            "url": "https://clarin.com",         "rss": "https://www.clarin.com/rss/politica/",                          "region": "latin_america", "country": "Argentina","lat": -34.6037, "lon": -58.3816},
        {"name": "Perfil",            "url": "https://perfil.com",         "rss": "https://www.perfil.com/rss/",                                   "region": "latin_america", "country": "Argentina","lat": -34.6037, "lon": -58.3816},
        {"name": "Página 12",         "url": "https://pagina12.com.ar",    "rss": "https://www.pagina12.com.ar/rss/portada",                       "region": "latin_america", "country": "Argentina","lat": -34.6037, "lon": -58.3816},
        {"name": "El Cronista",       "url": "https://cronista.com",       "rss": "https://www.cronista.com/feed/",                                "region": "latin_america", "country": "Argentina","lat": -34.6037, "lon": -58.3816},
        {"name": "Ámbito Financiero", "url": "https://ambito.com",         "rss": "https://www.ambito.com/rss/politica",                           "region": "latin_america", "country": "Argentina","lat": -34.6037, "lon": -58.3816},
        {"name": "O Globo",           "url": "https://oglobo.globo.com",   "rss": "https://oglobo.globo.com/rss.xml",                              "region": "latin_america", "country": "Brazil",  "lat": -22.9068, "lon": -43.1729},
        {"name": "Folha de São Paulo","url": "https://folha.uol.com.br",   "rss": "https://feeds.folha.uol.com.br/poder/rss091.xml",               "region": "latin_america", "country": "Brazil",  "lat": -23.5505, "lon": -46.6333},
        {"name": "Estadão",           "url": "https://estadao.com.br",     "rss": "https://feeds.estadao.com.br/politica",                         "region": "latin_america", "country": "Brazil",  "lat": -23.5505, "lon": -46.6333},
        {"name": "UOL Notícias",      "url": "https://noticias.uol.com.br","rss": "https://rss.uol.com.br/feed/noticias.xml",                      "region": "latin_america", "country": "Brazil",  "lat": -23.5505, "lon": -46.6333},
        {"name": "BBC Brasil",        "url": "https://bbc.com/portuguese", "rss": "https://feeds.bbci.co.uk/portuguese/rss.xml",                   "region": "latin_america", "country": "Brazil",  "lat": -15.7801, "lon": -47.9292},
        {"name": "Agencia Brasil",    "url": "https://agenciabrasil.ebc.com.br","rss": "https://agenciabrasil.ebc.com.br/rss/ultimasnoticias/feed.xml","region": "latin_america", "country": "Brazil","lat": -15.7801, "lon": -47.9292},
        {"name": "El Mercurio CL",    "url": "https://emol.com",           "rss": "https://www.emol.com/rss/?seccion=nacional",                    "region": "latin_america", "country": "Chile",   "lat": -33.4489, "lon": -70.6693},
        {"name": "La Tercera",        "url": "https://latercera.com",      "rss": "https://www.latercera.com/rss/",                                "region": "latin_america", "country": "Chile",   "lat": -33.4489, "lon": -70.6693},
        {"name": "CIPER Chile",       "url": "https://ciperchile.cl",      "rss": "https://www.ciperchile.cl/feed/",                               "region": "latin_america", "country": "Chile",   "lat": -33.4489, "lon": -70.6693},
        {"name": "El Mostrador",      "url": "https://elmostrador.cl",     "rss": "https://www.elmostrador.cl/rss/",                               "region": "latin_america", "country": "Chile",   "lat": -33.4489, "lon": -70.6693},
        {"name": "El Tiempo CO",      "url": "https://eltiempo.com",       "rss": "https://www.eltiempo.com/rss/politica.xml",                     "region": "latin_america", "country": "Colombia","lat": 4.7110, "lon": -74.0721},
        {"name": "El Espectador",     "url": "https://elespectador.com",   "rss": "https://www.elespectador.com/arc/outboundfeeds/rss/",           "region": "latin_america", "country": "Colombia","lat": 4.7110, "lon": -74.0721},
        {"name": "Semana",            "url": "https://semana.com",         "rss": "https://www.semana.com/rss/rss.xml",                            "region": "latin_america", "country": "Colombia","lat": 4.7110, "lon": -74.0721},
        {"name": "La Silla Vacía",    "url": "https://lasillavacia.com",   "rss": "https://lasillavacia.com/feed/",                                "region": "latin_america", "country": "Colombia","lat": 4.7110, "lon": -74.0721},
        {"name": "El Comercio PE",    "url": "https://elcomercio.pe",      "rss": "https://elcomercio.pe/arcio/rss/",                              "region": "latin_america", "country": "Peru",    "lat": -12.0464, "lon": -77.0428},
        {"name": "La República PE",   "url": "https://larepublica.pe",     "rss": "https://larepublica.pe/rss/",                                   "region": "latin_america", "country": "Peru",    "lat": -12.0464, "lon": -77.0428},
        {"name": "IDL Reporteros",    "url": "https://idl-reporteros.pe",  "rss": "https://idl-reporteros.pe/feed/",                               "region": "latin_america", "country": "Peru",    "lat": -12.0464, "lon": -77.0428},
        {"name": "El País Uruguay",   "url": "https://elpais.com.uy",      "rss": "https://www.elpais.com.uy/rss/",                                "region": "latin_america", "country": "Uruguay", "lat": -34.9011, "lon": -56.1645},
        {"name": "La Diaria",         "url": "https://ladiaria.com.uy",    "rss": "https://ladiaria.com.uy/feed/",                                 "region": "latin_america", "country": "Uruguay", "lat": -34.9011, "lon": -56.1645},
        {"name": "Búsqueda",          "url": "https://busqueda.com.uy",    "rss": "https://www.busqueda.com.uy/feed/",                             "region": "latin_america", "country": "Uruguay", "lat": -34.9011, "lon": -56.1645},
        {"name": "ABC Color PY",      "url": "https://abc.com.py",         "rss": "https://www.abc.com.py/feeds/rss/",                             "region": "latin_america", "country": "Paraguay","lat": -25.2867, "lon": -57.6470},
        {"name": "El Nacional VE",    "url": "https://elnacional.com",     "rss": "https://www.elnacional.com/feed/",                              "region": "latin_america", "country": "Venezuela","lat": 10.4806, "lon": -66.9036},
        {"name": "Efecto Cocuyo",     "url": "https://efectococuyo.com",   "rss": "https://efectococuyo.com/feed/",                                "region": "latin_america", "country": "Venezuela","lat": 10.4806, "lon": -66.9036},
        {"name": "La Prensa Gráfica", "url": "https://laprensagrafica.com","rss": "https://www.laprensagrafica.com/rss/",                          "region": "latin_america", "country": "El Salvador","lat": 13.6929, "lon": -89.2182},
        {"name": "El Faro ES",        "url": "https://elfaro.net",         "rss": "https://www.elfaro.net/feed",                                   "region": "latin_america", "country": "El Salvador","lat": 13.6929, "lon": -89.2182},
        {"name": "Confidencial Nicaragua","url": "https://confidencial.com.ni","rss": "https://confidencial.com.ni/feed/",                        "region": "latin_america", "country": "Nicaragua","lat": 12.1149, "lon": -86.2362},
        {"name": "La Prensa Honduras","url": "https://laprensa.hn",        "rss": "https://www.laprensa.hn/feed/",                                 "region": "latin_america", "country": "Honduras","lat": 14.0818, "lon": -87.2068},
        {"name": "elPeriódico GT",    "url": "https://elperiodico.com.gt", "rss": "https://elperiodico.com.gt/feed/",                             "region": "latin_america", "country": "Guatemala","lat": 14.6349, "lon": -90.5069},
        {"name": "La Prensa CR",      "url": "https://laprensalibre.cr",   "rss": "https://www.laprensalibre.cr/feed/",                            "region": "latin_america", "country": "Costa Rica","lat": 9.9281, "lon": -84.0907},
        {"name": "La Estrella Panamá","url": "https://laestrella.com.pa",  "rss": "https://www.laestrella.com.pa/rss/",                           "region": "latin_america", "country": "Panama",  "lat": 8.9936, "lon": -79.5197},
        {"name": "Diario Libre DR",   "url": "https://diariolibre.com",    "rss": "https://www.diariolibre.com/feed/",                             "region": "latin_america", "country": "Dom. Rep.","lat": 18.4861, "lon": -69.9312},
        {"name": "El Caribe DR",      "url": "https://elcaribe.com.do",    "rss": "https://www.elcaribe.com.do/feed/",                             "region": "latin_america", "country": "Dom. Rep.","lat": 18.4861, "lon": -69.9312},
        {"name": "14ymedio Cuba",     "url": "https://14ymedio.com",       "rss": "https://www.14ymedio.com/feed/",                                "region": "latin_america", "country": "Cuba",    "lat": 23.1136, "lon": -82.3666},
        {"name": "CiberCuba",         "url": "https://cibercuba.com",      "rss": "https://www.cibercuba.com/feed/",                               "region": "latin_america", "country": "Cuba",    "lat": 23.1136, "lon": -82.3666},
        {"name": "Granma Cuba",       "url": "https://granma.cu",          "rss": "https://www.granma.cu/RSS/",                                    "region": "latin_america", "country": "Cuba",    "lat": 23.1136, "lon": -82.3666},
        {"name": "Telesur",           "url": "https://telesurtv.net",      "rss": "https://www.telesurtv.net/rss/noticias.rss",                    "region": "latin_america", "country": "Venezuela","lat": 10.4806, "lon": -66.9036},
        {"name": "NACLA Report",      "url": "https://nacla.org",          "rss": "https://nacla.org/feed/",                                       "region": "latin_america", "country": "USA",    "lat": 40.7128, "lon": -74.0060},
        {"name": "WOLA Latin Am.",    "url": "https://wola.org/latin",     "rss": "https://www.wola.org/category/latin-america/feed/",             "region": "latin_america", "country": "USA",    "lat": 38.8977, "lon": -77.0365},
        {"name": "Agencia EFE",       "url": "https://efe.com",            "rss": "https://www.efe.com/efe/espana/portada/rss",                    "region": "latin_america", "country": "Spain",  "lat": 40.4168, "lon": -3.7038},
        {"name": "Mercopress",        "url": "https://mercopress.com",     "rss": "https://en.mercopress.com/rss",                                 "region": "latin_america", "country": "Uruguay", "lat": -34.9011, "lon": -56.1645},
        {"name": "Nodal",             "url": "https://nodal.am",           "rss": "https://nodal.am/feed/",                                        "region": "latin_america", "country": "Argentina","lat": -34.6037, "lon": -58.3816},
        {"name": "Resumen Latinoam.", "url": "https://resumenlatinoamericano.org","rss": "https://www.resumenlatinoamericano.org/feed/",           "region": "latin_america", "country": "Argentina","lat": -34.6037, "lon": -58.3816},
        {"name": "Desinformémonos",   "url": "https://desinformemonos.org","rss": "https://desinformemonos.org/feed/",                             "region": "latin_america", "country": "Mexico",  "lat": 19.4326, "lon": -99.1332},
    ],

    # ── 6. ÁFRICA (50) ──────────────────────────────────────────────────────
    "africa": [
        {"name": "Al Jazeera Arabic", "url": "https://aljazeera.net",      "rss": "https://www.aljazeera.net/xml/rss/all.xml",                     "region": "africa", "country": "Qatar",   "lat": 25.2854, "lon": 51.5310},
        {"name": "Al Jazeera English","url": "https://aljazeera.com",      "rss": "https://www.aljazeera.com/xml/rss/all.xml",                     "region": "africa", "country": "Qatar",   "lat": 25.2854, "lon": 51.5310},
        {"name": "Africa Report",     "url": "https://theafricareport.com","rss": "https://www.theafricareport.com/feed/",                         "region": "africa", "country": "France",  "lat": 48.8566, "lon": 2.3522},
        {"name": "AllAfrica",         "url": "https://allafrica.com",      "rss": "https://allafrica.com/tools/headlines/rdf/latest/headlines.rdf","region": "africa", "country": "USA",    "lat": 38.8977, "lon": -77.0365},
        {"name": "Mail & Guardian ZA","url": "https://mg.co.za",           "rss": "https://mg.co.za/feed/",                                        "region": "africa", "country": "S.Africa","lat": -25.7461, "lon": 28.1881},
        {"name": "Daily Maverick ZA", "url": "https://dailymaverick.co.za","rss": "https://www.dailymaverick.co.za/feed/",                         "region": "africa", "country": "S.Africa","lat": -33.9249, "lon": 18.4241},
        {"name": "News24 ZA",         "url": "https://news24.com",         "rss": "https://feeds.news24.com/articles/news24/TopStories/rss",       "region": "africa", "country": "S.Africa","lat": -33.9249, "lon": 18.4241},
        {"name": "IOL South Africa",  "url": "https://iol.co.za",          "rss": "https://www.iol.co.za/rss",                                     "region": "africa", "country": "S.Africa","lat": -33.9249, "lon": 18.4241},
        {"name": "The Citizen ZA",    "url": "https://citizen.co.za",      "rss": "https://citizen.co.za/feed/",                                   "region": "africa", "country": "S.Africa","lat": -26.2041, "lon": 28.0473},
        {"name": "BusinessDay ZA",    "url": "https://businesslive.co.za", "rss": "https://www.businesslive.co.za/rss/",                           "region": "africa", "country": "S.Africa","lat": -26.2041, "lon": 28.0473},
        {"name": "The Nation KE",     "url": "https://nation.africa",      "rss": "https://nation.africa/kenya/rss.xml",                           "region": "africa", "country": "Kenya",   "lat": -1.2921, "lon": 36.8219},
        {"name": "Daily Nation KE",   "url": "https://nation.africa",      "rss": "https://nation.africa/rss",                                     "region": "africa", "country": "Kenya",   "lat": -1.2921, "lon": 36.8219},
        {"name": "The Standard KE",   "url": "https://standardmedia.co.ke","rss": "https://www.standardmedia.co.ke/rss/articles",                 "region": "africa", "country": "Kenya",   "lat": -1.2921, "lon": 36.8219},
        {"name": "The EastAfrican",   "url": "https://theeastafrican.co.ke","rss": "https://www.theeastafrican.co.ke/tea/rss.xml",                 "region": "africa", "country": "Kenya",   "lat": -1.2921, "lon": 36.8219},
        {"name": "Vanguard Nigeria",  "url": "https://vanguardngr.com",    "rss": "https://www.vanguardngr.com/feed/",                             "region": "africa", "country": "Nigeria", "lat": 6.5244, "lon": 3.3792},
        {"name": "Punch Nigeria",     "url": "https://punchng.com",        "rss": "https://punchng.com/feed/",                                     "region": "africa", "country": "Nigeria", "lat": 6.5244, "lon": 3.3792},
        {"name": "The Guardian NG",   "url": "https://guardian.ng",        "rss": "https://guardian.ng/feed/",                                     "region": "africa", "country": "Nigeria", "lat": 6.5244, "lon": 3.3792},
        {"name": "Premium Times NG",  "url": "https://premiumtimesng.com", "rss": "https://www.premiumtimesng.com/feed/",                          "region": "africa", "country": "Nigeria", "lat": 9.0579, "lon": 7.4951},
        {"name": "This Day Nigeria",  "url": "https://thisdaylive.com",    "rss": "https://www.thisdaylive.com/feed/",                             "region": "africa", "country": "Nigeria", "lat": 6.5244, "lon": 3.3792},
        {"name": "Daily Trust NG",    "url": "https://dailytrust.com",     "rss": "https://dailytrust.com/feed/",                                  "region": "africa", "country": "Nigeria", "lat": 11.8469, "lon": 13.1572},
        {"name": "Ethiopia Observer", "url": "https://addisstandard.com",  "rss": "https://addisstandard.com/feed/",                               "region": "africa", "country": "Ethiopia","lat": 9.0248, "lon": 38.7469},
        {"name": "The Reporter ET",   "url": "https://en.thereporterethiopia.com","rss": "https://en.thereporterethiopia.com/feed/",               "region": "africa", "country": "Ethiopia","lat": 9.0248, "lon": 38.7469},
        {"name": "The Monitor UG",    "url": "https://monitor.co.ug",      "rss": "https://www.monitor.co.ug/Uganda/feed/",                        "region": "africa", "country": "Uganda",  "lat": 0.3476, "lon": 32.5825},
        {"name": "New Vision UG",     "url": "https://newvision.co.ug",    "rss": "https://www.newvision.co.ug/rss/",                              "region": "africa", "country": "Uganda",  "lat": 0.3476, "lon": 32.5825},
        {"name": "Daily News TZ",     "url": "https://dailynews.co.tz",    "rss": "https://www.dailynews.co.tz/rss/",                              "region": "africa", "country": "Tanzania","lat": -6.3690, "lon": 34.8888},
        {"name": "The Citizen TZ",    "url": "https://thecitizen.co.tz",   "rss": "https://thecitizen.co.tz/rss.xml",                              "region": "africa", "country": "Tanzania","lat": -6.3690, "lon": 34.8888},
        {"name": "Jeune Afrique",     "url": "https://jeuneafrique.com",   "rss": "https://www.jeuneafrique.com/feed/",                            "region": "africa", "country": "France",  "lat": 48.8566, "lon": 2.3522},
        {"name": "RFI Afrique",       "url": "https://rfi.fr/afrique",     "rss": "https://www.rfi.fr/fr/podcasts/journal-afrique/podcast",        "region": "africa", "country": "France",  "lat": 48.8566, "lon": 2.3522},
        {"name": "Africa Confidential","url": "https://africa-confidential.com","rss": "https://www.africa-confidential.com/feed/",               "region": "africa", "country": "UK",      "lat": 51.5074, "lon": -0.1278},
        {"name": "Le Monde Afrique",  "url": "https://lemonde.fr/afrique", "rss": "https://www.lemonde.fr/afrique/rss_full.xml",                  "region": "africa", "country": "France",  "lat": 48.8566, "lon": 2.3522},
        {"name": "Morocco World News","url": "https://moroccoworldnews.com","rss": "https://www.moroccoworldnews.com/feed/",                       "region": "africa", "country": "Morocco", "lat": 34.0209, "lon": -6.8416},
        {"name": "Médias24 MA",       "url": "https://medias24.com",       "rss": "https://medias24.com/feed/",                                    "region": "africa", "country": "Morocco", "lat": 34.0209, "lon": -6.8416},
        {"name": "HuffPost Maghreb",  "url": "https://huffpostmaghreb.com","rss": "https://www.huffpostmaghreb.com/feeds/index.xml",               "region": "africa", "country": "Algeria", "lat": 36.7538, "lon": 3.0588},
        {"name": "Jeune Algérie",     "url": "https://jeunealgerie.com",   "rss": "https://jeunealgerie.com/feed/",                                "region": "africa", "country": "Algeria", "lat": 36.7538, "lon": 3.0588},
        {"name": "Tunisie Numerique", "url": "https://www.tunisienumerique.com","rss": "https://www.tunisienumerique.com/feed/",                   "region": "africa", "country": "Tunisia", "lat": 36.8190, "lon": 10.1658},
        {"name": "Kapitalis",         "url": "https://kapitalis.com",      "rss": "https://www.kapitalis.com/feed/",                               "region": "africa", "country": "Tunisia", "lat": 36.8190, "lon": 10.1658},
        {"name": "Libya Observer",    "url": "https://libyaobserver.ly",   "rss": "https://libyaobserver.ly/feed/",                                "region": "africa", "country": "Libya",   "lat": 32.9011, "lon": 13.1803},
        {"name": "Sudan Tribune",     "url": "https://sudantribune.com",   "rss": "https://sudantribune.com/feed/",                                "region": "africa", "country": "Sudan",   "lat": 15.5007, "lon": 32.5599},
        {"name": "Al-Monitor (Horn of Africa)","url": "https://al-monitor.com","rss": "https://www.al-monitor.com/rss.xml",                       "region": "africa", "country": "USA",    "lat": 38.9072, "lon": -77.0369},
        {"name": "The Africa Report (FR)","url": "https://theafricareport.com/fr","rss": "https://www.theafricareport.com/fr/feed/",              "region": "africa", "country": "France",  "lat": 48.8566, "lon": 2.3522},
        {"name": "Ghanaian Times",    "url": "https://ghanaiantimes.com.gh","rss": "https://ghanaiantimes.com.gh/feed/",                          "region": "africa", "country": "Ghana",   "lat": 5.6037, "lon": -0.1870},
        {"name": "JoyNews Ghana",     "url": "https://myjoyonline.com",    "rss": "https://www.myjoyonline.com/feed/",                             "region": "africa", "country": "Ghana",   "lat": 5.6037, "lon": -0.1870},
        {"name": "Cote d'Ivoire Inf.","url": "https://connectionivoirienne.net","rss": "https://connectionivoirienne.net/feed/",                  "region": "africa", "country": "Ivory Coast","lat": 5.3600, "lon": -4.0083},
        {"name": "Fraternité Matin",  "url": "https://fratmat.info",       "rss": "https://fratmat.info/feed/",                                   "region": "africa", "country": "Ivory Coast","lat": 5.3600, "lon": -4.0083},
        {"name": "L'Essor Mali",      "url": "https://essor.ml",           "rss": "https://essor.ml/feed/",                                       "region": "africa", "country": "Mali",    "lat": 12.6392, "lon": -8.0029},
        {"name": "Le Monde Diplomatique (Af.)","url": "https://monde-diplomatique.fr","rss": "https://www.monde-diplomatique.fr/rss/",            "region": "africa", "country": "France",  "lat": 48.8566, "lon": 2.3522},
        {"name": "Zambia Daily Mail", "url": "https://daily-mail.co.zm",   "rss": "https://www.daily-mail.co.zm/feed/",                           "region": "africa", "country": "Zambia",  "lat": -15.4167, "lon": 28.2833},
        {"name": "The Herald ZW",     "url": "https://herald.co.zw",       "rss": "https://www.herald.co.zw/feed/",                               "region": "africa", "country": "Zimbabwe","lat": -17.8252, "lon": 31.0335},
        {"name": "Mozambique News",   "url": "https://clubofmozambique.com","rss": "https://clubofmozambique.com/feed/",                          "region": "africa", "country": "Mozambique","lat": -18.6657, "lon": 35.5296},
        {"name": "Madagascar Tribune","url": "https://madagasikara.mg",    "rss": "https://www.madagasikara.mg/feed/",                            "region": "africa", "country": "Madagascar","lat": -18.9249, "lon": 47.5185},
    ],

    # ── 7. ASIA (50) ────────────────────────────────────────────────────────
    "asia": [
        {"name": "Al Jazeera (Asia)", "url": "https://aljazeera.com/asia", "rss": "https://www.aljazeera.com/xml/rss/all.xml",                    "region": "asia", "country": "Qatar",   "lat": 25.2854, "lon": 51.5310},
        {"name": "South China Morning Post","url": "https://scmp.com",     "rss": "https://www.scmp.com/rss/5/feed",                              "region": "asia", "country": "HK",      "lat": 22.3193, "lon": 114.1694},
        {"name": "Caixin Global",     "url": "https://caixinglobal.com",   "rss": "https://www.caixinglobal.com/rss/",                            "region": "asia", "country": "China",   "lat": 39.9042, "lon": 116.4074},
        {"name": "Global Times CN",   "url": "https://globaltimes.cn",     "rss": "https://www.globaltimes.cn/rss/outbrain.xml",                  "region": "asia", "country": "China",   "lat": 39.9042, "lon": 116.4074},
        {"name": "China Daily",       "url": "https://chinadaily.com.cn",  "rss": "https://www.chinadaily.com.cn/rss/china_rss.xml",              "region": "asia", "country": "China",   "lat": 39.9042, "lon": 116.4074},
        {"name": "Xinhua News",       "url": "https://xinhuanet.com",      "rss": "https://www.xinhuanet.com/english/rss/chinarss.xml",           "region": "asia", "country": "China",   "lat": 39.9042, "lon": 116.4074},
        {"name": "Japan Times",       "url": "https://japantimes.co.jp",   "rss": "https://www.japantimes.co.jp/news_category/national/feed/",    "region": "asia", "country": "Japan",   "lat": 35.6895, "lon": 139.6917},
        {"name": "Asahi Shimbun",     "url": "https://asahi.com",          "rss": "https://www.asahi.com/rss/asahi/newsheadlines.rdf",            "region": "asia", "country": "Japan",   "lat": 35.6895, "lon": 139.6917},
        {"name": "NHK World",         "url": "https://nhk.or.jp/nhkworld", "rss": "https://www3.nhk.or.jp/rss/news/cat0.xml",                    "region": "asia", "country": "Japan",   "lat": 35.6895, "lon": 139.6917},
        {"name": "The Mainichi",      "url": "https://mainichi.jp/english","rss": "https://mainichi.jp/rss/etc/mainichi-flash.rss",               "region": "asia", "country": "Japan",   "lat": 35.6895, "lon": 139.6917},
        {"name": "Korea Herald",      "url": "https://koreaherald.com",    "rss": "https://www.koreaherald.com/common/rss.php?hn_idx=all",        "region": "asia", "country": "S.Korea", "lat": 37.5665, "lon": 126.9780},
        {"name": "Korea Times",       "url": "https://koreatimes.co.kr",   "rss": "https://www.koreatimes.co.kr/www/rss/rss.xml",                 "region": "asia", "country": "S.Korea", "lat": 37.5665, "lon": 126.9780},
        {"name": "Yonhap News",       "url": "https://yna.co.kr/en",       "rss": "https://en.yna.co.kr/RSS/news.xml",                            "region": "asia", "country": "S.Korea", "lat": 37.5665, "lon": 126.9780},
        {"name": "The Hindu",         "url": "https://thehindu.com",       "rss": "https://www.thehindu.com/news/national/?service=rss",          "region": "asia", "country": "India",   "lat": 28.6139, "lon": 77.2090},
        {"name": "Indian Express",    "url": "https://indianexpress.com",  "rss": "https://indianexpress.com/feed/",                              "region": "asia", "country": "India",   "lat": 19.0760, "lon": 72.8777},
        {"name": "NDTV",              "url": "https://ndtv.com",           "rss": "https://feeds.feedburner.com/ndtvnews-top-stories",             "region": "asia", "country": "India",   "lat": 28.6139, "lon": 77.2090},
        {"name": "Times of India",    "url": "https://timesofindia.com",   "rss": "https://timesofindia.indiatimes.com/rssfeeds/296589292.cms",   "region": "asia", "country": "India",   "lat": 19.0760, "lon": 72.8777},
        {"name": "Hindustan Times",   "url": "https://hindustantimes.com", "rss": "https://www.hindustantimes.com/rss/topnews/rssfeed.xml",       "region": "asia", "country": "India",   "lat": 28.6139, "lon": 77.2090},
        {"name": "The Wire India",    "url": "https://thewire.in",         "rss": "https://thewire.in/feed",                                      "region": "asia", "country": "India",   "lat": 28.6139, "lon": 77.2090},
        {"name": "Dawn Pakistan",     "url": "https://dawn.com",           "rss": "https://www.dawn.com/feeds/home",                              "region": "asia", "country": "Pakistan","lat": 33.6844, "lon": 73.0479},
        {"name": "The News Int'l PK", "url": "https://thenews.com.pk",     "rss": "https://www.thenews.com.pk/rss/1/1",                           "region": "asia", "country": "Pakistan","lat": 24.8607, "lon": 67.0011},
        {"name": "Express Tribune PK","url": "https://tribune.com.pk",     "rss": "https://tribune.com.pk/feed/",                                 "region": "asia", "country": "Pakistan","lat": 31.5497, "lon": 74.3436},
        {"name": "Daily Star BD",     "url": "https://thedailystar.net",   "rss": "https://www.thedailystar.net/frontpage/rss.xml",               "region": "asia", "country": "Bangladesh","lat": 23.8103, "lon": 90.4125},
        {"name": "Prothom Alo BD",    "url": "https://prothomalo.com",     "rss": "https://www.prothomalo.com/feed/",                             "region": "asia", "country": "Bangladesh","lat": 23.8103, "lon": 90.4125},
        {"name": "The Himalayan Times","url": "https://thehimalayantimes.com","rss": "https://thehimalayantimes.com/feed/",                      "region": "asia", "country": "Nepal",   "lat": 27.7172, "lon": 85.3240},
        {"name": "Myanmar Times",     "url": "https://mmtimes.com",        "rss": "https://www.mmtimes.com/rss/",                                 "region": "asia", "country": "Myanmar", "lat": 16.8661, "lon": 96.1951},
        {"name": "Irrawaddy",         "url": "https://irrawaddy.com",      "rss": "https://www.irrawaddy.com/feed",                               "region": "asia", "country": "Myanmar", "lat": 16.8661, "lon": 96.1951},
        {"name": "Bangkok Post",      "url": "https://bangkokpost.com",    "rss": "https://www.bangkokpost.com/rss/data/news.xml",                "region": "asia", "country": "Thailand","lat": 13.7563, "lon": 100.5018},
        {"name": "The Nation TH",     "url": "https://nationthailand.com", "rss": "https://www.nationthailand.com/rss.xml",                       "region": "asia", "country": "Thailand","lat": 13.7563, "lon": 100.5018},
        {"name": "Vietnam News",      "url": "https://vietnamnews.vn",     "rss": "https://vietnamnews.vn/rss/",                                  "region": "asia", "country": "Vietnam", "lat": 21.0278, "lon": 105.8342},
        {"name": "VnExpress Int'l",   "url": "https://e.vnexpress.net",    "rss": "https://e.vnexpress.net/rss/news.rss",                         "region": "asia", "country": "Vietnam", "lat": 10.8231, "lon": 106.6297},
        {"name": "Jakarta Post",      "url": "https://thejakartapost.com", "rss": "https://www.thejakartapost.com/news.rss",                      "region": "asia", "country": "Indonesia","lat": -6.2088, "lon": 106.8456},
        {"name": "Kompas ID",         "url": "https://kompas.com",         "rss": "https://rss.kompas.com/read/xml/2012/01/17/rss20.xml",         "region": "asia", "country": "Indonesia","lat": -6.2088, "lon": 106.8456},
        {"name": "Philippine Daily Inquirer","url": "https://inquirer.net","rss": "https://inquirer.net/fullrss.xml",                             "region": "asia", "country": "Philippines","lat": 14.5995, "lon": 120.9842},
        {"name": "Rappler PH",        "url": "https://rappler.com",        "rss": "https://www.rappler.com/feed/",                                "region": "asia", "country": "Philippines","lat": 14.5995, "lon": 120.9842},
        {"name": "Straits Times SG",  "url": "https://straitstimes.com",   "rss": "https://www.straitstimes.com/news/singapore/rss.xml",          "region": "asia", "country": "Singapore","lat": 1.3521, "lon": 103.8198},
        {"name": "Channel News Asia", "url": "https://channelnewsasia.com","rss": "https://www.channelnewsasia.com/rssfeeds/8395986",             "region": "asia", "country": "Singapore","lat": 1.3521, "lon": 103.8198},
        {"name": "Malaysiakini",       "url": "https://malaysiakini.com",  "rss": "https://www.malaysiakini.com/rss.rss",                         "region": "asia", "country": "Malaysia","lat": 3.1390, "lon": 101.6869},
        {"name": "New Straits Times MY","url": "https://nst.com.my",       "rss": "https://www.nst.com.my/feed",                                  "region": "asia", "country": "Malaysia","lat": 3.1390, "lon": 101.6869},
        {"name": "Arab News",         "url": "https://arabnews.com",       "rss": "https://www.arabnews.com/rss.xml",                             "region": "asia", "country": "Saudi Arabia","lat": 24.7136, "lon": 46.6753},
        {"name": "Haaretz",           "url": "https://haaretz.com",        "rss": "https://www.haaretz.com/cmlink/1.628765",                      "region": "asia", "country": "Israel",  "lat": 31.7683, "lon": 35.2137},
        {"name": "Jerusalem Post",    "url": "https://jpost.com",          "rss": "https://www.jpost.com/rss/rssfeedsfrontpage.aspx",             "region": "asia", "country": "Israel",  "lat": 31.7683, "lon": 35.2137},
        {"name": "Iran International","url": "https://iranintl.com",       "rss": "https://www.iranintl.com/rss/en/feed.xml",                     "region": "asia", "country": "Iran",    "lat": 35.6892, "lon": 51.3890},
        {"name": "Radio Free Asia",   "url": "https://rfa.org",            "rss": "https://www.rfa.org/english/news/rss2.xml",                    "region": "asia", "country": "USA",     "lat": 38.8977, "lon": -77.0365},
        {"name": "Asia Times",        "url": "https://asiatimes.com",      "rss": "https://asiatimes.com/feed/",                                  "region": "asia", "country": "HK",      "lat": 22.3193, "lon": 114.1694},
        {"name": "Nikkei Asia",       "url": "https://asia.nikkei.com",    "rss": "https://asia.nikkei.com/rss/feed/site.rss",                    "region": "asia", "country": "Japan",   "lat": 35.6895, "lon": 139.6917},
        {"name": "The Diplomat",      "url": "https://thediplomat.com",    "rss": "https://thediplomat.com/category/asia/feed/",                  "region": "asia", "country": "USA",     "lat": 38.9072, "lon": -77.0369},
        {"name": "Lowy Institute",    "url": "https://lowyinstitute.org",  "rss": "https://www.lowyinstitute.org/publications/rss.xml",           "region": "asia", "country": "Australia","lat": -33.8688, "lon": 151.2093},
        {"name": "The Australian",    "url": "https://theaustralian.com.au","rss": "https://www.theaustralian.com.au/feed/",                      "region": "asia", "country": "Australia","lat": -25.2744, "lon": 133.7751},
        {"name": "ABC Australia",     "url": "https://abc.net.au/news",    "rss": "https://www.abc.net.au/news/feed/2942460/rss.xml",             "region": "asia", "country": "Australia","lat": -25.2744, "lon": 133.7751},
    ],
}

# ── Catálogo plano (lista de todas las fuentes) ─────────────────────────────
ALL_SOURCES: list[dict] = [
    source
    for region_sources in MEDIA_SOURCES.values()
    for source in region_sources
]

REGIONS = list(MEDIA_SOURCES.keys())

# ── Fuentes prioritarias (España + Europa) para ingesta rápida ──────────────
PRIORITY_SOURCES: list[dict] = (
    MEDIA_SOURCES["local_spain"]
    + MEDIA_SOURCES["regional_spain"]
    + MEDIA_SOURCES["europe"]
)

def get_sources_by_country(country: str) -> list[dict]:
    return [s for s in ALL_SOURCES if s["country"].lower() == country.lower()]

def get_sources_by_region(region: str) -> list[dict]:
    return MEDIA_SOURCES.get(region, [])
