import type { Briefing } from '@/types/briefing';

export const MOCK_BRIEFINGS: Briefing[] = [
  {
    id: 'b-001',
    titulo: 'Briefing Diario — 10 de mayo 2026',
    tipo: 'diario',
    fecha: new Date().toISOString(),
    estado: 'listo',
    score_riesgo_contexto: 78,
    resumen_ejecutivo: 'Jornada marcada por la escalada de la crisis de coalición entre PSOE y Sumar, con declaraciones de líneas rojas presupuestarias que amenazan la gobernabilidad. Simultáneamente, la expansión del Caso Koldo a altos cargos del Ministerio del Interior eleva el riesgo reputacional del Gobierno. En el plano territorial, la suspensión cautelar de dos artículos de la Ley de Amnistía por el TC introduce una variable de incertidumbre en las relaciones con Junts. El índice global de riesgo político se sitúa en 78/100 (nivel ALTO), con tendencia ascendente.',
    secciones: [
      { id: 'sec-01', tipo: 'situacion', titulo: 'Situación actual', nivel_alerta: 'alto', fuentes_usadas: ['El País', 'El Mundo', 'La Vanguardia'], contenido: '## Análisis de situación\n\nEl escenario político español atraviesa una fase de **tensión acumulada** en múltiples frentes simultáneos, lo que eleva la probabilidad de eventos disruptivos.\n\n### Coalición PSOE-Sumar\n\nLas discrepancias presupuestarias han alcanzado un punto crítico. Yolanda Díaz ha establecido explícitamente sus "líneas rojas" en gasto social y política fiscal, contradiciendo las posiciones del equipo económico de La Moncloa. Fuentes parlamentarias de Sumar señalan que **sin avances concretos en 72 horas**, el partido podría votar en contra de los próximos Presupuestos Generales.\n\n### Marco judicial\n\nLa expansión del Caso Koldo a nuevos imputados en el Ministerio del Interior introduce una dimensión institucional que trasciende el caso individual y afecta la credibilidad del Gobierno en materia de transparencia e integridad.', bullets: ['Crisis de coalición en fase aguda — riesgo de ruptura antes de verano', 'Caso Koldo se expande al Ministerio del Interior', 'TC suspende artículos de Ley de Amnistía — tensión con Junts'] },
      { id: 'sec-02', tipo: 'senales', titulo: 'Señales prioritarias', nivel_alerta: 'critico', fuentes_usadas: ['El Mundo', 'ABC', 'El Confidencial'], contenido: '## Señales de alta prioridad\n\n### Breaking: Yolanda Díaz fija líneas rojas\n\nLa declaración pública de límites a la negociación presupuestaria por parte de la vicepresidenta marca un **punto de no retorno** en las negociaciones internas de la coalición. El tono utilizado sugiere que las diferencias son más profundas que las puramente técnicas.\n\n### Caso Koldo: nuevas imputaciones\n\nLa expansión judicial a cargos del Ministerio del Interior **eleva el riesgo reputacional** del Gobierno de forma significativa. Se espera cobertura mediática intensiva durante las próximas 48-72 horas.', bullets: ['3 señales Breaking activas en las últimas 6 horas', '94% score de relevancia en noticias sobre Caso Koldo', 'Cobertura mediática negativa en 7 de los 10 principales medios'] },
      { id: 'sec-03', tipo: 'recomendaciones', titulo: 'Recomendaciones estratégicas', fuentes_usadas: [], contenido: '## Acciones recomendadas\n\n### Prioridad ALTA\n\n1. **Monitorización intensiva** de la crisis PSOE-Sumar: seguimiento cada 2 horas de declaraciones de portavoces y fuentes parlamentarias\n2. **Preparar escenarios** de respuesta ante posible ruptura de coalición o convocatoria anticipada de elecciones\n3. **Análisis de impacto** del Caso Koldo: mapear conexiones entre imputados y estructura de gobierno\n\n### Prioridad MEDIA\n\n4. Seguimiento de la resolución del TC sobre la Ley de Amnistía y su impacto en la relación con Junts\n5. Evaluar el estado de las negociaciones de financiación autonómica y su efecto en la estabilidad parlamentaria', bullets: ['Activar protocolo de crisis para monitorización de coalición', 'Preparar escenarios de ruptura y sus implicaciones', 'Reforzar análisis judicial del Caso Koldo'] },
    ],
    escenarios: [
      { nombre: 'Ruptura de coalición antes del verano', probabilidad: 0.38, descripcion: 'Las negociaciones presupuestarias fracasan y Sumar retira su apoyo formal al gobierno. Se convoca un período de negociación de urgencia que desemboca en elecciones anticipadas.', impacto: 'alto', horizonte: '3 meses', triggers: ['Fracaso negociación presupuestaria', 'Declaraciones públicas de ruptura de Díaz', 'Moción de censura del PP con apoyos'] },
      { nombre: 'Acuerdo mínimo de supervivencia', probabilidad: 0.45, descripcion: 'PSOE y Sumar alcanzan un acuerdo parcial en el menor denominador común presupuestario, posponiendo las diferencias estructurales a la siguiente negociación.', impacto: 'medio', horizonte: '1 mes', triggers: ['Mediación externa exitosa', 'Concesiones mutuas en puntos clave', 'Presión común de los socios parlamentarios'] },
      { nombre: 'Crisis institucional por Ley de Amnistía', probabilidad: 0.17, descripcion: 'El TC emite un fallo contrario a los intereses de Junts, quien retira su apoyo parlamentario desencadenando una crisis de gobernabilidad de alta intensidad.', impacto: 'alto', horizonte: '2 meses', triggers: ['Sentencia adversa del TC', 'Ruptura de acuerdos de investidura', 'Convocatoria de elecciones anticipadas'] },
    ],
    generado_por: 'Politeia Brain v2.1',
    tiempo_generacion_s: 47,
    signals_analizadas: 1847,
    palabras: 2340,
  },
  {
    id: 'b-002',
    titulo: 'Briefing Diario — 9 de mayo 2026',
    tipo: 'diario',
    fecha: new Date(Date.now() - 86400000).toISOString(),
    estado: 'archivado',
    score_riesgo_contexto: 74,
    resumen_ejecutivo: 'Jornada dominada por las primeras declaraciones de Yolanda Díaz sobre divergencias en política fiscal, marcando el inicio de la tensión presupuestaria actual. El índice de riesgo subió 4 puntos respecto a la jornada anterior.',
    secciones: [],
    escenarios: [],
    generado_por: 'Politeia Brain v2.1',
    tiempo_generacion_s: 42,
    signals_analizadas: 1623,
    palabras: 1980,
  },
  {
    id: 'b-003',
    titulo: 'Briefing Diario — 8 de mayo 2026',
    tipo: 'diario',
    fecha: new Date(Date.now() - 172800000).toISOString(),
    estado: 'archivado',
    score_riesgo_contexto: 70,
    resumen_ejecutivo: 'Inicio de semana con señales de tensión en la coalición y primeros rumores sobre la expansión judicial del Caso Koldo. El mercado de deuda española se mantuvo estable.',
    secciones: [],
    escenarios: [],
    generado_por: 'Politeia Brain v2.1',
    tiempo_generacion_s: 38,
    signals_analizadas: 1445,
    palabras: 1756,
  },
];
