"""
Perfiles de votante, constantes de campaña y biblioteca de nombres.

Módulo de solo datos — sin dependencias de Streamlit ni DB.
Importar desde aquí en lugar de leer de 5_Agentes_LLM.py.

Los datos sintéticos están calibrados con las últimas oleadas publicadas del CIS.
"""
from __future__ import annotations

# ── Perfiles canónicos de votante ──────────────────────────────────────────────
PERFILES: list[dict] = [
    {
        "id": 1,
        "etiqueta": "Izquierda Urbana Joven",
        "peso": 0.18,
        "n_personas": "6,9 millones",
        "ideo_media": 2.5,
        "ideo_label": "Izquierda",
        "ideo_color": "#DC2626",
        "edad_media": 31,
        "edad_rango": "18-40 años",
        "tendencia_perfil": "estable_decreciente",
        "tendencia_desc": "Ligera pérdida (-0,8 pp) por emigración y baja natalidad urbana",
        "ccaa": {"Madrid": 22, "Catalunya": 19, "País Vasco": 12, "Andalucía": 11, "C. Valenciana": 10, "Resto": 26},
        "preocupaciones": [
            ("Vivienda y alquiler", 91), ("Cambio climático", 74), ("Empleo precario", 71),
            ("Igualdad de género", 65), ("Sanidad pública", 58), ("Educación", 52),
            ("Corrupción", 48), ("Inmigración", 12),
        ],
        "intencion_voto": {"SUMAR": 42, "PSOE": 28, "Abstención": 15, "ERC/EH Bildu": 8, "Otros": 7},
        "tendencia_voto": "Abstención creciente (+3 pp vs 2023) por desencanto con PSOE",
        "opinion_gobierno": "Decepcionados con el ritmo de la agenda social. Apoyan la coalición pero exigen más.",
        "opinion_economia": "Muy pesimistas: el 78% cree que su situación económica es peor que hace 3 años.",
        "opinion_territorial": "Abiertos al diálogo con Cataluña. El 63% apoya un referéndum pactado.",
        "micro_eco": {
            "Renta media anual": "22.000€", "Tasa de paro": "18%", "% en alquiler": "73%",
            "Cuota media alquiler": "850€/mes", "Ahorro mensual": "-85€ (endeudamiento neto)",
            "Edad media emancipación": "30 años",
        },
    },
    {
        "id": 2,
        "etiqueta": "Centro Pragmático",
        "peso": 0.22,
        "n_personas": "8,4 millones",
        "ideo_media": 5.0,
        "ideo_label": "Centro",
        "ideo_color": "#6B7280",
        "edad_media": 44,
        "edad_rango": "35-55 años",
        "tendencia_perfil": "estable",
        "tendencia_desc": "Estable. Es el segmento más determinante en elecciones generales",
        "ccaa": {"Madrid": 24, "Andalucía": 18, "Catalunya": 15, "C. Valenciana": 12, "País Vasco": 8, "Resto": 23},
        "preocupaciones": [
            ("Economía y empleo", 81), ("Sanidad pública", 69), ("Corrupción", 63),
            ("Educación", 58), ("Pensiones", 52), ("Vivienda", 48),
            ("Seguridad ciudadana", 44), ("Inmigración", 35),
        ],
        "intencion_voto": {"PP": 38, "PSOE": 31, "CS": 12, "SUMAR": 9, "Otros": 10},
        "tendencia_voto": "Migración desde PSOE hacia PP (+5 pp) por inflación 2022-2024",
        "opinion_gobierno": "Valoran la estabilidad pero critican la dependencia de socios nacionalistas.",
        "opinion_economia": "Moderadamente pesimistas. La hipoteca y la cesta de la compra son sus mayores angustias.",
        "opinion_territorial": "Prefieren la negociación a la confrontación pero rechazan concesiones constitucionales.",
        "micro_eco": {
            "Renta media anual": "32.000€", "Tasa de paro": "8%", "% en alquiler": "39%",
            "Cuota media hipoteca": "820€/mes", "Ahorro mensual": "380€",
            "Patrimonio principal": "Vivienda propia + plan de pensiones",
        },
    },
    {
        "id": 3,
        "etiqueta": "Derecha Tradicional",
        "peso": 0.20,
        "n_personas": "7,7 millones",
        "ideo_media": 7.5,
        "ideo_label": "Derecha",
        "ideo_color": "#0066CC",
        "edad_media": 55,
        "edad_rango": "45-70 años",
        "tendencia_perfil": "decreciente",
        "tendencia_desc": "Envejecimiento del perfil. Pérdida de -1,2 pp por defunciones sin reposición joven",
        "ccaa": {"Madrid": 22, "Andalucía": 20, "Castilla y León": 12, "Murcia": 8, "Aragón": 6, "Resto": 32},
        "preocupaciones": [
            ("Inmigración", 79), ("Seguridad ciudadana", 74), ("Economía y empleo", 68),
            ("Unidad nacional", 65), ("Pensiones", 61), ("Corrupción", 55),
            ("Familia y valores", 48), ("Sanidad", 42),
        ],
        "intencion_voto": {"PP": 52, "VOX": 28, "PSOE": 8, "Otros": 12},
        "tendencia_voto": "Desplazamiento hacia VOX (+4 pp) por política migratoria y pactos con independentistas",
        "opinion_gobierno": "Muy críticos. El 84% valora negativamente la gestión del gobierno.",
        "opinion_economia": "Preocupados por impuestos sobre herencias y ahorro. El 70% tiene vivienda en propiedad.",
        "opinion_territorial": "Rechazan firmemente cualquier concesión a independentistas. Prioridad: unidad de España.",
        "micro_eco": {
            "Renta media anual": "38.000€", "Tasa de paro": "5%", "% en propiedad": "78%",
            "Ahorro mensual": "650€", "Pensión media (jubilados)": "1.400€/mes",
            "Activos principales": "Vivienda, cartera de valores, seguros de vida",
        },
    },
    {
        "id": 4,
        "etiqueta": "Nacionalista Periférico",
        "peso": 0.12,
        "n_personas": "4,6 millones",
        "ideo_media": 4.0,
        "ideo_label": "Centro-izquierda",
        "ideo_color": "#00C0B2",
        "edad_media": 42,
        "edad_rango": "30-55 años",
        "tendencia_perfil": "estable_creciente",
        "tendencia_desc": "Leve crecimiento (+0,3 pp) por consolidación del voto en Cataluña y País Vasco",
        "ccaa": {"Catalunya": 38, "País Vasco": 28, "Galicia": 18, "Navarra": 10, "Resto": 6},
        "preocupaciones": [
            ("Autogobierno / soberanía", 88), ("Lengua y cultura propia", 76),
            ("Financiación autonómica", 71), ("Economía local", 64),
            ("Sanidad", 59), ("Educación en lengua propia", 55),
            ("Vivienda", 42), ("Seguridad", 28),
        ],
        "intencion_voto": {"Partidos locales": 68, "PSOE": 15, "SUMAR": 10, "PP": 5, "Otros": 2},
        "tendencia_voto": "Estable. Clave como árbitro en gobiernos de coalición nacionales",
        "opinion_gobierno": "Evaluación transaccional: apoyan si hay contrapartidas concretas para sus comunidades.",
        "opinion_economia": "Satisfechos con el desempeño económico de sus CCAA vs la media estatal.",
        "opinion_territorial": "El autogobierno es el eje central de toda su visión política.",
        "micro_eco": {
            "Renta media anual": "36.000€", "PIB/cápita vs media": "+18% sobre media estatal",
            "Tasa de paro": "7%", "% en propiedad": "62%",
            "Ahorro mensual": "480€", "Sector predominante": "Industria, servicios avanzados, turismo",
        },
    },
    {
        "id": 5,
        "etiqueta": "Voto Rural Conservador",
        "peso": 0.15,
        "n_personas": "5,8 millones",
        "ideo_media": 6.5,
        "ideo_label": "Centro-derecha",
        "ideo_color": "#D97706",
        "edad_media": 58,
        "edad_rango": "45-75 años",
        "tendencia_perfil": "muy_decreciente",
        "tendencia_desc": "Pérdida estructural de -2,1 pp por despoblación y envejecimiento rural",
        "ccaa": {"Castilla-La Mancha": 18, "Extremadura": 14, "Aragón": 12, "Castilla y León": 18, "Andalucía rural": 15, "Resto": 23},
        "preocupaciones": [
            ("Despoblación rural", 82), ("Precios agrícolas / PAC", 77),
            ("Sanidad en zonas rurales", 71), ("Infraestructuras y conectividad", 68),
            ("Pensiones", 65), ("Inmigración", 52),
            ("Coste de vida", 49), ("Sequía y agua", 44),
        ],
        "intencion_voto": {"PP": 45, "PSOE": 30, "VOX": 15, "Otros": 10},
        "tendencia_voto": "Abstención creciente (+2 pp) por sensación de abandono institucional",
        "opinion_gobierno": "Sensación de que las políticas urbanas ignoran las necesidades del campo.",
        "opinion_economia": "Muy afectados por el coste de los fertilizantes y la competencia de importaciones.",
        "opinion_territorial": "Indiferentes al debate catalán salvo cuando perciben un trato fiscal desigual.",
        "micro_eco": {
            "Renta media anual": "19.000€", "Tasa de paro": "11%",
            "% en propiedad": "71%", "Pensión media": "900€/mes",
            "Renta vs media": "-20% respecto a la media nacional",
            "Sector predominante": "Agricultura, ganadería, servicios municipales",
        },
    },
    {
        "id": 6,
        "etiqueta": "Joven Abstencionista",
        "peso": 0.13,
        "n_personas": "5,0 millones",
        "ideo_media": 4.5,
        "ideo_label": "Centro-izquierda difuso",
        "ideo_color": "#7C3AED",
        "edad_media": 24,
        "edad_rango": "18-30 años",
        "tendencia_perfil": "creciente",
        "tendencia_desc": "Crecimiento (+1,5 pp) por entrada de nuevos votantes que no se identifican con los partidos actuales",
        "ccaa": {"Madrid": 20, "Catalunya": 16, "Andalucía": 15, "C. Valenciana": 11, "País Vasco": 7, "Resto": 31},
        "preocupaciones": [
            ("Vivienda y emancipación", 91), ("Empleo estable y salarios", 85),
            ("Cambio climático", 72), ("Corrupción e impunidad", 69),
            ("Educación y formación", 61), ("Sanidad mental", 54),
            ("Igualdad", 51), ("Pensiones futuras", 47),
        ],
        "intencion_voto": {"Abstención": 45, "SUMAR": 22, "PSOE": 14, "Blanco/Nulo": 10, "Otros": 9},
        "tendencia_voto": "Mayor desmovilización. Potencial reservorio para SUMAR o nuevas formaciones",
        "opinion_gobierno": "Alta desconfianza institucional. Solo el 23% confía en que un gobierno puede mejorar su situación.",
        "opinion_economia": "Muy pesimistas: el 81% cree que vivirá peor que sus padres.",
        "opinion_territorial": "Poco interés en el debate territorial. Prefieren hablar de políticas concretas.",
        "micro_eco": {
            "Renta media anual": "16.000€", "Tasa de paro juvenil": "27%",
            "% viviendo con padres": "48%", "Salario primer empleo": "16.000€/año",
            "Ahorro mensual": "-120€ (endeudamiento)", "Edad media emancipación": "30,2 años (récord histórico)",
        },
    },
]

# ── Modelo de impacto de campaña ───────────────────────────────────────────────
TEMAS_IMPACTO: dict[str, dict[str, dict[str, float]]] = {
    "Bajada de impuestos a clase media": {
        "PP":   {"pp_impacto": +3.2, "perfiles": ["Centro Pragmático", "Derecha Tradicional"]},
        "PSOE": {"pp_impacto": -1.8},
        "SUMAR":{"pp_impacto": -3.5},
        "VOX":  {"pp_impacto": +1.5},
    },
    "Regulación del alquiler y vivienda pública": {
        "SUMAR":{"pp_impacto": +4.1, "perfiles": ["Izquierda Urbana Joven", "Joven Abstencionista"]},
        "PSOE": {"pp_impacto": +2.2},
        "PP":   {"pp_impacto": -1.2},
        "VOX":  {"pp_impacto": -1.8},
    },
    "Política migratoria restrictiva": {
        "VOX":  {"pp_impacto": +5.2, "perfiles": ["Derecha Tradicional", "Voto Rural Conservador"]},
        "PP":   {"pp_impacto": +2.1},
        "PSOE": {"pp_impacto": -2.8},
        "SUMAR":{"pp_impacto": -4.1},
    },
    "Subida del salario mínimo": {
        "SUMAR":{"pp_impacto": +3.8, "perfiles": ["Izquierda Urbana Joven", "Joven Abstencionista"]},
        "PSOE": {"pp_impacto": +2.0},
        "PP":   {"pp_impacto": -1.5},
        "VOX":  {"pp_impacto": -2.0},
    },
    "Refuerzo de la unidad territorial": {
        "PP":   {"pp_impacto": +2.8, "perfiles": ["Derecha Tradicional"]},
        "VOX":  {"pp_impacto": +3.5},
        "PSOE": {"pp_impacto": -1.0},
        "Junts":{"pp_impacto": -4.5},
        "ERC":  {"pp_impacto": -3.5},
    },
    "Transición energética y agenda verde": {
        "SUMAR":{"pp_impacto": +3.5, "perfiles": ["Izquierda Urbana Joven"]},
        "PSOE": {"pp_impacto": +1.8},
        "PP":   {"pp_impacto": -0.5},
        "VOX":  {"pp_impacto": -5.0},
    },
    "Reducción del gasto público": {
        "PP":   {"pp_impacto": +2.5, "perfiles": ["Centro Pragmático", "Derecha Tradicional"]},
        "VOX":  {"pp_impacto": +1.5},
        "PSOE": {"pp_impacto": -2.2},
        "SUMAR":{"pp_impacto": -4.0},
    },
    "Más inversión en sanidad pública": {
        "PSOE": {"pp_impacto": +3.2, "perfiles": ["Centro Pragmático", "Voto Rural Conservador"]},
        "SUMAR":{"pp_impacto": +2.8},
        "PP":   {"pp_impacto": -0.5},
        "VOX":  {"pp_impacto": -1.0},
    },
}

# ── Multiplicadores de receptividad por perfil ────────────────────────────────
REACCION_PERFIL: dict[str, dict[str, float]] = {
    "Izquierda Urbana Joven":  {"izquierda": 0.9, "derecha": 0.1, "social": 1.3, "eco": 1.2, "territorial": 0.6},
    "Centro Pragmático":       {"izquierda": 0.5, "derecha": 0.5, "social": 0.8, "eco": 0.6, "territorial": 0.4},
    "Derecha Tradicional":     {"izquierda": 0.1, "derecha": 0.9, "social": 0.5, "eco": 0.3, "territorial": 0.9},
    "Nacionalista Periférico": {"izquierda": 0.5, "derecha": 0.3, "social": 0.7, "eco": 0.6, "territorial": 1.5},
    "Voto Rural Conservador":  {"izquierda": 0.2, "derecha": 0.8, "social": 0.7, "eco": 0.4, "territorial": 0.5},
    "Joven Abstencionista":    {"izquierda": 0.6, "derecha": 0.2, "social": 1.0, "eco": 1.1, "territorial": 0.3},
}

# ── Biblioteca de nombres para perfiles empíricos ────────────────────────────
PROFILE_NAME_LIBRARY: list[str] = [
    "Socialista de Siempre",
    "Votante Popular Clásico",
    "Votante de VOX Obrero",
    "Joven Progresista Urbana",
    "Abstencionista Desencantado",
    "Profesional Liberal Centrista",
    "Independentista Catalán",
    "Ama de Casa Conservadora",
    "Votante del PNV Vasco",
    "Joven VOX Urbano",
    "Pensionista de Izquierda",
    "Universitaria Progresista",
    "Empresario de Derechas",
    "Escéptico Ilustrado",
    "Votante Nacionalista Gallega",
    "Migrante Nuevo Ciudadano",
    "Rural Castellano Conservador",
    "Joven Feminista Crítica",
    "Ex-Ciudadanos Flotante",
    "Izquierda Abertzale",
]
