import { NextResponse } from 'next/server';

// ── SUCESOS GEORREFERENCIADOS DE LAS GUERRAS ACTIVAS ──────────────────────────
// Dataset curado OSINT: los hitos más importantes de cada guerra activa, con
// coordenadas verificadas, fecha, tipo y fuente. Color asignado por guerra para
// poder "separarlos por cada guerra" desde el selector.
// Fuentes: ISW, Reuters, AP, BBC, Al Jazeera, HRW, Wikipedia (timelines).

export const dynamic = 'force-static';

// Color por guerra (debe coincidir con OsirisMap y LegendFooter)
const WAR_COLORS: Record<string, string> = {
  ucrania: '#4FC3F7',
  gaza: '#EF5350',
  libano: '#FF7043',
  iran: '#AB47BC',
  sudan: '#FBC02D',
  myanmar: '#26A69A',
  congo: '#66BB6A',
  sahel: '#8D6E63',
  siria: '#EC407A',
};

const WARS = [
  { id: 'ucrania', label: 'Rusia–Ucrania', actors: 'Rusia · Ucrania', since: 'feb 2022' },
  { id: 'gaza', label: 'Israel–Gaza', actors: 'Israel · Hamás', since: 'oct 2023' },
  { id: 'libano', label: 'Israel–Hezbolá (Líbano)', actors: 'Israel · Hezbolá', since: 'sep 2024' },
  { id: 'iran', label: 'Israel–Irán', actors: 'Israel · Irán', since: 'abr 2024' },
  { id: 'sudan', label: 'Sudán (SAF–RSF)', actors: 'SAF · RSF', since: 'abr 2023' },
  { id: 'myanmar', label: 'Myanmar', actors: 'Junta · PDF / EAOs', since: 'feb 2021' },
  { id: 'congo', label: 'RD Congo (M23)', actors: 'RDC · M23 / Ruanda', since: '2022' },
  { id: 'sahel', label: 'Sahel (JNIM / EIGS)', actors: 'Estados · JNIM / EIGS', since: '2012' },
  { id: 'siria', label: 'Siria (post-Ásad)', actors: 'HTS / Gobierno · facciones', since: 'nov 2024' },
].map((w) => ({ ...w, color: WAR_COLORS[w.id] }));

const RAW = [
  // ───────────────────────── RUSIA–UCRANIA ─────────────────────────
  { war: 'ucrania', title: 'Masacre de Bucha', date: 'mar 2022', place: 'Bucha', lat: 50.5436, lng: 30.2122, type: 'masacre', desc: 'Tropas rusas asesinaron a cientos de civiles en Bucha; se hallaron 458 cuerpos tras la retirada rusa de Kiev.', source: 'https://en.wikipedia.org/wiki/Bucha_massacre' },
  { war: 'ucrania', title: 'Bombardeo del teatro de Mariúpol', date: 'mar 2022', place: 'Mariúpol', lat: 47.0960, lng: 37.5486, type: 'ataque aéreo', desc: 'Un ataque aéreo ruso destruyó el teatro-refugio de Mariúpol, marcado con la palabra «NIÑOS», matando a cientos de civiles.', source: 'https://en.wikipedia.org/wiki/Mariupol_theatre_airstrike' },
  { war: 'ucrania', title: 'Hundimiento del Moskvá', date: 'abr 2022', place: 'Mar Negro (frente a Odesa)', lat: 45.3000, lng: 30.9167, type: 'ataque naval', desc: 'Misiles Neptune ucranianos hundieron el crucero Moskvá, buque insignia de la Flota del Mar Negro rusa.', source: 'https://www.britannica.com/event/Russia-Ukraine-War' },
  { war: 'ucrania', title: 'Caída de Azovstal (Mariúpol)', date: 'may 2022', place: 'Mariúpol', lat: 47.1061, lng: 37.6030, type: 'asedio', desc: 'Tras 86 días de asedio, la guarnición ucraniana atrincherada en la acería Azovstal se rindió, completando la toma de Mariúpol.', source: 'https://en.wikipedia.org/wiki/Siege_of_Mariupol' },
  { war: 'ucrania', title: 'Contraofensiva de Járkov', date: 'sep 2022', place: 'Izium', lat: 49.2123, lng: 37.2506, type: 'contraofensiva', desc: 'Ucrania recuperó unos 12.000 km² en días, liberando Izium y Kupiansk en un colapso del frente ruso.', source: 'https://en.wikipedia.org/wiki/2022_Kharkiv_counteroffensive' },
  { war: 'ucrania', title: 'Primer ataque al puente de Crimea', date: 'oct 2022', place: 'Puente de Kerch', lat: 45.3470, lng: 36.5180, type: 'sabotaje', desc: 'Un camión bomba derrumbó tramos del puente de Kerch, vía clave de suministro ruso a Crimea; murieron cinco personas.', source: 'https://en.wikipedia.org/wiki/2022_Crimean_Bridge_explosion' },
  { war: 'ucrania', title: 'Liberación de Jersón', date: 'nov 2022', place: 'Jersón', lat: 46.6354, lng: 32.6169, type: 'contraofensiva', desc: 'Las fuerzas rusas se retiraron de la margen derecha del Dniéper y Ucrania recuperó la única capital regional ocupada.', source: 'https://en.wikipedia.org/wiki/Liberation_of_Kherson' },
  { war: 'ucrania', title: 'Caída de Bajmut', date: 'may 2023', place: 'Bajmut', lat: 48.5957, lng: 37.9994, type: 'batalla', desc: 'Tras más de nueve meses, las fuerzas rusas y Wagner tomaron Bajmut en la batalla más sangrienta de la guerra.', source: 'https://en.wikipedia.org/wiki/Battle_of_Bakhmut' },
  { war: 'ucrania', title: 'Destrucción de la presa de Kajovka', date: 'jun 2023', place: 'Nova Kajovka', lat: 46.7780, lng: 33.3700, type: 'sabotaje', desc: 'La voladura de la presa de Kajovka en el Dniéper inundó vastas zonas río abajo y devastó comunidades enteras.', source: 'https://en.wikipedia.org/wiki/Destruction_of_the_Kakhovka_Dam' },
  { war: 'ucrania', title: 'Caída de Avdíivka', date: 'feb 2024', place: 'Avdíivka', lat: 48.1392, lng: 37.7461, type: 'captura', desc: 'Tras meses de combates, Rusia tomó Avdíivka, su mayor avance desde Bajmut y puerta hacia el oeste del Donetsk.', source: 'https://en.wikipedia.org/wiki/Battle_of_Avdiivka' },
  { war: 'ucrania', title: 'Incursión de Kursk', date: 'ago 2024', place: 'Sudzha', lat: 51.1939, lng: 35.2731, type: 'incursión', desc: 'Ucrania irrumpió en territorio ruso de Kursk, capturando Sudzha y más de 1.250 km² en una operación sin precedentes.', source: 'https://en.wikipedia.org/wiki/Kursk_offensive_(2024)' },
  { war: 'ucrania', title: 'Caída de Vuhledar', date: 'oct 2024', place: 'Vuhledar', lat: 47.7833, lng: 37.2500, type: 'captura', desc: 'Rusia capturó la fortaleza de Vuhledar tras dos años de defensa ucraniana, abriendo avances al oeste del Donetsk.', source: 'https://en.wikipedia.org/wiki/Battle_of_Vuhledar' },
  { war: 'ucrania', title: 'Rusia retoma Sudzha (Kursk)', date: 'mar 2025', place: 'Sudzha', lat: 51.2339, lng: 35.3231, type: 'contraofensiva', desc: 'Con apoyo de tropas norcoreanas, Rusia recuperó Sudzha y expulsó a Ucrania de casi todo el saliente de Kursk.', source: 'https://www.aljazeera.com/news/2025/3/13/russian-forces-recapture-kursk' },
  { war: 'ucrania', title: 'Operación Telaraña', date: 'jun 2025', place: 'Base aérea de Belaya (Irkutsk)', lat: 52.9167, lng: 103.0667, type: 'sabotaje', desc: 'Drones ucranianos lanzados desde camiones golpearon bombarderos estratégicos rusos en cinco bases hasta Siberia.', source: 'https://en.wikipedia.org/wiki/Operation_Spiderweb' },
  { war: 'ucrania', title: 'Liberación de Kupiansk', date: 'nov 2025', place: 'Kupiansk', lat: 49.7106, lng: 37.6156, type: 'contraofensiva', desc: 'Ucrania recuperó gran parte de Kupiansk en otoño de 2025, deteniendo el avance ruso en el frente nororiental.', source: 'https://www.understandingwar.org/' },
  { war: 'ucrania', title: 'Caída de Pokrovsk', date: 'ene 2026', place: 'Pokrovsk', lat: 48.2833, lng: 37.1764, type: 'asedio', desc: 'Tras 18 meses de asedio, Rusia tomó el nudo logístico de Pokrovsk y la vecina Myrnohrad a comienzos de 2026.', source: 'https://en.wikipedia.org/wiki/Pokrovsk_offensive' },

  // ───────────────────────── ISRAEL–GAZA ─────────────────────────
  { war: 'gaza', title: 'Masacre del festival Nova en Re’im', date: 'oct 2023', place: 'Re’im, frontera de Gaza', lat: 31.295, lng: 34.402, type: 'masacre', desc: 'Comandos de Hamás asaltaron el festival de música Supernova y mataron a 378 personas, secuestrando a decenas.', source: 'https://en.wikipedia.org/wiki/Nova_music_festival_massacre' },
  { war: 'gaza', title: 'Masacre del kibutz Be’eri', date: 'oct 2023', place: 'Kibutz Be’eri', lat: 31.422, lng: 34.491, type: 'masacre', desc: 'Milicianos de Hamás mataron a más de cien residentes y tomaron decenas de rehenes tras un asedio de horas.', source: 'https://en.wikipedia.org/wiki/October_7_attacks' },
  { war: 'gaza', title: 'Asalto a Sderot', date: 'oct 2023', place: 'Sderot', lat: 31.525, lng: 34.596, type: 'incursión', desc: 'Pistoleros de Hamás dispararon en las calles y asaltaron la comisaría, matando a civiles y policías israelíes.', source: 'https://en.wikipedia.org/wiki/Battle_of_Sderot' },
  { war: 'gaza', title: 'Inicio de la invasión terrestre', date: 'oct 2023', place: 'Beit Hanún, norte de Gaza', lat: 31.537, lng: 34.538, type: 'ofensiva', desc: 'Israel lanzó la invasión terrestre con decenas de miles de soldados sobre el norte de Gaza.', source: 'https://en.wikipedia.org/wiki/Israeli_ground_invasion_of_the_Gaza_Strip' },
  { war: 'gaza', title: 'Bombardeo del campo de Jabalia', date: 'oct 2023', place: 'Campo de refugiados de Jabalia', lat: 31.532, lng: 34.503, type: 'ataque aéreo', desc: 'Un ataque israelí contra túneles bajo Jabalia mató a más de cien personas, en su mayoría mujeres y niños.', source: 'https://en.wikipedia.org/wiki/Jabalia_refugee_camp_airstrikes' },
  { war: 'gaza', title: 'Asedio del hospital Al-Shifa', date: 'nov 2023', place: 'Hospital Al-Shifa, Ciudad de Gaza', lat: 31.524, lng: 34.444, type: 'asedio', desc: 'Tropas israelíes asaltaron el mayor hospital de Gaza alegando un centro de mando de Hamás bajo el complejo.', source: 'https://en.wikipedia.org/wiki/Al-Shifa_Hospital_siege' },
  { war: 'gaza', title: 'Asedio de Jan Yunis', date: 'dic 2023', place: 'Jan Yunis', lat: 31.346, lng: 34.303, type: 'asedio', desc: 'Israel expandió la ofensiva terrestre al sur, cercando Jan Yunis en busca de líderes de Hamás.', source: 'https://en.wikipedia.org/wiki/Siege_of_Khan_Yunis' },
  { war: 'gaza', title: 'Ofensiva de Rafah', date: 'may 2024', place: 'Rafah', lat: 31.287, lng: 34.255, type: 'ofensiva', desc: 'Israel tomó el lado gazatí del paso de Rafah y el corredor de Filadelfia tras ordenar evacuar a cien mil civiles.', source: 'https://en.wikipedia.org/wiki/Rafah_offensive' },

  // ───────────────────────── ISRAEL–HEZBOLÁ (LÍBANO) ─────────────────────────
  { war: 'libano', title: 'Ataques de buscas y walkie-talkies', date: 'sep 2024', place: 'Dahieh, sur de Beirut', lat: 33.851, lng: 35.502, type: 'sabotaje', desc: 'Israel hizo explotar simultáneamente miles de buscas y radios de Hezbolá, matando a decenas e hiriendo a miles.', source: 'https://en.wikipedia.org/wiki/2024_Lebanon_electronic_device_attacks' },
  { war: 'libano', title: 'Magnicidio de Hasán Nasralá', date: 'sep 2024', place: 'Haret Hreik, Dahieh (Beirut)', lat: 33.8514, lng: 35.5039, type: 'magnicidio', desc: 'Israel lanzó más de ochenta bombas sobre el búnker subterráneo de Hezbolá, matando a su líder Hasán Nasralá.', source: 'https://en.wikipedia.org/wiki/Assassination_of_Hassan_Nasrallah' },
  { war: 'libano', title: 'Invasión del sur del Líbano', date: 'oct 2024', place: 'Sur del Líbano', lat: 33.27, lng: 35.45, type: 'ofensiva', desc: 'Tropas israelíes cruzaron la Línea Azul e invadieron el sur del Líbano hasta el río Litani contra Hezbolá.', source: 'https://en.wikipedia.org/wiki/2024_Israeli_invasion_of_Lebanon' },

  // ───────────────────────── ISRAEL–IRÁN ─────────────────────────
  { war: 'iran', title: 'Primer ataque directo iraní', date: 'abr 2024', place: 'Israel (centro)', lat: 32.000, lng: 34.850, type: 'ataque con misiles', desc: 'Irán lanzó por primera vez de forma directa más de trescientos drones y misiles contra Israel, casi todos interceptados.', source: 'https://en.wikipedia.org/wiki/April_2024_Iranian_strikes_on_Israel' },
  { war: 'iran', title: 'Represalia israelí en Isfahán', date: 'abr 2024', place: 'Isfahán', lat: 32.654, lng: 51.677, type: 'ataque aéreo', desc: 'Israel respondió con un ataque limitado contra un radar de defensa aérea cerca de una base en Isfahán.', source: 'https://en.wikipedia.org/wiki/April_2024_Israeli_strikes_on_Iran' },
  { war: 'iran', title: 'Magnicidio de Ismail Haniya', date: 'jul 2024', place: 'Teherán', lat: 35.8194, lng: 51.4158, type: 'magnicidio', desc: 'El líder político de Hamás fue asesinado en una residencia de la Guardia Revolucionaria en el norte de Teherán.', source: 'https://en.wikipedia.org/wiki/Assassination_of_Ismail_Haniyeh' },
  { war: 'iran', title: 'Segundo ataque masivo iraní', date: 'oct 2024', place: 'Israel', lat: 32.085, lng: 34.781, type: 'ataque con misiles', desc: 'Irán disparó unos doscientos misiles balísticos contra Israel en represalia por los magnicidios de líderes aliados.', source: 'https://en.wikipedia.org/wiki/October_2024_Iranian_strikes_on_Israel' },
  { war: 'iran', title: 'Guerra de los Doce Días: ataque a Fordow', date: 'jun 2025', place: 'Planta nuclear de Fordow', lat: 34.884, lng: 50.993, type: 'ataque aéreo', desc: 'Israel y luego EE.UU. bombardearon las plantas nucleares de Fordow, Natanz e Isfahán en doce días de guerra abierta.', source: 'https://en.wikipedia.org/wiki/Twelve-Day_War' },

  // ───────────────────────── SUDÁN (SAF–RSF) ─────────────────────────
  { war: 'sudan', title: 'Estallido de la guerra en Jartum', date: 'abr 2023', place: 'Jartum', lat: 15.5518, lng: 32.5324, type: 'batalla', desc: 'Estallan combates entre el Ejército (SAF) y las Fuerzas de Apoyo Rápido (RSF); la RSF toma gran parte de la capital.', source: 'https://en.wikipedia.org/wiki/Battle_of_Khartoum_(2023%E2%80%932025)' },
  { war: 'sudan', title: 'Masacre de El Geneina', date: 'jun 2023', place: 'El Geneina (Darfur Occidental)', lat: 13.45, lng: 22.45, type: 'masacre', desc: 'Tras matar al gobernador, la RSF y milicias árabes asesinan a miles de civiles masalit en una limpieza étnica.', source: 'https://www.hrw.org/report/2024/05/09/massalit-will-not-come-home' },
  { war: 'sudan', title: 'Caída de Wad Madani', date: 'dic 2023', place: 'Wad Madani (Gezira)', lat: 14.4012, lng: 33.5199, type: 'captura', desc: 'La RSF toma la segunda ciudad del país, refugio de desplazados, y obliga a huir a unas 300.000 personas.', source: 'https://en.wikipedia.org/wiki/Battle_of_Wad_Madani' },
  { war: 'sudan', title: 'Comienza el asedio de El Fasher', date: 'may 2024', place: 'El Fasher (Darfur del Norte)', lat: 13.6279, lng: 25.3494, type: 'asedio', desc: 'La RSF cerca El Fasher, último bastión del Ejército en Darfur, iniciando un asedio que duraría 18 meses.', source: 'https://en.wikipedia.org/wiki/Siege_of_El_Fasher' },
  { war: 'sudan', title: 'Bombardeo del campo de Zamzam', date: 'dic 2024', place: 'Campo de Zamzam (Darfur del Norte)', lat: 13.50, lng: 25.30, type: 'ataque aéreo', desc: 'La RSF bombardea casi a diario el campo de desplazados de Zamzam, golpeado por la hambruna, con decenas de muertos.', source: 'https://en.wikipedia.org/wiki/Zamzam_camp' },
  { war: 'sudan', title: 'El Ejército recupera Wad Madani', date: 'ene 2025', place: 'Wad Madani (Gezira)', lat: 14.4512, lng: 33.5699, type: 'ofensiva', desc: 'El SAF expulsa a la RSF de Wad Madani, cortando sus líneas de suministro y marcando un giro en la guerra.', source: 'https://www.aljazeera.com/news/2025/1/12/sudan-army-captures-wad-madani' },
  { war: 'sudan', title: 'El SAF retoma Jartum', date: 'mar 2025', place: 'Jartum', lat: 15.6018, lng: 32.5824, type: 'ofensiva', desc: 'El Ejército recupera el palacio presidencial y casi toda la capital tras dos años de control de la RSF.', source: 'https://www.aljazeera.com/news/2025/3/21/sudans-army-retakes-presidential-palace' },
  { war: 'sudan', title: 'La RSF arrasa el campo de Zamzam', date: 'abr 2025', place: 'Campo de Zamzam (Darfur del Norte)', lat: 13.45, lng: 25.24, type: 'masacre', desc: 'La RSF arrasa el mayor campo de desplazados de Sudán; al menos 1.000 civiles muertos y 400.000 huyen.', source: 'https://www.aljazeera.com/news/2025/4/13/sudans-rsf-claims-control-of-zamzam-camp' },
  { war: 'sudan', title: 'Caída y masacre de El Fasher', date: 'oct 2025', place: 'El Fasher (Darfur del Norte)', lat: 13.6779, lng: 25.4094, type: 'masacre', desc: 'La RSF captura El Fasher y ejecuta a miles de civiles; la ONU halla indicios de genocidio contra zaghawa y fur.', source: 'https://en.wikipedia.org/wiki/El_Fasher_massacre' },
  { war: 'sudan', title: 'Ataques de la RSF en Bara', date: 'may 2026', place: 'Bara (Kordofán del Norte)', lat: 13.70, lng: 30.3667, type: 'incursión', desc: 'Vehículos de combate de la RSF asaltan aldeas al oeste de Bara y matan a más de treinta civiles indefensos.', source: 'https://sudantribune.com/' },

  // ───────────────────────── MYANMAR ─────────────────────────
  { war: 'myanmar', title: 'Golpe militar en Naipyidó', date: 'feb 2021', place: 'Naipyidó', lat: 19.7450, lng: 96.1297, type: 'golpe', desc: 'El Tatmadaw derroca al gobierno electo, detiene a Aung San Suu Kyi e instala una junta militar.', source: 'https://en.wikipedia.org/wiki/2021_Myanmar_coup_d%27%C3%A9tat' },
  { war: 'myanmar', title: 'Masacre aérea de Pazigyi', date: 'abr 2023', place: 'Pazigyi, Kanbalu (Sagaing)', lat: 23.0044, lng: 95.9208, type: 'ataque aéreo', desc: 'Cazas y helicópteros de la junta bombardean una celebración y matan a unas 165 personas, muchas mujeres y niños.', source: 'https://en.wikipedia.org/wiki/Pazigyi_massacre' },
  { war: 'myanmar', title: 'Operación 1027 en el norte de Shan', date: 'oct 2023', place: 'Chinshwehaw (Shan)', lat: 23.5500, lng: 98.5900, type: 'ofensiva', desc: 'La Alianza de las Tres Hermandades lanza una ofensiva coordinada que captura decenas de posiciones de la junta.', source: 'https://en.wikipedia.org/wiki/Operation_1027' },
  { war: 'myanmar', title: 'Caída de Laukkai (Kokang)', date: 'ene 2024', place: 'Laukkai (Shan)', lat: 23.7000, lng: 98.7500, type: 'captura', desc: 'El MNDAA toma el mando regional de Kokang tras la rendición de unos 2.400 soldados de la junta.', source: 'https://en.wikipedia.org/wiki/Battle_of_Laukkai' },
  { war: 'myanmar', title: 'Toma de Paletwa por el Ejército de Arakán', date: 'ene 2024', place: 'Paletwa (Chin)', lat: 21.3036, lng: 92.8540, type: 'captura', desc: 'El Ejército de Arakán conquista Paletwa, nudo fluvial estratégico junto a la frontera con Bangladés e India.', source: 'https://www.aljazeera.com/news/2024/1/16/arakan-army-claims-control-of-paletwa' },
  { war: 'myanmar', title: 'Caída de Myawaddy (frontera tailandesa)', date: 'abr 2024', place: 'Myawaddy (Kayin)', lat: 16.6843, lng: 98.5007, type: 'captura', desc: 'Fuerzas karen (KNLA) y PDF toman el mayor paso fronterizo con Tailandia, aunque la junta lo recupera después.', source: 'https://www.cnn.com/2024/04/11/asia/myanmar-myawaddy-knu-military-junta-intl-hnk' },
  { war: 'myanmar', title: 'Asalto a Buthidaung y huida rohinyá', date: 'may 2024', place: 'Buthidaung (Rakáin)', lat: 20.8639, lng: 92.5403, type: 'captura', desc: 'El Ejército de Arakán toma Buthidaung; barrios rohinyá son incendiados y miles de civiles huyen.', source: 'https://www.hrw.org/news/2024/08/12/myanmar-armies-target-ethnic-rohingya-rakhine' },
  { war: 'myanmar', title: 'Caída del Mando Nordeste en Lashio', date: 'ago 2024', place: 'Lashio (Shan)', lat: 22.9359, lng: 97.7498, type: 'captura', desc: 'MNDAA y TNLA conquistan el primer mando regional del Tatmadaw y capturan a su general al mando.', source: 'https://www.aljazeera.com/news/2024/8/6/myanmar-anti-coup-forces-claim-base' },
  { war: 'myanmar', title: 'Control rohinyá de Maungdaw y la frontera', date: 'dic 2024', place: 'Maungdaw (Rakáin)', lat: 20.8186, lng: 92.3614, type: 'captura', desc: 'El Ejército de Arakán toma Maungdaw y domina los 270 km de frontera con Bangladés.', source: 'https://thediplomat.com/2024/12/myanmars-border-with-bangladesh/' },
  { war: 'myanmar', title: 'Caída del Mando Oeste en Ann', date: 'dic 2024', place: 'Ann (Rakáin)', lat: 19.7830, lng: 94.0330, type: 'captura', desc: 'El Ejército de Arakán captura el cuartel del Mando Occidental y controla cerca del 80% de Rakáin.', source: 'https://en.wikipedia.org/wiki/Battle_of_Ann' },

  // ───────────────────────── RD CONGO (M23) ─────────────────────────
  { war: 'congo', title: 'M23 toma Bunagana', date: 'jun 2022', place: 'Bunagana (Kivu del Norte)', lat: -1.3000, lng: 29.5950, type: 'captura', desc: 'El M23 captura el puesto fronterizo de Bunagana con Uganda, forzando a la guarnición congoleña a huir al exterior.', source: 'https://en.wikipedia.org/wiki/M23_campaign_(2022%E2%80%93present)' },
  { war: 'congo', title: 'Masacre de Kishishe', date: 'nov 2022', place: 'Kishishe (Rutshuru)', lat: -0.88, lng: 29.13, type: 'masacre', desc: 'El M23 ejecuta sumariamente al menos a 171 civiles en Kishishe y Bambo, según la ONU; decenas murieron en una iglesia.', source: 'https://en.wikipedia.org/wiki/Kishishe_massacre' },
  { war: 'congo', title: 'Caída de Goma', date: 'ene 2025', place: 'Goma (Kivu del Norte)', lat: -1.6792, lng: 29.2228, type: 'captura', desc: 'El M23 y tropas ruandesas toman Goma, mayor ciudad del este congoleño, tras días de combates y la rendición del aeropuerto.', source: 'https://en.wikipedia.org/wiki/2025_Goma_offensive' },
  { war: 'congo', title: 'Caída de Bukavu', date: 'feb 2025', place: 'Bukavu (Kivu del Sur)', lat: -2.5083, lng: 28.8608, type: 'captura', desc: 'El M23 entra en Bukavu, capital de Kivu del Sur, sin resistencia tras la retirada del ejército congoleño.', source: 'https://www.aljazeera.com/news/2025/2/16/dr-congos-m23-rebels-enter-bukavu' },
  { war: 'congo', title: 'M23 toma Walikale', date: 'mar 2025', place: 'Walikale (Kivu del Norte)', lat: -1.4167, lng: 28.0333, type: 'captura', desc: 'El M23 captura el centro minero de Walikale, su avance más occidental, desafiando un llamamiento al alto el fuego en Doha.', source: 'https://en.wikipedia.org/wiki/2025_Walikale_offensive' },
  { war: 'congo', title: 'M23 toma Uvira', date: 'dic 2025', place: 'Uvira (Kivu del Sur)', lat: -3.3833, lng: 29.1389, type: 'captura', desc: 'El M23 toma sin resistencia Uvira, en la frontera con Burundi, días después del acuerdo de paz firmado en Washington.', source: 'https://en.wikipedia.org/wiki/2025_Uvira_offensive' },
  { war: 'congo', title: 'El ejército recupera Uvira', date: 'ene 2026', place: 'Uvira (Kivu del Sur)', lat: -3.4333, lng: 29.1689, type: 'batalla', desc: 'Las FARDC retoman Uvira tras la retirada del M23 exigida por mediadores de EE. UU., acusando a los rebeldes de saqueos.', source: 'https://www.france24.com/en/africa/' },

  // ───────────────────────── SAHEL (JNIM / EIGS) ─────────────────────────
  { war: 'sahel', title: 'Emboscada de Tinzaouaten', date: 'jul 2024', place: 'Tinzaouaten (Malí)', lat: 19.9433, lng: 2.7019, type: 'emboscada', desc: 'Rebeldes tuareg y JNIM emboscan un convoy del ejército maliés y Wagner; decenas de mercenarios rusos murieron.', source: 'https://en.wikipedia.org/wiki/Battle_of_Tinzaouaten_(2024)' },
  { war: 'sahel', title: 'Masacre de Barsalogho', date: 'ago 2024', place: 'Barsalogho (Burkina Faso)', lat: 13.415, lng: -1.0564, type: 'masacre', desc: 'El JNIM mata a entre 200 y 600 civiles que cavaban trincheras defensivas; la peor masacre de la insurgencia burkinesa.', source: 'https://en.wikipedia.org/wiki/Barsalogho_massacre' },
  { war: 'sahel', title: 'Asalto del JNIM a Djibo', date: 'may 2025', place: 'Djibo (Burkina Faso)', lat: 14.1011, lng: -1.6306, type: 'asedio', desc: 'Cientos de combatientes del JNIM arrasan las bases militares de Djibo, ciudad asediada desde hace años, matando a un centenar.', source: 'https://en.wikipedia.org/wiki/Siege_of_Djibo' },
  { war: 'sahel', title: 'JNIM toma Diapaga', date: 'may 2025', place: 'Diapaga (Burkina Faso)', lat: 12.0731, lng: 1.7884, type: 'captura', desc: 'El JNIM desborda Diapaga, capital de la provincia de Tapoa, saquea edificios y libera presos de la cárcel local.', source: 'https://www.criticalthreats.org/' },
  { war: 'sahel', title: 'Ataque a la base de Banibangou', date: 'jun 2025', place: 'Banibangou (Níger)', lat: 14.53, lng: 2.45, type: 'incursión', desc: 'El Estado Islámico-Sahel asalta con motos una base del ejército nigerino cerca de Malí, matando hasta a 71 soldados.', source: 'https://en.wikipedia.org/wiki/2025_Banibangou_attack' },
  { war: 'sahel', title: 'Bloqueo de combustible a Bamako', date: 'sep 2025', place: 'Bamako (Malí)', lat: 12.6392, lng: -8.0029, type: 'asedio', desc: 'El JNIM bloquea el suministro de combustible a Bamako, destruye cientos de cisternas y paraliza la capital maliense.', source: 'https://en.wikipedia.org/wiki/Mali_fuel_blockade' },

  // ───────────────────────── SIRIA (post-Ásad) ─────────────────────────
  { war: 'siria', title: 'Ofensiva «Disuasión de la Agresión» toma Alepo', date: 'nov 2024', place: 'Alepo', lat: 36.2021, lng: 37.1343, type: 'ofensiva', desc: 'HTS y rebeldes aliados lanzan una ofensiva relámpago y capturan Alepo en días tras el colapso del Ejército sirio.', source: 'https://en.wikipedia.org/wiki/Northwestern_Syria_offensive_(2024)' },
  { war: 'siria', title: 'Captura de Hama', date: 'dic 2024', place: 'Hama', lat: 35.1318, lng: 36.7578, type: 'captura', desc: 'Las fuerzas progubernamentales se retiran y los rebeldes toman Hama, cuarta ciudad de Siria, avanzando hacia el sur.', source: 'https://en.wikipedia.org/wiki/Fall_of_the_Assad_regime' },
  { war: 'siria', title: 'Caída de Homs', date: 'dic 2024', place: 'Homs', lat: 34.7308, lng: 36.7090, type: 'captura', desc: 'La toma de Homs aísla Damasco de los bastiones costeros alauíes de Tartús y Latakia, sellando el destino del régimen.', source: 'https://en.wikipedia.org/wiki/Fall_of_the_Assad_regime' },
  { war: 'siria', title: 'Caída de Damasco y huida de Ásad', date: 'dic 2024', place: 'Damasco', lat: 33.5138, lng: 36.2765, type: 'colapso', desc: 'Los rebeldes entran en Damasco; Bashar al-Ásad huye a Moscú y recibe asilo, terminando 54 años de poder de su familia.', source: 'https://en.wikipedia.org/wiki/Fall_of_Damascus_(2024)' },
  { war: 'siria', title: 'Incursión israelí en el Monte Hermón', date: 'dic 2024', place: 'Monte Hermón', lat: 33.4167, lng: 35.8575, type: 'incursión', desc: 'Israel ocupa la zona desmilitarizada del Golán y la cumbre del Hermón, tomando unos 350 km² tras la caída de Ásad.', source: 'https://en.wikipedia.org/wiki/Israeli_invasion_of_Syria_(2024%E2%80%93present)' },
  { war: 'siria', title: 'El SNA proturco captura Manbij', date: 'dic 2024', place: 'Manbij', lat: 36.5282, lng: 37.9550, type: 'batalla', desc: 'El Ejército Nacional Sirio respaldado por Turquía expulsa a las SDF kurdas de Manbij tras tomar antes Tell Rifaat.', source: 'https://en.wikipedia.org/wiki/Manbij_offensive_(2024)' },
  { war: 'siria', title: 'Batalla por la presa de Tishrín', date: 'ene 2025', place: 'Presa de Tishrín', lat: 36.3814, lng: 38.1833, type: 'batalla', desc: 'SNA y SDF combaten meses por la presa del Éufrates; más de 280 muertos y daños graves a su central eléctrica.', source: 'https://www.longwarjournal.org/' },
  { war: 'siria', title: 'Masacres de alauíes en la costa', date: 'mar 2025', place: 'Latakia', lat: 35.5317, lng: 35.7915, type: 'masacre', desc: 'Tras una emboscada de leales a Ásad, fuerzas progubernamentales matan a más de 1.300 alauíes en Latakia y Tartús.', source: 'https://en.wikipedia.org/wiki/2025_massacres_of_Syrian_Alawites' },
  { war: 'siria', title: 'Choques con drusos en Sweida', date: 'jul 2025', place: 'Sweida', lat: 32.7094, lng: 36.5694, type: 'masacre', desc: 'Combates entre milicias drusas, beduinos y el gobierno dejan más de 1.700 muertos; Israel bombardea para proteger a los drusos.', source: 'https://en.wikipedia.org/wiki/Southern_Syria_clashes_(2025)' },
  { war: 'siria', title: 'Israel bombardea Defensa en Damasco', date: 'jul 2025', place: 'Damasco', lat: 33.4902, lng: 36.3013, type: 'ataque aéreo', desc: 'Cazas israelíes golpean el Estado Mayor y el Ministerio de Defensa junto a la plaza Umayyad como advertencia por Sweida.', source: 'https://en.wikipedia.org/wiki/July_2025_Damascus_airstrikes' },
  { war: 'siria', title: 'Ofensiva del gobierno contra las SDF', date: 'ene 2026', place: 'Deir Hafer (este de Alepo)', lat: 36.1500, lng: 37.7000, type: 'ofensiva', desc: 'El gobierno de al-Sharaa ataca a las SDF en el este de Alepo y Raqa, desplazando a decenas de miles antes de un alto el fuego.', source: 'https://en.wikipedia.org/wiki/Syrian_civil_war' },
];

const EVENTS = RAW.map((e) => ({ ...e, color: WAR_COLORS[e.war] || '#FF1744' }));

export async function GET() {
  return NextResponse.json({ events: EVENTS, wars: WARS, total: EVENTS.length });
}
