"""Metadatos de fuentes de datos por dominio (URLs, formatos, notas operativas)."""

FUENTES_DATOS = {
    "resultados_electorales": {
        "fuente": "Ministerio del Interior",
        "url_base": "https://infoelectoral.interior.gob.es/opencms/es/elecciones-celebradas/",
        "formato": "ZIP con MDB/CSV por tipo elección",
        "frecuencia": "por elección",
        "variables_clave": ["votos partido", "censo", "participación", "escaños"],
        "notas": "Descarga manual por tipo y año. Ficheros .DAT con codificación ISO-8859-1",
    },
    "cis_barometros": {
        "fuente": "Centro de Investigaciones Sociológicas",
        "url_base": "https://www.cis.es/es/detalle.html",
        "formato": "SPSS (.sav), Stata (.dta), CSV",
        "frecuencia": "mensual (barómetros), irregular (estudios ad-hoc)",
        "variables_clave": [
            "P1 (situación política)",
            "P4 (principal problema)",
            "P16 (valoración gobierno)",
            "P30 (intención de voto directo)",
            "P31 (simpatía de partido)",
            "P40 (escala ideológica)",
            "EDAD",
            "SEXO",
            "ESTUDIOS",
            "SITLAB",
            "TAMUNI",
            "REGION",
        ],
        "notas": "Requiere pyreadstat para leer .sav. Aplicar peso muestral PESO",
    },
    "ine_padron": {
        "fuente": "Instituto Nacional de Estadística",
        "url_api": "https://www.ine.es/jaxiT3/Tabla.htm",
        "formato": "JSON API (INEbase), CSV, Excel",
        "frecuencia": "anual (Padrón), trimestral (EPA), mensual (IPC, EPT)",
        "variables_clave": ["población por municipio", "edad", "sexo", "nacionalidad"],
        "script": "etl/sources/ine_api.py",
        "notas": "Usar ine-api-python o requests directo a API JSON INE",
    },
    "ine_epa": {
        "fuente": "INE - Encuesta Población Activa",
        "url_api": "https://www.ine.es/jaxiT3/Tabla.htm?t=4247",
        "formato": "API JSON INE",
        "frecuencia": "trimestral",
        "variables_clave": ["tasa paro", "tasa actividad", "ocupados", "CCAA", "edad", "sexo"],
    },
    "ine_atlas_renta": {
        "fuente": "INE - Atlas de Distribución de Renta de los Hogares",
        "url": "https://www.ine.es/experimental/atlas/experimental_atlas.htm",
        "formato": "CSV / Excel descargable",
        "frecuencia": "anual (con 2 años de retraso)",
        "variables_clave": ["renta media", "renta mediana", "Gini", "por sección censal"],
    },
    "bde_estadisticas": {
        "fuente": "Banco de España",
        "url_api": "https://www.bde.es/webbde/es/estadis/infoest/descarga_series_temporales.html",
        "formato": "CSV Series Temporales BdE",
        "frecuencia": "mensual/trimestral",
        "variables_clave": ["euríbor", "tipos BCE", "crédito", "morosidad", "deuda pública"],
    },
    "ree_esios": {
        "fuente": "Red Eléctrica de España (REE) - ESIOS",
        "url_api": "https://api.esios.ree.es/",
        "formato": "REST API JSON",
        "frecuencia": "horaria/diaria/mensual",
        "variables_clave": [
            "generación por tecnología",
            "precio pool",
            "demanda",
            "intercambios internacionales",
            "CO2 intensidad",
        ],
        "auth": "Token API gratuito en https://api.esios.ree.es/",
        "script": "etl/sources/ree_esios.py",
    },
    "hacienda_presupuestos": {
        "fuente": "Ministerio de Hacienda",
        "url": "https://www.hacienda.gob.es/es-ES/Estadistica%20e%20Informes/Paginas/Estadistica.aspx",
        "formato": "Excel / CSV descargable",
        "frecuencia": "anual",
        "variables_clave": ["créditos", "obligaciones", "programa", "ministerio"],
    },
    "mapa_estadisticas": {
        "fuente": "Ministerio Agricultura, Pesca y Alimentación (MAPA)",
        "url": "https://www.mapa.gob.es/es/estadistica/temas/estadisticas-agrarias/",
        "formato": "Excel descargable",
        "frecuencia": "anual",
        "variables_clave": ["producción por cultivo", "censo ganadero", "ayudas PAC", "precios percibidos"],
    },
    "iet_frontur_egatur": {
        "fuente": "Instituto Español de Turismo (IET) / INE",
        "url": "https://www.ine.es/dyngs/INEbase/es/operacion.htm?c=Estadistica_C&cid=1254736176990",
        "formato": "CSV / API INE",
        "frecuencia": "mensual",
        "variables_clave": ["llegadas por país origen", "pernoctaciones", "gasto medio", "CCAA"],
    },
    "puertos_estado": {
        "fuente": "Puertos del Estado",
        "url": "https://www.puertos.es/es-es/estadisticas/Paginas/Estadisticas.aspx",
        "formato": "Excel descargable",
        "frecuencia": "mensual/anual",
        "variables_clave": ["tráfico TEUs", "mercancías", "pasajeros", "por puerto"],
    },
    "eurostat_spain": {
        "fuente": "Eurostat",
        "url_api": "https://ec.europa.eu/eurostat/api/dissemination/",
        "formato": "REST API JSON (SDMX) o eurostat Python package",
        "frecuencia": "anual/trimestral",
        "variables_clave": ["PIB NUTS2", "empleo por sector", "I+D", "energía renovable", "AROPE"],
    },
    "encuestas_privadas_tracking": {
        "fuente": "Metroscopia, GAD3, 40dB, IMOP, Celeste-Tel, NC Report, SigmaDos",
        "formato": "Tablas PDF / scraping de medios",
        "frecuencia": "variable",
        "variables_clave": ["intención de voto", "valoración líderes", "estimación de escaños"],
        "notas": "Requiere scraping de medios. Usar tabula-py para PDFs",
    },
    "twitter_x_politico": {
        "fuente": "X (ex-Twitter) / Bluesky",
        "api": "X API v2 (Basic tier) / Bluesky AT Protocol (gratuito)",
        "variables_clave": ["texto", "engagement", "fecha", "autor", "menciones"],
        "notas": "Priorizar Bluesky (gratuito). X API Basic: límites mensuales",
    },
}
