/**
 * lib/tercer-sector/global-opportunities/sources.ts · CATÁLOGO CURADO del
 * GLOBAL OPPORTUNITY GRAPH · Tercer Sector cockpit · Sprint Ga.
 *
 * `SOURCES` es el mapa exhaustivo de fuentes de licitaciones / subvenciones /
 * convocatorias / oportunidades relevantes para el tercer sector a escala
 * mundial: organismos internacionales (ONU), bancos multilaterales de
 * desarrollo, instituciones UE, portales nacionales prioritarios, portales de
 * grants y agregadores OCDS.
 *
 * ESTE ARCHIVO NO HACE RED. Es metadata curada: cada entrada documenta cómo se
 * accede a la fuente, qué publica, para qué sirve a una ONG, qué campos expone y
 * su estado de integración. Todas las URLs / api_url son REALES (verificadas en
 * el spec del usuario; no se inventan endpoints).
 *
 * `integration_status`:
 *   - 'live'    → YA conectada en nuestro agregador (conectores reales en
 *                 lib/tercer-sector/licitaciones/* y lib/tercer-sector/iati-*):
 *                 place, bdns, ted, sedia, worldbank, uk-ocds (Find a Tender),
 *                 tendersguru, iati.
 *   - 'planned' → la añade el Sprint Gb (conectores live FREE nuevos):
 *                 grants.gov, prozorro, austender, secop, dncp.
 *   - 'catalog' → catalogada sin conector (resto).
 *
 * Cero emojis.
 */

import type { OpportunitySource } from './types.ts'

/**
 * Catálogo completo. Agrupado por familias (comentarios) para lectura humana;
 * el orden no es significativo para el endpoint (que ordena/filtra a su gusto).
 */
export const SOURCES: OpportunitySource[] = [
  // ───────────────────────────────────────────────────────────────────────
  // IATI — International Aid Transparency Initiative (cooperación)
  // ───────────────────────────────────────────────────────────────────────
  {
    id: 'iati-datastore',
    label: 'IATI Datastore (cooperación al desarrollo)',
    url: 'https://iatistandard.org/en/using-data/iati-tools-and-resources/iati-datastore/',
    api_url: 'https://api.iatistandard.org/datastore/activity/select',
    access_method: 'api',
    auth: 'api_key',
    cost: 'free',
    geography: ['global'],
    levels: ['international_org', 'national'],
    opportunity_types: ['project_pipeline', 'grant', 'implementing_partner_call'],
    useful_for_ngo: 'alta',
    fields_available: [
      'activity_id',
      'title',
      'description',
      'reporting_org',
      'recipient_country',
      'sector_dac',
      'budget',
      'transaction',
      'participating_org',
    ],
    update_frequency: 'continua',
    implementation_priority: 'P0',
    integration_status: 'live',
    notes:
      'API key gratuita en developer.iatistandard.org. No publica licitaciones abiertas, pero mapea quién financia qué y dónde (pipeline + socios). Ya integrado (iati-datastore.ts).',
  },
  {
    id: 'iati-registry',
    label: 'IATI Registry (publicadores y datasets)',
    url: 'https://www.iatiregistry.org/',
    api_url: 'https://iatiregistry.org/api/3/action/package_search',
    access_method: 'ckan',
    auth: 'none',
    cost: 'free',
    geography: ['global'],
    levels: ['international_org', 'national'],
    opportunity_types: ['project_pipeline'],
    useful_for_ngo: 'media',
    fields_available: ['package', 'organization', 'resources', 'iati_identifier'],
    update_frequency: 'continua',
    implementation_priority: 'P1',
    integration_status: 'catalog',
    notes:
      'Portal CKAN con el índice de todos los publicadores IATI. Útil para descubrir financiadores; complementa al Datastore.',
  },
  {
    id: 'iati-codelists',
    label: 'IATI Codelists (vocabularios DAC/sector/región)',
    url: 'https://iatistandard.org/en/iati-standard/203/codelists/',
    api_url: 'https://codelists.codeforiati.org/api/json/en/Sector.json',
    access_method: 'api',
    auth: 'none',
    cost: 'free',
    geography: ['global'],
    levels: ['international_org'],
    opportunity_types: ['project_pipeline'],
    useful_for_ngo: 'baja',
    fields_available: ['code', 'name', 'description', 'category'],
    update_frequency: 'baja',
    implementation_priority: 'P2',
    integration_status: 'live',
    notes:
      'Codelists oficiales (sectores DAC, países, regiones) para normalizar/etiquetar. Ya integrado (iati-codelists.ts).',
  },
  {
    id: 'iati-country-data',
    label: 'IATI Country Data (d-portal por país)',
    url: 'https://d-portal.org/',
    api_url: 'https://d-portal.org/q',
    access_method: 'api',
    auth: 'none',
    cost: 'free',
    geography: ['global'],
    levels: ['international_org', 'national'],
    opportunity_types: ['project_pipeline'],
    useful_for_ngo: 'media',
    fields_available: ['country', 'sector', 'activity', 'budget', 'org'],
    update_frequency: 'continua',
    implementation_priority: 'P2',
    integration_status: 'catalog',
    notes:
      'd-portal expone datos IATI agregados por país (API q). Vista geográfica de quién financia dónde.',
  },

  // ───────────────────────────────────────────────────────────────────────
  // Open Contracting — OCDS (estándar + registro + tooling)
  // ───────────────────────────────────────────────────────────────────────
  {
    id: 'ocds-data-registry',
    label: 'Open Contracting Data Registry (OCDS)',
    url: 'https://data.open-contracting.org/',
    api_url: 'https://data.open-contracting.org/api/publishers/',
    access_method: 'ocds',
    auth: 'none',
    cost: 'free',
    geography: ['global'],
    levels: ['national', 'regional', 'local'],
    opportunity_types: ['tender', 'award_notice', 'procurement_plan'],
    useful_for_ngo: 'media',
    fields_available: ['publisher', 'country', 'ocds_url', 'date_from', 'date_to', 'data_type'],
    update_frequency: 'continua',
    implementation_priority: 'P1',
    integration_status: 'catalog',
    notes:
      'Directorio canónico de TODOS los publicadores OCDS del mundo (qué país publica contratación en estándar OCDS y dónde). Punto de partida para añadir conectores OCDS nuevos.',
  },
  {
    id: 'ocds-kingfisher',
    label: 'OCDS Kingfisher (almacén de datos OCDS)',
    url: 'https://kingfisher-process.readthedocs.io/',
    api_url: null,
    access_method: 'bulk_download',
    auth: 'none',
    cost: 'free',
    geography: ['global'],
    levels: ['national', 'regional', 'local'],
    opportunity_types: ['tender', 'award_notice'],
    useful_for_ngo: 'baja',
    fields_available: ['ocid', 'tender', 'awards', 'parties', 'planning'],
    update_frequency: 'periódica',
    implementation_priority: 'P3',
    integration_status: 'catalog',
    notes:
      'Herramienta de OCP para recolectar/almacenar datos OCDS a escala (self-hosted). Útil si se quiere ETL OCDS propio masivo.',
  },
  {
    id: 'ocds-standard',
    label: 'OCDS Standard (esquema de contratación abierta)',
    url: 'https://standard.open-contracting.org/latest/en/',
    api_url:
      'https://standard.open-contracting.org/schema/1__1__5/release-package-schema.json',
    access_method: 'bulk_download',
    auth: 'none',
    cost: 'free',
    geography: ['global'],
    levels: ['national', 'regional', 'local'],
    opportunity_types: ['tender', 'award_notice'],
    useful_for_ngo: 'baja',
    fields_available: ['schema', 'codelists', 'extensions'],
    update_frequency: 'baja',
    implementation_priority: 'P3',
    integration_status: 'catalog',
    notes:
      'Esquema JSON del estándar OCDS + codelists. Referencia para parsear cualquier feed OCDS de forma uniforme.',
  },

  // ───────────────────────────────────────────────────────────────────────
  // ONU — agencias y fondos
  // ───────────────────────────────────────────────────────────────────────
  {
    id: 'ungm',
    label: 'UNGM — United Nations Global Marketplace',
    url: 'https://www.ungm.org/',
    api_url: 'https://www.ungm.org/Public/Notice',
    access_method: 'html_scrape',
    auth: 'registration',
    cost: 'free',
    geography: ['global'],
    levels: ['international_org'],
    opportunity_types: [
      'tender',
      'request_for_proposal',
      'invitation_to_bid',
      'request_for_quotation',
      'expression_of_interest',
    ],
    useful_for_ngo: 'alta',
    fields_available: [
      'notice_id',
      'title',
      'agency',
      'deadline',
      'published',
      'unspsc',
      'country',
      'notice_type',
    ],
    update_frequency: 'diaria',
    implementation_priority: 'P0',
    integration_status: 'catalog',
    notes:
      'Mercado común de adquisiciones de TODO el sistema ONU. Registro gratuito (UNGM Vendor). No hay API pública oficial: el listado se obtiene de Public/Notice (scrape). La puerta de entrada nº1 a tenders ONU.',
  },
  {
    id: 'undp-quantum',
    label: 'UNDP Quantum / Procurement Notices (PNUD)',
    url: 'https://procurement-notices.undp.org/',
    api_url: 'https://procurement-notices.undp.org/api/getNotices',
    access_method: 'api',
    auth: 'none',
    cost: 'free',
    geography: ['global'],
    levels: ['international_org'],
    opportunity_types: [
      'tender',
      'request_for_proposal',
      'invitation_to_bid',
      'consultancy',
      'expression_of_interest',
    ],
    useful_for_ngo: 'alta',
    fields_available: [
      'id',
      'title',
      'procurement_process',
      'deadline',
      'posted',
      'office',
      'country',
    ],
    update_frequency: 'diaria',
    implementation_priority: 'P0',
    integration_status: 'catalog',
    notes:
      'PNUD publica sus avisos de adquisición con un endpoint JSON (getNotices) sin auth. Muy aprovechable para ONG (consultorías y servicios). Migrando a la plataforma Quantum.',
  },
  {
    id: 'unops',
    label: 'UNOPS — eSourcing / Procurement',
    url: 'https://www.unops.org/business-opportunities',
    api_url: 'https://esourcing.unops.org/',
    access_method: 'html_scrape',
    auth: 'registration',
    cost: 'free',
    geography: ['global'],
    levels: ['international_org'],
    opportunity_types: ['tender', 'request_for_proposal', 'invitation_to_bid', 'consultancy'],
    useful_for_ngo: 'media',
    fields_available: ['title', 'deadline', 'reference', 'country', 'category'],
    update_frequency: 'diaria',
    implementation_priority: 'P1',
    integration_status: 'catalog',
    notes:
      'Oficina de servicios de proyectos de la ONU. Oportunidades vía eSourcing (registro). Mucho contrato de obra/servicios; encaje ONG selectivo.',
  },
  {
    id: 'unicef',
    label: 'UNICEF Supply / Procurement',
    url: 'https://www.unicef.org/supply/working-unicef',
    api_url: 'https://www.ungm.org/Public/Notice',
    access_method: 'html_scrape',
    auth: 'registration',
    cost: 'free',
    geography: ['global'],
    levels: ['international_org'],
    opportunity_types: [
      'tender',
      'request_for_proposal',
      'invitation_to_bid',
      'implementing_partner_call',
    ],
    useful_for_ngo: 'alta',
    fields_available: ['title', 'deadline', 'reference', 'country', 'type'],
    update_frequency: 'diaria',
    implementation_priority: 'P1',
    integration_status: 'catalog',
    notes:
      'UNICEF publica adquisiciones y llamadas a socios implementadores (PCA/CSO). La mayoría se centraliza en UNGM; las CSO partnerships salen en sus oficinas de país.',
  },
  {
    id: 'wfp',
    label: 'WFP — World Food Programme Procurement',
    url: 'https://www.wfp.org/procurement',
    api_url: 'https://www.ungm.org/Public/Notice',
    access_method: 'html_scrape',
    auth: 'registration',
    cost: 'free',
    geography: ['global'],
    levels: ['international_org'],
    opportunity_types: [
      'tender',
      'invitation_to_bid',
      'request_for_proposal',
      'implementing_partner_call',
    ],
    useful_for_ngo: 'media',
    fields_available: ['title', 'deadline', 'reference', 'country'],
    update_frequency: 'diaria',
    implementation_priority: 'P2',
    integration_status: 'catalog',
    notes:
      'Programa Mundial de Alimentos. Field-Level Agreements con ONG en emergencias; licitaciones de bienes/servicios vía UNGM.',
  },
  {
    id: 'who',
    label: 'WHO — Procurement / Contracting (OMS)',
    url: 'https://www.who.int/about/procurement',
    api_url: 'https://www.ungm.org/Public/Notice',
    access_method: 'html_scrape',
    auth: 'registration',
    cost: 'free',
    geography: ['global'],
    levels: ['international_org'],
    opportunity_types: ['tender', 'request_for_proposal', 'consultancy'],
    useful_for_ngo: 'media',
    fields_available: ['title', 'deadline', 'reference', 'country'],
    update_frequency: 'diaria',
    implementation_priority: 'P2',
    integration_status: 'catalog',
    notes:
      'Organización Mundial de la Salud. Avisos en UNGM + APW (Agreement for Performance of Work) para entidades. Encaje ONG salud/cooperación.',
  },
  {
    id: 'fao',
    label: 'FAO — Procurement (agricultura/alimentación)',
    url: 'https://www.fao.org/unfao/procurement/en/',
    api_url: 'https://www.ungm.org/Public/Notice',
    access_method: 'html_scrape',
    auth: 'registration',
    cost: 'free',
    geography: ['global'],
    levels: ['international_org'],
    opportunity_types: ['tender', 'request_for_proposal', 'consultancy'],
    useful_for_ngo: 'media',
    fields_available: ['title', 'deadline', 'reference', 'country'],
    update_frequency: 'diaria',
    implementation_priority: 'P2',
    integration_status: 'catalog',
    notes:
      'Organización para la Alimentación y la Agricultura. Centraliza en UNGM. Encaje ONG desarrollo rural / seguridad alimentaria.',
  },
  {
    id: 'iom',
    label: 'IOM — Organización Internacional para las Migraciones',
    url: 'https://www.iom.int/procurement-opportunities',
    api_url: 'https://www.ungm.org/Public/Notice',
    access_method: 'html_scrape',
    auth: 'registration',
    cost: 'free',
    geography: ['global'],
    levels: ['international_org'],
    opportunity_types: [
      'tender',
      'request_for_proposal',
      'implementing_partner_call',
      'consultancy',
    ],
    useful_for_ngo: 'alta',
    fields_available: ['title', 'deadline', 'reference', 'country'],
    update_frequency: 'diaria',
    implementation_priority: 'P1',
    integration_status: 'catalog',
    notes:
      'OIM: migraciones y desplazamiento. Encaje ALTO para ONG de migrantes/refugiados. Avisos en su web + UNGM.',
  },
  {
    id: 'unhcr',
    label: 'UNHCR — ACNUR (refugiados)',
    url: 'https://www.unhcr.org/procurement',
    api_url: 'https://www.ungm.org/Public/Notice',
    access_method: 'html_scrape',
    auth: 'registration',
    cost: 'free',
    geography: ['global'],
    levels: ['international_org'],
    opportunity_types: [
      'tender',
      'request_for_proposal',
      'implementing_partner_call',
    ],
    useful_for_ngo: 'alta',
    fields_available: ['title', 'deadline', 'reference', 'country'],
    update_frequency: 'diaria',
    implementation_priority: 'P1',
    integration_status: 'catalog',
    notes:
      'ACNUR: acuerdos con socios (Partner Portal) + licitaciones en UNGM. Encaje ALTO para ONG de protección/refugio.',
  },
  {
    id: 'un-women',
    label: 'UN Women — Procurement (igualdad de género)',
    url: 'https://www.unwomen.org/en/about-us/procurement',
    api_url: 'https://www.ungm.org/Public/Notice',
    access_method: 'html_scrape',
    auth: 'registration',
    cost: 'free',
    geography: ['global'],
    levels: ['international_org'],
    opportunity_types: ['tender', 'request_for_proposal', 'call_for_proposal', 'consultancy'],
    useful_for_ngo: 'alta',
    fields_available: ['title', 'deadline', 'reference', 'country'],
    update_frequency: 'diaria',
    implementation_priority: 'P1',
    integration_status: 'catalog',
    notes:
      'ONU Mujeres: subvenciones y contratos de igualdad/empoderamiento. Encaje ALTO para ONG de género. UNGM + calls propias.',
  },
  {
    id: 'ifrc',
    label: 'IFRC — Federación Internacional Cruz Roja / Media Luna Roja',
    url: 'https://www.ifrc.org/who-we-are/governance/procurement',
    api_url: null,
    access_method: 'html_scrape',
    auth: 'registration',
    cost: 'free',
    geography: ['global'],
    levels: ['international_org'],
    opportunity_types: ['tender', 'request_for_proposal', 'invitation_to_bid'],
    useful_for_ngo: 'media',
    fields_available: ['title', 'deadline', 'reference', 'country'],
    update_frequency: 'semanal',
    implementation_priority: 'P2',
    integration_status: 'catalog',
    notes:
      'IFRC: adquisiciones humanitarias. No es ONU pero opera en el ecosistema. Encaje ONG de acción humanitaria.',
  },

  // ───────────────────────────────────────────────────────────────────────
  // Bancos multilaterales de desarrollo (MDB)
  // ───────────────────────────────────────────────────────────────────────
  {
    id: 'world-bank-procnotices',
    label: 'World Bank — Procurement Notices',
    url: 'https://projects.worldbank.org/en/projects-operations/procurement',
    api_url: 'https://search.worldbank.org/api/v3/procnotices',
    access_method: 'api',
    auth: 'none',
    cost: 'free',
    geography: ['global'],
    levels: ['mdb'],
    opportunity_types: [
      'tender',
      'request_for_proposal',
      'expression_of_interest',
      'consultancy',
      'procurement_plan',
    ],
    useful_for_ngo: 'media',
    fields_available: [
      'id',
      'project_id',
      'notice_type',
      'notice_lang_name',
      'country_name',
      'submission_deadline_date',
      'noticedate',
      'project_ctry_name',
    ],
    update_frequency: 'diaria',
    implementation_priority: 'P0',
    integration_status: 'live',
    notes:
      'API v3 pública (procnotices) sin auth. Avisos de adquisición de proyectos financiados por el Banco Mundial. Ya integrado (worldbank.ts).',
  },
  {
    id: 'world-bank-projects',
    label: 'World Bank — Projects API (cartera)',
    url: 'https://projects.worldbank.org/',
    api_url: 'https://search.worldbank.org/api/v3/projects',
    access_method: 'api',
    auth: 'none',
    cost: 'free',
    geography: ['global'],
    levels: ['mdb'],
    opportunity_types: ['project_pipeline'],
    useful_for_ngo: 'media',
    fields_available: [
      'id',
      'project_name',
      'countryname',
      'totalcommamt',
      'sector',
      'theme',
      'boardapprovaldate',
    ],
    update_frequency: 'diaria',
    implementation_priority: 'P1',
    integration_status: 'live',
    notes:
      'API v3 de proyectos (cartera, sectores, montos). Pipeline anticipado: de qué proyectos saldrán adquisiciones. Ya integrado (worldbank.ts).',
  },
  {
    id: 'un-development-business',
    label: 'UN Development Business (UNDB)',
    url: 'https://devbusiness.un.org/',
    api_url: null,
    access_method: 'html_scrape',
    auth: 'login',
    cost: 'freemium',
    geography: ['global'],
    levels: ['mdb', 'international_org'],
    opportunity_types: [
      'tender',
      'expression_of_interest',
      'procurement_plan',
      'project_pipeline',
    ],
    useful_for_ngo: 'media',
    fields_available: ['title', 'deadline', 'country', 'sector', 'funding_agency'],
    update_frequency: 'diaria',
    implementation_priority: 'P2',
    integration_status: 'catalog',
    notes:
      'Agregador histórico de oportunidades de bancos de desarrollo y agencias ONU. Suscripción de pago para el detalle (freemium).',
  },
  {
    id: 'adb',
    label: 'ADB — Asian Development Bank',
    url: 'https://www.adb.org/projects/tenders',
    api_url: 'https://www.adb.org/projects/tenders/feed',
    access_method: 'rss',
    auth: 'none',
    cost: 'free',
    geography: ['asia', 'pacific'],
    levels: ['mdb'],
    opportunity_types: [
      'tender',
      'expression_of_interest',
      'consultancy',
      'procurement_plan',
    ],
    useful_for_ngo: 'media',
    fields_available: ['title', 'deadline', 'country', 'sector', 'type', 'link'],
    update_frequency: 'diaria',
    implementation_priority: 'P2',
    integration_status: 'catalog',
    notes:
      'Banco Asiático de Desarrollo. Tenders con feed RSS público. Consultorías (CMS) y EOIs. Cobertura Asia-Pacífico.',
  },
  {
    id: 'afdb',
    label: 'AfDB — African Development Bank',
    url: 'https://www.afdb.org/en/projects-and-operations/procurement',
    api_url: null,
    access_method: 'html_scrape',
    auth: 'none',
    cost: 'free',
    geography: ['africa'],
    levels: ['mdb'],
    opportunity_types: [
      'tender',
      'expression_of_interest',
      'consultancy',
      'procurement_plan',
    ],
    useful_for_ngo: 'media',
    fields_available: ['title', 'deadline', 'country', 'sector', 'type'],
    update_frequency: 'diaria',
    implementation_priority: 'P2',
    integration_status: 'catalog',
    notes:
      'Banco Africano de Desarrollo. Avisos de adquisición y EOIs. Cobertura África.',
  },
  {
    id: 'idb',
    label: 'IDB — Inter-American Development Bank (BID)',
    url: 'https://www.iadb.org/en/how-we-can-work-together/public-sector/procurement',
    api_url: 'https://www.iadb.org/en/projects-search',
    access_method: 'html_scrape',
    auth: 'none',
    cost: 'free',
    geography: ['latam'],
    levels: ['mdb'],
    opportunity_types: [
      'tender',
      'expression_of_interest',
      'consultancy',
      'project_pipeline',
    ],
    useful_for_ngo: 'media',
    fields_available: ['title', 'deadline', 'country', 'sector', 'project'],
    update_frequency: 'diaria',
    implementation_priority: 'P2',
    integration_status: 'catalog',
    notes:
      'Banco Interamericano de Desarrollo. Adquisiciones y proyectos en América Latina y el Caribe. Idioma ES/EN.',
  },
  {
    id: 'ebrd',
    label: 'EBRD — European Bank for Reconstruction and Development',
    url: 'https://www.ebrd.com/work-with-us/procurement.html',
    api_url: 'https://www.ebrd.com/cs/Satellite?c=Page&pagename=EBRD/procurement/notices',
    access_method: 'html_scrape',
    auth: 'none',
    cost: 'free',
    geography: ['europe', 'central_asia', 'mena'],
    levels: ['mdb'],
    opportunity_types: [
      'tender',
      'expression_of_interest',
      'consultancy',
      'procurement_plan',
    ],
    useful_for_ngo: 'baja',
    fields_available: ['title', 'deadline', 'country', 'sector', 'type'],
    update_frequency: 'diaria',
    implementation_priority: 'P3',
    integration_status: 'catalog',
    notes:
      'BERD: reconstrucción y desarrollo en Europa del Este/Asia Central. Sesgo a infraestructura/sector privado; encaje ONG bajo.',
  },
  {
    id: 'eib',
    label: 'EIB — European Investment Bank',
    url: 'https://www.eib.org/en/about/procurement/index.htm',
    api_url: 'https://www.eib.org/en/projects/pipelines/index.htm',
    access_method: 'html_scrape',
    auth: 'none',
    cost: 'free',
    geography: ['europe', 'global'],
    levels: ['mdb', 'eu'],
    opportunity_types: ['tender', 'consultancy', 'project_pipeline'],
    useful_for_ngo: 'baja',
    fields_available: ['title', 'deadline', 'country', 'sector', 'project'],
    update_frequency: 'semanal',
    implementation_priority: 'P3',
    integration_status: 'catalog',
    notes:
      'Banco Europeo de Inversiones. Corporate procurement + pipeline de proyectos. Encaje ONG bajo (infra/financiero).',
  },
  {
    id: 'ceb',
    label: 'CEB — Council of Europe Development Bank',
    url: 'https://coebank.org/en/project-financing/procurement/',
    api_url: null,
    access_method: 'html_scrape',
    auth: 'none',
    cost: 'free',
    geography: ['europe'],
    levels: ['mdb'],
    opportunity_types: ['tender', 'project_pipeline'],
    useful_for_ngo: 'media',
    fields_available: ['title', 'deadline', 'country', 'sector'],
    update_frequency: 'semanal',
    implementation_priority: 'P3',
    integration_status: 'catalog',
    notes:
      'Banco de Desarrollo del Consejo de Europa. Financia proyectos sociales (vivienda, integración, refugiados). Encaje ONG medio.',
  },
  {
    id: 'isdb',
    label: 'IsDB — Islamic Development Bank',
    url: 'https://www.isdb.org/project-procurement',
    api_url: null,
    access_method: 'html_scrape',
    auth: 'none',
    cost: 'free',
    geography: ['mena', 'africa', 'asia'],
    levels: ['mdb'],
    opportunity_types: ['tender', 'expression_of_interest', 'consultancy'],
    useful_for_ngo: 'baja',
    fields_available: ['title', 'deadline', 'country', 'sector'],
    update_frequency: 'semanal',
    implementation_priority: 'P3',
    integration_status: 'catalog',
    notes:
      'Banco Islámico de Desarrollo. Países miembros OIC. Adquisiciones de proyectos.',
  },
  {
    id: 'aiib',
    label: 'AIIB — Asian Infrastructure Investment Bank',
    url: 'https://www.aiib.org/en/opportunities/business/project-procurement/index.html',
    api_url: null,
    access_method: 'html_scrape',
    auth: 'none',
    cost: 'free',
    geography: ['asia', 'global'],
    levels: ['mdb'],
    opportunity_types: ['tender', 'consultancy', 'project_pipeline'],
    useful_for_ngo: 'baja',
    fields_available: ['title', 'deadline', 'country', 'sector'],
    update_frequency: 'semanal',
    implementation_priority: 'P3',
    integration_status: 'catalog',
    notes:
      'Banco Asiático de Inversión en Infraestructura. Sesgo infraestructura; encaje ONG bajo.',
  },
  {
    id: 'caf',
    label: 'CAF — Banco de Desarrollo de América Latina',
    url: 'https://www.caf.com/es/sobre-caf/compras-y-contrataciones/',
    api_url: null,
    access_method: 'html_scrape',
    auth: 'none',
    cost: 'free',
    geography: ['latam'],
    levels: ['mdb'],
    opportunity_types: ['tender', 'consultancy', 'project_pipeline'],
    useful_for_ngo: 'baja',
    fields_available: ['title', 'deadline', 'country', 'sector'],
    update_frequency: 'semanal',
    implementation_priority: 'P3',
    integration_status: 'catalog',
    notes:
      'CAF: banco de desarrollo de América Latina. Compras y contrataciones en español. Sesgo infraestructura.',
  },
  {
    id: 'cdb',
    label: 'CDB — Caribbean Development Bank',
    url: 'https://www.caribank.org/work-with-us/procurement',
    api_url: null,
    access_method: 'html_scrape',
    auth: 'none',
    cost: 'free',
    geography: ['caribbean'],
    levels: ['mdb'],
    opportunity_types: ['tender', 'expression_of_interest', 'consultancy'],
    useful_for_ngo: 'baja',
    fields_available: ['title', 'deadline', 'country', 'sector'],
    update_frequency: 'semanal',
    implementation_priority: 'P3',
    integration_status: 'catalog',
    notes:
      'Banco de Desarrollo del Caribe. Cobertura regional pequeña. Adquisiciones y EOIs.',
  },
  {
    id: 'ndf',
    label: 'NDF — Nordic Development Fund',
    url: 'https://www.ndf.int/our-work/procurement.html',
    api_url: null,
    access_method: 'html_scrape',
    auth: 'none',
    cost: 'free',
    geography: ['global'],
    levels: ['mdb'],
    opportunity_types: ['tender', 'consultancy', 'project_pipeline'],
    useful_for_ngo: 'media',
    fields_available: ['title', 'deadline', 'country', 'sector'],
    update_frequency: 'mensual',
    implementation_priority: 'P3',
    integration_status: 'catalog',
    notes:
      'Fondo Nórdico de Desarrollo. Clima y desarrollo en países de renta baja. Encaje ONG clima/desarrollo medio.',
  },

  // ───────────────────────────────────────────────────────────────────────
  // Unión Europea
  // ───────────────────────────────────────────────────────────────────────
  {
    id: 'ted',
    label: 'TED — Tenders Electronic Daily (DOUE)',
    url: 'https://ted.europa.eu/',
    api_url: 'https://api.ted.europa.eu/v3/notices/search',
    access_method: 'api',
    auth: 'api_key',
    cost: 'free',
    geography: ['eu', 'eea'],
    levels: ['eu', 'national', 'regional', 'local'],
    opportunity_types: ['tender', 'award_notice', 'framework_agreement'],
    useful_for_ngo: 'alta',
    fields_available: [
      'publication_number',
      'title',
      'buyer_name',
      'buyer_country',
      'cpv',
      'deadline',
      'publication_date',
      'value',
    ],
    update_frequency: 'diaria',
    implementation_priority: 'P0',
    integration_status: 'live',
    notes:
      'Diario oficial de licitaciones de la UE por encima de umbrales. API v3 (Search). Ya integrado (ted.ts). Filtrable por CPV social.',
  },
  {
    id: 'ted-api',
    label: 'TED Developer Portal (API + bulk)',
    url: 'https://docs.ted.europa.eu/api/index.html',
    api_url: 'https://api.ted.europa.eu/v3/notices/search',
    access_method: 'api',
    auth: 'api_key',
    cost: 'free',
    geography: ['eu', 'eea'],
    levels: ['eu', 'national', 'regional', 'local'],
    opportunity_types: ['tender', 'award_notice'],
    useful_for_ngo: 'alta',
    fields_available: ['notice', 'eforms_xml', 'cpv', 'value', 'deadline'],
    update_frequency: 'diaria',
    implementation_priority: 'P1',
    integration_status: 'live',
    notes:
      'Documentación del API TED (eForms, expert search, bulk). Misma fuente que `ted` (conector ya vivo); entrada separada para el canal de developers/bulk.',
  },
  {
    id: 'eu-funding-tenders-sedia',
    label: 'EU Funding & Tenders Portal (SEDIA)',
    url: 'https://ec.europa.eu/info/funding-tenders/opportunities/portal/screen/home',
    api_url:
      'https://api.tech.ec.europa.eu/search-api/prod/rest/search?apiKey=SEDIA&text=***',
    access_method: 'api',
    auth: 'api_key',
    cost: 'free',
    geography: ['eu', 'global'],
    levels: ['eu'],
    opportunity_types: ['grant', 'call_for_proposal', 'tender'],
    useful_for_ngo: 'alta',
    fields_available: [
      'identifier',
      'title',
      'programme',
      'deadline',
      'status',
      'type_of_action',
      'topic',
    ],
    update_frequency: 'diaria',
    implementation_priority: 'P0',
    integration_status: 'live',
    notes:
      'Portal único de calls/grants UE (Horizon, CERV, Erasmus+, AMIF…) + tenders de la Comisión. API SEDIA Search (apiKey pública "SEDIA"). Ya integrado (sedia.ts). Encaje ALTO.',
  },
  {
    id: 'cordis',
    label: 'CORDIS — Resultados y proyectos I+D de la UE',
    url: 'https://cordis.europa.eu/',
    api_url: 'https://cordis.europa.eu/data/',
    access_method: 'bulk_download',
    auth: 'none',
    cost: 'free',
    geography: ['eu'],
    levels: ['eu'],
    opportunity_types: ['project_pipeline'],
    useful_for_ngo: 'media',
    fields_available: ['project_id', 'title', 'programme', 'participants', 'funding', 'topics'],
    update_frequency: 'periódica',
    implementation_priority: 'P2',
    integration_status: 'catalog',
    notes:
      'Base de datos de proyectos financiados por la UE (no convocatorias abiertas). Inteligencia: quién gana qué, con quién consorciarse.',
  },
  {
    id: 'e-certis',
    label: 'e-Certis — Certificados exigidos por país (UE)',
    url: 'https://ec.europa.eu/tools/ecertis/',
    api_url: 'https://ec.europa.eu/tools/ecertis/api/',
    access_method: 'api',
    auth: 'none',
    cost: 'free',
    geography: ['eu', 'eea'],
    levels: ['eu', 'national'],
    opportunity_types: ['tender'],
    useful_for_ngo: 'baja',
    fields_available: ['criterion', 'evidence', 'country', 'issuer'],
    update_frequency: 'baja',
    implementation_priority: 'P3',
    integration_status: 'catalog',
    notes:
      'Mapa de qué certificados/evidencias exige cada Estado miembro en contratación. No es fuente de oportunidades; ayuda a preparar documentación.',
  },
  {
    id: 'espd',
    label: 'ESPD — European Single Procurement Document',
    url: 'https://docs.ted.europa.eu/ESPD-EDM/latest/index.html',
    api_url: null,
    access_method: 'bulk_download',
    auth: 'none',
    cost: 'free',
    geography: ['eu', 'eea'],
    levels: ['eu', 'national'],
    opportunity_types: ['tender'],
    useful_for_ngo: 'baja',
    fields_available: ['model', 'criteria', 'xsd'],
    update_frequency: 'baja',
    implementation_priority: 'P3',
    integration_status: 'catalog',
    notes:
      'Modelo de datos del DEUC (declaración responsable única europea). Soporte documental para licitar en la UE; no es fuente de oportunidades.',
  },

  // ───────────────────────────────────────────────────────────────────────
  // España
  // ───────────────────────────────────────────────────────────────────────
  {
    id: 'placsp',
    label: 'PLACSP — Plataforma de Contratación del Sector Público (ATOM)',
    url: 'https://contrataciondelestado.es/',
    api_url:
      'https://contrataciondelestado.es/sindicacion/sindicacion_643/licitacionesPerfilesContratanteCompleto3.atom',
    access_method: 'atom',
    auth: 'none',
    cost: 'free',
    geography: ['ES'],
    levels: ['national', 'regional', 'local'],
    opportunity_types: ['tender', 'award_notice', 'framework_agreement'],
    useful_for_ngo: 'alta',
    fields_available: [
      'id',
      'title',
      'contracting_authority',
      'cpv',
      'deadline',
      'value',
      'status',
      'place',
    ],
    update_frequency: 'continua',
    implementation_priority: 'P0',
    integration_status: 'live',
    notes:
      'Sindicación ATOM oficial de TODAS las licitaciones públicas españolas (AGE + CCAA + EELL adheridas). Ya integrado (place.ts). Sin auth.',
  },
  {
    id: 'bdns',
    label: 'BDNS — Base de Datos Nacional de Subvenciones',
    url: 'https://www.infosubvenciones.es/bdnstrans/GE/es/index',
    api_url: 'https://www.infosubvenciones.es/bdnstrans/api/convocatorias/busqueda',
    access_method: 'api',
    auth: 'none',
    cost: 'free',
    geography: ['ES'],
    levels: ['national', 'regional', 'local'],
    opportunity_types: ['grant'],
    useful_for_ngo: 'alta',
    fields_available: [
      'numeroConvocatoria',
      'descripcion',
      'organo',
      'fechaRecepcion',
      'importeTotal',
      'tipoBeneficiario',
      'instrumentos',
      'sectores',
    ],
    update_frequency: 'diaria',
    implementation_priority: 'P0',
    integration_status: 'live',
    notes:
      'Registro nacional de TODAS las convocatorias de subvenciones de España. API pública (BDNSTrans). Ya integrado (bdns.ts). Encaje ALTO: muchas líneas para tercer sector.',
  },
  {
    id: 'boe',
    label: 'BOE — Boletín Oficial del Estado (anuncios/subvenciones)',
    url: 'https://www.boe.es/',
    api_url: 'https://www.boe.es/datosabiertos/api/boe/sumario/',
    access_method: 'api',
    auth: 'none',
    cost: 'free',
    geography: ['ES'],
    levels: ['national'],
    opportunity_types: ['grant', 'tender', 'award_notice'],
    useful_for_ngo: 'media',
    fields_available: ['identificador', 'titulo', 'seccion', 'departamento', 'fecha', 'url_pdf'],
    update_frequency: 'diaria',
    implementation_priority: 'P2',
    integration_status: 'catalog',
    notes:
      'Diario oficial estatal. API de datos abiertos (sumario diario). Convocatorias y anuncios; menos estructurado que BDNS para subvenciones.',
  },
  {
    id: 'datos-gob-es',
    label: 'datos.gob.es — Catálogo nacional de datos abiertos (CKAN)',
    url: 'https://datos.gob.es/',
    api_url: 'https://datos.gob.es/apidata',
    access_method: 'ckan',
    auth: 'none',
    cost: 'free',
    geography: ['ES'],
    levels: ['national', 'regional', 'local'],
    opportunity_types: ['grant', 'tender'],
    useful_for_ngo: 'baja',
    fields_available: ['dataset', 'publisher', 'theme', 'distribution', 'format'],
    update_frequency: 'continua',
    implementation_priority: 'P3',
    integration_status: 'catalog',
    notes:
      'Catálogo federado de datos abiertos de España (CKAN/DCAT). Descubre datasets de subvenciones/contratación de CCAA y EELL. Indirecto.',
  },

  // ───────────────────────────────────────────────────────────────────────
  // Estados Unidos
  // ───────────────────────────────────────────────────────────────────────
  {
    id: 'sam-gov',
    label: 'SAM.gov — Contract Opportunities (federal USA)',
    url: 'https://sam.gov/content/opportunities',
    api_url: 'https://api.sam.gov/opportunities/v2/search',
    access_method: 'api',
    auth: 'api_key',
    cost: 'free',
    geography: ['US', 'global'],
    levels: ['national'],
    opportunity_types: [
      'tender',
      'request_for_proposal',
      'request_for_quotation',
      'invitation_to_bid',
      'consultancy',
    ],
    useful_for_ngo: 'media',
    fields_available: [
      'noticeId',
      'title',
      'department',
      'naicsCode',
      'responseDeadLine',
      'postedDate',
      'placeOfPerformance',
      'type',
    ],
    update_frequency: 'diaria',
    implementation_priority: 'P1',
    integration_status: 'catalog',
    notes:
      'Portal federal de contratación de EE. UU. API v2 con api_key (data.gov gratuita). Incluye USAID. Encaje ONG vía USAID/cooperación.',
  },
  {
    id: 'grants-gov',
    label: 'Grants.gov — Federal grants (USA)',
    url: 'https://www.grants.gov/',
    api_url: 'https://api.grants.gov/v1/api/search2',
    access_method: 'api',
    auth: 'none',
    cost: 'free',
    geography: ['US', 'global'],
    levels: ['national'],
    opportunity_types: ['grant', 'call_for_proposal'],
    useful_for_ngo: 'alta',
    fields_available: [
      'opportunityId',
      'opportunityTitle',
      'agencyCode',
      'closeDate',
      'openDate',
      'cfdaList',
      'eligibilities',
      'fundingCategories',
    ],
    update_frequency: 'diaria',
    implementation_priority: 'P0',
    integration_status: 'planned',
    notes:
      'Portal federal de subvenciones de EE. UU. API search2 pública SIN auth. Muchas elegibles para nonprofits internacionales (incl. USAID/Dept. State). Lo añade el Sprint Gb (live FREE).',
  },
  {
    id: 'usaspending',
    label: 'USAspending.gov — Gasto federal (USA)',
    url: 'https://www.usaspending.gov/',
    api_url: 'https://api.usaspending.gov/api/v2/',
    access_method: 'api',
    auth: 'none',
    cost: 'free',
    geography: ['US', 'global'],
    levels: ['national'],
    opportunity_types: ['award_notice'],
    useful_for_ngo: 'baja',
    fields_available: ['award_id', 'recipient', 'awarding_agency', 'amount', 'cfda', 'naics'],
    update_frequency: 'diaria',
    implementation_priority: 'P2',
    integration_status: 'catalog',
    notes:
      'Datos de adjudicaciones federales de EE. UU. (grants + contratos). Inteligencia de competencia/financiadores, no oportunidades abiertas. API v2 sin auth.',
  },
  {
    id: 'foreign-assistance',
    label: 'ForeignAssistance.gov — Ayuda exterior USA',
    url: 'https://www.foreignassistance.gov/',
    api_url: 'https://api.foreignassistance.gov/',
    access_method: 'api',
    auth: 'none',
    cost: 'free',
    geography: ['global'],
    levels: ['national'],
    opportunity_types: ['project_pipeline', 'award_notice'],
    useful_for_ngo: 'media',
    fields_available: ['country', 'agency', 'sector', 'amount', 'fiscal_year'],
    update_frequency: 'periódica',
    implementation_priority: 'P3',
    integration_status: 'catalog',
    notes:
      'Datos de ayuda exterior de EE. UU. por país/sector. Pipeline e inteligencia de prioridades de donantes; no oportunidades abiertas.',
  },

  // ───────────────────────────────────────────────────────────────────────
  // Nacionales prioritarios (resto del mundo)
  // ───────────────────────────────────────────────────────────────────────
  {
    id: 'uk-find-a-tender',
    label: 'UK — Find a Tender Service (OCDS)',
    url: 'https://www.find-tender.service.gov.uk/',
    api_url: 'https://www.find-tender.service.gov.uk/api/1.0/ocdsReleasePackages',
    access_method: 'ocds',
    auth: 'none',
    cost: 'free',
    geography: ['GB'],
    levels: ['national', 'regional', 'local'],
    opportunity_types: ['tender', 'award_notice', 'framework_agreement'],
    useful_for_ngo: 'media',
    fields_available: ['ocid', 'tender', 'awards', 'parties', 'buyer', 'value', 'tender_period'],
    update_frequency: 'diaria',
    implementation_priority: 'P0',
    integration_status: 'live',
    notes:
      'Portal de contratación del Reino Unido sobre umbral, en OCDS (releasePackages). Ya integrado (uk-ocds.ts). Sin auth.',
  },
  {
    id: 'uk-contracts-finder',
    label: 'UK — Contracts Finder (bajo umbral, OCDS)',
    url: 'https://www.contractsfinder.service.gov.uk/',
    api_url: 'https://www.contractsfinder.service.gov.uk/Published/Notices/OCDS/Search',
    access_method: 'ocds',
    auth: 'none',
    cost: 'free',
    geography: ['GB'],
    levels: ['national', 'regional', 'local'],
    opportunity_types: ['tender', 'award_notice'],
    useful_for_ngo: 'media',
    fields_available: ['ocid', 'tender', 'awards', 'buyer', 'value'],
    update_frequency: 'diaria',
    implementation_priority: 'P1',
    integration_status: 'catalog',
    notes:
      'Contratos públicos del Reino Unido por debajo de umbral (más accesibles a ONG locales). OCDS sin auth. Complementa a Find a Tender.',
  },
  {
    id: 'canadabuys',
    label: 'Canadá — CanadaBuys / Open Canada',
    url: 'https://canadabuys.canada.ca/en/tender-opportunities',
    api_url:
      'https://canadabuys.canada.ca/opendata/pub/openTenderNotice-ouvertAvisAppelOffres.csv',
    access_method: 'bulk_download',
    auth: 'none',
    cost: 'free',
    geography: ['CA'],
    levels: ['national', 'regional'],
    opportunity_types: ['tender', 'request_for_proposal', 'request_for_quotation'],
    useful_for_ngo: 'media',
    fields_available: ['referenceNumber', 'title', 'category', 'closingDate', 'publishedDate', 'gsin'],
    update_frequency: 'diaria',
    implementation_priority: 'P2',
    integration_status: 'catalog',
    notes:
      'Portal federal de Canadá. Open tender notices en CSV (open data). También en open.canada.ca. Idioma EN/FR.',
  },
  {
    id: 'austender',
    label: 'Australia — AusTender (tenders federales)',
    url: 'https://www.tenders.gov.au/',
    api_url: 'https://api.tenders.gov.au/ocds/findByDates/',
    access_method: 'ocds',
    auth: 'none',
    cost: 'free',
    geography: ['AU'],
    levels: ['national'],
    opportunity_types: ['tender', 'request_for_proposal', 'expression_of_interest'],
    useful_for_ngo: 'media',
    fields_available: ['ocid', 'tender', 'buyer', 'value', 'tender_period', 'category'],
    update_frequency: 'diaria',
    implementation_priority: 'P1',
    integration_status: 'planned',
    notes:
      'Portal federal de Australia con API OCDS pública (findByDates) sin auth. Lo añade el Sprint Gb (live FREE).',
  },
  {
    id: 'grantconnect',
    label: 'Australia — GrantConnect (grants federales)',
    url: 'https://www.grants.gov.au/',
    api_url: 'https://www.grants.gov.au/Go/List',
    access_method: 'html_scrape',
    auth: 'registration',
    cost: 'free',
    geography: ['AU'],
    levels: ['national'],
    opportunity_types: ['grant', 'call_for_proposal'],
    useful_for_ngo: 'alta',
    fields_available: ['grantId', 'title', 'agency', 'closeDate', 'category', 'eligibility'],
    update_frequency: 'diaria',
    implementation_priority: 'P2',
    integration_status: 'catalog',
    notes:
      'Portal federal australiano de subvenciones (GO — Grant Opportunities). Registro para alertas; listado público scrapeable. Encaje ONG alto.',
  },
  {
    id: 'chile-mercadopublico',
    label: 'Chile — Mercado Público (ChileCompra)',
    url: 'https://www.mercadopublico.cl/',
    api_url: 'https://api.mercadopublico.cl/servicios/v1/publico/licitaciones.json',
    access_method: 'api',
    auth: 'api_key',
    cost: 'free',
    geography: ['CL'],
    levels: ['national', 'regional', 'local'],
    opportunity_types: ['tender', 'request_for_proposal'],
    useful_for_ngo: 'media',
    fields_available: ['CodigoExterno', 'Nombre', 'Comprador', 'FechaCierre', 'Estado', 'MontoEstimado'],
    update_frequency: 'continua',
    implementation_priority: 'P2',
    integration_status: 'catalog',
    notes:
      'ChileCompra: API pública de licitaciones (ticket gratuito como api_key). Idioma ES. Cobertura amplia del Estado chileno.',
  },
  {
    id: 'colombia-secop',
    label: 'Colombia — SECOP (Socrata / OCDS)',
    url: 'https://www.colombiacompra.gov.co/secop',
    api_url: 'https://www.datos.gov.co/resource/p6dx-8zbt.json',
    access_method: 'socrata',
    auth: 'none',
    cost: 'free',
    geography: ['CO'],
    levels: ['national', 'regional', 'local'],
    opportunity_types: ['tender', 'request_for_proposal', 'award_notice'],
    useful_for_ngo: 'media',
    fields_available: [
      'id_del_proceso',
      'entidad',
      'objeto_del_contrato',
      'fecha_de_publicacion',
      'estado',
      'valor',
    ],
    update_frequency: 'continua',
    implementation_priority: 'P1',
    integration_status: 'planned',
    notes:
      'Colombia Compra Eficiente. Datos SECOP I/II en Socrata (datos.gov.co) sin auth + publicación OCDS. Idioma ES. Lo añade el Sprint Gb (live FREE).',
  },
  {
    id: 'paraguay-dncp',
    label: 'Paraguay — DNCP (OCDS)',
    url: 'https://www.contrataciones.gov.py/',
    api_url: 'https://www.contrataciones.gov.py/datos/api/v3/doc/search/processes',
    access_method: 'ocds',
    auth: 'none',
    cost: 'free',
    geography: ['PY'],
    levels: ['national', 'regional', 'local'],
    opportunity_types: ['tender', 'award_notice'],
    useful_for_ngo: 'media',
    fields_available: ['ocid', 'tender', 'buyer', 'value', 'tender_period', 'planning'],
    update_frequency: 'continua',
    implementation_priority: 'P1',
    integration_status: 'planned',
    notes:
      'Dirección Nacional de Contrataciones Públicas de Paraguay. API OCDS v3 pública sin auth. Idioma ES. Lo añade el Sprint Gb (live FREE).',
  },
  {
    id: 'ukraine-prozorro',
    label: 'Ucrania — Prozorro (OCDS)',
    url: 'https://prozorro.gov.ua/en',
    api_url: 'https://public.api.openprocurement.org/api/2.5/tenders',
    access_method: 'ocds',
    auth: 'none',
    cost: 'free',
    geography: ['UA'],
    levels: ['national', 'regional', 'local'],
    opportunity_types: ['tender', 'award_notice', 'framework_agreement'],
    useful_for_ngo: 'media',
    fields_available: ['id', 'tenderID', 'title', 'value', 'enquiryPeriod', 'tenderPeriod', 'status'],
    update_frequency: 'continua',
    implementation_priority: 'P1',
    integration_status: 'planned',
    notes:
      'Sistema de contratación de Ucrania (referente OCDS mundial). API openprocurement pública sin auth. Relevante para reconstrucción. Lo añade el Sprint Gb (live FREE).',
  },
  {
    id: 'brazil-compras',
    label: 'Brasil — Compras.gov.br / PNCP',
    url: 'https://www.gov.br/compras/pt-br',
    api_url: 'https://pncp.gov.br/api/consulta/v1/contratacoes/proposta',
    access_method: 'api',
    auth: 'none',
    cost: 'free',
    geography: ['BR'],
    levels: ['national', 'regional', 'local'],
    opportunity_types: ['tender', 'request_for_proposal'],
    useful_for_ngo: 'media',
    fields_available: [
      'numeroControlePNCP',
      'objetoCompra',
      'orgaoEntidade',
      'dataEncerramentoProposta',
      'valorTotalEstimado',
      'modalidadeNome',
    ],
    update_frequency: 'continua',
    implementation_priority: 'P2',
    integration_status: 'catalog',
    notes:
      'Portal Nacional de Contratações Públicas de Brasil (PNCP) + Compras.gov.br. API pública sin auth. Idioma PT.',
  },
  {
    id: 'mexico-compranet',
    label: 'México — CompraNet / Contrataciones Abiertas (OCDS)',
    url: 'https://compranet.hacienda.gob.mx/',
    api_url: 'https://api.datos.gob.mx/v1/contrataciones',
    access_method: 'ocds',
    auth: 'none',
    cost: 'free',
    geography: ['MX'],
    levels: ['national', 'regional', 'local'],
    opportunity_types: ['tender', 'award_notice'],
    useful_for_ngo: 'media',
    fields_available: ['ocid', 'tender', 'buyer', 'value', 'tender_period'],
    update_frequency: 'periódica',
    implementation_priority: 'P3',
    integration_status: 'catalog',
    notes:
      'CompraNet (Hacienda) con publicación en estándar de Contrataciones Abiertas (OCDS) vía datos.gob.mx. Idioma ES.',
  },
  {
    id: 'portugal-base',
    label: 'Portugal — BASE / Portal BASE.gov',
    url: 'https://www.base.gov.pt/',
    api_url: 'https://www.base.gov.pt/Base4/pt/resultados/',
    access_method: 'html_scrape',
    auth: 'none',
    cost: 'free',
    geography: ['PT'],
    levels: ['national', 'regional', 'local'],
    opportunity_types: ['tender', 'award_notice'],
    useful_for_ngo: 'media',
    fields_available: ['id', 'objeto', 'entidade', 'prazo', 'preco_base', 'tipo'],
    update_frequency: 'diaria',
    implementation_priority: 'P2',
    integration_status: 'catalog',
    notes:
      'Portal de contratos públicos de Portugal. Anuncios también en Diário da República. Idioma PT; vecino y relevante para ONG ibéricas.',
  },
  {
    id: 'france-boamp',
    label: 'Francia — BOAMP / data.gouv.fr',
    url: 'https://www.boamp.fr/',
    api_url:
      'https://www.boamp.fr/api/explore/v2.1/catalog/datasets/boamp/records',
    access_method: 'api',
    auth: 'none',
    cost: 'free',
    geography: ['FR'],
    levels: ['national', 'regional', 'local'],
    opportunity_types: ['tender', 'award_notice'],
    useful_for_ngo: 'media',
    fields_available: ['idweb', 'objet', 'acheteur', 'datelimitereponse', 'dateparution', 'famille'],
    update_frequency: 'diaria',
    implementation_priority: 'P2',
    integration_status: 'catalog',
    notes:
      'Boletín oficial de anuncios de contratos públicos de Francia. API Opendatasoft (Explore v2.1) sin auth. Idioma FR.',
  },
  {
    id: 'italy-anac',
    label: 'Italia — ANAC (dati.anticorruzione)',
    url: 'https://dati.anticorruzione.it/',
    api_url: 'https://dati.anticorruzione.it/opendata/api/3/action/package_search',
    access_method: 'ckan',
    auth: 'none',
    cost: 'free',
    geography: ['IT'],
    levels: ['national', 'regional', 'local'],
    opportunity_types: ['tender', 'award_notice'],
    useful_for_ngo: 'baja',
    fields_available: ['cig', 'oggetto', 'stazione_appaltante', 'importo', 'data'],
    update_frequency: 'periódica',
    implementation_priority: 'P3',
    integration_status: 'catalog',
    notes:
      'Autoridad Anticorrupción de Italia: open data de contratación (CKAN). Más orientado a transparencia/datos que a oportunidades abiertas. Idioma IT.',
  },
  {
    id: 'south-africa-etender',
    label: 'Sudáfrica — eTender Publication Portal',
    url: 'https://www.etenders.gov.za/',
    api_url: 'https://www.etenders.gov.za/Home/opendata',
    access_method: 'bulk_download',
    auth: 'none',
    cost: 'free',
    geography: ['ZA'],
    levels: ['national', 'regional'],
    opportunity_types: ['tender', 'request_for_quotation'],
    useful_for_ngo: 'media',
    fields_available: ['tender_number', 'description', 'department', 'closing_date', 'category'],
    update_frequency: 'diaria',
    implementation_priority: 'P3',
    integration_status: 'catalog',
    notes:
      'Portal nacional de licitaciones de Sudáfrica con sección open data (JSON). Idioma EN.',
  },
  {
    id: 'nigeria-nocopo',
    label: 'Nigeria — NOCOPO (BPP)',
    url: 'https://nocopo.bpp.gov.ng/',
    api_url: null,
    access_method: 'html_scrape',
    auth: 'registration',
    cost: 'free',
    geography: ['NG'],
    levels: ['national'],
    opportunity_types: ['tender', 'award_notice'],
    useful_for_ngo: 'baja',
    fields_available: ['title', 'ministry', 'deadline', 'category'],
    update_frequency: 'periódica',
    implementation_priority: 'P3',
    integration_status: 'catalog',
    notes:
      'Nigeria Open Contracting Portal (Bureau of Public Procurement). Cobertura federal; calidad de datos variable.',
  },
  {
    id: 'kenya-ppip',
    label: 'Kenia — PPIP (Public Procurement Information Portal)',
    url: 'https://tenders.go.ke/',
    api_url: null,
    access_method: 'html_scrape',
    auth: 'registration',
    cost: 'free',
    geography: ['KE'],
    levels: ['national', 'regional'],
    opportunity_types: ['tender', 'request_for_quotation'],
    useful_for_ngo: 'baja',
    fields_available: ['tender_no', 'title', 'entity', 'closing_date', 'category'],
    update_frequency: 'periódica',
    implementation_priority: 'P3',
    integration_status: 'catalog',
    notes:
      'Portal de información de compras públicas de Kenia. Registro de proveedores; listados públicos.',
  },
  {
    id: 'india-cppp',
    label: 'India — Central Public Procurement Portal (CPPP/GeM)',
    url: 'https://eprocure.gov.in/cppp/',
    api_url: null,
    access_method: 'html_scrape',
    auth: 'none',
    cost: 'free',
    geography: ['IN'],
    levels: ['national', 'regional'],
    opportunity_types: ['tender', 'request_for_proposal'],
    useful_for_ngo: 'baja',
    fields_available: ['tender_id', 'title', 'organisation', 'closing_date', 'value'],
    update_frequency: 'diaria',
    implementation_priority: 'P3',
    integration_status: 'catalog',
    notes:
      'Portal central de contratación de India (+ marketplace GeM). Volumen muy alto; encaje ONG selectivo.',
  },
  {
    id: 'philippines-philgeps',
    label: 'Filipinas — PhilGEPS',
    url: 'https://www.philgeps.gov.ph/',
    api_url: null,
    access_method: 'html_scrape',
    auth: 'registration',
    cost: 'free',
    geography: ['PH'],
    levels: ['national', 'regional', 'local'],
    opportunity_types: ['tender', 'request_for_quotation'],
    useful_for_ngo: 'baja',
    fields_available: ['reference_no', 'title', 'procuring_entity', 'closing_date', 'category'],
    update_frequency: 'diaria',
    implementation_priority: 'P3',
    integration_status: 'catalog',
    notes:
      'Sistema electrónico de compras del Gobierno de Filipinas. Registro para licitar; listados públicos. Idioma EN.',
  },
  {
    id: 'singapore-gebiz',
    label: 'Singapur — GeBIZ',
    url: 'https://www.gebiz.gov.sg/',
    api_url: 'https://data.gov.sg/datasets?query=GeBIZ',
    access_method: 'api',
    auth: 'none',
    cost: 'free',
    geography: ['SG'],
    levels: ['national'],
    opportunity_types: ['tender', 'request_for_quotation', 'invitation_to_bid'],
    useful_for_ngo: 'baja',
    fields_available: ['tender_no', 'description', 'agency', 'closing_date', 'awarded_amt'],
    update_frequency: 'diaria',
    implementation_priority: 'P3',
    integration_status: 'catalog',
    notes:
      'Portal de compras del Gobierno de Singapur. Datasets (incl. adjudicaciones) en data.gov.sg. Idioma EN.',
  },

  // ───────────────────────────────────────────────────────────────────────
  // Grants / subvenciones (familia transversal — algunas ya listadas arriba)
  // ───────────────────────────────────────────────────────────────────────
  {
    id: 'uk-find-a-grant',
    label: 'UK — Find a Grant',
    url: 'https://www.find-government-grants.service.gov.uk/',
    api_url: null,
    access_method: 'html_scrape',
    auth: 'none',
    cost: 'free',
    geography: ['GB'],
    levels: ['national'],
    opportunity_types: ['grant', 'call_for_proposal'],
    useful_for_ngo: 'alta',
    fields_available: ['title', 'funder', 'closing_date', 'amount', 'eligibility', 'summary'],
    update_frequency: 'diaria',
    implementation_priority: 'P2',
    integration_status: 'catalog',
    notes:
      'Portal del Gobierno del Reino Unido para subvenciones públicas. Encaje ONG alto (muchas líneas para charities). Sin API; scrape del listado.',
  },
  {
    id: 'oecd-crs',
    label: 'OECD CRS — Creditor Reporting System (AOD)',
    url: 'https://stats.oecd.org/Index.aspx?DataSetCode=CRS1',
    api_url: 'https://sdmx.oecd.org/public/rest/data/OECD.DCD.FSD,DSD_CRS@DF_CRS/',
    access_method: 'sdmx',
    auth: 'none',
    cost: 'free',
    geography: ['global'],
    levels: ['international_org', 'national'],
    opportunity_types: ['project_pipeline', 'award_notice'],
    useful_for_ngo: 'media',
    fields_available: ['donor', 'recipient', 'sector', 'amount', 'flow', 'year', 'channel'],
    update_frequency: 'anual',
    implementation_priority: 'P2',
    integration_status: 'catalog',
    notes:
      'Datos CRS de la OCDE: quién da AOD a quién, por sector/canal (incl. ONG como canal). API SDMX. Inteligencia de donantes, no oportunidades abiertas.',
  },
  {
    id: 'aiddata',
    label: 'AidData — Flujos de financiación al desarrollo',
    url: 'https://www.aiddata.org/datasets',
    api_url: null,
    access_method: 'bulk_download',
    auth: 'none',
    cost: 'free',
    geography: ['global'],
    levels: ['international_org', 'national'],
    opportunity_types: ['project_pipeline'],
    useful_for_ngo: 'baja',
    fields_available: ['funder', 'recipient', 'sector', 'amount', 'year'],
    update_frequency: 'periódica',
    implementation_priority: 'P3',
    integration_status: 'catalog',
    notes:
      'Datasets de investigación sobre financiación al desarrollo (incl. China). Descargas masivas; inteligencia macro de donantes.',
  },

  // ───────────────────────────────────────────────────────────────────────
  // Agregadores
  // ───────────────────────────────────────────────────────────────────────
  {
    id: 'tendersguru',
    label: 'Tenders.guru — Agregador multipaís UE',
    url: 'https://tenders.guru/',
    api_url: 'https://tenders.guru/api/es/tenders',
    access_method: 'api',
    auth: 'none',
    cost: 'free',
    geography: ['eu'],
    levels: ['national', 'regional', 'local'],
    opportunity_types: ['tender', 'award_notice'],
    useful_for_ngo: 'media',
    fields_available: ['id', 'title', 'awarding_authority', 'deadline', 'value', 'country', 'cpvs'],
    update_frequency: 'diaria',
    implementation_priority: 'P1',
    integration_status: 'live',
    notes:
      'Agregador JSON keyless de licitaciones de varios países UE (ES, FR, PL, RO, UK…). Ya integrado (tendersguru.ts). Sin auth.',
  },
  {
    id: 'opentender-eu',
    label: 'OpenTender.eu — Datos de contratación UE',
    url: 'https://opentender.eu/',
    api_url: 'https://opentender.eu/data/files/',
    access_method: 'bulk_download',
    auth: 'none',
    cost: 'free',
    geography: ['eu'],
    levels: ['national', 'regional', 'local'],
    opportunity_types: ['tender', 'award_notice'],
    useful_for_ngo: 'baja',
    fields_available: ['tender_id', 'title', 'buyer', 'value', 'cpv', 'country', 'indicators'],
    update_frequency: 'periódica',
    implementation_priority: 'P3',
    integration_status: 'catalog',
    notes:
      'Proyecto DIGIWHIST: datos limpios de contratación de 30+ países europeos para análisis (descargas). Histórico/analítico, no avisos en vivo.',
  },
  {
    id: 'reliefweb',
    label: 'ReliefWeb — Jobs & Calls (OCHA)',
    url: 'https://reliefweb.int/',
    api_url: 'https://api.reliefweb.int/v1/jobs',
    access_method: 'api',
    auth: 'none',
    cost: 'free',
    geography: ['global'],
    levels: ['international_org'],
    opportunity_types: ['call_for_proposal', 'consultancy', 'implementing_partner_call'],
    useful_for_ngo: 'media',
    fields_available: ['id', 'title', 'source', 'country', 'date', 'type', 'career_categories'],
    update_frequency: 'continua',
    implementation_priority: 'P2',
    integration_status: 'catalog',
    notes:
      'Plataforma humanitaria de OCHA. API v1 pública (jobs/reports). Sale RFP/consultorías humanitarias y llamadas a socios. Encaje ONG humanitarias.',
  },
  {
    id: 'hdx',
    label: 'HDX — Humanitarian Data Exchange (CKAN)',
    url: 'https://data.humdata.org/',
    api_url: 'https://data.humdata.org/api/3/action/package_search',
    access_method: 'ckan',
    auth: 'none',
    cost: 'free',
    geography: ['global'],
    levels: ['international_org'],
    opportunity_types: ['project_pipeline'],
    useful_for_ngo: 'baja',
    fields_available: ['dataset', 'organization', 'tags', 'resources', 'location'],
    update_frequency: 'continua',
    implementation_priority: 'P3',
    integration_status: 'catalog',
    notes:
      'Plataforma de datos humanitarios de OCHA (CKAN). No publica oportunidades pero da contexto/datos para justificar proyectos.',
  },
]

/** Número total de fuentes catalogadas (conveniencia para tests/UI). */
export const SOURCES_COUNT = SOURCES.length
