import type { InboxItem } from "@/types/inbox";

const isoMinutesAgo = (m: number) => new Date(Date.now() - m * 60_000).toISOString();

export const inboxMock: InboxItem[] = [
  {
    id: "inb_001",
    workspaceId: "ws_espana_2026",
    source: "boe",
    origin: "BOE núm. 113 · Sección I",
    title: "Real Decreto 423/2026, de 6 de mayo, por el que se modifica el régimen de vivienda turística",
    excerpt: "El presente real decreto introduce un sistema de cupo autonómico para licencias de vivienda turística y refuerza los requisitos de inscripción.",
    url: "https://www.boe.es/diario_boe/",
    score: 94,
    status: "unread",
    entities: [
      { type: "law", id: "law_vivienda_turistica", name: "Vivienda turística 423/2026" },
      { type: "sector", id: "sec_vivienda", name: "Vivienda" },
    ],
    tags: ["vivienda", "regulación", "ccaa"],
    receivedAt: isoMinutesAgo(8),
  },
  {
    id: "inb_002",
    workspaceId: "ws_espana_2026",
    source: "rss",
    origin: "El País · Política",
    title: "Junts mantiene la incertidumbre sobre el voto a la senda de estabilidad",
    excerpt: "Fuentes parlamentarias señalan que Junts no comunicará posición hasta el martes; la negociación con Moncloa sigue trabada por la cuestión catalana.",
    url: "https://elpais.com/",
    score: 88,
    status: "unread",
    entities: [
      { type: "actor", id: "act_junts_portavoz", name: "Portavoz Junts" },
      { type: "party", id: "junts", name: "Junts" },
      { type: "event", id: "evt_senda_estabilidad", name: "Senda de estabilidad" },
    ],
    tags: ["junts", "presupuestos"],
    receivedAt: isoMinutesAgo(22),
  },
  {
    id: "inb_003",
    workspaceId: "ws_espana_2026",
    source: "google_alerts",
    origin: "Google Alerts · «plan vive»",
    title: "Comunidad de Madrid amplía las ayudas del Plan Vive en 250 millones",
    excerpt: "El gobierno regional anuncia una segunda fase del programa que duplica las viviendas en alquiler asequible disponibles.",
    score: 76,
    status: "unread",
    entities: [
      { type: "actor", id: "act_pres_cam", name: "Presidenta Comunidad de Madrid" },
      { type: "sector", id: "sec_vivienda", name: "Vivienda" },
    ],
    tags: ["madrid", "vivienda"],
    receivedAt: isoMinutesAgo(46),
  },
  {
    id: "inb_004",
    workspaceId: "ws_espana_2026",
    source: "twitter",
    origin: "X · @susanagm_quesada",
    title: "Hilo: análisis del último CIS — desgaste contenido en PSOE, repunte sutil de Sumar entre jóvenes",
    excerpt: "Sumar +1.2pp en 18-34, PSOE -1.8pp en pensionistas urbanos, PP estancado. Cataluña y País Vasco no muestran movimientos materiales en este oleaje.",
    score: 71,
    status: "unread",
    entities: [
      { type: "party", id: "psoe", name: "PSOE" },
      { type: "party", id: "sumar", name: "Sumar" },
    ],
    tags: ["cis", "demoscopia"],
    receivedAt: isoMinutesAgo(67),
  },
  {
    id: "inb_005",
    workspaceId: "ws_espana_2026",
    source: "newsletter",
    origin: "Politico Pro · Brussels",
    title: "AI Act enforcement — primeras directrices de la Comisión sobre uso público de modelos generativos",
    excerpt: "Bruselas publica el primer borrador de orientaciones que afectarán a las administraciones nacionales con previsión de despliegue para Q4 2026.",
    score: 64,
    status: "read",
    entities: [
      { type: "law", id: "law_ai_act", name: "AI Act" },
      { type: "sector", id: "sec_tech", name: "Tech & Digital" },
    ],
    tags: ["ue", "ia", "regulación"],
    receivedAt: isoMinutesAgo(140),
  },
  {
    id: "inb_006",
    workspaceId: "ws_espana_2026",
    source: "rss",
    origin: "La Vanguardia",
    title: "ERC pacta con el Govern la actualización del modelo de financiación autonómica catalana",
    excerpt: "Un acuerdo previo a la cumbre territorial fija un marco bilateral con compromisos cuantificables en infraestructuras y agencia tributaria.",
    score: 60,
    status: "unread",
    entities: [
      { type: "party", id: "erc", name: "ERC" },
      { type: "event", id: "evt_financiacion_catalana", name: "Financiación catalana" },
    ],
    tags: ["cataluña", "financiación"],
    receivedAt: isoMinutesAgo(180),
  },
  {
    id: "inb_007",
    workspaceId: "ws_espana_2026",
    source: "boe",
    origin: "BOE núm. 112 · Sección III",
    title: "Resolución del Tribunal de Cuentas — informe de fiscalización del sector eléctrico (2024)",
    excerpt: "El informe identifica desviaciones contables en tres operadores y recomienda revisar la metodología de retribución de la distribución.",
    score: 55,
    status: "unread",
    entities: [
      { type: "sector", id: "sec_energia", name: "Energía" },
    ],
    tags: ["energía", "tribunal_cuentas"],
    receivedAt: isoMinutesAgo(220),
  },
  {
    id: "inb_008",
    workspaceId: "ws_espana_2026",
    source: "google_alerts",
    origin: "Google Alerts · «defensa»",
    title: "Aumento del 12% en el presupuesto de Defensa para 2026: prioridad en ciberdefensa y disuasión",
    excerpt: "Defensa presenta su Plan de Modernización con foco en capacidades cibernéticas y modernización de la flota; impacto industrial pendiente de cuantificar.",
    score: 52,
    status: "unread",
    entities: [
      { type: "sector", id: "sec_defensa", name: "Defensa" },
    ],
    tags: ["defensa", "presupuestos"],
    receivedAt: isoMinutesAgo(295),
  },
  {
    id: "inb_009",
    workspaceId: "ws_espana_2026",
    source: "rss",
    origin: "El Mundo · Tribunales",
    title: "Avanza la instrucción del caso de los bulos pre-electorales en la AN",
    excerpt: "La fiscalía solicita la declaración de tres administradores de canales en plataformas anónimas; la defensa pide archivar por falta de pruebas materiales.",
    score: 47,
    status: "read",
    entities: [
      { type: "event", id: "evt_bulos_electorales", name: "Bulos electorales" },
    ],
    tags: ["bulos", "judicial"],
    receivedAt: isoMinutesAgo(420),
  },
  {
    id: "inb_010",
    workspaceId: "ws_espana_2026",
    source: "newsletter",
    origin: "Eldiario.es · Sumario diario",
    title: "Cinco temas que dominarán la semana parlamentaria",
    excerpt: "Senda de estabilidad, AI Act, financiación autonómica, comisión bulos y modificación del régimen turístico.",
    score: 44,
    status: "unread",
    entities: [],
    tags: ["agenda"],
    receivedAt: isoMinutesAgo(540),
  },
  {
    id: "inb_011",
    workspaceId: "ws_espana_2026",
    source: "twitter",
    origin: "X · @gobierno_es",
    title: "Comunicado: el Gobierno reafirma su compromiso con la senda de estabilidad",
    excerpt: "El Ejecutivo emite nota oficial recordando que la senda es condición necesaria para activar fondos y reiterando la voluntad negociadora con grupos.",
    score: 38,
    status: "unread",
    entities: [
      { type: "actor", id: "act_min_economia", name: "Ministra de Economía" },
    ],
    tags: ["gobierno", "comunicado"],
    receivedAt: isoMinutesAgo(720),
  },
  {
    id: "inb_012",
    workspaceId: "ws_espana_2026",
    source: "rss",
    origin: "Cinco Días",
    title: "La banca española prepara el ejercicio anual de stress test del BCE",
    excerpt: "Seis entidades nacionales participan en la batería de escenarios de la Autoridad Bancaria Europea con foco en exposición inmobiliaria.",
    score: 32,
    status: "archived",
    entities: [
      { type: "sector", id: "sec_banca", name: "Banca" },
    ],
    tags: ["banca", "europa"],
    receivedAt: isoMinutesAgo(1240),
  },
];
