import type { MatrizRiesgo } from '@/types/riesgo';

// Generate 30 days of historical data escalating from 62 to 78
const now = new Date();
const historico_30d = Array.from({ length: 30 }, (_, i) => ({
  fecha: new Date(now.getTime() - (29 - i) * 86400000).toISOString().split('T')[0],
  score: Math.round(62 + (i / 29) * 16 + (Math.random() - 0.5) * 4),
}));

export const MOCK_MATRIZ: MatrizRiesgo = {
  fecha_calculo: new Date().toISOString(),
  score_global: 78,
  nivel_global: 'alto',
  alertas_activas: 5,
  historico_30d,
  indicadores: [
    {
      id: 'ind-01',
      dimension: 'estabilidad_gubernamental',
      titulo: 'Crisis de coalición: divergencias presupuestarias PSOE-Sumar',
      descripcion: 'Las negociaciones presupuestarias entre PSOE y Sumar han entrado en una fase crítica con desacuerdos profundos en política fiscal, gasto social y reducción de deuda. Fuentes parlamentarias señalan posibilidad de ruptura antes de fin de legislatura.',
      nivel: 'critico',
      score: 91,
      variacion_7d: 8.2,
      tendencia: 'subiendo',
      ultima_actualizacion: new Date(now.getTime() - 3600000).toISOString(),
      actores_implicados: ['Pedro Sánchez', 'Yolanda Díaz', 'PSOE', 'Sumar'],
      fuentes: ['El País', 'El Mundo', 'La Vanguardia'],
      horizonte: '7d',
    },
    {
      id: 'ind-02',
      dimension: 'tension_territorial',
      titulo: 'Catalunya: tensión fiscal tras rechazo de la condonación de deuda',
      descripcion: 'El Congreso rechaza por segunda vez la singular financiación para Catalunya, elevando la tensión con el gobierno catalán. ERC amenaza con retirar apoyo en votaciones clave si no hay avances concretos antes del pleno de presupuestos.',
      nivel: 'critico',
      score: 88,
      variacion_7d: 5.1,
      tendencia: 'subiendo',
      ultima_actualizacion: new Date(now.getTime() - 7200000).toISOString(),
      actores_implicados: ['Salvador Illa', 'Pere Aragonès', 'ERC', 'Govern'],
      fuentes: ['La Vanguardia', 'El Confidencial', 'ACN'],
      horizonte: '30d',
    },
    {
      id: 'ind-03',
      dimension: 'riesgo_electoral',
      titulo: 'Volatilidad en intención de voto: PP recupera ventaja de 6 puntos',
      descripcion: 'Tres encuestas consecutivas muestran al PP recuperando terreno perdido tras el escándalo de financiación irregular, con ventaja de 5-7 puntos sobre el PSOE en voto directo. El Partido Popular mantiene impulso en territorios clave para elecciones autonómicas.',
      nivel: 'alto',
      score: 74,
      variacion_7d: 3.4,
      tendencia: 'subiendo',
      ultima_actualizacion: new Date(now.getTime() - 14400000).toISOString(),
      actores_implicados: ['PP', 'PSOE', 'Alberto Núñez Feijóo'],
      fuentes: ['CIS', 'GAD3', 'Metroscopia'],
      horizonte: '90d',
    },
    {
      id: 'ind-04',
      dimension: 'conflicto_social',
      titulo: 'Huelga general del transporte: sector amenaza con paro indefinido',
      descripcion: 'Los sindicatos del transporte de mercancías han convocado movilizaciones ante el fracaso de la negociación colectiva. Se estiman impactos directos en cadenas de distribución y suministro con afectación a sectores agroindustrial y farmacéutico.',
      nivel: 'alto',
      score: 71,
      variacion_7d: 12.0,
      tendencia: 'subiendo',
      ultima_actualizacion: new Date(now.getTime() - 18000000).toISOString(),
      actores_implicados: ['CCOO', 'UGT', 'Ministerio de Transportes'],
      fuentes: ['El Economista', 'Cinco Días', 'Europa Press'],
      horizonte: '7d',
    },
    {
      id: 'ind-05',
      dimension: 'presion_mediatica',
      titulo: 'Caso Koldo: nuevos imputados generan presión sobre gobierno',
      descripcion: 'La expansión de la causa judicial a nuevos cargos del PSOE y el Gobierno central aumenta la cobertura mediática negativa. Análisis de sentimiento muestra deterioro sostenido de imagen gubernamental en medios de comunicación nacionales.',
      nivel: 'alto',
      score: 68,
      variacion_7d: 2.8,
      tendencia: 'estable',
      ultima_actualizacion: new Date(now.getTime() - 21600000).toISOString(),
      actores_implicados: ['PSOE', 'Ministerio del Interior', 'Juzgado Central'],
      fuentes: ['El Mundo', 'ABC', 'La Razón'],
      horizonte: '30d',
    },
    {
      id: 'ind-06',
      dimension: 'riesgo_legislativo',
      titulo: 'Ley de Amnistía: pendiente de resolución en Tribunal Constitucional',
      descripcion: 'El TC mantiene suspendida parte de la Ley de Amnistía, generando incertidumbre jurídica y política. La resolución final podría desencadenar crisis de gobernabilidad si el fallo contradice los acuerdos de investidura.',
      nivel: 'alto',
      score: 66,
      variacion_7d: -1.2,
      tendencia: 'bajando',
      ultima_actualizacion: new Date(now.getTime() - 28800000).toISOString(),
      actores_implicados: ['TC', 'PSOE', 'Junts', 'ERC'],
      fuentes: ['El Confidencial', 'elDiario.es', 'BOE'],
      horizonte: '30d',
    },
    {
      id: 'ind-07',
      dimension: 'estabilidad_gubernamental',
      titulo: 'Rotación ministerial: rumores de remodelación antes de verano',
      descripcion: 'Fuentes del entorno de La Moncloa señalan posibles cambios en la composición del Consejo de Ministros antes del período vacacional, como estrategia de renovación de imagen ante caída de popularidad.',
      nivel: 'medio',
      score: 55,
      variacion_7d: 1.5,
      tendencia: 'estable',
      ultima_actualizacion: new Date(now.getTime() - 36000000).toISOString(),
      actores_implicados: ['Pedro Sánchez', 'Consejo de Ministros'],
      fuentes: ['El País', 'Cadena SER'],
      horizonte: '30d',
    },
    {
      id: 'ind-08',
      dimension: 'tension_territorial',
      titulo: 'País Vasco: concierto económico en fase de renegociación',
      descripcion: 'Las negociaciones del concierto económico vasco entran en fase técnica con posiciones alejadas en cupo y solidaridad interterritorial. El PNV condiciona su apoyo parlamentario al avance de las negociaciones.',
      nivel: 'medio',
      score: 52,
      variacion_7d: -0.5,
      tendencia: 'bajando',
      ultima_actualizacion: new Date(now.getTime() - 43200000).toISOString(),
      actores_implicados: ['PNV', 'Gobierno Vasco', 'Ministerio de Hacienda'],
      fuentes: ['El Correo', 'Noticias de Gipuzkoa'],
      horizonte: '90d',
    },
    {
      id: 'ind-09',
      dimension: 'conflicto_social',
      titulo: 'Manifestaciones por vivienda: presión ciudadana en grandes ciudades',
      descripcion: 'Las movilizaciones por el derecho a la vivienda se consolidan con una convocatoria mensual que mantiene afluencia creciente. El movimiento gana respaldo institucional de algunos ayuntamientos y presiona al gobierno por medidas estructurales.',
      nivel: 'medio',
      score: 48,
      variacion_7d: 4.2,
      tendencia: 'subiendo',
      ultima_actualizacion: new Date(now.getTime() - 50400000).toISOString(),
      actores_implicados: ['Plataformas de Vivienda', 'CCOO', 'Podemos'],
      fuentes: ['elDiario.es', 'Público', 'El Salto'],
      horizonte: '7d',
    },
    {
      id: 'ind-10',
      dimension: 'riesgo_legislativo',
      titulo: 'Reforma laboral: revisión de los ERTE post-pandemia',
      descripcion: 'El gobierno estudia modificaciones al sistema de ERTE para adaptarlo a situaciones estructurales. La reforma tiene apoyo sindical pero encuentra resistencia patronal y podría generar debate parlamentario complejo.',
      nivel: 'bajo',
      score: 34,
      variacion_7d: -2.1,
      tendencia: 'bajando',
      ultima_actualizacion: new Date(now.getTime() - 57600000).toISOString(),
      actores_implicados: ['Ministerio de Trabajo', 'CCOO', 'UGT', 'CEOE'],
      fuentes: ['El Economista', 'Cinco Días'],
      horizonte: '90d',
    },
  ],
};
