/**
 * Catálogo · Subtab 15 "Cultura, ocio & economía social" v3.
 * Foco: turismo, cultura, industrias creativas, eventos, ocio, presión
 * turística. v1 con turismo INE Frontur + IPC servicios + IMF + macro.
 */
import type { PulsoIndicatorMeta } from "./pulso-indicators";

export const CULTURA_OCIO_INDICATORS: PulsoIndicatorMeta[] = [
  {
    id: "co-pib-imf",
    family: "pib",
    label: "PIB real · IMF NGDP_RPCH",
    shortLabel: "PIB",
    unit: "%",
    decimals: 2,
    source: "IMF DataMapper · WEO",
    sourceCode: "NGDP_RPCH",
    frequency: "annual",
    description: "Crecimiento PIB. Turismo y servicios culturales aportan ~12-13% PIB en España; correlacionan fuerte con ciclo macro.",
    endpoint: "/api/imf/country?iso=ESP&indicator=NGDP_RPCH",
    parser: "imf-country",
    imfIndicator: "NGDP_RPCH",
    accent: "#0F766E",
  },
  {
    id: "co-exports-yoy",
    family: "exterior",
    label: "Exportaciones reales · IMF TX_RPCH",
    shortLabel: "Exports",
    unit: "%",
    decimals: 2,
    source: "IMF DataMapper · WEO",
    sourceCode: "TX_RPCH",
    frequency: "annual",
    description: "Exportaciones reales totales. Turismo entra como exportación de servicios; clave para la economía cultural-turística.",
    endpoint: "/api/imf/country?iso=ESP&indicator=TX_RPCH",
    parser: "imf-country",
    imfIndicator: "TX_RPCH",
    accent: "#0891b2",
  },
  {
    id: "co-paro-imf",
    family: "empleo",
    label: "Tasa paro · IMF LUR",
    shortLabel: "Paro",
    unit: "%",
    decimals: 2,
    source: "IMF DataMapper · WEO",
    sourceCode: "LUR",
    frequency: "annual",
    description: "Tasa de paro. Hostelería, ocio y cultura son sectores con alta intensidad de empleo y temporalidad.",
    endpoint: "/api/imf/country?iso=ESP&indicator=LUR",
    parser: "imf-country",
    imfIndicator: "LUR",
    threshold: { amber: 12, red: 18, goodAbove: false },
    accent: "#f59e0b",
  },
  {
    id: "co-ipv-general",
    family: "pib",
    label: "IPV vivienda · INE 76201",
    shortLabel: "IPV",
    unit: "",
    decimals: 1,
    source: "INE WSTempus · IPV",
    sourceCode: "IPV76201",
    frequency: "quarterly",
    description: "Precio vivienda. Lead indicator de presión turística (vivienda turística vs residencial) en ciudades y costa.",
    endpoint: "/api/ine/ipv?n=24",
    parser: "ine-ipc",
    parserKey: "general",
    accent: "#16a34a",
  },
  {
    id: "co-ipc-anual",
    family: "precios",
    label: "IPC anual · INE 290750",
    shortLabel: "IPC YoY",
    unit: "%",
    decimals: 2,
    source: "INE WSTempus · IPC",
    sourceCode: "IPC290750",
    frequency: "monthly",
    description: "Inflación general. Componente hostelería y ocio dentro del IPC anticipa coste turístico para visitantes.",
    endpoint: "/api/ine/ipc?n=36",
    parser: "ine-ipc",
    parserKey: "anual",
    threshold: { amber: 2, red: 4, goodAbove: false },
    accent: "#dc2626",
  },
  {
    id: "co-frontur",
    family: "demanda",
    label: "Turistas internacionales · INE Frontur 23988",
    shortLabel: "Turistas",
    unit: "",
    decimals: 0,
    source: "INE WSTempus · Frontur",
    sourceCode: "FRONTUR23988",
    frequency: "monthly",
    description:
      "Llegadas mensuales de turistas internacionales (Frontur). Driver directo del sector — pico estacional jul-ago.",
    endpoint: "/api/ine/frontur?n=24",
    parser: "ine-frontur",
    accent: "#8b5cf6",
  },
  {
    id: "co-tourism-nights-eurostat",
    family: "demanda",
    label: "Pernoctaciones turísticas · Eurostat tour_occ_nin",
    shortLabel: "Pernoct.",
    unit: "",
    decimals: 0,
    source: "Eurostat · tour_occ_nin",
    sourceCode: "tour_occ_nin",
    frequency: "monthly",
    description:
      "Pernoctaciones en establecimientos turísticos. Métrica intensiva (no sólo llegadas) — refleja estancia media y peso económico real del turismo cultural.",
    endpoint: "/api/eurostat/dataset?code=tour_occ_nin&filters=geo=ES;c_resid=TOTAL;nace_r2=I551-I553;unit=NR",
    parser: "eurostat-simple",
    accent: "#a855f7",
  },
  // Sprint L F6 · +1 turismo non-residente (gasto cultural-ocio)
  {
    id: "co-tourism-arrivals-eurostat",
    family: "exterior",
    label: "Llegadas turistas non-resident · Eurostat tour_occ_arm",
    shortLabel: "Arrivals",
    unit: "",
    decimals: 0,
    source: "Eurostat · tour_occ_arm",
    sourceCode: "tour_occ_arm",
    frequency: "monthly",
    description:
      "Llegadas mensuales de turistas no residentes a establecimientos en España (Eurostat armonizado UE). Complementa Frontur con visión comparable europea.",
    endpoint: "/api/eurostat/dataset?code=tour_occ_arm&filters=geo=ES;c_resid=FOR;nace_r2=I551-I553;unit=NR",
    parser: "eurostat-simple",
    accent: "#7c3aed",
  },
];

export const CULTURA_OCIO_META = {
  slug: "cultura-ocio",
  label: "Cultura, ocio & economía social",
  shortLabel: "Cultura",
  accent: "#8b5cf6",
  description: "Turismo, cultura, industrias creativas, ocio, deporte, patrimonio, eventos y presión turística sobre vivienda y servicios urbanos.",
};
