/**
 * Catálogo · Subtab 11 "Demografía & territorio" v3.
 * Foco: crecimiento, envejecimiento, despoblación, migración, hogares.
 * Para v1 usamos los indicadores macro disponibles que tienen relación
 * con el área demográfica. Datasets específicos de padrón/censo INE
 * via /api/datos-gob/csv quedan para alimentar bloques especializados.
 */
import type { PulsoIndicatorMeta } from "./pulso-indicators";

export const DEMOGRAFIA_TERRITORIO_INDICATORS: PulsoIndicatorMeta[] = [
  {
    id: "dt-pib-percapita",
    family: "pib",
    label: "PIB per cápita · IMF NGDPDPC",
    shortLabel: "PIB pc",
    unit: " USD",
    decimals: 0,
    source: "IMF DataMapper · WEO",
    sourceCode: "NGDPDPC",
    frequency: "annual",
    description: "PIB per cápita en USD. Proxy de renta agregada por habitante. Crucial en demografía: relación entre tamaño poblacional, productividad y renta.",
    endpoint: "/api/imf/country?iso=ESP&indicator=NGDPDPC",
    parser: "imf-country",
    imfIndicator: "NGDPDPC",
    accent: "#0F766E",
  },
  {
    id: "dt-paro-imf",
    family: "empleo",
    label: "Tasa paro IMF · LUR",
    shortLabel: "Paro",
    unit: "%",
    decimals: 2,
    source: "IMF DataMapper · WEO",
    sourceCode: "LUR",
    frequency: "annual",
    description: "Tasa de paro WEO. Conecta demografía (población activa, juventud) con mercado laboral.",
    endpoint: "/api/imf/country?iso=ESP&indicator=LUR",
    parser: "imf-country",
    imfIndicator: "LUR",
    threshold: { amber: 12, red: 18, goodAbove: false },
    accent: "#f59e0b",
  },
  {
    id: "dt-paro-epa-jovenes",
    family: "empleo",
    label: "Paro juvenil <25 EPA · INE 86912",
    shortLabel: "Paro <25",
    unit: "%",
    decimals: 2,
    source: "INE WSTempus · EPA",
    sourceCode: "EPA86912",
    frequency: "quarterly",
    description: "Tasa de paro en menores de 25 años. Lead indicator de presión sobre emancipación juvenil y migración interregional.",
    endpoint: "/api/ine/epa?n=24",
    parser: "ine-epa",
    parserKey: "menores_25",
    threshold: { amber: 25, red: 35, goodAbove: false },
    accent: "#dc2626",
  },
  {
    id: "dt-paro-epa-general",
    family: "empleo",
    label: "Tasa paro EPA general · INE 86913",
    shortLabel: "Paro EPA",
    unit: "%",
    decimals: 2,
    source: "INE WSTempus · EPA",
    sourceCode: "EPA86913",
    frequency: "quarterly",
    description: "Tasa paro general de EPA. Indicador clave de cohesión laboral con desagregación territorial disponible (no integrado v1).",
    endpoint: "/api/ine/epa?n=24",
    parser: "ine-epa",
    parserKey: "general",
    threshold: { amber: 12, red: 18, goodAbove: false },
    accent: "#f59e0b",
  },
  {
    id: "dt-ipv-general",
    family: "pib",
    label: "IPV vivienda · INE 76201",
    shortLabel: "IPV",
    unit: "",
    decimals: 1,
    source: "INE WSTempus · IPV",
    sourceCode: "IPV76201",
    frequency: "quarterly",
    description: "Índice de Precios de Vivienda. Demográficamente clave: precio absorbe demanda residencial y condiciona emancipación + migración hacia áreas tensionadas.",
    endpoint: "/api/ine/ipv?n=24",
    parser: "ine-ipc",
    parserKey: "general",
    accent: "#16a34a",
  },
  {
    id: "dt-etcl-coste-laboral",
    family: "empleo",
    label: "Coste laboral medio · INE ETCL",
    shortLabel: "Coste laboral",
    unit: "€/mes",
    decimals: 0,
    source: "INE WSTempus · ETCL",
    sourceCode: "ETCL",
    frequency: "quarterly",
    description: "Salarios + cotizaciones por trabajador y mes. Cruza renta laboral con coste de vida y demanda potencial de vivienda.",
    endpoint: "/api/ine/etcl?n=24",
    parser: "ine-ipc",
    parserKey: "total",
    accent: "#7c3aed",
  },
  {
    id: "dt-poblacion-eurostat",
    family: "demanda",
    label: "Edad media población · Eurostat demo_pjanind",
    shortLabel: "Edad media",
    unit: " años",
    decimals: 1,
    source: "Eurostat · demo_pjanind",
    sourceCode: "demo_pjanind",
    frequency: "annual",
    description:
      "Edad media de la población residente. Indicador de envejecimiento estructural — España es uno de los países más envejecidos de la UE.",
    endpoint: "/api/eurostat/dataset?code=demo_pjanind&filters=geo=ES;indic_de=AGEMEDPOP",
    parser: "eurostat-simple",
    threshold: { amber: 45, red: 50, goodAbove: false },
    accent: "#0EA5E9",
  },
  // Sprint L F6 · +1 fertilidad
  {
    id: "dt-fertilidad-eurostat",
    family: "demanda",
    label: "Tasa de fertilidad · Eurostat demo_find",
    shortLabel: "Fertilidad",
    unit: " h/m",
    decimals: 2,
    source: "Eurostat · demo_find",
    sourceCode: "demo_find:TOTFERRT",
    frequency: "annual",
    description:
      "Tasa global de fecundidad (hijos por mujer). España ~1.2 es de las más bajas UE-27 (media ~1.5). Driver estructural del problema demográfico y de la pirámide poblacional.",
    endpoint: "/api/eurostat/dataset?code=demo_find&filters=geo=ES;indic_de=TOTFERRT",
    parser: "eurostat-simple",
    threshold: { amber: 1.5, red: 1.2, goodAbove: true },
    accent: "#dc2626",
  },
];

export const DEMOGRAFIA_TERRITORIO_META = {
  slug: "demografia-territorio",
  label: "Demografía & territorio",
  shortLabel: "Demografía",
  accent: "#7c3aed",
  description: "Presiones demográficas y territoriales: crecimiento, envejecimiento, migración, hogares, despoblación y concentración urbana.",
};
