/**
 * Catálogo · Subtab 4 "Dependencias externas" v3 (Sprint N1).
 * Foco: cuenta corriente, exposición exterior, concentración de partners,
 * dependencia financiera neta, exposición a shocks externos.
 */
import type { PulsoIndicatorMeta } from "./pulso-indicators";

export const DEPENDENCIAS_EXTERNAS_INDICATORS: PulsoIndicatorMeta[] = [
  {
    id: "de-cuenta-corriente",
    family: "exterior",
    label: "Cuenta corriente %PIB · IMF BCA_NGDPD",
    shortLabel: "CC %PIB",
    unit: "%",
    decimals: 2,
    source: "IMF DataMapper · WEO",
    sourceCode: "BCA_NGDPD",
    frequency: "annual",
    description:
      "Saldo cuenta corriente sobre PIB. Métrica fundamental de dependencia externa: positivo = exportador neto de ahorro, negativo = necesita financiación exterior.",
    endpoint: "/api/imf/country?iso=ESP&indicator=BCA_NGDPD",
    parser: "imf-country",
    imfIndicator: "BCA_NGDPD",
    threshold: { amber: -2, red: -4, goodAbove: true },
    accent: "#0F766E",
  },
  {
    id: "de-exports-yoy-imf",
    family: "exterior",
    label: "Exportaciones reales YoY · IMF TX_RPCH",
    shortLabel: "Exports YoY",
    unit: "%",
    decimals: 2,
    source: "IMF DataMapper · WEO",
    sourceCode: "TX_RPCH",
    frequency: "annual",
    description:
      "Variación interanual de exportaciones reales totales. Sensible a demanda externa y competitividad-precio.",
    endpoint: "/api/imf/country?iso=ESP&indicator=TX_RPCH",
    parser: "imf-country",
    imfIndicator: "TX_RPCH",
    accent: "#0891b2",
  },
  {
    id: "de-imports-yoy-imf",
    family: "exterior",
    label: "Importaciones reales YoY · IMF TM_RPCH",
    shortLabel: "Imports YoY",
    unit: "%",
    decimals: 2,
    source: "IMF DataMapper · WEO",
    sourceCode: "TM_RPCH",
    frequency: "annual",
    description:
      "Variación interanual de importaciones reales. Indicador procíclico — correlaciona con demanda interna.",
    endpoint: "/api/imf/country?iso=ESP&indicator=TM_RPCH",
    parser: "imf-country",
    imfIndicator: "TM_RPCH",
    accent: "#f97316",
  },
  {
    id: "de-cnt-exports",
    family: "exterior",
    label: "Exportaciones b/s YoY · INE CNT 7267",
    shortLabel: "Exp INE",
    unit: "%",
    decimals: 2,
    source: "INE WSTempus · CNT",
    sourceCode: "CNTR7267",
    frequency: "quarterly",
    description:
      "Exportaciones reales totales (bienes + servicios) según CNT base 2010 SA. Mensualidad trimestral más fina que IMF anual.",
    endpoint: "/api/ine/cnt-extra?n=24",
    parser: "ine-cnt-extra",
    parserKey: "exports",
    accent: "#0891b2",
  },
  {
    id: "de-cnt-imports",
    family: "exterior",
    label: "Importaciones b/s YoY · INE CNT 7287",
    shortLabel: "Imp INE",
    unit: "%",
    decimals: 2,
    source: "INE WSTempus · CNT",
    sourceCode: "CNTR7287",
    frequency: "quarterly",
    description:
      "Importaciones reales totales según CNT base 2010 SA. Procíclica con demanda interna.",
    endpoint: "/api/ine/cnt-extra?n=24",
    parser: "ine-cnt-extra",
    parserKey: "imports",
    accent: "#f97316",
  },
  {
    id: "de-iip-eurostat",
    family: "exterior",
    label: "Posición Inversión Internacional Neta %PIB · Eurostat bop_iip6_q",
    shortLabel: "IIP neta",
    unit: "%",
    decimals: 1,
    source: "Eurostat · bop_iip6_q",
    sourceCode: "bop_iip6_q:NIIP",
    frequency: "quarterly",
    description:
      "Stock acumulado activos exteriores - pasivos sobre PIB. España estructuralmente -70/-80% PIB (deudor neto). Métrica directa de dependencia exterior.",
    endpoint: "/api/eurostat/dataset?code=bop_iip6_q&filters=geo=ES;sector=S1;stk_flow=NIIP;bop_item=FA;unit=PC_GDP",
    parser: "eurostat-simple",
    threshold: { amber: -50, red: -80, goodAbove: true },
    accent: "#8b5cf6",
  },
  {
    id: "de-yield-10y",
    family: "exterior",
    label: "Yield 10Y bono soberano · Eurostat irt_lt_mcby_m",
    shortLabel: "10Y yield",
    unit: "%",
    decimals: 2,
    source: "Eurostat · irt_lt_mcby_m",
    sourceCode: "irt_lt_mcby_m",
    frequency: "monthly",
    description:
      "Yield mensual del bono soberano a 10 años. Coste implícito de financiación exterior; subidas = inversores externos exigen más prima por dependencia financiera.",
    endpoint: "/api/eurostat/dataset?code=irt_lt_mcby_m&filters=geo=ES",
    parser: "eurostat-simple",
    threshold: { amber: 3.5, red: 5, goodAbove: false },
    accent: "#dc2626",
  },
  {
    id: "de-inversion-bruta",
    family: "exterior",
    label: "Inversión bruta %PIB · IMF NID_NGDP",
    shortLabel: "Inversión",
    unit: "%",
    decimals: 2,
    source: "IMF DataMapper · WEO",
    sourceCode: "NID_NGDP",
    frequency: "annual",
    description:
      "FBCF sobre PIB. Una economía con baja inversión doméstica tiende a depender más del ahorro exterior para financiar capital nuevo.",
    endpoint: "/api/imf/country?iso=ESP&indicator=NID_NGDP",
    parser: "imf-country",
    imfIndicator: "NID_NGDP",
    accent: "#16a34a",
  },
];

export const DEPENDENCIAS_EXTERNAS_META = {
  slug: "dependencias-externas",
  label: "Dependencias externas",
  shortLabel: "Externo",
  accent: "#7c3aed",
  description:
    "Exposición exterior agregada: cuenta corriente, concentración de partners comerciales, posición de inversión internacional, dependencia financiera y vulnerabilidad ante shocks externos.",
};
