/**
 * Catálogo · Subtab 16 "Instituciones, sector público & capacidad estatal" v3.
 * Foco: ejecución presupuestaria, contratación, subvenciones, justicia,
 * empleo público, transparencia, confianza institucional.
 */
import type { PulsoIndicatorMeta } from "./pulso-indicators";

export const INSTITUCIONES_ESTADO_INDICATORS: PulsoIndicatorMeta[] = [
  {
    id: "ie-gasto-aapp",
    family: "demanda",
    label: "Gasto AAPP %PIB · Eurostat gov_10a_main",
    shortLabel: "Gasto AAPP",
    unit: "%",
    decimals: 2,
    source: "Eurostat · gov_10a_main",
    sourceCode: "gov_10a_main:TE",
    frequency: "annual",
    description: "Tamaño efectivo del Estado. Total expenditure (TE) de las AAPP sobre PIB. Define el espacio de gasto sobre el que se ejerce capacidad administrativa.",
    endpoint: "/api/eurostat/dataset?code=gov_10a_main&filters=geo=ES;na_item=TE;sector=S13;unit=PC_GDP",
    parser: "eurostat-simple",
    accent: "#dc2626",
  },
  {
    id: "ie-ingresos-aapp",
    family: "demanda",
    label: "Ingresos AAPP %PIB · Eurostat gov_10a_main",
    shortLabel: "Ingresos",
    unit: "%",
    decimals: 2,
    source: "Eurostat · gov_10a_main",
    sourceCode: "gov_10a_main:TR",
    frequency: "annual",
    description: "Total revenue (TR) AAPP %PIB. Capacidad recaudatoria es pilar de capacidad estatal — sin recaudación no hay ejecución.",
    endpoint: "/api/eurostat/dataset?code=gov_10a_main&filters=geo=ES;na_item=TR;sector=S13;unit=PC_GDP",
    parser: "eurostat-simple",
    accent: "#16a34a",
  },
  {
    id: "ie-saldo-imf",
    family: "forecast",
    label: "Saldo fiscal · IMF GGXCNL_NGDP",
    shortLabel: "Saldo",
    unit: "%",
    decimals: 2,
    source: "IMF DataMapper · WEO",
    sourceCode: "GGXCNL_NGDP",
    frequency: "annual",
    description: "Saldo total AAPP %PIB. Refleja equilibrio entre ingreso y gasto ejecutado. Crítico para credibilidad fiscal y margen administrativo.",
    endpoint: "/api/imf/country?iso=ESP&indicator=GGXCNL_NGDP",
    parser: "imf-country",
    imfIndicator: "GGXCNL_NGDP",
    threshold: { amber: -3, red: -6, goodAbove: true },
    accent: "#f59e0b",
  },
  {
    id: "ie-deuda-imf",
    family: "pib",
    label: "Deuda pública · IMF GGXWDG_NGDP",
    shortLabel: "Deuda",
    unit: "%",
    decimals: 1,
    source: "IMF DataMapper · WEO",
    sourceCode: "GGXWDG_NGDP",
    frequency: "annual",
    description: "Stock deuda Maastricht %PIB. Alta deuda reduce flexibilidad fiscal y aumenta carga de intereses sobre ejecución presupuestaria.",
    endpoint: "/api/imf/country?iso=ESP&indicator=GGXWDG_NGDP",
    parser: "imf-country",
    imfIndicator: "GGXWDG_NGDP",
    threshold: { amber: 100, red: 120, goodAbove: false },
    accent: "#0F766E",
  },
  // Saldo estructural eliminado en Sprint L F3: IMF GGSB_NGDP no devuelve dato
  // en el endpoint público; Eurostat no expone equivalente directo (AIReF lo
  // calcula vía PDF). Pendiente de scraper AIReF futuro.
  {
    id: "ie-saldo-primario",
    family: "forecast",
    label: "Saldo primario %PIB · Eurostat gov_10dd_edpt1",
    shortLabel: "Primario",
    unit: "%",
    decimals: 2,
    source: "Eurostat · gov_10dd_edpt1",
    sourceCode: "gov_10dd_edpt1:B9P",
    frequency: "annual",
    description: "Saldo excluyendo intereses (net lending excl. interest). Diferencia con saldo total indica carga de servicio de deuda.",
    endpoint: "/api/eurostat/dataset?code=gov_10dd_edpt1&filters=geo=ES;na_item=B9P;sector=S13;unit=PC_GDP",
    parser: "eurostat-simple",
    threshold: { amber: 0, red: -2, goodAbove: true },
    accent: "#10b981",
  },
  {
    id: "ie-altas-empresas-eurostat",
    family: "demanda",
    label: "Demografía empresarial · Eurostat bd_size_r3",
    shortLabel: "Empresas",
    unit: "",
    decimals: 0,
    source: "Eurostat · bd_size_r3",
    sourceCode: "bd_size_r3:BUSI_CR",
    frequency: "annual",
    description:
      "Tasa de creación empresarial (BUSI_CR). Proxy de actividad económica formal y respuesta del tejido empresarial a la capacidad estatal regulatoria. DIRCE INE complementaria pero menos freshness.",
    endpoint: "/api/eurostat/dataset?code=bd_size_r3&filters=geo=ES;indic_sb=BUSI_CR;nace_r2=B-S_X_O_S94",
    parser: "eurostat-simple",
    accent: "#0891b2",
  },
  {
    id: "ie-id-rd-eurostat",
    family: "oferta",
    label: "I+D pública %PIB · Eurostat rd_e_gerdtot",
    shortLabel: "I+D %PIB",
    unit: "%",
    decimals: 2,
    source: "Eurostat · rd_e_gerdtot",
    sourceCode: "rd_e_gerdtot",
    frequency: "annual",
    description:
      "Gasto en I+D sobre PIB. Proxy de capacidad institucional para invertir en conocimiento y ciencia. España persiste ~30% por debajo de la media UE.",
    endpoint: "/api/eurostat/dataset?code=rd_e_gerdtot&filters=geo=ES;sectperf=GOV;unit=PC_GDP",
    parser: "eurostat-simple",
    threshold: { amber: 0.6, red: 0.4, goodAbove: true },
    accent: "#7c3aed",
  },
];

export const INSTITUCIONES_ESTADO_META = {
  slug: "instituciones-estado",
  label: "Instituciones, sector público & capacidad estatal",
  shortLabel: "Instituciones",
  accent: "#0891b2",
  description: "Capacidad estatal: ejecución presupuestaria, contratación pública, subvenciones, justicia, empleo público, transparencia y confianza institucional.",
};
