/**
 * Catálogo · Subtab 16 "Instituciones, sector público & capacidad estatal" v3.
 * Foco: ejecución presupuestaria, contratación, subvenciones, justicia,
 * empleo público, transparencia, confianza institucional.
 */
import type { PulsoIndicatorMeta } from "./pulso-indicators";

export const INSTITUCIONES_ESTADO_INDICATORS: PulsoIndicatorMeta[] = [
  {
    id: "ie-gasto-aapp",
    family: "demanda",
    label: "Gasto AAPP %PIB · IMF GGX_NGDP",
    shortLabel: "Gasto AAPP",
    unit: "%",
    decimals: 2,
    source: "IMF DataMapper · WEO",
    sourceCode: "GGX_NGDP",
    frequency: "annual",
    description: "Tamaño efectivo del Estado. Define el espacio de gasto sobre el que se ejerce capacidad administrativa.",
    endpoint: "/api/imf/country?iso=ESP&indicator=GGX_NGDP",
    parser: "imf-country",
    imfIndicator: "GGX_NGDP",
    accent: "#dc2626",
  },
  {
    id: "ie-ingresos-aapp",
    family: "demanda",
    label: "Ingresos AAPP %PIB · IMF GGR_NGDP",
    shortLabel: "Ingresos",
    unit: "%",
    decimals: 2,
    source: "IMF DataMapper · WEO",
    sourceCode: "GGR_NGDP",
    frequency: "annual",
    description: "Recursos AAPP %PIB. Capacidad recaudatoria es pilar de capacidad estatal — sin recaudación no hay ejecución.",
    endpoint: "/api/imf/country?iso=ESP&indicator=GGR_NGDP",
    parser: "imf-country",
    imfIndicator: "GGR_NGDP",
    accent: "#16a34a",
  },
  {
    id: "ie-saldo-imf",
    family: "forecast",
    label: "Saldo fiscal · IMF GGXCNL_NGDP",
    shortLabel: "Saldo",
    unit: "%",
    decimals: 2,
    source: "IMF DataMapper · WEO",
    sourceCode: "GGXCNL_NGDP",
    frequency: "annual",
    description: "Saldo total AAPP %PIB. Refleja equilibrio entre ingreso y gasto ejecutado. Crítico para credibilidad fiscal y margen administrativo.",
    endpoint: "/api/imf/country?iso=ESP&indicator=GGXCNL_NGDP",
    parser: "imf-country",
    imfIndicator: "GGXCNL_NGDP",
    threshold: { amber: -3, red: -6, goodAbove: true },
    accent: "#f59e0b",
  },
  {
    id: "ie-deuda-imf",
    family: "pib",
    label: "Deuda pública · IMF GGXWDG_NGDP",
    shortLabel: "Deuda",
    unit: "%",
    decimals: 1,
    source: "IMF DataMapper · WEO",
    sourceCode: "GGXWDG_NGDP",
    frequency: "annual",
    description: "Stock deuda Maastricht %PIB. Alta deuda reduce flexibilidad fiscal y aumenta carga de intereses sobre ejecución presupuestaria.",
    endpoint: "/api/imf/country?iso=ESP&indicator=GGXWDG_NGDP",
    parser: "imf-country",
    imfIndicator: "GGXWDG_NGDP",
    threshold: { amber: 100, red: 120, goodAbove: false },
    accent: "#0F766E",
  },
  {
    id: "ie-saldo-estructural",
    family: "forecast",
    label: "Saldo estructural · IMF GGSB_NGDP",
    shortLabel: "Estructural",
    unit: "%",
    decimals: 2,
    source: "IMF DataMapper · WEO",
    sourceCode: "GGSB_NGDP",
    frequency: "annual",
    description: "Saldo cíclicamente ajustado. Métrica AIReF / Pacto de Estabilidad. Aísla capacidad fiscal estructural del ciclo.",
    endpoint: "/api/imf/country?iso=ESP&indicator=GGSB_NGDP",
    parser: "imf-country",
    imfIndicator: "GGSB_NGDP",
    threshold: { amber: -1, red: -3, goodAbove: true },
    accent: "#7c3aed",
  },
  {
    id: "ie-saldo-primario",
    family: "forecast",
    label: "Saldo primario · IMF GGXONLB_NGDP",
    shortLabel: "Primario",
    unit: "%",
    decimals: 2,
    source: "IMF DataMapper · WEO",
    sourceCode: "GGXONLB_NGDP",
    frequency: "annual",
    description: "Saldo excluyendo intereses. Diferencia con saldo total indica carga de servicio de deuda.",
    endpoint: "/api/imf/country?iso=ESP&indicator=GGXONLB_NGDP",
    parser: "imf-country",
    imfIndicator: "GGXONLB_NGDP",
    threshold: { amber: 0, red: -2, goodAbove: true },
    accent: "#10b981",
  },
];

export const INSTITUCIONES_ESTADO_META = {
  slug: "instituciones-estado",
  label: "Instituciones, sector público & capacidad estatal",
  shortLabel: "Instituciones",
  accent: "#0891b2",
  description: "Capacidad estatal: ejecución presupuestaria, contratación pública, subvenciones, justicia, empleo público, transparencia y confianza institucional.",
};
