/**
 * Catálogo · Subtab 13 "Medio rural & cohesión territorial" v3.
 * Foco: vulnerabilidad rural, agricultura, agua, PAC, servicios rurales.
 * v1 con indicadores macro relacionados; datasets FEGA/PAC/MAPA/MITECO
 * vendrán por /api/datos-gob/csv (parser ya disponible).
 */
import type { PulsoIndicatorMeta } from "./pulso-indicators";

export const MEDIO_RURAL_INDICATORS: PulsoIndicatorMeta[] = [
  {
    id: "mr-pib-percapita",
    family: "pib",
    label: "PIB per cápita · IMF NGDPDPC",
    shortLabel: "PIB pc",
    unit: " USD",
    decimals: 0,
    source: "IMF DataMapper · WEO",
    sourceCode: "NGDPDPC",
    frequency: "annual",
    description: "Referencia de renta nacional. Para evaluar brecha rural-urbana cruzar con datasets de renta municipal (datos.gob.es).",
    endpoint: "/api/imf/country?iso=ESP&indicator=NGDPDPC",
    parser: "imf-country",
    imfIndicator: "NGDPDPC",
    accent: "#0F766E",
  },
  {
    id: "mr-paro-imf",
    family: "empleo",
    label: "Tasa paro · IMF LUR",
    shortLabel: "Paro",
    unit: "%",
    decimals: 2,
    source: "IMF DataMapper · WEO",
    sourceCode: "LUR",
    frequency: "annual",
    description: "Tasa de paro. Proxy de presión laboral en mundo rural (típicamente <urbano salvo en zonas con paro agrario estacional).",
    endpoint: "/api/imf/country?iso=ESP&indicator=LUR",
    parser: "imf-country",
    imfIndicator: "LUR",
    threshold: { amber: 12, red: 18, goodAbove: false },
    accent: "#f59e0b",
  },
  {
    id: "mr-exports-yoy",
    family: "exterior",
    label: "Exportaciones reales · IMF TX_RPCH",
    shortLabel: "Exports",
    unit: "%",
    decimals: 2,
    source: "IMF DataMapper · WEO",
    sourceCode: "TX_RPCH",
    frequency: "annual",
    description: "Crecimiento de exportaciones reales. España agroalimentaria es exportadora neta — proxy de demanda externa para producción rural.",
    endpoint: "/api/imf/country?iso=ESP&indicator=TX_RPCH",
    parser: "imf-country",
    imfIndicator: "TX_RPCH",
    accent: "#0891b2",
  },
  {
    id: "mr-inversion-bruta",
    family: "demanda",
    label: "Inversión bruta %PIB · IMF NID_NGDP",
    shortLabel: "Inversión",
    unit: "%",
    decimals: 2,
    source: "IMF DataMapper · WEO",
    sourceCode: "NID_NGDP",
    frequency: "annual",
    description: "FBCF %PIB. La inversión rural (regadío, infraestructura agraria, energías renovables) requiere capex sostenido.",
    endpoint: "/api/imf/country?iso=ESP&indicator=NID_NGDP",
    parser: "imf-country",
    imfIndicator: "NID_NGDP",
    accent: "#f97316",
  },
  {
    id: "mr-ipc-anual",
    family: "precios",
    label: "IPC anual (alimentos drivers) · INE 290750",
    shortLabel: "IPC YoY",
    unit: "%",
    decimals: 2,
    source: "INE WSTempus · IPC",
    sourceCode: "IPC290750",
    frequency: "monthly",
    description: "IPC general. Componente alimentación dentro del IPC afecta rentas agrarias y poder negociador rural.",
    endpoint: "/api/ine/ipc?n=36",
    parser: "ine-ipc",
    parserKey: "anual",
    threshold: { amber: 2, red: 4, goodAbove: false },
    accent: "#dc2626",
  },
  {
    id: "mr-frontur-rural",
    family: "demanda",
    label: "Turistas internacionales · INE Frontur 23988",
    shortLabel: "Turistas",
    unit: "",
    decimals: 0,
    source: "INE WSTempus · Frontur",
    sourceCode: "FRONTUR23988",
    frequency: "monthly",
    description:
      "Llegadas mensuales de turistas internacionales. El turismo rural absorbe ~15% del flujo total — relevante para vertebración territorial.",
    endpoint: "/api/ine/frontur?n=24",
    parser: "ine-frontur",
    accent: "#16a34a",
  },
];

export const MEDIO_RURAL_META = {
  slug: "medio-rural",
  label: "Medio rural & cohesión territorial",
  shortLabel: "Rural",
  accent: "#16a34a",
  description: "Vulnerabilidad rural, agricultura, ganadería, agua, PAC, servicios públicos rurales y cohesión territorial.",
};
