/**
 * Catálogo · Subtab 13 "Medio rural & cohesión territorial" v3.
 * Foco: vulnerabilidad rural, agricultura, agua, PAC, servicios rurales.
 * v1 con indicadores macro relacionados; datasets FEGA/PAC/MAPA/MITECO
 * vendrán por /api/datos-gob/csv (parser ya disponible).
 */
import type { PulsoIndicatorMeta } from "./pulso-indicators";

/**
 * Sprint N6.2 cleanup: removidos PIB pc, Paro IMF, Exports, Inversión bruta,
 * IPC general, Turistas FRONTUR (todos copiados de otros catálogos).
 * Esta versión se centra en lo realmente rural: empleo agrario, valor añadido
 * agro %PIB, animal stock, vulnerabilidad climática.
 */
export const MEDIO_RURAL_INDICATORS: PulsoIndicatorMeta[] = [
  {
    id: "mr-empleo-agrario",
    family: "empleo",
    label: "Empleo agrario (NACE A) %total",
    shortLabel: "Empleo agro",
    unit: "%",
    decimals: 1,
    source: "Eurostat · lfsq_egan2",
    sourceCode: "lfsq_egan2:A:ES",
    frequency: "quarterly",
    description:
      "% ocupados en agricultura/ganadería sobre total ocupados. España ~4% (vs UE 4%). Caída estructural histórica — desierto poblacional rural.",
    endpoint: "/api/eurostat/dataset?code=lfsq_egan2&filters=geo=ES;nace_r2=A",
    parser: "eurostat-simple",
    threshold: { amber: 3.5, red: 3, goodAbove: true },
    accent: "#16a34a",
  },
  {
    id: "mr-vab-agrario-pib",
    family: "pib",
    label: "VAB agrario %PIB",
    shortLabel: "VAB agro",
    unit: "%",
    decimals: 1,
    source: "Eurostat · nama_10_a10",
    sourceCode: "nama_10_a10:A:ES",
    frequency: "annual",
    description:
      "Valor añadido bruto agricultura+ganadería+silvicultura sobre PIB. España ~2.7% vs UE 1.7%. Reflejo del peso económico del sector primario.",
    endpoint: "/api/eurostat/dataset?code=nama_10_a10&filters=geo=ES;nace_r2=A",
    parser: "eurostat-simple",
    accent: "#84cc16",
  },
  {
    id: "mr-arrendamientos-agrarios",
    family: "precios",
    label: "Precios productor agrario (PPRI)",
    shortLabel: "PPRI agro",
    unit: "%",
    decimals: 1,
    source: "Eurostat · apri_pi20_outa",
    sourceCode: "apri_pi20_outa:ES",
    frequency: "annual",
    description:
      "Índice precios productor agrario. Driver clave de la renta rural (compraventa a mayoristas/industria). Shock 2022 con precios cereales y aceite.",
    endpoint: "/api/eurostat/dataset?code=apri_pi20_outa&filters=geo=ES",
    parser: "eurostat-simple",
    accent: "#f59e0b",
  },
  {
    id: "mr-energia-agro",
    family: "oferta",
    label: "Consumo final energía agricultura",
    shortLabel: "Energía agro",
    unit: " ktoe",
    decimals: 0,
    source: "Eurostat · nrg_bal_c",
    sourceCode: "nrg_bal_c:FC_OTH_AF_E:ES",
    frequency: "annual",
    description:
      "Consumo final de energía en agricultura+silvicultura. Sensibilidad al shock energético: precios gasóleo agrícola = movilización rural (2022).",
    endpoint: "/api/eurostat/dataset?code=nrg_bal_c&filters=geo=ES;nrg_bal=FC_OTH_AF_E",
    parser: "eurostat-simple",
    accent: "#dc2626",
  },
  // Sprint N13.1 · Bug fix · eliminado duplicado consecutivo de mr-aei-eurostat
  {
    id: "mr-aei-eurostat",
    family: "oferta",
    label: "Renta empresarial agraria",
    shortLabel: "Renta agro",
    unit: "",
    decimals: 0,
    source: "Eurostat · aact_eaa04",
    sourceCode: "aact_eaa04:ENTREP_HOL_RY:ES",
    frequency: "annual",
    description:
      "Renta empresarial agraria por unidad de trabajo anual (índice). Rentabilidad efectiva del campo · volátil por dependencia climatológica + PAC + precios energía.",
    endpoint: "/api/eurostat/dataset?code=aact_eaa04&filters=geo=ES;indic_ag=ENTREP_HOL_RY",
    parser: "eurostat-simple",
    accent: "#84cc16",
  },
  // Sprint L F6 · +1 superficie agraria utilizada (SAU)
  {
    id: "mr-sau-eurostat",
    family: "oferta",
    label: "Superficie agraria útil · Eurostat ef_lus_main",
    shortLabel: "SAU",
    unit: " ha",
    decimals: 0,
    source: "Eurostat · ef_lus_main",
    sourceCode: "ef_lus_main:UAA",
    frequency: "annual",
    description:
      "Superficie agraria útil (UAA) total. Mide cuánta tierra está realmente cultivada o usada para ganadería — proxy de presión territorial agraria y desertificación.",
    endpoint: "/api/eurostat/dataset?code=ef_lus_main&filters=geo=ES;crops=UAA;agrarea=TOTAL",
    parser: "eurostat-simple",
    accent: "#16a34a",
  },

  // ─── Sprint N13.2 · Expansión nicho rural (Eurostat agro stats) ────────
  {
    id: "mr-censo-porcino",
    family: "oferta",
    label: "Censo porcino España",
    shortLabel: "Porcino",
    unit: " mil cab.",
    decimals: 0,
    source: "Eurostat · apro_mt_lspig",
    sourceCode: "apro_mt_lspig:ES",
    frequency: "annual",
    description:
      "Cabaña porcina total · España es 1º productor UE y 3º mundial. Driver de exports cárnicos + impacto medioambiental (purines, agua).",
    endpoint: "/api/eurostat/dataset?code=apro_mt_lspig&filters=geo=ES",
    parser: "eurostat-simple",
    accent: "#f97316",
  },
  {
    id: "mr-censo-bovino",
    family: "oferta",
    label: "Censo bovino España",
    shortLabel: "Bovino",
    unit: " mil cab.",
    decimals: 0,
    source: "Eurostat · apro_mt_lscatl",
    sourceCode: "apro_mt_lscatl:ES",
    frequency: "annual",
    description:
      "Cabaña vacuno · proxy de la ganadería extensiva española. Caída estructural en dehesa por concentración + leche extensiva.",
    endpoint: "/api/eurostat/dataset?code=apro_mt_lscatl&filters=geo=ES",
    parser: "eurostat-simple",
    accent: "#a16207",
  },
  {
    id: "mr-fertilizantes",
    family: "oferta",
    label: "Uso fertilizantes N",
    shortLabel: "Fertilizantes",
    unit: " kg/ha",
    decimals: 1,
    source: "Eurostat · aei_fm_usefert",
    sourceCode: "aei_fm_usefert:ES",
    frequency: "annual",
    description:
      "Uso de fertilizantes nitrogenados sintéticos por hectárea. Intensificación agraria · driver emisiones N2O + nitratos en acuíferos.",
    endpoint: "/api/eurostat/dataset?code=aei_fm_usefert&filters=geo=ES",
    parser: "eurostat-simple",
    accent: "#dc2626",
  },
  {
    id: "mr-erosion-suelo",
    family: "oferta",
    label: "Erosión suelo agrario",
    shortLabel: "Erosión",
    unit: " t/ha/año",
    decimals: 1,
    source: "Eurostat · aei_pr_soiler",
    sourceCode: "aei_pr_soiler:ES",
    frequency: "annual",
    description:
      "Pérdida de suelo por erosión hídrica (RUSLE) tn/ha/año. España >7 t/ha (umbral OCDE tolerable ~10) · riesgo desertificación · vulnerabilidad climática.",
    endpoint: "/api/eurostat/dataset?code=aei_pr_soiler&filters=geo=ES",
    parser: "eurostat-simple",
    threshold: { amber: 7, red: 10, goodAbove: false },
    accent: "#dc2626",
  },
  {
    id: "mr-cereales-produccion",
    family: "oferta",
    label: "Producción cereales total",
    shortLabel: "Cereales",
    unit: " kt",
    decimals: 0,
    source: "Eurostat · apro_cpsh1",
    sourceCode: "apro_cpsh1:C0000:ES",
    frequency: "annual",
    description:
      "Producción cereales totales (trigo, cebada, maíz). Sensible a sequía. Cosecha 2022 -36% por sequía severa.",
    endpoint: "/api/eurostat/dataset?code=apro_cpsh1&filters=geo=ES;crops=C0000",
    parser: "eurostat-simple",
    accent: "#84cc16",
  },
  {
    id: "mr-mano-obra-agraria",
    family: "empleo",
    label: "Mano de obra agraria total (UTA)",
    shortLabel: "UTA agro",
    unit: " mil UTA",
    decimals: 0,
    source: "Eurostat · ef_kvecsleg",
    sourceCode: "ef_kvecsleg:ES",
    frequency: "annual",
    description:
      "Unidades de Trabajo Anual (UTA) totales en agricultura · familiar + asalariado + temporal. Mide capacidad productiva real, no censo empleo formal.",
    endpoint: "/api/eurostat/dataset?code=ef_kvecsleg&filters=geo=ES",
    parser: "eurostat-simple",
    accent: "#16a34a",
  },

  // ─── Sprint N16 · AEMET clima rural (requiere AEMET_API_KEY en Vercel) ─
  {
    id: "mr-precipitacion-and",
    family: "oferta",
    label: "Precipitación mensual Andalucía (Almería)",
    shortLabel: "Lluvia AND",
    unit: " mm",
    decimals: 1,
    source: "AEMET · OpenData climatologías",
    sourceCode: "AEMET_PRECIP_04",
    frequency: "monthly",
    description:
      "Precipitación acumulada mensual estación representativa Almería (provincia 04). Andalucía es uno de los principales focos de sequía hidrológica en España · driver del estrés hídrico agrícola.",
    endpoint: "/api/aemet/precipitacion-ccaa?ccaa=AND",
    parser: "aemet-precipitacion",
    parserKey: "precip",
    threshold: { amber: 20, red: 8, goodAbove: true },
    accent: "#0891b2",
    methodologyNote:
      "Climatología mensual oficial AEMET. Una sola estación por provincia (no agregado areal). Valores 'Ip' (inapreciable) tratados como 0. Series oficiales del Banco de Datos Climatológico.",
    releaseSchedule: "Mensual · publicación T+15 días tras fin de mes",
    confidenceLevel: "high",
    relatedIndicatorIds: ["mr-cereales-produccion", "mr-erosion-suelo"],
  },
  {
    id: "mr-precipitacion-cyl",
    family: "oferta",
    label: "Precipitación mensual Castilla y León (Valladolid)",
    shortLabel: "Lluvia CYL",
    unit: " mm",
    decimals: 1,
    source: "AEMET · OpenData climatologías",
    sourceCode: "AEMET_PRECIP_47",
    frequency: "monthly",
    description:
      "Precipitación mensual Valladolid. Indicador hidrológico para cereal de secano en la principal cuenca productora · sensibilidad a sequía determina cosecha trigo/cebada.",
    endpoint: "/api/aemet/precipitacion-ccaa?ccaa=CYL",
    parser: "aemet-precipitacion",
    parserKey: "precip",
    threshold: { amber: 25, red: 10, goodAbove: true },
    accent: "#0891b2",
    methodologyNote:
      "Climatología mensual estación Valladolid. CYL es la mayor superficie cerealista de España (~1.3M ha); lluvia en abril-mayo determina la cosecha de junio.",
    releaseSchedule: "Mensual · T+15 días",
    confidenceLevel: "high",
    relatedIndicatorIds: ["mr-cereales-produccion"],
  },
  {
    id: "mr-temperatura-mad",
    family: "oferta",
    label: "Temperatura media mensual Madrid",
    shortLabel: "Tm MAD",
    unit: " ºC",
    decimals: 1,
    source: "AEMET · OpenData climatologías",
    sourceCode: "AEMET_TM_28",
    frequency: "monthly",
    description:
      "Temperatura media mensual estación Madrid (provincia 28). Driver del estrés térmico veraniego: anomalías superiores a +2ºC sobre la media histórica activan olas de calor con impacto en mortalidad y demanda eléctrica.",
    endpoint: "/api/aemet/precipitacion-ccaa?ccaa=MAD",
    parser: "aemet-precipitacion",
    parserKey: "tm",
    accent: "#dc2626",
    methodologyNote:
      "Temperatura media diaria agregada mensualmente. Comparativa con periodo climático estándar 1991-2020 (referencia OMM). Anomalías estructurales reflejan calentamiento.",
    releaseSchedule: "Mensual · T+15 días",
    confidenceLevel: "high",
  },

  // ─── Sprint N18 · AEMET broad coverage · 11 CCAA peninsulares + insulares ──
  {
    id: "mr-precipitacion-ara",
    family: "oferta",
    label: "Precipitación mensual Aragón (Zaragoza)",
    shortLabel: "Lluvia ARA",
    unit: " mm",
    decimals: 1,
    source: "AEMET · OpenData climatologías",
    sourceCode: "AEMET_PRECIP_50",
    frequency: "monthly",
    description:
      "Precipitación mensual Zaragoza. Cuenca Ebro · driver irrigación intensiva y regadío frutícola. Sensibilidad alta a sequía hidrológica embalses CHE.",
    endpoint: "/api/aemet/precipitacion-ccaa?ccaa=ARA",
    parser: "aemet-precipitacion",
    parserKey: "precip",
    threshold: { amber: 25, red: 12, goodAbove: true },
    accent: "#0891b2",
    methodologyNote:
      "Climatología mensual estación Zaragoza-Aeropuerto. Aragón depende del Ebro: precipitación pirenaica + Sistema Ibérico determina la cosecha frutícola + cereal de Aragón + suministro Tarragona/Castellón.",
    releaseSchedule: "Mensual · T+15 días",
    confidenceLevel: "high",
    relatedIndicatorIds: ["mr-precipitacion-cyl", "mr-cereales-produccion"],
  },
  {
    id: "mr-precipitacion-ast",
    family: "oferta",
    label: "Precipitación mensual Asturias",
    shortLabel: "Lluvia AST",
    unit: " mm",
    decimals: 1,
    source: "AEMET · OpenData climatologías",
    sourceCode: "AEMET_PRECIP_33",
    frequency: "monthly",
    description:
      "Precipitación mensual Oviedo. Cornisa cantábrica · clima oceánico húmedo. Estructuralmente alto (~1000mm/año). Anomalías a la baja anticipan stress hidroeléctrico Endesa/EDP.",
    endpoint: "/api/aemet/precipitacion-ccaa?ccaa=AST",
    parser: "aemet-precipitacion",
    parserKey: "precip",
    accent: "#0EA5E9",
    methodologyNote:
      "Climatología Asturias. Región peninsular más lluviosa después de Galicia. Caída sostenida tiene impacto hidroeléctrico (Salime, Tanes) + ganadería leche extensiva.",
    releaseSchedule: "Mensual · T+15 días",
    confidenceLevel: "high",
    relatedIndicatorIds: ["mr-precipitacion-gal"],
  },
  {
    id: "mr-precipitacion-bal",
    family: "oferta",
    label: "Precipitación mensual Baleares",
    shortLabel: "Lluvia BAL",
    unit: " mm",
    decimals: 1,
    source: "AEMET · OpenData climatologías",
    sourceCode: "AEMET_PRECIP_07",
    frequency: "monthly",
    description:
      "Precipitación mensual Palma de Mallorca. Insular mediterráneo · estructuralmente seco. Crítico para acuíferos costeros + suministro turístico verano.",
    endpoint: "/api/aemet/precipitacion-ccaa?ccaa=BAL",
    parser: "aemet-precipitacion",
    parserKey: "precip",
    threshold: { amber: 15, red: 5, goodAbove: true },
    accent: "#0891b2",
    methodologyNote:
      "Climatología Palma-Aeropuerto. Baleares depende de acuíferos sobreexplotados + plantas desalinización (suministro turístico Q3). Sequía pico restringe trasvases internos.",
    releaseSchedule: "Mensual · T+15 días",
    confidenceLevel: "high",
    relatedIndicatorIds: ["mr-precipitacion-and", "co-frontur"],
  },
  {
    id: "mr-precipitacion-can",
    family: "oferta",
    label: "Precipitación mensual Canarias",
    shortLabel: "Lluvia CAN",
    unit: " mm",
    decimals: 1,
    source: "AEMET · OpenData climatologías",
    sourceCode: "AEMET_PRECIP_35",
    frequency: "monthly",
    description:
      "Precipitación mensual Las Palmas. Insular atlántico subtropical · estructuralmente muy seco. 100% dependencia desalinización agua dulce.",
    endpoint: "/api/aemet/precipitacion-ccaa?ccaa=CAN",
    parser: "aemet-precipitacion",
    parserKey: "precip",
    accent: "#f59e0b",
    methodologyNote:
      "Las Palmas (provincia oriental). Canarias depende ~100% de desalinización + reutilización. Lluvia ocasional alivia coste energético desal pero no es driver primario.",
    releaseSchedule: "Mensual · T+15 días",
    confidenceLevel: "high",
  },
  {
    id: "mr-precipitacion-ctb",
    family: "oferta",
    label: "Precipitación mensual Cantabria",
    shortLabel: "Lluvia CTB",
    unit: " mm",
    decimals: 1,
    source: "AEMET · OpenData climatologías",
    sourceCode: "AEMET_PRECIP_39",
    frequency: "monthly",
    description:
      "Precipitación mensual Santander. Cornisa cantábrica · clima oceánico. Stress hidroeléctrico cuenca Pas-Pisueña-Saja-Besaya impacta industria Cantabria.",
    endpoint: "/api/aemet/precipitacion-ccaa?ccaa=CTB",
    parser: "aemet-precipitacion",
    parserKey: "precip",
    accent: "#0EA5E9",
    methodologyNote:
      "Climatología Santander. Similar a Asturias (oceánica). Indicador stress hidroeléctrico + ganadería leche extensiva.",
    releaseSchedule: "Mensual · T+15 días",
    confidenceLevel: "high",
  },
  {
    id: "mr-precipitacion-clm",
    family: "oferta",
    label: "Precipitación mensual Castilla-La Mancha",
    shortLabel: "Lluvia CLM",
    unit: " mm",
    decimals: 1,
    source: "AEMET · OpenData climatologías",
    sourceCode: "AEMET_PRECIP_13",
    frequency: "monthly",
    description:
      "Precipitación mensual Ciudad Real. Meseta Sur · clima continental seco. Driver olivar + viñedo La Mancha + cereal · sensibilidad sequía agrícola alta.",
    endpoint: "/api/aemet/precipitacion-ccaa?ccaa=CLM",
    parser: "aemet-precipitacion",
    parserKey: "precip",
    threshold: { amber: 25, red: 10, goodAbove: true },
    accent: "#0891b2",
    methodologyNote:
      "Climatología Ciudad Real. CLM es 1ª productora olivar regado + 1ª viñedo España. Sequía severa puede colapsar la cosecha.",
    releaseSchedule: "Mensual · T+15 días",
    confidenceLevel: "high",
    relatedIndicatorIds: ["mr-cereales-produccion", "mr-precipitacion-and"],
  },
  {
    id: "mr-precipitacion-cat",
    family: "oferta",
    label: "Precipitación mensual Cataluña (Barcelona)",
    shortLabel: "Lluvia CAT",
    unit: " mm",
    decimals: 1,
    source: "AEMET · OpenData climatologías",
    sourceCode: "AEMET_PRECIP_08",
    frequency: "monthly",
    description:
      "Precipitación mensual Barcelona. Mediterráneo norte · clima de transición. Sequía severa 2023-24 forzó restricciones suministro AMB + escenarios desal/trasvases.",
    endpoint: "/api/aemet/precipitacion-ccaa?ccaa=CAT",
    parser: "aemet-precipitacion",
    parserKey: "precip",
    threshold: { amber: 30, red: 15, goodAbove: true },
    accent: "#0891b2",
    methodologyNote:
      "Climatología Barcelona-Aeropuerto. Cataluña sufrió la peor sequía del siglo XXI en 2023-24 (embalses Ter-Llobregat al 16%). Driver clave estabilidad suministro AMB.",
    releaseSchedule: "Mensual · T+15 días",
    confidenceLevel: "high",
    relatedIndicatorIds: ["mr-precipitacion-and"],
  },
  {
    id: "mr-precipitacion-cva",
    family: "oferta",
    label: "Precipitación mensual C. Valenciana",
    shortLabel: "Lluvia CVA",
    unit: " mm",
    decimals: 1,
    source: "AEMET · OpenData climatologías",
    sourceCode: "AEMET_PRECIP_46",
    frequency: "monthly",
    description:
      "Precipitación mensual Valencia. Mediterráneo · clima semiárido. Driver cítricos + arrozal Albufera + suministro turístico Benidorm.",
    endpoint: "/api/aemet/precipitacion-ccaa?ccaa=CVA",
    parser: "aemet-precipitacion",
    parserKey: "precip",
    threshold: { amber: 25, red: 10, goodAbove: true },
    accent: "#0891b2",
    methodologyNote:
      "Climatología Valencia-Aeropuerto. CVA depende del Júcar + trasvase Tajo-Segura. Octubre suele ser mes pico precipitación (gota fría · DANAs).",
    releaseSchedule: "Mensual · T+15 días",
    confidenceLevel: "high",
  },
  {
    id: "mr-precipitacion-ext",
    family: "oferta",
    label: "Precipitación mensual Extremadura",
    shortLabel: "Lluvia EXT",
    unit: " mm",
    decimals: 1,
    source: "AEMET · OpenData climatologías",
    sourceCode: "AEMET_PRECIP_10",
    frequency: "monthly",
    description:
      "Precipitación mensual Cáceres. Mediterráneo continental · sequía estival. Driver dehesa extensiva + olivar + cuenca Tajo (regadío + hidroeléctrico Iberdrola).",
    endpoint: "/api/aemet/precipitacion-ccaa?ccaa=EXT",
    parser: "aemet-precipitacion",
    parserKey: "precip",
    threshold: { amber: 25, red: 10, goodAbove: true },
    accent: "#0891b2",
    methodologyNote:
      "Climatología Cáceres. Estiaje fuerte jun-sep. Cuenca Tajo: trasvase Tajo-Segura politizado por reducción aportaciones por cambio climático.",
    releaseSchedule: "Mensual · T+15 días",
    confidenceLevel: "high",
  },
  {
    id: "mr-precipitacion-gal",
    family: "oferta",
    label: "Precipitación mensual Galicia",
    shortLabel: "Lluvia GAL",
    unit: " mm",
    decimals: 1,
    source: "AEMET · OpenData climatologías",
    sourceCode: "AEMET_PRECIP_15",
    frequency: "monthly",
    description:
      "Precipitación mensual A Coruña. Atlántico noroeste · clima oceánico hiperhúmedo. Estructuralmente alta (~1200mm/año). Caídas anticipan stress hidroeléctrico cuencas Miño-Sil-Tambre.",
    endpoint: "/api/aemet/precipitacion-ccaa?ccaa=GAL",
    parser: "aemet-precipitacion",
    parserKey: "precip",
    accent: "#0EA5E9",
    methodologyNote:
      "Climatología A Coruña. Galicia genera ~30% hidroelectricidad nacional (Saltos del Sil + Salime). Sequía severa estresa precios mayoristas eléctrica.",
    releaseSchedule: "Mensual · T+15 días",
    confidenceLevel: "high",
  },
  {
    id: "mr-precipitacion-mur",
    family: "oferta",
    label: "Precipitación mensual Murcia",
    shortLabel: "Lluvia MUR",
    unit: " mm",
    decimals: 1,
    source: "AEMET · OpenData climatologías",
    sourceCode: "AEMET_PRECIP_30",
    frequency: "monthly",
    description:
      "Precipitación mensual Murcia. SE peninsular · clima árido (la zona más seca de la España peninsular). Driver crítico regadío Segura + trasvase Tajo-Segura.",
    endpoint: "/api/aemet/precipitacion-ccaa?ccaa=MUR",
    parser: "aemet-precipitacion",
    parserKey: "precip",
    threshold: { amber: 15, red: 5, goodAbove: true },
    accent: "#dc2626",
    methodologyNote:
      "Climatología Murcia-Aeropuerto. Región más árida peninsular (~300mm/año). 'Huerta Europa' depende 30% trasvase Tajo-Segura — recortes generan tensión política recurrente.",
    releaseSchedule: "Mensual · T+15 días",
    confidenceLevel: "high",
    relatedIndicatorIds: ["mr-precipitacion-and"],
  },
  // ─── Sprint Tab13-Hero · 10 indicadores nuevos del spec Tab 13.md ─────
  {
    id: "mr-municipios-1000",
    family: "demanda",
    label: "Municipios <1000 hab. % total",
    shortLabel: "Mun <1000",
    unit: "%",
    decimals: 1,
    source: "Derivado · INE Padrón municipal",
    sourceCode: "DERIVED_MUN_1000",
    frequency: "annual",
    description:
      "% municipios con menos de 1000 habitantes sobre total (8131 municipios). España ~62% — núcleo de la 'España vaciada'.",
    endpoint: "/api/spanish-stats/municipios-1000?country=ESP",
    parser: "spanish-stats-points",
    threshold: { amber: 55, red: 65, goodAbove: false },
    accent: "#dc2626",
    methodologyNote:
      "Umbral 1000 hab. = criterio MAPA para zona rural escasamente poblada. Concentrado en interior peninsular (Castilla y León, Aragón, Castilla-La Mancha, Extremadura).",
    releaseSchedule: "Anual · derivado",
    confidenceLevel: "low",
    relatedIndicatorIds: ["dt-municipios-despoblacion", "dt-poblacion-rural"],
  },
  {
    id: "mr-pob-mun-5000",
    family: "demanda",
    label: "% población en municipios <5000 hab.",
    shortLabel: "Pob <5k",
    unit: "%",
    decimals: 1,
    source: "Derivado · INE Padrón",
    sourceCode: "DERIVED_POB_5000",
    frequency: "annual",
    description:
      "% población española residente en municipios <5000 hab. ~13%. Pequeño pero territorialmente ocupa >70% del país. Brecha territorial.",
    endpoint: "/api/spanish-stats/pob-mun-5000?country=ESP",
    parser: "spanish-stats-points",
    accent: "#7C3AED",
    methodologyNote:
      "Inverso de metropolización. Países UE15 con concentración urbana media: ~10-15% rural. España estructuralmente baja densidad demográfica.",
    releaseSchedule: "Anual · derivado",
    confidenceLevel: "low",
    relatedIndicatorIds: ["mr-municipios-1000"],
  },
  {
    id: "mr-ratio-pib-ccaa",
    family: "demanda",
    label: "Ratio PIB pc CCAA rica/pobre",
    shortLabel: "PIB pc Δ",
    unit: "x",
    decimals: 2,
    source: "Derivado · INE Contabilidad Regional",
    sourceCode: "DERIVED_RATIO_PIB_CCAA",
    frequency: "annual",
    description:
      "Cociente PIB per cápita CCAA más rica (Madrid) / CCAA más pobre (Extremadura). España ~1.8x. Mayor que media UE.",
    endpoint: "/api/spanish-stats/ratio-pib-ccaa?country=ESP",
    parser: "spanish-stats-points",
    threshold: { amber: 1.7, red: 2, goodAbove: false },
    accent: "#dc2626",
    methodologyNote:
      "Indicador divergencia territorial. España >UE15 estructuralmente — bloque sur-noreste vs interior-suroeste.",
    releaseSchedule: "Anual · derivado",
    confidenceLevel: "low",
    relatedIndicatorIds: ["mr-sigma-convergencia"],
  },
  {
    id: "mr-sigma-convergencia",
    family: "demanda",
    label: "Sigma-convergencia PIB pc CCAA",
    shortLabel: "σ-conv.",
    unit: "",
    decimals: 3,
    source: "Derivado · INE",
    sourceCode: "DERIVED_SIGMA_CCAA",
    frequency: "annual",
    description:
      "Desviación típica logaritmos PIB pc CCAA. Disminuye = convergencia regional. España estancada desde 2008.",
    endpoint: "/api/spanish-stats/sigma-ccaa?country=ESP",
    parser: "spanish-stats-points",
    accent: "#f59e0b",
    methodologyNote:
      "Indicador estándar literatura crecimiento regional (Barro-Sala-i-Martin). Convergencia σ vs convergencia β.",
    releaseSchedule: "Anual · derivado",
    confidenceLevel: "low",
    relatedIndicatorIds: ["mr-ratio-pib-ccaa"],
  },
  {
    id: "mr-pac-fondos",
    family: "fiscalidad",
    label: "Fondos PAC recibidos España",
    shortLabel: "PAC €bn",
    unit: " €bn",
    decimals: 2,
    source: "FEGA · pagos directos",
    sourceCode: "FEGA_PAC_TOTAL",
    frequency: "annual",
    description:
      "PAC España ~7 €bn/año. Driver renta agraria + cohesión territorial rural. Ayudas directas + desarrollo rural.",
    endpoint: "/api/spanish-stats/pac-fondos?country=ESP",
    parser: "spanish-stats-points",
    accent: "#16a34a",
    methodologyNote:
      "FEGA datos abiertos. Distribución muy concentrada (top 20% beneficiarios → 80% fondos). Política UE en revisión post-2027.",
    releaseSchedule: "Anual · FEGA",
    confidenceLevel: "low",
    relatedIndicatorIds: ["mr-vab-agrario-pib"],
  },
  {
    id: "mr-feder-feader",
    family: "fiscalidad",
    label: "FEDER+FEADER ejecutado %",
    shortLabel: "FEDER/FEADER",
    unit: "%",
    decimals: 1,
    source: "CE cohesiondata",
    sourceCode: "EU_COHESION_ES",
    frequency: "annual",
    description:
      "% fondos cohesión UE (FEDER+FEADER) ejecutados vs asignados. Indicador clave capacidad administrativa territorial.",
    endpoint: "/api/spanish-stats/feder-feader?country=ESP",
    parser: "spanish-stats-points",
    threshold: { amber: 60, red: 40, goodAbove: true },
    accent: "#0F766E",
    methodologyNote:
      "cohesiondata.ec.europa.eu API. España riesgo devolución por baja ejecución hist. Periodo 2014-2020 cerrado a 2024 — atención al cierre.",
    releaseSchedule: "Trimestral · CE",
    confidenceLevel: "low",
    relatedIndicatorIds: ["mr-pac-fondos"],
  },
  {
    id: "mr-banda-ancha-rural",
    family: "demanda",
    label: "Cobertura banda ancha rural >30Mbps",
    shortLabel: "Banda ancha",
    unit: "%",
    decimals: 1,
    source: "CNMC · cobertura municipal",
    sourceCode: "CNMC_BANDA_ANCHA_RURAL",
    frequency: "annual",
    description:
      "% municipios <5000 hab. con cobertura >30 Mbps. Driver despoblación: cobertura insuficiente acelera éxodo rural.",
    endpoint: "/api/spanish-stats/banda-ancha-rural?country=ESP",
    parser: "spanish-stats-points",
    threshold: { amber: 80, red: 60, goodAbove: true },
    accent: "#7C3AED",
    methodologyNote:
      "CNMC publica anualmente cobertura por municipio. Brecha estructural: zonas urbanas >95%, rurales 50-80%.",
    releaseSchedule: "Anual · CNMC junio",
    confidenceLevel: "low",
    relatedIndicatorIds: ["mr-municipios-1000"],
  },
  {
    id: "mr-precio-tierra",
    family: "demanda",
    label: "Precio medio tierra agrícola",
    shortLabel: "Precio tierra",
    unit: " €/ha",
    decimals: 0,
    source: "MAPA · Encuesta precios tierra",
    sourceCode: "MAPA_PRECIO_TIERRA",
    frequency: "annual",
    description:
      "Precio medio €/ha tierra agrícola. España ~10.000 €/ha. Indicador rentabilidad agraria y especulación territorial.",
    endpoint: "/api/spanish-stats/precio-tierra?country=ESP",
    parser: "spanish-stats-points",
    accent: "#16a34a",
    methodologyNote:
      "MAPA Encuesta anual. Variación significativa por CCAA (regadío vs secano, viñedo, olivar).",
    releaseSchedule: "Anual · MAPA",
    confidenceLevel: "low",
    relatedIndicatorIds: ["mr-vab-agrario-pib", "mr-arrendamientos-agrarios"],
  },
  {
    id: "mr-renovables-mix",
    family: "demanda",
    label: "Renovables % mix Spain",
    shortLabel: "Renovables",
    unit: "%",
    decimals: 1,
    source: "ESIOS REE · mix renovable",
    sourceCode: "ESIOS_MIX_RENOVABLE",
    frequency: "daily",
    description:
      "% mix eléctrico Spain proveniente de renovables. ~50% (2024). Generación concentrada en CCAA rurales (Castilla y León, Aragón, Extremadura).",
    endpoint: "/api/esios/mix-renovable?n=12",
    parser: "ine-ipc",
    threshold: { amber: 50, red: 40, goodAbove: true },
    accent: "#16a34a",
    methodologyNote:
      "ESIOS Red Eléctrica de España. Renovables = eólica + solar FV + hidráulica + termosolar. Distribución territorial: rurales producen, urbanas consumen.",
    releaseSchedule: "Diario · ESIOS",
    confidenceLevel: "low",
    relatedIndicatorIds: ["mr-energia-agro"],
  },
  {
    id: "mr-indice-cohesion-terr",
    family: "demanda",
    label: "Índice cohesión territorial compuesto",
    shortLabel: "Cohesión",
    unit: "",
    decimals: 1,
    source: "Derivado · PIB + paro + población + servicios CCAA",
    sourceCode: "DERIVED_COHESION_TERR",
    frequency: "annual",
    description:
      "Compuesto cuatro dimensiones territoriales (PIB pc, paro, densidad, servicios públicos pc). Permite ranking CCAA.",
    endpoint: "/api/macro/derived/cohesion_territorial",
    parser: "ine-ipc",
    accent: "#7C3AED",
    methodologyNote:
      "Indicador propio (Politeia). Combina 4 dimensiones normalizadas Z-score y agregadas. Permite monitorizar convergencia/divergencia territorial.",
    releaseSchedule: "Anual · derivado",
    confidenceLevel: "low",
    relatedIndicatorIds: ["mr-sigma-convergencia", "mr-ratio-pib-ccaa"],
  },
];

export const MEDIO_RURAL_META = {
  slug: "medio-rural",
  label: "Medio rural & cohesión territorial",
  shortLabel: "Rural",
  accent: "#16a34a",
  description: "Vulnerabilidad rural, agricultura, ganadería, agua, PAC, servicios públicos rurales y cohesión territorial.",
};
