/**
 * Catálogo · Subtab 12 "Sociedad, bienestar & desigualdad" v3 (Sprint N17).
 * Foco: cómo se distribuye el bienestar — pobreza, desigualdad, renta
 * real, educación, salud, prestaciones, malestar percibido.
 *
 * Sprint N6.2 cleanup: removidos PIB pc, IPC, Paro general, Paro juvenil,
 * Gasto AAPP, IPV, ETCL (todos duplicados de pulso-macro / margen-fiscal /
 * hogares-empleo-vivienda). Conservado AROPE + Gini (estructurales únicos)
 * y añadidos indicadores específicos de bienestar: pobreza monetaria,
 * carencia material severa, abandono escolar, S80/S20 (desigualdad extremos).
 *
 * Sprint N17 · methodology + release + confidence + related ids.
 */
import type { PulsoIndicatorMeta } from "./pulso-indicators";

export const SOCIEDAD_BIENESTAR_INDICATORS: PulsoIndicatorMeta[] = [
  {
    id: "sb-pobreza-monetaria",
    family: "demanda",
    label: "Pobreza monetaria (riesgo) · Eurostat",
    shortLabel: "Pobreza",
    unit: "%",
    decimals: 1,
    source: "Eurostat · ilc_li02",
    sourceCode: "ilc_li02:ES",
    frequency: "annual",
    description:
      "% población con renta disponible <60% mediana nacional. Métrica europea estándar de pobreza relativa. España persistente ~20% vs UE 17%.",
    endpoint: "/api/eurostat/dataset?code=ilc_li02&filters=geo=ES;sex=T;age=TOTAL",
    parser: "eurostat-simple",
    threshold: { amber: 18, red: 22, goodAbove: false },
    accent: "#dc2626",
    methodologyNote:
      "Renta equivalente <60% mediana. Métrica EU oficial pobreza relativa. España persistente ~20% — mejor 2008-13 (recesión sube todos los % rel) que post-recovery (sube proporción 'no recuperada').",
    releaseSchedule: "Anual · encuesta SILC · publicación T+12 meses",
    confidenceLevel: "high",
    relatedIndicatorIds: ["sb-arope-eurostat", "sb-carencia-material-severa", "sb-gini-eurostat"],
  },
  {
    id: "sb-carencia-material-severa",
    family: "demanda",
    label: "Carencia material severa",
    shortLabel: "CMS",
    unit: "%",
    decimals: 1,
    source: "Eurostat · ilc_mdsd07",
    sourceCode: "ilc_mdsd07:ES",
    frequency: "annual",
    description:
      "% hogares con privación severa (no pagar facturas, comer carne 2/sem, calefacción, vacaciones, lavadora/coche/tv/teléfono). Pobreza absoluta operativa.",
    endpoint: "/api/eurostat/dataset?code=ilc_mdsd07&filters=geo=ES",
    parser: "eurostat-simple",
    threshold: { amber: 7, red: 10, goodAbove: false },
    accent: "#dc2626",
    methodologyNote:
      "Hogares con >4 de 9 items privación: facturas, comer carne, calefacción, vacaciones, lavadora, coche, TV, teléfono, comida proteica. Pobreza 'dura' (absoluta). Menos sensible al ciclo que pobreza relativa.",
    releaseSchedule: "Anual · SILC · T+12 meses",
    confidenceLevel: "high",
    relatedIndicatorIds: ["sb-pobreza-monetaria", "sb-pobreza-energetica", "sb-arope-eurostat"],
  },
  {
    id: "sb-s80-s20",
    family: "demanda",
    label: "Ratio S80/S20 (desigualdad)",
    shortLabel: "S80/S20",
    unit: "",
    decimals: 1,
    source: "Eurostat · ilc_di11",
    sourceCode: "ilc_di11:ES",
    frequency: "annual",
    description:
      "Ratio renta total quintil superior / quintil inferior. Mide desigualdad entre extremos. España ~6.0 vs UE 4.7. Sensible a impacto de prestaciones.",
    endpoint: "/api/eurostat/dataset?code=ilc_di11&filters=geo=ES",
    parser: "eurostat-simple",
    threshold: { amber: 5.5, red: 6.5, goodAbove: false },
    accent: "#8b5cf6",
    methodologyNote:
      "Renta quintil 5 / quintil 1. Más sensible a extremos que Gini. España ~6.0 vs UE 4.7. IMV + reformas IRPF 2021-22 redujeron 0.3 pp.",
    releaseSchedule: "Anual · SILC · T+12 meses",
    confidenceLevel: "high",
    relatedIndicatorIds: ["sb-gini-eurostat", "sb-pobreza-monetaria"],
  },
  {
    id: "sb-abandono-escolar",
    family: "empleo",
    label: "Abandono escolar temprano 18-24",
    shortLabel: "Abandono",
    unit: "%",
    decimals: 1,
    source: "Eurostat · edat_lfse_14",
    sourceCode: "edat_lfse_14:ES",
    frequency: "annual",
    description:
      "% personas 18-24 años solo ESO sin estudios posteriores. España ~13% vs UE 9%. Indicador estructural del fallo educativo y reproducción de pobreza.",
    endpoint: "/api/eurostat/dataset?code=edat_lfse_14&filters=geo=ES",
    parser: "eurostat-simple",
    threshold: { amber: 10, red: 14, goodAbove: false },
    accent: "#f59e0b",
    methodologyNote:
      "18-24 con máximo ESO + no en formación. Tendencia descendente desde 32% (2008) → 13% (2024) — gran avance, aún por encima objetivo UE 2030 (<9%).",
    releaseSchedule: "Anual · LFS · T+6 meses",
    confidenceLevel: "high",
    relatedIndicatorIds: ["paro-epa-jovenes", "rs-neet", "pc-educacion-terciaria"],
  },
  {
    id: "sb-gasto-social-pib",
    family: "demanda",
    label: "Gasto en protección social %PIB",
    shortLabel: "Gasto social",
    unit: "%",
    decimals: 1,
    source: "Eurostat · spr_exp_sum",
    sourceCode: "spr_exp_sum:ES",
    frequency: "annual",
    description:
      "Gasto total protección social como % PIB (pensiones, sanidad, desempleo, familia, vivienda, exclusión). España ~25% vs UE 28%. Mide compromiso con welfare.",
    endpoint: "/api/eurostat/dataset?code=spr_exp_sum&filters=geo=ES",
    parser: "eurostat-simple",
    threshold: { amber: 24, red: 22, goodAbove: true },
    accent: "#0891b2",
    methodologyNote:
      "ESSPROS (European System of Integrated Social Protection Statistics). Mayor partida: vejez (44%) + sanidad (28%) + desempleo (7%) + familia (5%) + exclusión social (3%). España gap UE -3 pp.",
    releaseSchedule: "Anual · publicación T+24 meses",
    confidenceLevel: "high",
    relatedIndicatorIds: ["sb-pension-pib", "mf-prestaciones-d62", "ie-gasto-sanitario"],
  },
  {
    id: "sb-arope-eurostat",
    family: "demanda",
    label: "AROPE · Eurostat ilc_peps01n",
    shortLabel: "AROPE",
    unit: "%",
    decimals: 1,
    source: "Eurostat · ilc_peps01n",
    sourceCode: "ilc_peps01n",
    frequency: "annual",
    description:
      "People at risk of poverty or social exclusion (AROPE). Indicador EU oficial que combina pobreza monetaria + carencia material severa + baja intensidad laboral en el hogar.",
    endpoint: "/api/eurostat/dataset?code=ilc_peps01n&filters=geo=ES;sex=T;age=TOTAL;unit=PC",
    parser: "eurostat-simple",
    threshold: { amber: 22, red: 28, goodAbove: false },
    accent: "#dc2626",
    methodologyNote:
      "AROPE = at-risk-of-poverty + severe material deprivation + low work intensity (unión). Métrica oficial EU 2030 (target ES: -2.8M personas vs 2019). Histórico ES ~25-26%.",
    releaseSchedule: "Anual · SILC · publicación T+12 meses",
    confidenceLevel: "high",
    relatedIndicatorIds: ["sb-pobreza-monetaria", "sb-carencia-material-severa"],
  },
  {
    id: "sb-gini-eurostat",
    family: "demanda",
    label: "Coeficiente Gini · Eurostat ilc_di12",
    shortLabel: "Gini",
    unit: "",
    decimals: 1,
    source: "Eurostat · ilc_di12",
    sourceCode: "ilc_di12",
    frequency: "annual",
    description:
      "Índice de Gini de la renta disponible equivalente. 0=igualdad perfecta, 100=desigualdad máxima. Métrica estándar internacional de desigualdad.",
    endpoint: "/api/eurostat/dataset?code=ilc_di12&filters=geo=ES",
    parser: "eurostat-simple",
    threshold: { amber: 32, red: 36, goodAbove: false },
    accent: "#8b5cf6",
    methodologyNote:
      "Renta disponible equivalente (post-impuestos + post-transferencias). Captura efecto redistribución. Pre-transferencias ES ~48 (alto); post ~33. Diferencia mide poder redistributivo Estado.",
    releaseSchedule: "Anual · SILC · T+12 meses",
    confidenceLevel: "high",
    relatedIndicatorIds: ["sb-s80-s20", "sb-pobreza-monetaria"],
  },

  // ─── Sprint N13.2 · Bienestar nicho · pobreza energética + salud + working poor ──
  {
    id: "sb-pobreza-energetica",
    family: "precios",
    label: "Pobreza energética (no calentar vivienda)",
    shortLabel: "Pobreza energ.",
    unit: "%",
    decimals: 1,
    source: "Eurostat · ilc_mdes01",
    sourceCode: "ilc_mdes01:ES",
    frequency: "annual",
    description:
      "% hogares que no pueden mantener su vivienda adecuadamente caliente. Disparó +3pp en 2022 con crisis energética. Critico en hogares Q1+Q2 + sur España.",
    endpoint: "/api/eurostat/dataset?code=ilc_mdes01&filters=geo=ES",
    parser: "eurostat-simple",
    threshold: { amber: 10, red: 15, goodAbove: false },
    accent: "#dc2626",
    methodologyNote:
      "% hogares 'unable to keep home adequately warm'. España elevada vs UE (peor aislamiento + facturas energía). Pico 2022 +3pp con crisis gas — bono social eléctrico mitiga parcialmente.",
    releaseSchedule: "Anual · SILC · T+12 meses",
    confidenceLevel: "high",
    relatedIndicatorIds: ["rs-hicp-energia", "sb-carencia-material-severa"],
  },
  {
    id: "sb-esperanza-vida-saludable",
    family: "demanda",
    label: "Healthy Life Years ≥65 (mujeres)",
    shortLabel: "HLY 65 mujeres",
    unit: " años",
    decimals: 1,
    source: "Eurostat · hlth_hlye",
    sourceCode: "hlth_hlye:Y65_GE:F:ES",
    frequency: "annual",
    description:
      "Años de vida saludable a partir de los 65. España tiene la mayor esperanza vida total pero gap con peers en HLY: vivimos más pero con más discapacidad.",
    endpoint: "/api/eurostat/dataset?code=hlth_hlye&filters=geo=ES;age=Y65_GE;sex=F",
    parser: "eurostat-simple",
    accent: "#0EA5E9",
    methodologyNote:
      "HLY = años esperados sin discapacidad. España ~10 años desde 65 (peor que Suecia 14, Francia 12). Gap entre esperanza vida total y HLY → presión gasto sanitario crónicos.",
    releaseSchedule: "Anual · publicación T+18 meses",
    confidenceLevel: "medium",
    relatedIndicatorIds: ["dt-esperanza-vida", "ie-gasto-sanitario"],
  },
  {
    id: "sb-pension-pib",
    family: "demanda",
    label: "Gasto pensiones %PIB",
    shortLabel: "Pensiones",
    unit: "%",
    decimals: 1,
    source: "Eurostat · spr_exp_pens",
    sourceCode: "spr_exp_pens:ES",
    frequency: "annual",
    description:
      "Gasto público en pensiones %PIB. España ~13% y subiendo · driver dominante de la presión fiscal por envejecimiento + reforma 2021/2023.",
    endpoint: "/api/eurostat/dataset?code=spr_exp_pens&filters=geo=ES",
    parser: "eurostat-simple",
    threshold: { amber: 14, red: 17, goodAbove: false },
    accent: "#f59e0b",
    methodologyNote:
      "Sólo pensiones (jubilación + invalidez + viudedad). NO incluye desempleo + IT. Reforma 2021-23 indexa IPC + MEI demográfico — proyección 2050: ~17% PIB (AIReF central scenario).",
    releaseSchedule: "Anual · publicación T+24 meses",
    confidenceLevel: "high",
    relatedIndicatorIds: ["mf-prestaciones-d62", "sb-gasto-social-pib", "dt-poblacion-mayores"],
  },
  {
    id: "sb-working-poor",
    family: "empleo",
    label: "Working poor (trabajadores pobres)",
    shortLabel: "In-work poverty",
    unit: "%",
    decimals: 1,
    source: "Eurostat · ilc_iw01",
    sourceCode: "ilc_iw01:ES",
    frequency: "annual",
    description:
      "% trabajadores en riesgo pobreza. España ~13% vs UE 9%. Refleja temporalidad + parcialidad involuntaria + sectores baja productividad (HORECA, agro, servicio doméstico).",
    endpoint: "/api/eurostat/dataset?code=ilc_iw01&filters=geo=ES",
    parser: "eurostat-simple",
    threshold: { amber: 12, red: 15, goodAbove: false },
    accent: "#7c3aed",
    methodologyNote:
      "Ocupados en riesgo pobreza (<60% renta mediana). Driver: temporalidad + parcialidad involuntaria + sectores baja productividad. SMI 2018-23 +47% redujo levemente la ratio.",
    releaseSchedule: "Anual · SILC · T+12 meses",
    confidenceLevel: "high",
    relatedIndicatorIds: ["hev-tiempo-parcial-involunt", "sb-pobreza-monetaria"],
  },
  {
    id: "sb-neet-15-29",
    family: "empleo",
    label: "NEET 15-29 años",
    shortLabel: "NEET",
    unit: "%",
    decimals: 1,
    source: "Eurostat · edat_lfse_20",
    sourceCode: "edat_lfse_20:Y15-29:T:ES",
    frequency: "annual",
    description:
      "% jóvenes 15-29 ni estudian ni trabajan. España ~12% (mejor que histórico 22% post-crisis pero peor que UE 10%). Indicador clave desperdicio capital humano joven.",
    endpoint: "/api/eurostat/dataset?code=edat_lfse_20&filters=geo=ES;age=Y15-29;sex=T",
    parser: "eurostat-simple",
    threshold: { amber: 12, red: 16, goodAbove: false },
    accent: "#dc2626",
    methodologyNote:
      "Not in Education, Employment or Training. Cohorte 15-29 (más amplia que clásica 16-24). Espa ~12% — recuperación post-2013 pero aún encima UE 10%. Categoría 25-29 peor (gap formación-empleo).",
    releaseSchedule: "Anual · publicación abril del año T+1",
    confidenceLevel: "high",
    relatedIndicatorIds: ["rs-neet", "paro-epa-jovenes", "sb-abandono-escolar"],
  },
  {
    id: "sb-mortalidad-infantil",
    family: "demanda",
    label: "Mortalidad infantil por 1000 nv",
    shortLabel: "Mort. infantil",
    unit: "‰",
    decimals: 1,
    source: "Eurostat · demo_minfind",
    sourceCode: "demo_minfind:ES",
    frequency: "annual",
    description:
      "Tasa mortalidad infantil <1 año por 1000 nacidos vivos. España ~2.6 (entre los mejores UE) · proxy de calidad sistema sanitario público + atención prenatal.",
    endpoint: "/api/eurostat/dataset?code=demo_minfind&filters=geo=ES",
    parser: "eurostat-simple",
    threshold: { amber: 3.5, red: 5, goodAbove: false },
    accent: "#16a34a",
    methodologyNote:
      "Muertes <1 año / 1000 nacidos vivos. Proxy calidad sistema sanitario público (atención prenatal + parto + neonatal). España ~2.6 — entre mejores UE.",
    releaseSchedule: "Anual · publicación T+12 meses",
    confidenceLevel: "high",
    relatedIndicatorIds: ["ie-gasto-sanitario", "dt-esperanza-vida"],
  },
  // ─── Sprint Tab12-Hero · 9 indicadores nuevos del spec Tab 12.md ──────
  {
    id: "sb-gini-vs-ocde",
    family: "demanda",
    label: "Gini ES vs DE/FR/IT/OCDE",
    shortLabel: "Gini G5",
    unit: "",
    decimals: 1,
    source: "OECD · IDD GINI",
    sourceCode: "OECD_IDD_GINI",
    frequency: "annual",
    description:
      "Índice Gini renta disponible comparado con núcleo OCDE. España ~33 (alto en UE15). Permite contextualizar la desigualdad española.",
    endpoint: "/api/oecd/metric?name=gini&country=ESP",
    parser: "eurostat-simple",
    accent: "#dc2626",
    methodologyNote:
      "OECD Income Distribution Database (IDD) vía /api/oecd/metric SDMX proxy. Definición unificada OCDE. España entre top-5 UE con Gini más alto. Si el endpoint devuelve missing, verificar SDMX path en sdmx.oecd.org (DSD_WISE_IDD).",
    releaseSchedule: "Anual · OECD T+18 meses",
    confidenceLevel: "medium",
    relatedIndicatorIds: ["sb-gini-eurostat", "sb-s80-s20"],
  },
  {
    id: "sb-arope-vs-ue",
    family: "demanda",
    label: "AROPE ES vs media UE (delta)",
    shortLabel: "AROPE Δ UE",
    unit: " pp",
    decimals: 1,
    source: "Derivado · Eurostat ilc_peps01",
    sourceCode: "DERIVED_AROPE_GAP",
    frequency: "annual",
    description:
      "Diferencia España − UE-27 en tasa AROPE. España ~+4-5pp por encima media UE estructuralmente.",
    endpoint: "/api/macro/derived/arope_gap",
    parser: "eurostat-simple",
    threshold: { amber: 3, red: 5, goodAbove: false },
    accent: "#dc2626",
    methodologyNote:
      "Derivación server-side · `/api/macro/derived/arope_gap` ejecuta dos queries a Eurostat ilc_peps01 (ES y EU27_2020) y calcula la diferencia ES − UE27 sobre el último año común. España mejoró tras 2014 pero el gap se mantiene en ~4-5pp.",
    releaseSchedule: "Anual · derivado",
    confidenceLevel: "high",
    relatedIndicatorIds: ["sb-arope-eurostat"],
  },
  {
    id: "sb-gasto-social-ocde",
    family: "fiscalidad",
    label: "Gasto social ES vs OCDE",
    shortLabel: "Gasto soc. G5",
    unit: "%",
    decimals: 1,
    source: "OECD · SOCX_AGG",
    sourceCode: "OECD_SOCX",
    frequency: "annual",
    description:
      "Gasto social total %PIB comparado con OCDE. España ~26%, media OCDE ~21%. Modelo social mediterráneo.",
    endpoint: "/api/oecd/metric?name=social_spending&country=ESP",
    parser: "eurostat-simple",
    accent: "#7C3AED",
    methodologyNote:
      "OECD Social Expenditure Database (SOCX_AGG) vía /api/oecd/metric. Public + mandatory private %PIB. España alto por peso pensiones.",
    releaseSchedule: "Anual · OECD",
    confidenceLevel: "medium",
    relatedIndicatorIds: ["sb-gasto-social-pib"],
  },
  {
    id: "sb-gasto-educacion-pib",
    family: "fiscalidad",
    label: "Gasto público educación %PIB",
    shortLabel: "Educ. %PIB",
    unit: "%",
    decimals: 2,
    source: "Eurostat · educ_uoe_fine06",
    sourceCode: "educ_uoe_fine06:ES",
    frequency: "annual",
    description:
      "Gasto público educación %PIB. ~4.5% — bajo vs UE (media 5%).",
    endpoint: "/api/eurostat/dataset?code=educ_uoe_fine06&filters=geo=ES",
    parser: "eurostat-simple",
    threshold: { amber: 4.5, red: 4, goodAbove: true },
    accent: "#0F766E",
    methodologyNote:
      "Eurostat UOE. Estructuralmente por debajo media UE15.",
    releaseSchedule: "Anual · Eurostat T+18 meses",
    confidenceLevel: "high",
    relatedIndicatorIds: ["sb-abandono-escolar"],
  },
  {
    id: "sb-abandono-vs-ue",
    family: "demanda",
    label: "Abandono escolar ES vs UE",
    shortLabel: "Abandono Δ UE",
    unit: " pp",
    decimals: 1,
    source: "Derivado · Eurostat edat_lfse_14",
    sourceCode: "DERIVED_ABANDONO_GAP",
    frequency: "annual",
    description:
      "Diferencia ES − UE abandono escolar. ES ~13% vs UE ~9%.",
    endpoint: "/api/macro/derived/abandono_gap",
    parser: "eurostat-simple",
    threshold: { amber: 3, red: 5, goodAbove: false },
    accent: "#dc2626",
    methodologyNote:
      "Derivación server-side · `/api/macro/derived/abandono_gap` computa España − UE27 sobre Eurostat edat_lfse_14 (abandono escolar temprano 18-24). España cumplió UE2020 (15%) pero sigue líder negativo con gap ~+4pp.",
    releaseSchedule: "Anual · derivado",
    confidenceLevel: "high",
    relatedIndicatorIds: ["sb-abandono-escolar"],
  },
  {
    id: "sb-gasto-sanidad-publica",
    family: "fiscalidad",
    label: "Gasto sanidad pública %PIB",
    shortLabel: "Sanidad %PIB",
    unit: "%",
    decimals: 2,
    source: "Eurostat · hlth_sha11_hf",
    sourceCode: "hlth_sha11_hf:ES",
    frequency: "annual",
    description:
      "Gasto público sanidad %PIB. ~7% (UE15 ~8%). Driver sostenibilidad SNS.",
    endpoint: "/api/eurostat/dataset?code=hlth_sha11_hf&filters=geo=ES;hf=HF1",
    parser: "eurostat-simple",
    threshold: { amber: 7, red: 6, goodAbove: true },
    accent: "#16a34a",
    methodologyNote:
      "Eurostat SHA. Sólo público (HF1). Calidad por euro alta, financiación absoluta baja.",
    releaseSchedule: "Anual · Eurostat T+18 meses",
    confidenceLevel: "high",
    relatedIndicatorIds: ["sb-esperanza-vida-saludable"],
  },
  {
    id: "sb-movilidad-intergen",
    family: "demanda",
    label: "Movilidad social intergeneracional",
    shortLabel: "Movilidad",
    unit: "",
    decimals: 2,
    source: "OECD · A_FAMILY",
    sourceCode: "OECD_INTERGEN_ELAST",
    frequency: "annual",
    description:
      "Elasticidad renta padre-hijo (0=movilidad perfecta). ES ~0.4 — alta persistencia.",
    endpoint: "/api/oecd/metric?name=intergen_mobility&country=ESP",
    parser: "eurostat-simple",
    threshold: { amber: 0.4, red: 0.5, goodAbove: false },
    accent: "#dc2626",
    methodologyNote:
      "OECD A Family Affair (DSD_FAMILY) vía /api/oecd/metric. Great Gatsby Curve. España + Italia + UK en grupo de baja movilidad. Series irregulares; si endpoint devuelve missing usar last available.",
    releaseSchedule: "Anual · OECD irregular",
    confidenceLevel: "medium",
    relatedIndicatorIds: ["sb-arope-eurostat", "sb-abandono-escolar"],
  },
  {
    id: "sb-idh-undp",
    family: "demanda",
    label: "Índice Desarrollo Humano (IDH)",
    shortLabel: "IDH",
    unit: "",
    decimals: 3,
    source: "UNDP · HDR",
    sourceCode: "UNDP_HDI_ES",
    frequency: "annual",
    description:
      "IDH España ~0.911 (Top 27 mundial). Compuesto educación + salud + renta.",
    endpoint: "/api/undp/hdi?country=ESP",
    parser: "eurostat-simple",
    threshold: { amber: 0.9, red: 0.85, goodAbove: true },
    accent: "#16a34a",
    methodologyNote:
      "Snapshot UNDP HDR 2023-2024 Statistical Annex Table 1 vía `/api/undp/hdi`. España HDI 0.911 (2022, Top 27 mundial). Estable arriba; IHDI (inequality-adjusted) baja por desigualdad interna. Update manual del snapshot tras nuevo HDR (marzo año T+1).",
    releaseSchedule: "Anual · UNDP marzo",
    confidenceLevel: "high",
    relatedIndicatorIds: ["sb-gini-eurostat", "sb-esperanza-vida-saludable"],
  },
  {
    id: "sb-confianza-interpersonal",
    family: "sentimiento",
    label: "Confianza interpersonal % (capital social)",
    shortLabel: "Confianza",
    unit: "%",
    decimals: 1,
    source: "Eurostat · ilc_scp",
    sourceCode: "ilc_scp:ES:TRUST",
    frequency: "annual",
    description:
      "% personas que confían en los demás. ES ~45% — bajo en UE (media 55%, Norte ~70%).",
    endpoint: "/api/_todo_eurostat_scp?filters=trust",
    parser: "eurostat-simple",
    threshold: { amber: 45, red: 35, goodAbove: true },
    accent: "#f59e0b",
    methodologyNote:
      "EU-SILC módulo capital social. Correlaciona con cohesión, instituciones, satisfacción vida.",
    releaseSchedule: "Bienal · Eurostat módulo ad hoc",
    confidenceLevel: "low",
    relatedIndicatorIds: ["sb-arope-eurostat"],
  },
];

export const SOCIEDAD_BIENESTAR_META = {
  slug: "sociedad-bienestar",
  label: "Sociedad, bienestar & desigualdad",
  shortLabel: "Bienestar",
  accent: "#dc2626",
  description: "Distribución del bienestar: pobreza, desigualdad, renta real, vivienda, educación, sanidad, prestaciones y malestar social.",
};
