/**
 * Catálogo · Subtab 12 "Sociedad, bienestar & desigualdad" v3.
 * Foco: cómo se distribuye el bienestar — pobreza, desigualdad, renta
 * real, educación, salud, prestaciones, malestar percibido.
 */
import type { PulsoIndicatorMeta } from "./pulso-indicators";

/**
 * Sprint N6.2 cleanup: removidos PIB pc, IPC, Paro general, Paro juvenil,
 * Gasto AAPP, IPV, ETCL (todos duplicados de pulso-macro / margen-fiscal /
 * hogares-empleo-vivienda). Conservado AROPE + Gini (estructurales únicos)
 * y añadidos indicadores específicos de bienestar: pobreza monetaria,
 * carencia material severa, abandono escolar, S80/S20 (desigualdad extremos).
 */
export const SOCIEDAD_BIENESTAR_INDICATORS: PulsoIndicatorMeta[] = [
  {
    id: "sb-pobreza-monetaria",
    family: "demanda",
    label: "Pobreza monetaria (riesgo) · Eurostat",
    shortLabel: "Pobreza",
    unit: "%",
    decimals: 1,
    source: "Eurostat · ilc_li02",
    sourceCode: "ilc_li02:ES",
    frequency: "annual",
    description:
      "% población con renta disponible <60% mediana nacional. Métrica europea estándar de pobreza relativa. España persistente ~20% vs UE 17%.",
    endpoint: "/api/eurostat/dataset?code=ilc_li02&filters=geo=ES;sex=T;age=TOTAL",
    parser: "eurostat-simple",
    threshold: { amber: 18, red: 22, goodAbove: false },
    accent: "#dc2626",
  },
  {
    id: "sb-carencia-material-severa",
    family: "demanda",
    label: "Carencia material severa",
    shortLabel: "CMS",
    unit: "%",
    decimals: 1,
    source: "Eurostat · ilc_mdsd07",
    sourceCode: "ilc_mdsd07:ES",
    frequency: "annual",
    description:
      "% hogares con privación severa (no pagar facturas, comer carne 2/sem, calefacción, vacaciones, lavadora/coche/tv/teléfono). Pobreza absoluta operativa.",
    endpoint: "/api/eurostat/dataset?code=ilc_mdsd07&filters=geo=ES",
    parser: "eurostat-simple",
    threshold: { amber: 7, red: 10, goodAbove: false },
    accent: "#dc2626",
  },
  {
    id: "sb-s80-s20",
    family: "demanda",
    label: "Ratio S80/S20 (desigualdad)",
    shortLabel: "S80/S20",
    unit: "",
    decimals: 1,
    source: "Eurostat · ilc_di11",
    sourceCode: "ilc_di11:ES",
    frequency: "annual",
    description:
      "Ratio renta total quintil superior / quintil inferior. Mide desigualdad entre extremos. España ~6.0 vs UE 4.7. Sensible a impacto de prestaciones.",
    endpoint: "/api/eurostat/dataset?code=ilc_di11&filters=geo=ES",
    parser: "eurostat-simple",
    threshold: { amber: 5.5, red: 6.5, goodAbove: false },
    accent: "#8b5cf6",
  },
  {
    id: "sb-abandono-escolar",
    family: "empleo",
    label: "Abandono escolar temprano 18-24",
    shortLabel: "Abandono",
    unit: "%",
    decimals: 1,
    source: "Eurostat · edat_lfse_14",
    sourceCode: "edat_lfse_14:ES",
    frequency: "annual",
    description:
      "% personas 18-24 años solo ESO sin estudios posteriores. España ~13% vs UE 9%. Indicador estructural del fallo educativo y reproducción de pobreza.",
    endpoint: "/api/eurostat/dataset?code=edat_lfse_14&filters=geo=ES",
    parser: "eurostat-simple",
    threshold: { amber: 10, red: 14, goodAbove: false },
    accent: "#f59e0b",
  },
  {
    id: "sb-gasto-social-pib",
    family: "demanda",
    label: "Gasto en protección social %PIB",
    shortLabel: "Gasto social",
    unit: "%",
    decimals: 1,
    source: "Eurostat · spr_exp_sum",
    sourceCode: "spr_exp_sum:ES",
    frequency: "annual",
    description:
      "Gasto total protección social como % PIB (pensiones, sanidad, desempleo, familia, vivienda, exclusión). España ~25% vs UE 28%. Mide compromiso con welfare.",
    endpoint: "/api/eurostat/dataset?code=spr_exp_sum&filters=geo=ES",
    parser: "eurostat-simple",
    threshold: { amber: 24, red: 22, goodAbove: true },
    accent: "#0891b2",
  },
  {
    id: "sb-arope-eurostat",
    family: "demanda",
    label: "AROPE · Eurostat ilc_peps01n",
    shortLabel: "AROPE",
    unit: "%",
    decimals: 1,
    source: "Eurostat · ilc_peps01n",
    sourceCode: "ilc_peps01n",
    frequency: "annual",
    description:
      "People at risk of poverty or social exclusion (AROPE). Indicador EU oficial que combina pobreza monetaria + carencia material severa + baja intensidad laboral en el hogar.",
    endpoint: "/api/eurostat/dataset?code=ilc_peps01n&filters=geo=ES;sex=T;age=TOTAL;unit=PC",
    parser: "eurostat-simple",
    threshold: { amber: 22, red: 28, goodAbove: false },
    accent: "#dc2626",
  },
  {
    id: "sb-gini-eurostat",
    family: "demanda",
    label: "Coeficiente Gini · Eurostat ilc_di12",
    shortLabel: "Gini",
    unit: "",
    decimals: 1,
    source: "Eurostat · ilc_di12",
    sourceCode: "ilc_di12",
    frequency: "annual",
    description:
      "Índice de Gini de la renta disponible equivalente. 0=igualdad perfecta, 100=desigualdad máxima. Métrica estándar internacional de desigualdad.",
    endpoint: "/api/eurostat/dataset?code=ilc_di12&filters=geo=ES",
    parser: "eurostat-simple",
    threshold: { amber: 32, red: 36, goodAbove: false },
    accent: "#8b5cf6",
  },

  // ─── Sprint N13.2 · Bienestar nicho · pobreza energética + salud + working poor ──
  {
    id: "sb-pobreza-energetica",
    family: "precios",
    label: "Pobreza energética (no calentar vivienda)",
    shortLabel: "Pobreza energ.",
    unit: "%",
    decimals: 1,
    source: "Eurostat · ilc_mdes01",
    sourceCode: "ilc_mdes01:ES",
    frequency: "annual",
    description:
      "% hogares que no pueden mantener su vivienda adecuadamente caliente. Disparó +3pp en 2022 con crisis energética. Critico en hogares Q1+Q2 + sur España.",
    endpoint: "/api/eurostat/dataset?code=ilc_mdes01&filters=geo=ES",
    parser: "eurostat-simple",
    threshold: { amber: 10, red: 15, goodAbove: false },
    accent: "#dc2626",
  },
  {
    id: "sb-esperanza-vida-saludable",
    family: "demanda",
    label: "Healthy Life Years ≥65 (mujeres)",
    shortLabel: "HLY 65 mujeres",
    unit: " años",
    decimals: 1,
    source: "Eurostat · hlth_hlye",
    sourceCode: "hlth_hlye:Y65_GE:F:ES",
    frequency: "annual",
    description:
      "Años de vida saludable a partir de los 65. España tiene la mayor esperanza vida total pero gap con peers en HLY: vivimos más pero con más discapacidad.",
    endpoint: "/api/eurostat/dataset?code=hlth_hlye&filters=geo=ES;age=Y65_GE;sex=F",
    parser: "eurostat-simple",
    accent: "#0EA5E9",
  },
  {
    id: "sb-pension-pib",
    family: "demanda",
    label: "Gasto pensiones %PIB",
    shortLabel: "Pensiones",
    unit: "%",
    decimals: 1,
    source: "Eurostat · spr_exp_pens",
    sourceCode: "spr_exp_pens:ES",
    frequency: "annual",
    description:
      "Gasto público en pensiones %PIB. España ~13% y subiendo · driver dominante de la presión fiscal por envejecimiento + reforma 2021/2023.",
    endpoint: "/api/eurostat/dataset?code=spr_exp_pens&filters=geo=ES",
    parser: "eurostat-simple",
    threshold: { amber: 14, red: 17, goodAbove: false },
    accent: "#f59e0b",
  },
  {
    id: "sb-working-poor",
    family: "empleo",
    label: "Working poor (trabajadores pobres)",
    shortLabel: "In-work poverty",
    unit: "%",
    decimals: 1,
    source: "Eurostat · ilc_iw01",
    sourceCode: "ilc_iw01:ES",
    frequency: "annual",
    description:
      "% trabajadores en riesgo pobreza. España ~13% vs UE 9%. Refleja temporalidad + parcialidad involuntaria + sectores baja productividad (HORECA, agro, servicio doméstico).",
    endpoint: "/api/eurostat/dataset?code=ilc_iw01&filters=geo=ES",
    parser: "eurostat-simple",
    threshold: { amber: 12, red: 15, goodAbove: false },
    accent: "#7c3aed",
  },
  {
    id: "sb-neet-15-29",
    family: "empleo",
    label: "NEET 15-29 años",
    shortLabel: "NEET",
    unit: "%",
    decimals: 1,
    source: "Eurostat · edat_lfse_20",
    sourceCode: "edat_lfse_20:Y15-29:T:ES",
    frequency: "annual",
    description:
      "% jóvenes 15-29 ni estudian ni trabajan. España ~12% (mejor que histórico 22% post-crisis pero peor que UE 10%). Indicador clave desperdicio capital humano joven.",
    endpoint: "/api/eurostat/dataset?code=edat_lfse_20&filters=geo=ES;age=Y15-29;sex=T",
    parser: "eurostat-simple",
    threshold: { amber: 12, red: 16, goodAbove: false },
    accent: "#dc2626",
  },
  {
    id: "sb-mortalidad-infantil",
    family: "demanda",
    label: "Mortalidad infantil por 1000 nv",
    shortLabel: "Mort. infantil",
    unit: "‰",
    decimals: 1,
    source: "Eurostat · demo_minfind",
    sourceCode: "demo_minfind:ES",
    frequency: "annual",
    description:
      "Tasa mortalidad infantil <1 año por 1000 nacidos vivos. España ~2.6 (entre los mejores UE) · proxy de calidad sistema sanitario público + atención prenatal.",
    endpoint: "/api/eurostat/dataset?code=demo_minfind&filters=geo=ES",
    parser: "eurostat-simple",
    threshold: { amber: 3.5, red: 5, goodAbove: false },
    accent: "#16a34a",
  },
];

export const SOCIEDAD_BIENESTAR_META = {
  slug: "sociedad-bienestar",
  label: "Sociedad, bienestar & desigualdad",
  shortLabel: "Bienestar",
  accent: "#dc2626",
  description: "Distribución del bienestar: pobreza, desigualdad, renta real, vivienda, educación, sanidad, prestaciones y malestar social.",
};
