# services/legislative/legislative_fixtures.py
"""Rich demo / fallback data for the Monitor Legislativo."""
from __future__ import annotations
from datetime import date, timedelta
from api.schemas.legislative import (
    LegislativeItem, LegislativeItemDetail, LegislativeEvent,
    SectorImpact, ActorLegislativePosition, LegislativeEvidence,
    CalendarItem, BoeItem, LegislativeKpis, LegislativeHeatmapCell,
    LegislativeOverviewResponse, LegislativeItemsResponse,
)

_today = date.today().isoformat()
_yesterday = (date.today() - timedelta(days=1)).isoformat()
_next_week = (date.today() + timedelta(days=7)).isoformat()

DEMO_ITEMS: list[LegislativeItem] = [
    LegislativeItem(
        id="leg-001",
        title="Proyecto de Ley de Vivienda Asequible 2026",
        short_title="Ley Vivienda 2026",
        procedure_type="proyecto_ley",
        procedure_label="Proyecto de Ley",
        jurisdiction="congreso",
        institution="camara_baja",
        proponent="Gobierno",
        proponent_party="PSOE-Sumar",
        proponent_color="#E03A3E",
        current_stage="pleno_debate",
        stage_label="Pleno — Debate",
        urgency="critical",
        submitted_at="2026-02-10",
        expected_vote=_next_week,
        last_activity=_today,
        impact_score=91,
        primary_sector="inmobiliario",
        tags=["vivienda", "alquiler", "ibex35", "socimi"],
        status="Pleno — Debate",
        is_government=True,
    ),
    LegislativeItem(
        id="leg-002",
        title="Reforma Fiscal SICAV y SOCIMI — Tributación mínima UE",
        short_title="Reforma SICAV/SOCIMI",
        procedure_type="proyecto_ley",
        procedure_label="Proyecto de Ley",
        jurisdiction="congreso",
        institution="camara_baja",
        proponent="Ministerio de Hacienda",
        proponent_party="PSOE",
        proponent_color="#E03A3E",
        current_stage="enmiendas",
        stage_label="Enmiendas parciales",
        urgency="high",
        submitted_at="2026-03-01",
        expected_vote=(date.today() + timedelta(days=21)).isoformat(),
        last_activity=_yesterday,
        impact_score=85,
        primary_sector="banca",
        tags=["fiscalidad", "sicav", "socimi", "hacienda", "ibex35"],
        status="Enmiendas",
        is_government=True,
        ue_origin=True,
    ),
    LegislativeItem(
        id="leg-003",
        title="Real Decreto-ley Fondos Europeos 2026-2030",
        short_title="RDL Fondos UE",
        procedure_type="real_decreto_ley",
        procedure_label="Real Decreto-ley",
        jurisdiction="boe",
        institution="gobierno",
        proponent="Presidencia del Gobierno",
        proponent_party="PSOE",
        proponent_color="#E03A3E",
        current_stage="boe_publicacion",
        stage_label="Publicado BOE",
        urgency="high",
        submitted_at="2026-04-28",
        last_activity=_yesterday,
        impact_score=78,
        primary_sector="general",
        tags=["fondos_ue", "ngeu", "inversión", "pymes"],
        status="Convalidación pendiente",
        is_government=True,
        ue_origin=True,
        boe_url="https://www.boe.es/boe/dias/2026/04/28/pdfs/BOE-A-2026-5123.pdf",
    ),
    LegislativeItem(
        id="leg-004",
        title="Directiva UE IA Act — Transposición española",
        short_title="Transposición IA Act",
        procedure_type="directiva_ue",
        procedure_label="Directiva UE",
        jurisdiction="ue",
        institution="ue_comision",
        proponent="Comisión Europea",
        proponent_party="UE",
        proponent_color="#003399",
        current_stage="comision",
        stage_label="Comisión Mixta UE",
        urgency="high",
        submitted_at="2026-01-15",
        expected_vote=(date.today() + timedelta(days=45)).isoformat(),
        last_activity=_yesterday,
        impact_score=82,
        primary_sector="tecnologia",
        tags=["ia", "regulacion", "tecnologia", "compliance", "bigtech"],
        status="Comisión Mixta",
        is_government=False,
        ue_origin=True,
    ),
    LegislativeItem(
        id="leg-005",
        title="Proposición de Ley Transición Energética Justa",
        short_title="Transición Energética",
        procedure_type="proposicion_ley",
        procedure_label="Proposición de Ley",
        jurisdiction="congreso",
        institution="camara_baja",
        proponent="Sumar",
        proponent_party="Sumar",
        proponent_color="#9B59B6",
        current_stage="ponencia",
        stage_label="Ponencia",
        urgency="medium",
        submitted_at="2026-03-10",
        expected_vote=(date.today() + timedelta(days=60)).isoformat(),
        last_activity=(date.today() - timedelta(days=3)).isoformat(),
        impact_score=71,
        primary_sector="energia",
        tags=["energia", "renovables", "clima", "empleos_verdes"],
        status="Ponencia",
        is_government=False,
    ),
    LegislativeItem(
        id="leg-006",
        title="Ley de Defensa Nacional — Presupuesto 2% PIB OTAN",
        short_title="Ley Defensa 2%",
        procedure_type="proyecto_ley",
        procedure_label="Proyecto de Ley",
        jurisdiction="congreso",
        institution="camara_baja",
        proponent="Ministerio de Defensa",
        proponent_party="PSOE",
        proponent_color="#E03A3E",
        current_stage="comision",
        stage_label="Comisión Defensa",
        urgency="medium",
        submitted_at="2026-04-01",
        expected_vote=(date.today() + timedelta(days=90)).isoformat(),
        last_activity=(date.today() - timedelta(days=5)).isoformat(),
        impact_score=64,
        primary_sector="defensa",
        tags=["defensa", "otan", "presupuesto", "industria_militar"],
        status="Comisión",
        is_government=True,
    ),
    LegislativeItem(
        id="leg-007",
        title="Reforma de la Ley de Telecomunicaciones — Infraestructuras 5G/6G",
        short_title="Telecom 5G/6G",
        procedure_type="proposicion_ley",
        procedure_label="Proposición de Ley",
        jurisdiction="congreso",
        institution="camara_baja",
        proponent="PP",
        proponent_party="PP",
        proponent_color="#1F77FF",
        current_stage="presentacion",
        stage_label="Presentada",
        urgency="low",
        submitted_at="2026-05-02",
        last_activity=_today,
        impact_score=55,
        primary_sector="telecomunicaciones",
        tags=["5g", "6g", "telecom", "digitalizacion"],
        status="Presentada",
        is_government=False,
    ),
    LegislativeItem(
        id="leg-008",
        title="Reglamento UE Taxonomía Verde 2026 — Impacto sectorial",
        short_title="Taxonomía Verde UE",
        procedure_type="reglamento_ue",
        procedure_label="Reglamento UE",
        jurisdiction="ue",
        institution="ue_comision",
        proponent="Comisión Europea",
        proponent_party="UE",
        proponent_color="#003399",
        current_stage="vigor",
        stage_label="En vigor",
        urgency="high",
        submitted_at="2025-12-01",
        last_activity=(date.today() - timedelta(days=2)).isoformat(),
        impact_score=80,
        primary_sector="banca",
        tags=["taxonomia", "esg", "finanzas_sostenibles", "banca", "energia"],
        status="En vigor",
        is_government=False,
        ue_origin=True,
    ),
]


def _day_label(d: date) -> str:
    return ["Lun", "Mar", "Mié", "Jue", "Vie", "Sáb", "Dom"][d.weekday()]


DEMO_CALENDAR: list[CalendarItem] = [
    CalendarItem(
        date=date.today().isoformat(),
        day_label=_day_label(date.today()),
        time="10:00",
        title="Pleno Congreso: Debate Ley Vivienda 2026",
        institution="camara_baja",
        event_type="pleno",
        event_type_label="Pleno",
        related_item_id="leg-001",
    ),
    CalendarItem(
        date=(date.today() + timedelta(days=1)).isoformat(),
        day_label=_day_label(date.today() + timedelta(days=1)),
        time="09:30",
        title="Comisión Hacienda: Enmiendas reforma SICAV/SOCIMI",
        institution="camara_baja",
        event_type="comision",
        event_type_label="Comisión",
        commission="Comisión de Hacienda",
        related_item_id="leg-002",
    ),
    CalendarItem(
        date=(date.today() + timedelta(days=2)).isoformat(),
        day_label=_day_label(date.today() + timedelta(days=2)),
        time="11:00",
        title="Ponencia Transición Energética: dictamen",
        institution="camara_baja",
        event_type="ponencia",
        event_type_label="Ponencia",
        commission="Comisión de Transición Ecológica",
        related_item_id="leg-005",
    ),
    CalendarItem(
        date=(date.today() + timedelta(days=3)).isoformat(),
        day_label=_day_label(date.today() + timedelta(days=3)),
        time="10:00",
        title="Comisión Mixta UE: IA Act — posición española",
        institution="ue_comision",
        event_type="comision",
        event_type_label="Comisión UE",
        commission="Comisión Mixta para la UE",
        related_item_id="leg-004",
    ),
    CalendarItem(
        date=(date.today() + timedelta(days=4)).isoformat(),
        day_label=_day_label(date.today() + timedelta(days=4)),
        time="12:00",
        title="Pleno Congreso: Votación RDL Fondos UE (convalidación)",
        institution="camara_baja",
        event_type="votacion",
        event_type_label="Votación",
        related_item_id="leg-003",
    ),
    CalendarItem(
        date=(date.today() + timedelta(days=7)).isoformat(),
        day_label=_day_label(date.today() + timedelta(days=7)),
        time="10:00",
        title="Comisión Defensa: audición Ministro, presupuesto OTAN",
        institution="camara_baja",
        event_type="comision",
        event_type_label="Comisión",
        commission="Comisión de Defensa",
        related_item_id="leg-006",
    ),
]


DEMO_BOE: list[BoeItem] = [
    BoeItem(title="RDL 8/2026 de medidas urgentes para la vivienda", section="I. Disposiciones generales", department="Presidencia", date=_today, url="https://www.boe.es/boe/dias/2026/05/06/pdfs/BOE-A-2026-5123.pdf", type="Real Decreto-ley", relevance="alta"),
    BoeItem(title="Orden HAC/520/2026 sobre tributación rentas capital", section="I. Disposiciones generales", department="Hacienda", date=_today, url=None, type="Orden", relevance="alta"),
    BoeItem(title="Resolución CNMV: normas transparencia ESG 2026", section="III. Otras disposiciones", department="CNMV", date=_today, url=None, type="Resolución", relevance="media"),
    BoeItem(title="Convocatoria fondos PERTE VEC 2026 — vehículo eléctrico", section="III. Otras disposiciones", department="Industria", date=_today, url=None, type="Convocatoria", relevance="media"),
    BoeItem(title="Licitación contratos defensa — sistemas C4ISR", section="V. Anuncios", department="Defensa", date=_today, url=None, type="Anuncio", relevance="baja"),
]


DEMO_HEATMAP: list[LegislativeHeatmapCell] = [
    LegislativeHeatmapCell(sector="inmobiliario", sector_label="Inmobiliario", urgency="critical", count=3, score=88.0),
    LegislativeHeatmapCell(sector="banca", sector_label="Banca", urgency="high", count=4, score=79.5),
    LegislativeHeatmapCell(sector="tecnologia", sector_label="Tecnología", urgency="high", count=2, score=76.0),
    LegislativeHeatmapCell(sector="energia", sector_label="Energía", urgency="medium", count=5, score=65.0),
    LegislativeHeatmapCell(sector="banca", sector_label="Banca", urgency="critical", count=1, score=85.0),
    LegislativeHeatmapCell(sector="tecnologia", sector_label="Tecnología", urgency="medium", count=3, score=58.0),
    LegislativeHeatmapCell(sector="defensa", sector_label="Defensa", urgency="medium", count=2, score=60.0),
    LegislativeHeatmapCell(sector="telecomunicaciones", sector_label="Telecomunicaciones", urgency="low", count=4, score=45.0),
    LegislativeHeatmapCell(sector="inmobiliario", sector_label="Inmobiliario", urgency="high", count=2, score=72.0),
    LegislativeHeatmapCell(sector="energia", sector_label="Energía", urgency="high", count=3, score=70.0),
    LegislativeHeatmapCell(sector="general", sector_label="General", urgency="high", count=6, score=68.0),
    LegislativeHeatmapCell(sector="agroalimentario", sector_label="Agroalimentario", urgency="low", count=3, score=38.0),
]


DEMO_KPIS = LegislativeKpis(
    active_initiatives=187,
    approved_this_month=23,
    critical_tramitation=9,
    upcoming_votes=14,
    mode="fallback",
)


def get_demo_overview() -> LegislativeOverviewResponse:
    return LegislativeOverviewResponse(
        kpis=DEMO_KPIS,
        critical_items=[i for i in DEMO_ITEMS if i.urgency in ("critical", "high")][:6],
        calendar_week=DEMO_CALENDAR,
        boe_today=DEMO_BOE,
        heatmap=DEMO_HEATMAP,
        mode="demo",
    )


def get_demo_items(page: int = 1, page_size: int = 20) -> LegislativeItemsResponse:
    start = (page - 1) * page_size
    end = start + page_size
    return LegislativeItemsResponse(
        items=DEMO_ITEMS[start:end],
        total=len(DEMO_ITEMS),
        page=page,
        page_size=page_size,
        mode="demo",
    )
