import type { DocTemplate } from "@/types/docs";

export const DOC_TEMPLATES: DocTemplate[] = [
  {
    id: "tpl_briefing_diario",
    kind: "briefing",
    name: "Briefing Diario",
    description: "Resumen ejecutivo del estado político del día",
    estimatedMinutes: 15,
    tags: ["diario", "equipo"],
    blocks: [
      { id: "b1", type: "heading", content: "Briefing Político — {{fecha}}", props: { level: 1 } },
      { id: "b2", type: "heading", content: "1. Contexto del día", props: { level: 2 } },
      { id: "b3", type: "paragraph", content: "Describe brevemente el contexto político del día." },
      { id: "b4", type: "heading", content: "2. Issues prioritarios", props: { level: 2 } },
      { id: "b5", type: "context-block", content: "", props: { source: "issues", filter: "critical", workspaceId: "{{workspaceId}}", limit: 5 } },
      { id: "b6", type: "heading", content: "3. Posiciones de actores clave", props: { level: 2 } },
      { id: "b7", type: "paragraph", content: "Describe movimientos y declaraciones de actores relevantes." },
      { id: "b8", type: "heading", content: "4. Recomendaciones", props: { level: 2 } },
      { id: "b9", type: "bullet", content: "Recomendación 1" },
      { id: "b10", type: "bullet", content: "Recomendación 2" },
      { id: "b11", type: "heading", content: "5. Próximos pasos", props: { level: 2 } },
      { id: "b12", type: "context-block", content: "", props: { source: "actions", filter: "pending", workspaceId: "{{workspaceId}}", limit: 5 } },
    ],
  },
  {
    id: "tpl_nota_crisis",
    kind: "crisis-note",
    name: "Nota de Crisis",
    description: "Documento de respuesta urgente ante un issue crítico",
    estimatedMinutes: 20,
    tags: ["crisis", "urgente"],
    blocks: [
      { id: "b1", type: "heading", content: "NOTA DE CRISIS — {{titulo_issue}}", props: { level: 1 } },
      { id: "b2", type: "callout", content: "Documento de uso interno. Confidencialidad alta.", props: { variant: "warning" } },
      { id: "b3", type: "heading", content: "1. Descripción del problema", props: { level: 2 } },
      { id: "b4", type: "context-block", content: "", props: { source: "issue", issueId: "{{issueId}}" } },
      { id: "b5", type: "heading", content: "2. Impacto estimado", props: { level: 2 } },
      { id: "b6", type: "paragraph", content: "Describe el impacto político, mediático y reputacional." },
      { id: "b7", type: "heading", content: "3. Narrativa de respuesta", props: { level: 2 } },
      { id: "b8", type: "paragraph", content: "Define el mensaje principal y los secundarios de respuesta." },
      { id: "b9", type: "heading", content: "4. Acciones inmediatas", props: { level: 2 } },
      { id: "b10", type: "numbered", content: "Acción 1 — responsable y plazo" },
      { id: "b11", type: "numbered", content: "Acción 2 — responsable y plazo" },
      { id: "b12", type: "heading", content: "5. Escalado", props: { level: 2 } },
      { id: "b13", type: "paragraph", content: "Cuándo escalar, a quién, qué umbrales activan protocolo de crisis mayor." },
    ],
  },
  {
    id: "tpl_talking_points",
    kind: "talking-points",
    name: "Talking Points",
    description: "Argumentario rápido para intervención pública o entrevista",
    estimatedMinutes: 10,
    tags: ["comunicación", "medios"],
    blocks: [
      { id: "b1", type: "heading", content: "Talking Points — {{tema}}", props: { level: 1 } },
      { id: "b2", type: "heading", content: "Mensaje principal", props: { level: 2 } },
      { id: "b3", type: "callout", content: "Una sola frase. Memorable. Repetible.", props: { variant: "info" } },
      { id: "b4", type: "heading", content: "Tres mensajes secundarios", props: { level: 2 } },
      { id: "b5", type: "numbered", content: "Mensaje 1" },
      { id: "b6", type: "numbered", content: "Mensaje 2" },
      { id: "b7", type: "numbered", content: "Mensaje 3" },
      { id: "b8", type: "heading", content: "Preguntas difíciles esperadas", props: { level: 2 } },
      { id: "b9", type: "paragraph", content: "Anticipar y preparar respuesta para cada pregunta incómoda." },
      { id: "b10", type: "heading", content: "Lo que NO decir", props: { level: 2 } },
      { id: "b11", type: "bullet", content: "Evitar mencionar..." },
    ],
  },
  {
    id: "tpl_informe_cliente",
    kind: "client-report",
    name: "Informe de Cliente",
    description: "Informe ejecutivo mensual o ad-hoc para cliente externo",
    estimatedMinutes: 45,
    tags: ["cliente", "externo"],
    blocks: [
      { id: "b1", type: "heading", content: "Informe Político — {{cliente}} · {{periodo}}", props: { level: 1 } },
      { id: "b2", type: "heading", content: "Resumen ejecutivo", props: { level: 2 } },
      { id: "b3", type: "paragraph", content: "3-4 líneas con los hallazgos más relevantes del periodo." },
      { id: "b4", type: "heading", content: "Contexto político general", props: { level: 2 } },
      { id: "b5", type: "paragraph", content: "" },
      { id: "b6", type: "heading", content: "Análisis sectorial", props: { level: 2 } },
      { id: "b7", type: "paragraph", content: "" },
      { id: "b8", type: "heading", content: "Actores y posiciones", props: { level: 2 } },
      { id: "b9", type: "paragraph", content: "" },
      { id: "b10", type: "heading", content: "Riesgos y oportunidades", props: { level: 2 } },
      { id: "b11", type: "context-block", content: "", props: { source: "opportunities", limit: 3, workspaceId: "{{workspaceId}}" } },
      { id: "b12", type: "heading", content: "Recomendaciones estratégicas", props: { level: 2 } },
      { id: "b13", type: "bullet", content: "Recomendación 1" },
    ],
  },
  {
    id: "tpl_posicionamiento",
    kind: "positioning",
    name: "Documento de Posicionamiento",
    description: "Posición política oficial sobre un tema legislativo",
    estimatedMinutes: 30,
    tags: ["legislativo", "posición"],
    blocks: [
      { id: "b1", type: "heading", content: "Posicionamiento: {{tema}}", props: { level: 1 } },
      { id: "b2", type: "heading", content: "Posición oficial", props: { level: 2 } },
      { id: "b3", type: "callout", content: "Declaración clara y directa de la posición.", props: { variant: "info" } },
      { id: "b4", type: "heading", content: "Argumentación", props: { level: 2 } },
      { id: "b5", type: "numbered", content: "Argumento 1" },
      { id: "b6", type: "numbered", content: "Argumento 2" },
      { id: "b7", type: "numbered", content: "Argumento 3" },
      { id: "b8", type: "heading", content: "Posiciones de otros actores", props: { level: 2 } },
      { id: "b9", type: "paragraph", content: "" },
      { id: "b10", type: "heading", content: "Línea roja — no negociable", props: { level: 2 } },
      { id: "b11", type: "callout", content: "Lo que nunca aceptaremos.", props: { variant: "danger" } },
    ],
  },
];
