import type { DocWithBlocks } from "@/types/docs";

const baseBlocks = (kind: string, title: string) => [
  { id: "b1", type: "heading", content: title, props: { level: 1 } },
  { id: "b2", type: "paragraph", content: `Documento de tipo ${kind}.` },
];

export const docsMockData: DocWithBlocks[] = [
  {
    id: "doc_001",
    workspaceId: "ws_espana_2026",
    title: "Nota de respuesta a bulos financiación",
    kind: "crisis-note",
    status: "review",
    authorId: "u3",
    createdAt: "2026-05-13T08:00:00Z",
    updatedAt: "2026-05-13T09:00:00Z",
    tags: ["crisis", "comunicación"],
    relatedIssueIds: ["iss_001"],
    summary: "Q&A defensivo para portavoces.",
    clientVisible: false,
    wordCount: 1240,
    blocks: baseBlocks("crisis-note", "Nota de respuesta a bulos financiación"),
  },
  {
    id: "doc_002",
    workspaceId: "ws_espana_2026",
    title: "Estrategia comunicación mayo 2026",
    kind: "positioning",
    status: "draft",
    authorId: "u3",
    createdAt: "2026-05-12T10:00:00Z",
    updatedAt: "2026-05-13T08:15:00Z",
    tags: ["estrategia"],
    relatedIssueIds: ["iss_001", "iss_002"],
    summary: "Mensajes clave del mes.",
    clientVisible: false,
    wordCount: 2400,
    blocks: baseBlocks("positioning", "Estrategia comunicación mayo 2026"),
  },
  {
    id: "doc_003",
    workspaceId: "ws_espana_2026",
    title: "Análisis sondeos territoriales Cataluña",
    kind: "analysis",
    status: "published",
    authorId: "u4",
    createdAt: "2026-05-10T00:00:00Z",
    updatedAt: "2026-05-12T16:30:00Z",
    tags: ["sondeo", "cataluña"],
    relatedIssueIds: ["iss_004"],
    summary: "Lectura cruzada CIS y barómetros propios.",
    clientVisible: false,
    wordCount: 3200,
    blocks: baseBlocks("analysis", "Análisis sondeos territoriales Cataluña"),
  },
  {
    id: "doc_004",
    workspaceId: "ws_espana_2026",
    title: "Q&A vivienda — preparación pleno",
    kind: "briefing",
    status: "review",
    authorId: "u1",
    createdAt: "2026-05-11T00:00:00Z",
    updatedAt: "2026-05-12T14:00:00Z",
    tags: ["vivienda", "pleno"],
    relatedIssueIds: ["iss_002"],
    summary: "Preguntas previsibles + respuestas argumentadas.",
    clientVisible: false,
    wordCount: 1800,
    blocks: baseBlocks("briefing", "Q&A vivienda — preparación pleno"),
  },
  {
    id: "doc_005",
    workspaceId: "ws_espana_2026",
    title: "Briefing presupuestos CC.AA. mayo",
    kind: "briefing",
    status: "published",
    authorId: "u2",
    createdAt: "2026-05-09T00:00:00Z",
    updatedAt: "2026-05-11T19:00:00Z",
    tags: ["presupuestos"],
    relatedIssueIds: ["iss_003"],
    summary: "Estado del FLA y posiciones por CCAA.",
    clientVisible: false,
    wordCount: 2100,
    blocks: baseBlocks("briefing", "Briefing presupuestos CC.AA. mayo"),
  },
  {
    id: "doc_006",
    workspaceId: "ws_espana_2026",
    title: "Marco legal reforma amnistía",
    kind: "analysis",
    status: "published",
    authorId: "u2",
    createdAt: "2026-05-05T00:00:00Z",
    updatedAt: "2026-05-10T17:20:00Z",
    tags: ["legal"],
    relatedIssueIds: [],
    summary: "Marco jurídico y precedentes TC.",
    clientVisible: false,
    wordCount: 4100,
    blocks: baseBlocks("analysis", "Marco legal reforma amnistía"),
  },
  {
    id: "doc_007",
    workspaceId: "ws_espana_2026",
    title: "Posicionamiento Sumar — reforma fiscal",
    kind: "positioning",
    status: "draft",
    authorId: "u2",
    createdAt: "2026-05-08T00:00:00Z",
    updatedAt: "2026-05-09T11:00:00Z",
    tags: ["fiscal"],
    relatedIssueIds: ["iss_005"],
    summary: "Mapa de incentivos de Sumar.",
    clientVisible: false,
    wordCount: 1500,
    blocks: baseBlocks("positioning", "Posicionamiento Sumar — reforma fiscal"),
  },
  {
    id: "doc_008",
    workspaceId: "ws_espana_2026",
    title: "Talking points entrevista TVE viernes",
    kind: "talking-points",
    status: "draft",
    authorId: "u3",
    createdAt: "2026-05-13T06:30:00Z",
    updatedAt: "2026-05-13T07:00:00Z",
    tags: ["tve"],
    relatedIssueIds: ["iss_001"],
    summary: "Mensaje principal + 3 secundarios + qué evitar.",
    clientVisible: false,
    wordCount: 900,
    blocks: baseBlocks("talking-points", "Talking points entrevista TVE viernes"),
  },
];
