/* AUTO-GENERATED · seed terminales del módulo Puertos. NO EDITAR.
   Regenerar con: python -c "from etl.sources.ports.seeds import ..." > ...
   Sincronizado con etl/sources/ports/seeds/port_terminals_seed.yaml */
export const TERMINALS_SEED = [
  {
    "port_slug": "algeciras",
    "terminal_name": "APM Terminals Algeciras",
    "operator_name": "APM Terminals (A.P. Moller-Maersk)",
    "operator_lei": "K9CB8W4QXLBT2GZQ9X06",
    "type": "container",
    "capacity_teu": 1700000,
    "berths_count": 6,
    "max_draft_m": 17.5,
    "quay_length_m": 2100,
    "reefer_plugs": 1900,
    "rail_access": true,
    "concession_end_year": 2058,
    "source": "curated",
    "data_quality": "seed"
  },
  {
    "port_slug": "algeciras",
    "terminal_name": "TTI Algeciras",
    "operator_name": "Total Terminal International (Hanjin/CMA CGM)",
    "type": "container",
    "capacity_teu": 1800000,
    "berths_count": 4,
    "max_draft_m": 18.5,
    "quay_length_m": 1200,
    "reefer_plugs": 1500,
    "rail_access": true,
    "concession_end_year": 2050,
    "source": "curated",
    "data_quality": "seed"
  },
  {
    "port_slug": "algeciras",
    "terminal_name": "Terminal Ro-Ro",
    "operator_name": "Acciona Trasmediterránea",
    "type": "roro",
    "berths_count": 5,
    "max_draft_m": 12.0,
    "rail_access": false,
    "source": "curated",
    "data_quality": "seed"
  },
  {
    "port_slug": "algeciras",
    "terminal_name": "Terminal Cepsa",
    "operator_name": "CEPSA Química",
    "type": "tanker",
    "capacity_tonnes": 27000000,
    "berths_count": 4,
    "max_draft_m": 23.0,
    "rail_access": false,
    "source": "curated",
    "data_quality": "seed"
  },
  {
    "port_slug": "algeciras",
    "terminal_name": "Terminal Granel Sólido",
    "operator_name": "APBA · Autoridad Portuaria",
    "type": "bulk",
    "berths_count": 3,
    "max_draft_m": 14.5,
    "rail_access": true,
    "source": "curated",
    "data_quality": "seed"
  },
  {
    "port_slug": "valencia",
    "terminal_name": "CSP Iberian Valencia Terminal",
    "operator_name": "COSCO Shipping Ports",
    "type": "container",
    "capacity_teu": 3000000,
    "berths_count": 7,
    "max_draft_m": 18.0,
    "quay_length_m": 2210,
    "reefer_plugs": 2100,
    "rail_access": true,
    "concession_end_year": 2049,
    "source": "curated",
    "data_quality": "seed"
  },
  {
    "port_slug": "valencia",
    "terminal_name": "MSC Terminal Valencia (TPV)",
    "operator_name": "Mediterranean Shipping Company (TPV)",
    "type": "container",
    "capacity_teu": 1800000,
    "berths_count": 5,
    "max_draft_m": 16.5,
    "quay_length_m": 1525,
    "reefer_plugs": 1200,
    "rail_access": true,
    "source": "curated",
    "data_quality": "seed"
  },
  {
    "port_slug": "valencia",
    "terminal_name": "APM Terminals Valencia",
    "operator_name": "APM Terminals (Maersk)",
    "type": "container",
    "capacity_teu": 900000,
    "berths_count": 3,
    "max_draft_m": 16.0,
    "quay_length_m": 1200,
    "rail_access": true,
    "source": "curated",
    "data_quality": "seed"
  },
  {
    "port_slug": "valencia",
    "terminal_name": "Terminal Pública Ro-Ro",
    "operator_name": "APV · Autoridad Portuaria de Valencia",
    "type": "roro",
    "berths_count": 8,
    "max_draft_m": 11.0,
    "rail_access": false,
    "source": "curated",
    "data_quality": "seed"
  },
  {
    "port_slug": "valencia",
    "terminal_name": "Terminal Granel Líquido Sagunto",
    "operator_name": "BP / Cepsa",
    "type": "tanker",
    "capacity_tonnes": 12000000,
    "berths_count": 3,
    "max_draft_m": 16.0,
    "rail_access": false,
    "source": "curated",
    "data_quality": "seed"
  },
  {
    "port_slug": "barcelona",
    "terminal_name": "BEST · Barcelona Europe South Terminal",
    "operator_name": "Hutchison Ports",
    "type": "container",
    "capacity_teu": 2700000,
    "berths_count": 4,
    "max_draft_m": 18.0,
    "quay_length_m": 1500,
    "reefer_plugs": 1600,
    "rail_access": true,
    "concession_end_year": 2056,
    "source": "curated",
    "data_quality": "seed"
  },
  {
    "port_slug": "barcelona",
    "terminal_name": "APM Terminals Barcelona",
    "operator_name": "APM Terminals (Maersk)",
    "type": "container",
    "capacity_teu": 1500000,
    "berths_count": 4,
    "max_draft_m": 16.0,
    "quay_length_m": 1500,
    "rail_access": true,
    "source": "curated",
    "data_quality": "seed"
  },
  {
    "port_slug": "barcelona",
    "terminal_name": "Terminal Cruceros Adossat",
    "operator_name": "Carnival + RCCL + MSC Cruises",
    "type": "cruise",
    "berths_count": 7,
    "max_draft_m": 12.0,
    "rail_access": false,
    "source": "curated",
    "data_quality": "seed"
  },
  {
    "port_slug": "barcelona",
    "terminal_name": "Terminal Grimaldi",
    "operator_name": "Grimaldi Lines",
    "type": "roro",
    "berths_count": 4,
    "rail_access": false,
    "source": "curated",
    "data_quality": "seed"
  },
  {
    "port_slug": "barcelona",
    "terminal_name": "Terminal Combustibles Energy Port",
    "operator_name": "Enagas / Cepsa",
    "type": "lng",
    "capacity_tonnes": 14000000,
    "berths_count": 2,
    "max_draft_m": 16.0,
    "rail_access": false,
    "source": "curated",
    "data_quality": "seed"
  },
  {
    "port_slug": "bilbao",
    "terminal_name": "NTC · Noatum Container Terminal",
    "operator_name": "Noatum (CMA CGM)",
    "type": "container",
    "capacity_teu": 1100000,
    "berths_count": 3,
    "max_draft_m": 21.0,
    "quay_length_m": 600,
    "rail_access": true,
    "source": "curated",
    "data_quality": "seed"
  },
  {
    "port_slug": "bilbao",
    "terminal_name": "Terminal Petronor",
    "operator_name": "Repsol Petronor",
    "type": "tanker",
    "capacity_tonnes": 11500000,
    "berths_count": 6,
    "max_draft_m": 24.0,
    "rail_access": true,
    "source": "curated",
    "data_quality": "seed"
  },
  {
    "port_slug": "bilbao",
    "terminal_name": "Terminal Ro-Ro Brittany Ferries",
    "operator_name": "Brittany Ferries",
    "type": "roro",
    "berths_count": 2,
    "rail_access": false,
    "source": "curated",
    "data_quality": "seed"
  },
  {
    "port_slug": "bilbao",
    "terminal_name": "Terminal Granel Sólido",
    "operator_name": "ArcelorMittal + Tubacex",
    "type": "bulk",
    "capacity_tonnes": 4500000,
    "berths_count": 4,
    "max_draft_m": 18.0,
    "rail_access": true,
    "source": "curated",
    "data_quality": "seed"
  },
  {
    "port_slug": "rotterdam",
    "terminal_name": "ECT Delta Terminal",
    "operator_name": "Hutchison Ports ECT",
    "type": "container",
    "capacity_teu": 5000000,
    "berths_count": 7,
    "max_draft_m": 19.0,
    "quay_length_m": 3600,
    "reefer_plugs": 4000,
    "rail_access": true,
    "source": "curated",
    "data_quality": "seed"
  },
  {
    "port_slug": "rotterdam",
    "terminal_name": "APM Terminals Maasvlakte II",
    "operator_name": "APM Terminals (Maersk)",
    "type": "container",
    "capacity_teu": 4500000,
    "berths_count": 4,
    "max_draft_m": 20.0,
    "quay_length_m": 1900,
    "reefer_plugs": 3500,
    "rail_access": true,
    "source": "curated",
    "data_quality": "seed"
  },
  {
    "port_slug": "rotterdam",
    "terminal_name": "RWG · Rotterdam World Gateway",
    "operator_name": "DP World + HMM + MOL + APL + CMA CGM",
    "type": "container",
    "capacity_teu": 4000000,
    "berths_count": 5,
    "max_draft_m": 20.0,
    "quay_length_m": 1700,
    "rail_access": true,
    "source": "curated",
    "data_quality": "seed"
  },
  {
    "port_slug": "rotterdam",
    "terminal_name": "Maasvlakte Olie Terminal (MOT)",
    "operator_name": "Vopak + Shell + BP",
    "type": "tanker",
    "capacity_tonnes": 36000000,
    "berths_count": 4,
    "max_draft_m": 24.0,
    "rail_access": false,
    "source": "curated",
    "data_quality": "seed"
  },
  {
    "port_slug": "rotterdam",
    "terminal_name": "Gate Terminal (LNG)",
    "operator_name": "Gasunie + Vopak",
    "type": "lng",
    "capacity_tonnes": 16000000,
    "berths_count": 3,
    "max_draft_m": 14.0,
    "rail_access": false,
    "source": "curated",
    "data_quality": "seed"
  },
  {
    "port_slug": "singapore",
    "terminal_name": "Tuas Mega Port (Phase 1)",
    "operator_name": "PSA International",
    "type": "container",
    "capacity_teu": 20000000,
    "berths_count": 21,
    "max_draft_m": 21.0,
    "quay_length_m": 8600,
    "reefer_plugs": 8000,
    "rail_access": false,
    "source": "curated",
    "data_quality": "seed"
  },
  {
    "port_slug": "singapore",
    "terminal_name": "Pasir Panjang Terminal",
    "operator_name": "PSA International",
    "type": "container",
    "capacity_teu": 15000000,
    "berths_count": 16,
    "max_draft_m": 18.0,
    "quay_length_m": 6800,
    "rail_access": false,
    "source": "curated",
    "data_quality": "seed"
  },
  {
    "port_slug": "singapore",
    "terminal_name": "Jurong Port (bulk)",
    "operator_name": "Jurong Port",
    "type": "bulk",
    "capacity_tonnes": 16000000,
    "berths_count": 21,
    "max_draft_m": 15.5,
    "rail_access": false,
    "source": "curated",
    "data_quality": "seed"
  },
  {
    "port_slug": "singapore",
    "terminal_name": "Universal Terminal",
    "operator_name": "Hin Leong + PetroChina",
    "type": "tanker",
    "capacity_tonnes": 23000000,
    "berths_count": 18,
    "max_draft_m": 21.0,
    "rail_access": false,
    "source": "curated",
    "data_quality": "seed"
  },
  {
    "port_slug": "shanghai",
    "terminal_name": "Yangshan Deep Water Port (Phase 4)",
    "operator_name": "Shanghai International Port Group",
    "type": "container",
    "capacity_teu": 7000000,
    "berths_count": 7,
    "max_draft_m": 16.0,
    "quay_length_m": 2350,
    "reefer_plugs": 3000,
    "rail_access": true,
    "source": "curated",
    "data_quality": "seed"
  },
  {
    "port_slug": "shanghai",
    "terminal_name": "Waigaoqiao Terminals",
    "operator_name": "Shanghai International Port Group",
    "type": "container",
    "capacity_teu": 16000000,
    "berths_count": 30,
    "max_draft_m": 14.5,
    "quay_length_m": 11000,
    "rail_access": true,
    "source": "curated",
    "data_quality": "seed"
  },
  {
    "port_slug": "shanghai",
    "terminal_name": "Luojing Terminal (bulk)",
    "operator_name": "Baoshan Iron & Steel",
    "type": "bulk",
    "capacity_tonnes": 60000000,
    "berths_count": 11,
    "max_draft_m": 13.0,
    "rail_access": true,
    "source": "curated",
    "data_quality": "seed"
  },
  {
    "port_slug": "jebel_ali",
    "terminal_name": "Container Terminal 3 (CT3)",
    "operator_name": "DP World",
    "type": "container",
    "capacity_teu": 4500000,
    "berths_count": 4,
    "max_draft_m": 18.0,
    "quay_length_m": 1860,
    "rail_access": false,
    "source": "curated",
    "data_quality": "seed"
  },
  {
    "port_slug": "jebel_ali",
    "terminal_name": "Container Terminal 2 (CT2)",
    "operator_name": "DP World",
    "type": "container",
    "capacity_teu": 6500000,
    "berths_count": 5,
    "max_draft_m": 16.0,
    "quay_length_m": 3000,
    "rail_access": false,
    "source": "curated",
    "data_quality": "seed"
  },
  {
    "port_slug": "jebel_ali",
    "terminal_name": "Terminal Cruise",
    "operator_name": "DP World Cruise Terminals",
    "type": "cruise",
    "berths_count": 3,
    "rail_access": false,
    "source": "curated",
    "data_quality": "seed"
  },
  {
    "port_slug": "hamburg",
    "terminal_name": "Burchardkai (CTB)",
    "operator_name": "HHLA · Hamburger Hafen und Logistik",
    "type": "container",
    "capacity_teu": 5200000,
    "berths_count": 9,
    "max_draft_m": 17.4,
    "quay_length_m": 2850,
    "rail_access": true,
    "source": "curated",
    "data_quality": "seed"
  },
  {
    "port_slug": "hamburg",
    "terminal_name": "Eurogate Container Terminal Hamburg",
    "operator_name": "Eurogate (BLG Logistics + Eurokai)",
    "type": "container",
    "capacity_teu": 4100000,
    "berths_count": 4,
    "max_draft_m": 17.4,
    "quay_length_m": 2080,
    "rail_access": true,
    "source": "curated",
    "data_quality": "seed"
  },
  {
    "port_slug": "hamburg",
    "terminal_name": "CTT · Container Terminal Tollerort",
    "operator_name": "HHLA (con minoría COSCO)",
    "type": "container",
    "capacity_teu": 1100000,
    "berths_count": 4,
    "max_draft_m": 14.5,
    "quay_length_m": 1240,
    "rail_access": true,
    "source": "curated",
    "data_quality": "seed"
  },
  {
    "port_slug": "los_angeles",
    "terminal_name": "Pier 400 · APM Terminals",
    "operator_name": "APM Terminals (Maersk)",
    "type": "container",
    "capacity_teu": 4500000,
    "berths_count": 8,
    "max_draft_m": 16.8,
    "quay_length_m": 1450,
    "rail_access": true,
    "source": "curated",
    "data_quality": "seed"
  },
  {
    "port_slug": "los_angeles",
    "terminal_name": "West Basin Container Terminal (WBCT)",
    "operator_name": "China Shipping Holding + Yang Ming",
    "type": "container",
    "capacity_teu": 2200000,
    "berths_count": 4,
    "max_draft_m": 15.2,
    "rail_access": true,
    "source": "curated",
    "data_quality": "seed"
  },
  {
    "port_slug": "los_angeles",
    "terminal_name": "TraPac Terminal",
    "operator_name": "Mitsui O.S.K. Lines (MOL)",
    "type": "container",
    "capacity_teu": 2000000,
    "berths_count": 4,
    "max_draft_m": 15.2,
    "rail_access": true,
    "source": "curated",
    "data_quality": "seed"
  },
  {
    "port_slug": "los_angeles",
    "terminal_name": "Vincent Thomas Cruise Terminal",
    "operator_name": "World Cruise Center",
    "type": "cruise",
    "berths_count": 3,
    "rail_access": false,
    "source": "curated",
    "data_quality": "seed"
  },
  {
    "port_slug": "antwerp",
    "terminal_name": "MSC Home Terminal Deurganck",
    "operator_name": "PSA Antwerp + MSC",
    "type": "container",
    "capacity_teu": 9000000,
    "berths_count": 6,
    "max_draft_m": 17.0,
    "quay_length_m": 2900,
    "rail_access": true,
    "source": "curated",
    "data_quality": "seed"
  },
  {
    "port_slug": "antwerp",
    "terminal_name": "Antwerp Gateway",
    "operator_name": "DP World + CMA CGM",
    "type": "container",
    "capacity_teu": 3500000,
    "berths_count": 4,
    "max_draft_m": 16.0,
    "quay_length_m": 1700,
    "rail_access": true,
    "source": "curated",
    "data_quality": "seed"
  },
  {
    "port_slug": "antwerp",
    "terminal_name": "BASF Chemical Terminal",
    "operator_name": "BASF Antwerpen",
    "type": "tanker",
    "capacity_tonnes": 25000000,
    "berths_count": 9,
    "max_draft_m": 17.0,
    "rail_access": true,
    "source": "curated",
    "data_quality": "seed"
  },
  {
    "port_slug": "antwerp",
    "terminal_name": "Terminal Ro-Ro Zeebrugge",
    "operator_name": "ICO Terminals (Cobelfret)",
    "type": "roro",
    "berths_count": 6,
    "max_draft_m": 15.0,
    "rail_access": true,
    "source": "curated",
    "data_quality": "seed"
  },
  {
    "port_slug": "piraeus",
    "terminal_name": "Container Terminal Pier II + III",
    "operator_name": "COSCO Shipping Ports",
    "type": "container",
    "capacity_teu": 6000000,
    "berths_count": 6,
    "max_draft_m": 18.5,
    "quay_length_m": 2400,
    "rail_access": true,
    "concession_end_year": 2052,
    "source": "curated",
    "data_quality": "seed"
  },
  {
    "port_slug": "piraeus",
    "terminal_name": "Cruise Terminal Piraeus",
    "operator_name": "PPA · Piraeus Port Authority (COSCO)",
    "type": "cruise",
    "berths_count": 11,
    "rail_access": false,
    "source": "curated",
    "data_quality": "seed"
  },
  {
    "port_slug": "piraeus",
    "terminal_name": "Terminal Vehículos",
    "operator_name": "Toyota Hellas + Hyundai Hellas",
    "type": "roro",
    "berths_count": 4,
    "rail_access": true,
    "source": "curated",
    "data_quality": "seed"
  },
  {
    "port_slug": "ny_nj",
    "terminal_name": "Port Newark Container Terminal (PNCT)",
    "operator_name": "Ports America + Terminal Investment",
    "type": "container",
    "capacity_teu": 1900000,
    "berths_count": 4,
    "max_draft_m": 15.2,
    "rail_access": true,
    "source": "curated",
    "data_quality": "seed"
  },
  {
    "port_slug": "ny_nj",
    "terminal_name": "APM Terminals Elizabeth",
    "operator_name": "APM Terminals (Maersk)",
    "type": "container",
    "capacity_teu": 1500000,
    "berths_count": 6,
    "max_draft_m": 15.2,
    "rail_access": true,
    "source": "curated",
    "data_quality": "seed"
  },
  {
    "port_slug": "ny_nj",
    "terminal_name": "GCT Bayonne",
    "operator_name": "Global Container Terminals",
    "type": "container",
    "capacity_teu": 1100000,
    "berths_count": 3,
    "max_draft_m": 15.2,
    "rail_access": true,
    "source": "curated",
    "data_quality": "seed"
  },
  {
    "port_slug": "ny_nj",
    "terminal_name": "Manhattan Cruise Terminal",
    "operator_name": "NYCEDC / Carnival / NCL",
    "type": "cruise",
    "berths_count": 3,
    "rail_access": false,
    "source": "curated",
    "data_quality": "seed"
  }
]
