/**
 * Dataset de 50 relaciones adicionales entre actores políticos españoles
 * importadas desde el CSV curado `relaciones_politicas_personas_next50.csv`
 * (mayo 2026).
 *
 * Cada relación tiene fuente periodística verificable con URL real
 * (campo sourceUrl). El pill "evidencia ↗" del grafo enlaza directamente
 * al artículo original cuando está disponible.
 */

import type { RelacionExplicita } from "./relaciones-explicitas";

// Helper · mismo algoritmo de slugificación que data/actores-fixture.ts
const slug = (n: string) => n
  .toLowerCase()
  .replace(/[^a-z0-9]+/g, '-')
  .replace(/(^-|-$)/g, '');

export const RELACIONES_CSV_CURADAS: RelacionExplicita[] = [
  { a: slug('Cuca Gamarra'), b: slug('Pedro Sánchez'), val: -85, tipo: 'oposicion_frontal',
    label: 'PP acusa al presidente de usar política internacional para desviar de corrupción (abr 2024)',
    sourceUrl: 'https://www.andaluciainformacion.es/articulo/espana/gamarra-acusa-sanchez-usar-politica-internacional/202509091042433135690.html' },
  { a: slug('María Pastor'), b: slug('Isabel Díaz Ayuso'), val: -65, tipo: 'critica_publica',
    label: 'Más Madrid critica viaje a México: "no tiene perfil institucional" (abr 2024)',
    sourceUrl: 'https://www.20minutos.es/madrid/oposicion-bloque-critica-viaje-diaz-ayuso-mexico-no-va-resolver-ningun-problema-los-madrilenos_6965954_0.html' },
  { a: slug('Mar Espinar'), b: slug('Isabel Díaz Ayuso'), val: -65, tipo: 'critica_publica',
    label: 'PSOE-M: "Ayuso no se preocupa por Madrid, tendrá que dar explicaciones" (abr 2024)',
    sourceUrl: 'https://www.20minutos.es/madrid/oposicion-bloque-critica-viaje-diaz-ayuso-mexico-no-va-resolver-ningun-problema-los-madrilenos_6965954_0.html' },
  { a: slug('Óscar Puente'), b: slug('Alberto Núñez Feijóo'), val: -85, tipo: 'oposicion_frontal',
    label: 'Ministro Transportes llama "imbécil" al líder del PP en redes (ene 2024)',
    sourceUrl: 'https://www.diariodesevilla.es/espana/oscar-puente-llama-imbecil-feijoo_0_2006805298.html' },
  { a: slug('Ester Muñoz'), b: slug('Óscar Puente'), val: -65, tipo: 'critica_publica',
    label: 'Portavoz PP acusa al ministro de pertenecer al partido más radical (ene 2024)',
    sourceUrl: 'https://www.diariodesevilla.es/espana/oscar-puente-llama-imbecil-feijoo_0_2006805298.html' },
  { a: slug('Margarita Robles'), b: slug('Isabel Díaz Ayuso'), val: -65, tipo: 'critica_publica',
    label: 'Ministra Defensa: Ayuso se equivocó al reunirse con Milei (abr 2024)',
    sourceUrl: 'https://www.servimedia.es/noticias/robles-dice-ayuso-equivoca-recibir-milei/1410187972' },
  { a: slug('Juan Lobato'), b: slug('Isabel Díaz Ayuso'), val: -65, tipo: 'critica_publica',
    label: 'PSOE-M reprocha condecoración a Milei: "España ofrece sanidad universal" (may 2024)',
    sourceUrl: 'https://www.20minutos.es/noticia/5522842/0/lobato-reprocha-a-ayuso-que-premie-a-milei-y-ella-le-responde-recibirle-es-un-honor/' },
  { a: slug('Isabel Díaz Ayuso'), b: slug('Javier Milei'), val: 85, tipo: 'aliado_partido',
    label: 'Ayuso defiende visita: "honor recibir a jefe de Estado legítimo" (may 2024)',
    sourceUrl: 'https://www.20minutos.es/noticia/5522842/0/lobato-reprocha-a-ayuso-que-premie-a-milei-y-ella-le-responde-recibirle-es-un-honor/' },
  { a: slug('Javier Milei'), b: slug('Pedro Sánchez'), val: -85, tipo: 'oposicion_frontal',
    label: 'Milei llama "corrupta" a esposa de Sánchez · España retira embajador (may 2024)',
    sourceUrl: 'https://www.reuters.com/world/europe/spain-recalls-ambassador-after-argentinas-milei-calls-pms-wife-corrupt-2024-05-19/' },
  { a: slug('José María Aznar'), b: slug('Pedro Sánchez'), val: -85, tipo: 'oposicion_frontal',
    label: 'Aznar califica el gobierno de "ineptocracia corrupta" (feb 2024)',
    sourceUrl: 'https://theobjective.com/espana/politica/2025-09-19/aznar-sanchez-ineptocracia/' },
  { a: slug('José María Aznar'), b: slug('Santiago Abascal'), val: -65, tipo: 'critica_publica',
    label: 'Aznar: "No me gustan los populismos de derecha ni de izquierda" (oct 2024)',
    sourceUrl: 'https://www.eldebate.com/espana/comunidad-valenciana/20260311/aznar-critica-populismo-abascal-vox-no-me-gustan_394784.html' },
  { a: slug('Juanma Moreno'), b: slug('Pedro Sánchez'), val: -65, tipo: 'critica_publica',
    label: 'Moreno reprocha falta de firmeza contra el narcotráfico (mar 2024)',
    sourceUrl: 'https://www.antena3.com/noticias/espana/moreno-descarta-acuerdo-como-extremadura-aragon-llega-mayoria-absoluta-psoe-vox-deberian-abstenerse_202605156a06f6fb716e9c5714707670.html' },
  { a: slug('Juanma Moreno'), b: slug('Fernando Grande-Marlaska'), val: -65, tipo: 'critica_publica',
    label: 'Reproche por no asistir a funerales de guardias civiles en Andalucía (mar 2024)',
    sourceUrl: 'https://www.antena3.com/noticias/espana/moreno-descarta-acuerdo-como-extremadura-aragon-llega-mayoria-absoluta-psoe-vox-deberian-abstenerse_202605156a06f6fb716e9c5714707670.html' },
  { a: slug('Ione Belarra'), b: slug('Juan Roig'), val: -65, tipo: 'critica_publica',
    label: 'Belarra acusa a Roig de "capo" de oligopolio del 25% del mercado (may 2023)',
    sourceUrl: 'https://www.antena3.com/noticias/espana/belarra-apuesta-crear-supermercado-publico-capo-juan-roig_202305076457b2bb73ab380001f27b58.html' },
  { a: slug('Alberto Núñez Feijóo'), b: slug('Pedro Sánchez'), val: -85, tipo: 'oposicion_frontal',
    label: 'Feijóo: con el pacto PSOE-Junts "España pierde, se fortalece el independentismo" (nov 2023)',
    sourceUrl: 'https://www.rtve.es/noticias/20231109/feijoo-pp-acuerdo-psoe-junts/2460482.shtml' },
  { a: slug('Alberto Núñez Feijóo'), b: slug('Isabel Díaz Ayuso'), val: 15, tipo: 'rivalidad_interna',
    label: 'Ayuso marca agenda PP antes que Feijóo: regularización, amnistía (abr 2024)',
    sourceUrl: 'https://www.infobae.com/espana/2026/04/15/feijoo-vuelve-a-quedarse-a-rebufo-de-ayuso-en-la-ofensiva-del-pp-contra-la-regularizacion-de-migrantes/' },
  { a: slug('Santiago Abascal'), b: slug('Alberto Núñez Feijóo'), val: -85, tipo: 'oposicion_frontal',
    label: 'Vox: PP "veleta azul" incapaz de romper con Sánchez · "guerra sucia" (mar 2026)',
    sourceUrl: 'https://www.lavanguardia.com/politica/20260309/11485282/abascal-eleva-tono-feijoo-acusar-pp-circular-mentiras-vox-luego-sanchez.html' },
  { a: slug('Alberto Núñez Feijóo'), b: slug('Carles Puigdemont'), val: -85, tipo: 'oposicion_frontal',
    label: 'Feijóo propone aplicar art. 155 si Puigdemont vuelve · "humillación" (jul 2025)',
    sourceUrl: 'https://www.infobae.com/espana/2025/07/06/feijoo-y-puigdemont-rebajan-el-tono-por-primera-vez-tras-anos-de-ataques-mutuos-la-posible-mocion-de-censura-a-sanchez-reordena-el-tablero-politico/' },
  { a: slug('Pedro Sánchez'), b: slug('Ione Belarra'), val: -85, tipo: 'oposicion_frontal',
    label: 'Belarra: Sánchez expulsó a Podemos del Gobierno y rompió unidad izquierda (nov 2023)',
    sourceUrl: 'https://www.telecinco.es/noticias/espana/20231205/desencuentro-podemos-y-sumar-rajada-igualdad-pedro-sanchez-diferencias-yolanda-diaz_18_011160216.html' },
  { a: slug('Nadia Calviño'), b: slug('Yolanda Díaz'), val: -85, tipo: 'oposicion_frontal',
    label: 'Choques repetidos por reforma laboral, SMI y subsidios desempleo (nov 2023)',
    sourceUrl: 'https://www.eldiario.es/economia/ultima-batalla-ideologica-nadia-calvino-yolanda-diaz_1_10735423.html' },
  { a: slug('Emiliano García-Page'), b: slug('Pedro Sánchez'), val: -85, tipo: 'oposicion_frontal',
    label: 'Página pide voto de confianza o nuevas elecciones · no aplaude en Comité Federal (jul 2025)',
    sourceUrl: 'https://www.infobae.com/espana/2025/07/05/el-gesto-de-garcia-page-tras-el-discurso-de-pedro-sanchez-el-unico-que-no-se-levanta-cuando-termina-de-hablar-el-presidente-del-gobierno/' },
  { a: slug('Juan Roig'), b: slug('Pedro Sánchez'), val: -65, tipo: 'critica_publica',
    label: 'Presidente Mercadona: "los pactos de investidura dividen a los españoles" (nov 2023)',
    sourceUrl: 'https://www.antena3.com/noticias/economia/juan-roig-muy-critico-pactos-investidura-sanchez-enfrenta-espanoles-todo-peor_2023111665564ef232499c000145dbae.html' },
  { a: slug('Pedro Sánchez'), b: slug('Carles Puigdemont'), val: 25, tipo: 'rivalidad_interna',
    label: 'Sánchez defiende amnistía pese a descartarla antes · clave para investidura (oct 2023)',
    sourceUrl: 'https://elpais.com/espana/2023-10-28/sanchez-defiende-la-amnistia-en-el-comite-federal-del-psoe-por-el-interes-de-espana-y-en-defensa-de-la-convivencia-entre-espanoles.html' },
  { a: slug('Aitor Esteban'), b: slug('Pedro Sánchez'), val: -65, tipo: 'critica_publica',
    label: 'PNV: "fin de la hemorragia de escándalos o convocar elecciones" (dic 2025)',
    sourceUrl: 'https://www.elconfidencial.com/espana/2025-12-13/pnv-aitor-esteben-psoe-cierra-hemorragia-escandolos-o-sanchez-convoca-elecciones_4265879/' },
  { a: slug('Santiago Abascal'), b: slug('Gabriel Rufián'), val: -85, tipo: 'oposicion_frontal',
    label: 'Rufián: Abascal "se parece más a Abderramán II que al Cid" (abr 2026)',
    sourceUrl: 'https://www.antena3.com/noticias/espana/rufian-abascal-sorprende-que-hable-pureza-alguien-que-parece-mas-abderraman-que-cid-campeador_2026042269e8993316cd5c2d4667d1e1.html' },
  { a: slug('Gabriel Rufián'), b: slug('Junts'), val: -85, tipo: 'oposicion_frontal',
    label: 'Rufián agita billete de 50€ a Junts por voto alquileres · "pelotón ejecución" (abr 2026)',
    sourceUrl: 'https://elpais.com/espana/2026-04-30/junts-acusa-a-rufian-de-actuar-al-mas-puro-estilo-vox.html' },
  { a: slug('Pere Aragonès'), b: slug('Carles Puigdemont'), val: -65, tipo: 'critica_publica',
    label: 'Aragonès: "se rinden quienes abandonan a mitad de legislatura" (mar 2024)',
    sourceUrl: 'https://www.eldiario.es/catalunya/politica/aragones-replica-puigdemont-rinde-abandona-govern-media-legislatura-vota-presupuestos_1_11247879.html' },
  { a: slug('Javier Tebas'), b: slug('Florentino Pérez'), val: -85, tipo: 'oposicion_frontal',
    label: 'Tebas vs Florentino por Superliga: "tono mesiánico, sectario y supremacista" (nov 2025)',
    sourceUrl: 'https://www.si.com/es-us/futbol/javier-tebas-no-se-queda-callado-y-responde-a-florentino-perez' },
  { a: slug('Isabel Díaz Ayuso'), b: slug('Pedro Sánchez'), val: -85, tipo: 'oposicion_frontal',
    label: 'Ayuso será "contrapeso de Sánchez" · vaticina 2026 muy oscuro (dic 2025)',
    sourceUrl: 'https://www.eldiariodemadrid.es/articulo/politica/ayuso-corrupcion-gobierno-sanchez-zapatero-balance-2025/20251217180450116706.html' },
  { a: slug('Mónica García'), b: slug('Isabel Díaz Ayuso'), val: -85, tipo: 'oposicion_frontal',
    label: 'Ministra Sanidad: Madrid "guarida de las peores políticas trumpistas" (abr 2024)',
    sourceUrl: 'https://www.20minutos.es/madrid/monica-garcia-critica-freno-madrid-para-avance-las-mejores-politicas-pide-acabar-con-traba-ayuso_6962927_0.html' },
  { a: slug('Ada Colau'), b: slug('Jaume Collboni'), val: -65, tipo: 'critica_publica',
    label: 'Colau: Collboni dejó Barcelona "sin modelo de futuro" tras frenar superilla (sep 2024)',
    sourceUrl: 'https://www.totbarcelona.cat/es/politica-es/colais-collboni-liderazgo-barcelona-ciudad-sin-futuro-517903/' },
  { a: slug('CSIF'), b: slug('Gobierno de España'), val: -65, tipo: 'critica_publica',
    label: 'CSIF propone movilizaciones · 1.200M deuda por subida 0,5% impagada (may 2026)',
    sourceUrl: 'https://www.servimedia.es/noticias/csif-propone-ugt-ccoo-una-protesta-nacional-para-exigir-gobierno-subida-salarial-funcionarios-nuevo-acuerdo/1411681845' },
  { a: slug('Unai Sordo'), b: slug('Gobierno de España'), val: -65, tipo: 'critica_publica',
    label: 'CCOO exige reducir jornada de 40 a 37,5h sin rebaja salarial (sep 2024)',
    sourceUrl: 'https://www.reuters.com/world/europe/unions-spain-protest-push-reduce-working-hours-2024-09-26/' },
  { a: slug('Ignacio Sánchez Galán'), b: slug('Gobierno de España'), val: -65, tipo: 'critica_publica',
    label: 'Iberdrola recurrirá impuesto a energéticas en tribunales (nov 2022)',
    sourceUrl: 'https://www.eldiario.es/economia/presidente-iberdrola-carga-impuesto-energeticas-acudiremos-tribunales_1_9655748.html' },
  { a: slug('Josu Jon Imaz'), b: slug('Gobierno de España'), val: -65, tipo: 'critica_publica',
    label: 'Repsol pagó 335M por tasa energéticas · augura desaparición en 2025 (feb 2025)',
    sourceUrl: 'https://www.servimedia.es/noticias/repsol-pagara-335-millones-impuesto-energeticas-2024-24-menos-ano-pasado/1410145492' },
  { a: slug('Antonio Garamendi'), b: slug('Gobierno de España'), val: -65, tipo: 'critica_publica',
    label: 'CEOE critica que el Gobierno culpe a las empresas · inestabilidad ahuyenta inversión (jul 2025)',
    sourceUrl: 'https://www.infobae.com/espana/2025/07/16/garamendi-ceoe-critica-al-gobierno-por-senalar-a-las-empresas-cuando-hay-que-buscar-culpables/' },
  { a: slug('Ana Botín'), b: slug('Pedro Sánchez'), val: -65, tipo: 'critica_publica',
    label: 'Botín pidió a Sánchez frenar impuesto a la banca · denuncia discriminación (dic 2024)',
    sourceUrl: 'https://www.vozpopuli.com/economia/banca/sanchez-ignoro-una-peticion-expresa-de-botin-para-frenar-el-impuestazo-a-la-banca.html' },
  { a: slug('Javier Milei'), b: slug('Josep Borrell'), val: -65, tipo: 'critica_publica',
    label: 'Borrell: ataques a familiares "no tienen cabida en nuestra cultura" (may 2024)',
    sourceUrl: 'https://www.reuters.com/world/europe/spain-recalls-ambassador-after-argentinas-milei-calls-pms-wife-corrupt-2024-05-19/' },
  { a: slug('Luis Rubiales'), b: slug('Jennifer Hermoso'), val: -85, tipo: 'oposicion_frontal',
    label: 'Beso sin consentimiento en Mundial · negativa a dimitir · suspensión FIFA (ago 2023)',
    sourceUrl: 'https://www.espn.com/soccer/story/_/id/38251952/luis-rubiales-rfef-allegations-jenni-hermoso-world-cup' },
  { a: slug('Sindicatos policiales'), b: slug('Fernando Grande-Marlaska'), val: -85, tipo: 'oposicion_frontal',
    label: 'Sindicatos amenazan con paralizar Consejo de Policía por equiparación salarial (sep 2024)',
    sourceUrl: 'https://www.infobae.com/espana/2024/02/02/los-sindicatos-amenazan-a-marlaska-con-paralizar-el-consejo-de-policia-hasta-negociar-la-equiparacion-salarial-estamos-hartos/' },
  { a: slug('Arnaldo Otegi'), b: slug('Pedro Sánchez'), val: 65, tipo: 'aliado_partido',
    label: 'Otegi: foto con Sánchez es "normalización y nueva etapa política" (oct 2023)',
    sourceUrl: 'https://www.infobae.com/espana/agencias/2023/10/16/otegi-dice-que-la-foto-con-sanchez-nos-situa-en-otra-fase-politica-aunque-unos-y-otros-no-quieran/' },
  { a: slug('Santiago Abascal'), b: slug('Alfonso Fernández Mañueco'), val: -65, tipo: 'critica_publica',
    label: 'Abascal: "del género tonto" demonizar a Vox y luego pedir sus votos (mar 2026)',
    sourceUrl: 'https://www.lavanguardia.com/politica/20260309/11485282/abascal-eleva-tono-feijoo-acusar-pp-circular-mentiras-vox-luego-sanchez.html' },
  { a: slug('Nadia Calviño'), b: slug('Pedro Sánchez'), val: -65, tipo: 'critica_publica',
    label: 'Tensiones internas por reforma laboral · Calviño reescribió partes (nov 2023)',
    sourceUrl: 'https://elpais.com/economia/2023-11-30/los-desencuentros-mas-sonados-entre-calvino-y-diaz.html' },
  { a: slug('Unai Sordo'), b: slug('CEOE'), val: -65, tipo: 'critica_publica',
    label: 'CCOO presiona por reducir jornada · patronal teme aumento costes (sep 2024)',
    sourceUrl: 'https://www.reuters.com/world/europe/unions-spain-protest-push-reduce-working-hours-2024-09-26/' },
  { a: slug('Pedro Sánchez'), b: slug('Unai Sordo'), val: 65, tipo: 'aliado_partido',
    label: 'Acuerdo reforma pensiones · sube bases máximas + cuota solidaridad (mar 2023)',
    sourceUrl: 'https://www.lamoncloa.gob.es/serviciosdeprensa/notasprensa/inclusion/paginas/2023/150323-reforma-pensiones.aspx' },
  { a: slug('Pedro Sánchez'), b: slug('Yolanda Díaz'), val: 65, tipo: 'aliado_partido',
    label: 'Sánchez evita criticar a Díaz por Junts · dirige reproches a Feijóo y Abascal (may 2026)',
    sourceUrl: 'https://www.democrata.es/politica/sanchez-elude-reprochar-a-diaz-por-junts-y-dirige-sus-criticas-a-feijoo-y-abascal/' },
  { a: slug('Pedro Sánchez'), b: slug('Santiago Abascal'), val: -65, tipo: 'critica_publica',
    label: 'Sánchez acusa a Feijóo y Abascal de apoyar guerra EEUU-Israel (mar 2026)',
    sourceUrl: 'https://www.antena3.com/noticias/espana/pedro-sanchez-critica-feijoo-abascal-apoyar-guera-que-perjudicaria-espanoles_2026030769ac1ff2e1ff634075ddaaa3.html' },
  { a: slug('Luis Rubiales'), b: slug('Gobierno de España'), val: -85, tipo: 'oposicion_frontal',
    label: 'Negativa a dimitir tras beso · Gobierno exige responsabilidades (ago 2023)',
    sourceUrl: 'https://www.espn.com/soccer/story/_/id/38251952/luis-rubiales-rfef-allegations-jenni-hermoso-world-cup' },
  { a: slug('CEOE'), b: slug('UGT'), val: 65, tipo: 'aliado_partido',
    label: 'V AENC: subida salarial 4% (2023) y 3% (2024-25) · cláusula revisión IPC (may 2023)',
    sourceUrl: 'https://orain.eus/es/actualidad/economia/2023/05/09/ceoe-y-sindicatos-ugt-y-cc-oo-firmaran-10-de-mayo-de-2023-pacto-de-salarios-20232025/' },
  { a: slug('AUGC'), b: slug('Leonardo Marcos'), val: -85, tipo: 'oposicion_frontal',
    label: 'AUGC celebra dimisión: "falta de diálogo, prepotencia y mala gestión" (sep 2024)',
    sourceUrl: 'https://www.h50.es/augc-celebra-la-dimision-de-leonardo-marcos-como-director-general-de-la-guardia-civil/' },
];
