/**
 * Dataset de 47 relaciones del CSV `relaciones_politicas_personas_top50.csv`
 * (mayo 2026). Complementa next50 con fechas más precisas y descripciones
 * de hechos clave 2023-2026.
 *
 * Cada relación tiene sourceUrl con noticia real verificable.
 */

import type { RelacionExplicita } from "./relaciones-explicitas";

const slug = (n: string) => n
  .toLowerCase()
  .replace(/[^a-z0-9]+/g, '-')
  .replace(/(^-|-$)/g, '');

// Alias: nombres del CSV con paréntesis o variantes → ID canónico
const ALIAS: Record<string, string> = {
  'Juan Manuel Moreno':                   'juanma-moreno',
  'Junts per Catalunya':                  'junts',
  'Pedro Sánchez/PSOE':                   'pedro-s-nchez',
  'Podemos (Ione Belarra)':               'ione-belarra',
  'UGT/CCOO':                              'ugt',
  'CEOE (Antonio Garamendi)':              'ceoe',
  'Gobierno de España (Pedro Sánchez)':    'gobierno-de-espa-a',
};

const id = (nombre: string): string => ALIAS[nombre] ?? slug(nombre);

export const RELACIONES_CSV_TOP50: RelacionExplicita[] = [
  { a: id('Pedro Sánchez'), b: id('Pere Aragonès'), val: 20, tipo: 'rivalidad_interna',
    label: 'Mesa de diálogo con Generalitat · Ingreso Mínimo Vital y plurilingüismo (dic 2023)',
    sourceUrl: 'https://www.rtve.es/noticias/20231221/sanchez-aragones-pactan-convocar-mesa-dialogo-inicio-2024/2468835.shtml' },
  { a: id('Pedro Sánchez'), b: id('Imanol Pradales'), val: 85, tipo: 'pacto_investidura',
    label: 'Acuerda transferir 7 nuevas competencias a Euskadi · aeropuertos, tráfico (mar 2026)',
    sourceUrl: 'https://cadenaser.com/euskadi/2026/03/27/euskadi-logra-siete-nuevas-transferencias-y-entra-por-primera-vez-en-la-gestion-de-sus-aeropuertos-radio-bilbao/' },
  { a: id('Pedro Sánchez'), b: id('Isabel Díaz Ayuso'), val: -85, tipo: 'oposicion_frontal',
    label: 'Ayuso: 2026 "muy oscuro" · acusa al Gobierno de usar Estado contra Madrid (dic 2025)',
    sourceUrl: 'https://www.eldiariodemadrid.es/articulo/politica/ayuso-corrupcion-gobierno-sanchez-zapatero-balance-2025/20251217180450116706.html' },
  { a: id('Pedro Sánchez'), b: id('Juan Manuel Moreno'), val: 15, tipo: 'rivalidad_interna',
    label: 'Comisión Bilateral resuelve 87% litigios · acuerdo en menores migrantes (abr 2025)',
    sourceUrl: 'https://www.diariodesevilla.es/andalucia/relacion-junta-andalucia-gobierno-central_0_2003762063.html' },
  { a: id('Pedro Sánchez'), b: id('Alfonso Fernández Mañueco'), val: -85, tipo: 'oposicion_frontal',
    label: 'Conflicto por protocolo antiabortista · Sánchez exige explicaciones (ene 2023)',
    sourceUrl: 'https://www.rtve.es/noticias/20230119/junta-castilla-leon-inadmite-requerimiento-gobierno-protocolo-antiaborto-no-existe/2416544.shtml' },
  { a: id('Margarita Robles'), b: id('Ejército del Aire y del Espacio'), val: 85, tipo: 'aliado_partido',
    label: 'Ministra elogia eficacia y humanidad en rescates DANA Valencia (nov 2024)',
    sourceUrl: 'https://www.lamoncloa.gob.es/serviciosdeprensa/notasprensa/defensa/paginas/2024/061124-robles-eficacia-ejercito-aire.aspx' },
  { a: id('Yolanda Díaz'), b: id('UGT/CCOO'), val: 85, tipo: 'aliado_sindical',
    label: 'Acuerdo SMI +5% (1.134€) con efecto retroactivo · flexibilidad sindical (ene 2024)',
    sourceUrl: 'https://cadenaser.com/nacional/2024/01/12/gobierno-patronal-y-sindicatos-se-reunen-para-cerrar-la-subida-del-salario-minimo-cadena-ser/' },
  { a: id('Yolanda Díaz'), b: id('CEOE (Antonio Garamendi)'), val: -65, tipo: 'critica_publica',
    label: 'CEOE se niega a firmar subida SMI · Gobierno denuncia falta de flexibilidad (ene 2024)',
    sourceUrl: 'https://cadenaser.com/nacional/2024/01/12/gobierno-patronal-y-sindicatos-se-reunen-para-cerrar-la-subida-del-salario-minimo-cadena-ser/' },
  { a: id('Nadia Calviño'), b: id('Yolanda Díaz'), val: -85, tipo: 'oposicion_frontal',
    label: 'Choques por ERTE, ley rider y reforma laboral · Calviño reescribe partes (nov 2023)',
    sourceUrl: 'https://elpais.com/economia/2023-11-30/los-desencuentros-mas-sonados-entre-calvino-y-diaz.html' },
  { a: id('CEOE (Antonio Garamendi)'), b: id('UGT/CCOO'), val: 85, tipo: 'aliado_sindical',
    label: 'V AENC firmado: +4% (2023), +3% (2024-25) con cláusula IPC (may 2023)',
    sourceUrl: 'https://orain.eus/es/actualidad/economia/2023/05/09/ceoe-y-sindicatos-ugt-y-cc-oo-firmaran-10-de-mayo-de-2023-pacto-de-salarios-20232025/' },
  { a: id('AUGC'), b: id('Leonardo Marcos'), val: -85, tipo: 'oposicion_frontal',
    label: 'AUGC celebra dimisión: "falta de diálogo y prepotencia tras gestión desastrosa" (sep 2024)',
    sourceUrl: 'https://www.h50.es/augc-celebra-la-dimision-de-leonardo-marcos-como-director-general-de-la-guardia-civil/' },
  { a: id('Luis Planas'), b: id('UPA'), val: 85, tipo: 'aliado_sindical',
    label: 'Acuerdo 43 medidas: simplificar PAC, fiscales, sanidad animal · respuesta protestas (abr 2024)',
    sourceUrl: 'https://www.mapa.gob.es/es/prensa/ultimas-noticias/detalle_noticias/luis-planas-firma-con-upa-el-acuerdo-sobre-las-43-medidas-de-respuesta-del-gobierno-a-las-inquietudes-de-agricultores-y-ganaderos-/10c6433a-3160-4cf6-9dc6-6f6b63c70fb0' },
  { a: id('Alberto Núñez Feijóo'), b: id('Pedro Sánchez'), val: -85, tipo: 'oposicion_frontal',
    label: 'Feijóo: pacto PSOE-Junts es "capitulación" · amnistía por conveniencia personal (nov 2023)',
    sourceUrl: 'https://www.rtve.es/noticias/20231109/feijoo-pp-acuerdo-psoe-junts/2460482.shtml' },
  { a: id('Alberto Núñez Feijóo'), b: id('Isabel Díaz Ayuso'), val: -75, tipo: 'rivalidad_interna',
    label: 'Ayuso presiona a Feijóo para romper negociaciones CGPJ · cede a su presión (2023)',
    sourceUrl: 'https://www.publico.es/politica/feijoo-ayuso-relacion-altibajos-pasa-momento-critico.html' },
  { a: id('Irene Montero'), b: id('Pedro Sánchez'), val: -85, tipo: 'oposicion_frontal',
    label: 'Montero: Sánchez echó a Podemos del Gobierno · "matrimonio de conveniencia" (dic 2023)',
    sourceUrl: 'https://www.telecinco.es/noticias/espana/20231205/desencuentro-podemos-y-sumar-rajada-igualdad-pedro-sanchez-diferencias-yolanda-diaz_18_011160216.html' },
  { a: id('Irene Montero'), b: id('Yolanda Díaz'), val: -85, tipo: 'oposicion_frontal',
    label: 'Montero: ruptura Podemos-Sumar definitiva · acusa a Díaz por la salida (dic 2023)',
    sourceUrl: 'https://www.telecinco.es/noticias/espana/20231205/desencuentro-podemos-y-sumar-rajada-igualdad-pedro-sanchez-diferencias-yolanda-diaz_18_011160216.html' },
  { a: id('Emiliano García-Page'), b: id('Pedro Sánchez'), val: -85, tipo: 'oposicion_frontal',
    label: 'Página exige voto de confianza o elecciones · no aplaude en Comité Federal (jul 2025)',
    sourceUrl: 'https://www.infobae.com/espana/2025/07/05/el-gesto-de-garcia-page-tras-el-discurso-de-pedro-sanchez-el-unico-que-no-se-levanta-cuando-termina-de-hablar-el-presidente-del-gobierno/' },
  { a: id('Juan Roig'), b: id('Pedro Sánchez'), val: -75, tipo: 'critica_publica',
    label: 'Mercadona: pactos de investidura dividen España y perjudican inversiones (nov 2023)',
    sourceUrl: 'https://www.antena3.com/noticias/economia/juan-roig-muy-critico-pactos-investidura-sanchez-enfrenta-espanoles-todo-peor_2023111665564ef232499c000145dbae.html' },
  { a: id('Ione Belarra'), b: id('Juan Roig'), val: -85, tipo: 'oposicion_frontal',
    label: 'Belarra: Roig "capo" de oligopolio · propone supermercado público (may 2023)',
    sourceUrl: 'https://www.antena3.com/noticias/espana/belarra-apuesta-crear-supermercado-publico-capo-juan-roig_202305076457b2bb73ab380001f27b58.html' },
  { a: id('Arnaldo Otegi'), b: id('Pedro Sánchez'), val: 75, tipo: 'pacto_investidura',
    label: 'Otegi celebra foto con Sánchez y Santos Cerdán · "nueva fase política" (oct 2023)',
    sourceUrl: 'https://www.infobae.com/espana/agencias/2023/10/16/otegi-dice-que-la-foto-con-sanchez-nos-situa-en-otra-fase-politica-aunque-unos-y-otros-no-quieran/' },
  { a: id('Carles Puigdemont'), b: id('Pedro Sánchez'), val: 20, tipo: 'rivalidad_interna',
    label: 'Sánchez defiende amnistía · Puigdemont fugado se vuelve clave para investidura (oct 2023)',
    sourceUrl: 'https://elpais.com/espana/2023-10-28/sanchez-defiende-la-amnistia-en-el-comite-federal-del-psoe-por-el-interes-de-espana-y-en-defensa-de-la-convivencia-entre-espanoles.html' },
  { a: id('Javier Tebas'), b: id('Florentino Pérez'), val: -85, tipo: 'oposicion_frontal',
    label: 'Tebas: Florentino "mesiánico, sectario y supremacista" en disputa Superliga (nov 2025)',
    sourceUrl: 'https://www.si.com/es-us/futbol/javier-tebas-no-se-queda-callado-y-responde-a-florentino-perez' },
  { a: id('Pere Aragonès'), b: id('Carles Puigdemont'), val: -85, tipo: 'oposicion_frontal',
    label: 'Aragonès: "se rinde quien deja gobierno a mitad legislatura" · electoralismo (mar 2024)',
    sourceUrl: 'https://www.eldiario.es/catalunya/politica/aragones-replica-puigdemont-rinde-abandona-govern-media-legislatura-vota-presupuestos_1_11247879.html' },
  { a: id('Sindicatos policiales'), b: id('Fernando Grande-Marlaska'), val: -85, tipo: 'oposicion_frontal',
    label: 'Conflicto colectivo · Marlaska apela sentencia equiparación Guardia Civil-Policía (feb 2026)',
    sourceUrl: 'https://www.infobae.com/espana/2024/02/02/los-sindicatos-amenazan-a-marlaska-con-paralizar-el-consejo-de-policia-hasta-negociar-la-equiparacion-salarial-estamos-hartos/' },
  { a: id('Aitor Esteban'), b: id('Pedro Sánchez'), val: -65, tipo: 'critica_publica',
    label: 'PNV urge fin de escándalos o elecciones · año y medio inviable (dic 2025)',
    sourceUrl: 'https://www.infobae.com/espana/2025/12/13/el-pnv-exige-al-gobierno-terminar-ya-con-los-escandalos-o-convocar-elecciones-asi-no-se-puede-aguantar-ano-y-medio/' },
  { a: id('Pedro Sánchez'), b: id('Junts per Catalunya'), val: 65, tipo: 'pacto_investidura',
    label: 'Sánchez anuncia real decreto con exigencias Junts · dispuesto a reunirse con Puigdemont (2026)',
    sourceUrl: 'https://cadenaser.com/nacional/2025/12/02/sanchez-anuncia-un-paquete-de-medidas-exigidas-por-junts-para-tratar-de-recomponer-su-relacion-cadena-ser/' },
  { a: id('Mónica García'), b: id('Isabel Díaz Ayuso'), val: -85, tipo: 'oposicion_frontal',
    label: 'Ministra Sanidad: Madrid "guarida de peores políticas trampistas" · freno al progreso (2024)',
    sourceUrl: 'https://www.20minutos.es/madrid/monica-garcia-critica-freno-madrid-para-avance-las-mejores-politicas-pide-acabar-con-traba-ayuso_6962927_0.html' },
  { a: id('Ada Colau'), b: id('Jaume Collboni'), val: -85, tipo: 'oposicion_frontal',
    label: 'Colau: Collboni dejó Barcelona "sin futuro" · frenó superillas, sin presupuestos (2024)',
    sourceUrl: 'https://www.totbarcelona.cat/es/politica-es/colais-collboni-liderazgo-barcelona-ciudad-sin-futuro-517903/' },
  { a: id('Alfonso Rueda'), b: id('Isabel Rodríguez'), val: 85, tipo: 'pacto_autonomico',
    label: 'Firma transferencia litoral gallego a Xunta · efectiva 1 julio (abr 2025)',
    sourceUrl: 'https://www.lamoncloa.gob.es/serviciosdeprensa/notasprensa/politica-territorial-memoria-democratica/paginas/2025/090425-traspaso-competencias-litoral-galicia.aspx' },
  { a: id('Pedro Sánchez'), b: id('Ana Botín'), val: -65, tipo: 'critica_publica',
    label: 'Sánchez ignora petición de Botín para frenar impuesto a la banca · denuncia discriminación (2024)',
    sourceUrl: 'https://www.vozpopuli.com/economia/banca/sanchez-ignoro-una-peticion-expresa-de-botin-para-frenar-el-impuestazo-a-la-banca.html' },
  { a: id('Ignacio Sánchez Galán'), b: id('Gobierno de España'), val: -85, tipo: 'oposicion_frontal',
    label: 'Iberdrola: impuesto energéticas contraviene directivas UE · recurre a tribunales (2022)',
    sourceUrl: 'https://www.eldiario.es/economia/presidente-iberdrola-carga-impuesto-energeticas-acudiremos-tribunales_1_9655748.html' },
  { a: id('Josu Jon Imaz'), b: id('Gobierno de España'), val: -75, tipo: 'critica_publica',
    label: 'Repsol pagó 335M por tasa · frena inversiones · desaparecerá en 2025 (may 2024)',
    sourceUrl: 'https://www.servimedia.es/noticias/repsol-pagara-335-millones-impuesto-energeticas-2024-24-menos-ano-pasado/1410145492' },
  { a: id('Gabriel Rufián'), b: id('Junts per Catalunya'), val: -85, tipo: 'oposicion_frontal',
    label: 'Rufián billete 50€ a Junts por decreto alquileres · "pelotón ejecución" (abr 2026)',
    sourceUrl: 'https://elpais.com/espana/2026-04-30/junts-acusa-a-rufian-de-actuar-al-mas-puro-estilo-vox.html' },
  { a: id('Luis Rubiales'), b: id('Jennifer Hermoso'), val: -85, tipo: 'oposicion_frontal',
    label: 'Beso sin consentimiento en Mundial · suspensión FIFA · negativa a dimitir (ago 2023)',
    sourceUrl: 'https://www.espn.com/soccer/story/_/id/38251952/luis-rubiales-rfef-allegations-jenni-hermoso-world-cup' },
  { a: id('Luis Rubiales'), b: id('Gobierno de España (Pedro Sánchez)'), val: -85, tipo: 'oposicion_frontal',
    label: 'Sánchez condena comportamiento Rubiales · disculpas insuficientes · expediente (ago 2023)',
    sourceUrl: 'https://www.espn.com/soccer/story/_/id/38251952/luis-rubiales-rfef-allegations-jenni-hermoso-world-cup' },
  { a: id('Gabriel Rufián'), b: id('Santiago Abascal'), val: -85, tipo: 'oposicion_frontal',
    label: 'Rufián: Abascal "más Abderramán II que el Cid" · racismo no debería permitirse (abr 2026)',
    sourceUrl: 'https://www.antena3.com/noticias/espana/rufian-abascal-sorprende-que-hable-pureza-alguien-que-parece-mas-abderraman-que-cid-campeador_2026042269e8993316cd5c2d4667d1e1.html' },
  { a: id('Santiago Abascal'), b: id('Alberto Núñez Feijóo'), val: -85, tipo: 'oposicion_frontal',
    label: 'Vox: PP "veleta azul" · obstaculiza pactos en Extremadura y Aragón (mar 2026)',
    sourceUrl: 'https://theobjective.com/espana/politica/2026-03-09/abascal-alerta-grave-error-feijoo/' },
  { a: id('Joan Laporta'), b: id('Javier Tebas'), val: -65, tipo: 'critica_publica',
    label: 'Laporta desmiente a Tebas: Barça cumple sistema 1:1 · LaLiga puso obstáculos (2026)',
    sourceUrl: 'https://www.football-espana.net/2025/06/18/barcelona-president-joan-laporta-disputes-javier-tebas-words-over-11-rule' },
  { a: id('Alberto Núñez Feijóo'), b: id('Carles Puigdemont'), val: -85, tipo: 'oposicion_frontal',
    label: 'Feijóo propone aplicar art. 155 · Puigdemont: PP "traicionero" por bloquear catalán UE (2025)',
    sourceUrl: 'https://www.infobae.com/espana/2025/07/06/feijoo-y-puigdemont-rebajan-el-tono-por-primera-vez-tras-anos-de-ataques-mutuos-la-posible-mocion-de-censura-a-sanchez-reordena-el-tablero-politico/' },
  { a: id('CSIF'), b: id('Gobierno de España'), val: -65, tipo: 'critica_publica',
    label: 'CSIF propone movilizaciones con UGT y CCOO · 1.200M pendientes subida 0,5% (may 2026)',
    sourceUrl: 'https://www.servimedia.es/noticias/csif-propone-ugt-ccoo-una-protesta-nacional-para-exigir-gobierno-subida-salarial-funcionarios-nuevo-acuerdo/1411681845' },
  { a: id('Unai Sordo'), b: id('CEOE (Antonio Garamendi)'), val: -65, tipo: 'critica_publica',
    label: 'CCOO protesta reducir jornada 40→37,5h · patronal teme mayores costes (sep 2024)',
    sourceUrl: 'https://www.reuters.com/world/europe/unions-spain-protest-push-reduce-working-hours-2024-09-26/' },
  { a: id('Antonio Garamendi'), b: id('Gobierno de España'), val: -65, tipo: 'critica_publica',
    label: 'CEOE: Gobierno culpa siempre a empresas · corrupción ahuyenta inversores (jul 2025)',
    sourceUrl: 'https://www.infobae.com/espana/2025/07/16/garamendi-ceoe-critica-al-gobierno-por-senalar-a-las-empresas-cuando-hay-que-buscar-culpables/' },
  { a: id('Isabel Díaz Ayuso'), b: id('Alberto Núñez Feijóo'), val: -85, tipo: 'rivalidad_interna',
    label: 'Ayuso compite por liderar oposición a Sánchez · presume su gobierno como verdadero contrapeso (ene 2026)',
    sourceUrl: 'https://www.elplural.com/politica/espana/ayuso-mantiene-pulso-feijoo-liderar-frente-contra-sanchez_377877102' },
  { a: id('Yolanda Díaz'), b: id('Podemos (Ione Belarra)'), val: -75, tipo: 'critica_publica',
    label: 'Díaz apela a unidad izquierda · Belarra la ignora por diferencias política militar/vivienda (ene 2026)',
    sourceUrl: 'https://www.elindependiente.com/espana/2026/01/16/el-efecto-enero-de-yolanda-diaz-con-podemos-vuelve-a-pedir-unidad-a-una-izquierda-incompatible/' },
  { a: id('Ione Belarra'), b: id('Pedro Sánchez/PSOE'), val: -85, tipo: 'oposicion_frontal',
    label: 'Belarra: PSOE "conservador y timorato" por no intervenir oligopolio alimentario (may 2023)',
    sourceUrl: 'https://www.antena3.com/noticias/espana/belarra-apuesta-crear-supermercado-publico-capo-juan-roig_202305076457b2bb73ab380001f27b58.html' },
  { a: id('Alfonso Rueda'), b: id('Pedro Sánchez'), val: 65, tipo: 'pacto_autonomico',
    label: 'Acercamiento Xunta-Gobierno: transferencia litoral y nuevas competencias a Galicia (abr 2025)',
    sourceUrl: 'https://www.lamoncloa.gob.es/serviciosdeprensa/notasprensa/politica-territorial-memoria-democratica/paginas/2025/090425-traspaso-competencias-litoral-galicia.aspx' },
  { a: id('Antonio Garamendi'), b: id('Pedro Sánchez'), val: -65, tipo: 'critica_publica',
    label: 'Garamendi: Sánchez responsabiliza siempre a empresas · espanta inversores con corrupción (jul 2025)',
    sourceUrl: 'https://www.infobae.com/espana/2025/07/16/garamendi-ceoe-critica-al-gobierno-por-senalar-a-las-empresas-cuando-hay-que-buscar-culpables/' },
  { a: id('Unai Sordo'), b: id('Gobierno de España'), val: 20, tipo: 'rivalidad_interna',
    label: 'Sordo apoya reducir jornada pero pide al Gobierno persuadir patronal sin afectar empleo (sep 2024)',
    sourceUrl: 'https://www.reuters.com/world/europe/unions-spain-protest-push-reduce-working-hours-2024-09-26/' },
];
