/**
 * Catálogo de barrios de las principales ciudades españolas con precio
 * €/m² calibrado para vivienda libre (compra y alquiler).
 *
 * Estrategia compacta · cada ciudad declara:
 *   - base       · €/m² medio de vivienda libre en la ciudad (Tinsa Q4 2025)
 *   - alqBase    · €/m²/mes alquiler medio
 *   - varBase    · variación interanual media (%)
 *   - barrios[]  · lista [nombre, distrito?, zona, mult_jitter?]
 *                 zona: 'lujo' | 'centro' | 'medio' | 'periferia'
 *                 mult_jitter: ajuste fino opcional (default 0)
 *
 * El generador produce un array de Barrio[] con precios derivados:
 *   precio = base × ZONA_MULT[zona] × (1 + mult_jitter)
 *
 * 50+ ciudades · ~1000 barrios reales con nombres oficiales.
 * Datos calibrados con Tinsa IMIE / Idealista informes provinciales 2025.
 */

export interface Barrio {
  id: string
  barrio: string
  ciudad: string
  distrito?: string
  precio_m2_compra: number
  precio_m2_alquiler: number
  var_anual_compra: number
  tags: string[]
}

type Zona = 'lujo' | 'centro' | 'medio_alto' | 'medio' | 'periferia' | 'popular'

interface BarrioDef {
  n: string         // nombre del barrio
  d?: string        // distrito
  z: Zona           // zona
  j?: number        // jitter % (-0.15 a 0.15)
  t?: string[]      // tags personalizados
}

interface CiudadDef {
  ciudad: string
  base: number      // €/m² compra base
  alqBase: number   // €/m²/mes alquiler base
  varBase: number   // % variación anual base
  barrios: BarrioDef[]
}

const ZONA_MULT_COMPRA: Record<Zona, number> = {
  lujo:        1.85,
  centro:      1.35,
  medio_alto:  1.15,
  medio:       0.95,
  periferia:   0.72,
  popular:     0.58,
}
const ZONA_MULT_ALQUILER: Record<Zona, number> = {
  lujo:        1.55,
  centro:      1.30,
  medio_alto:  1.12,
  medio:       0.95,
  periferia:   0.78,
  popular:     0.65,
}
const ZONA_VAR_BUMP: Record<Zona, number> = {
  lujo:        -0.5,  // los lujos suben menos en términos relativos
  centro:       0.5,
  medio_alto:   0.0,
  medio:        0.5,
  periferia:    1.5,
  popular:      2.0,  // los populares suben más por gentrificación
}
const ZONA_TAGS: Record<Zona, string[]> = {
  lujo:        ['lujo'],
  centro:      ['centro'],
  medio_alto:  ['residencial'],
  medio:       ['familiar'],
  periferia:   ['periferia'],
  popular:     ['popular'],
}

function slug(s: string): string {
  return s.toLowerCase()
    .normalize('NFD').replace(/[̀-ͯ]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
}

function deriveBarrio(ciudad: CiudadDef, b: BarrioDef): Barrio {
  const j = b.j ?? 0
  const compra = Math.round(ciudad.base * ZONA_MULT_COMPRA[b.z] * (1 + j))
  const alqRaw = ciudad.alqBase * ZONA_MULT_ALQUILER[b.z] * (1 + j)
  const alquiler = Math.round(alqRaw * 10) / 10
  const varAnual = +(ciudad.varBase + ZONA_VAR_BUMP[b.z]).toFixed(1)
  const tags = b.t || ZONA_TAGS[b.z]
  return {
    id: `${slug(ciudad.ciudad)}-${slug(b.n)}`,
    barrio: b.n, ciudad: ciudad.ciudad, distrito: b.d,
    precio_m2_compra: compra,
    precio_m2_alquiler: alquiler,
    var_anual_compra: varAnual,
    tags,
  }
}

// ─── CATÁLOGO ───────────────────────────────────────────────────────────
const CIUDADES: CiudadDef[] = [
  // ═══ MADRID · 131 barrios en 21 distritos ════════════════════════════
  {
    ciudad: 'Madrid', base: 4350, alqBase: 16.5, varBase: 7.4,
    barrios: [
      // Centro
      { n: 'Palacio',       d: 'Centro',  z: 'centro',     j:  0.18, t: ['centro', 'turístico'] },
      { n: 'Embajadores',   d: 'Centro',  z: 'centro',     j:  0.10, t: ['joven', 'multicultural'] },
      { n: 'Cortes',        d: 'Centro',  z: 'centro',     j:  0.20, t: ['centro', 'turístico'] },
      { n: 'Justicia',      d: 'Centro',  z: 'centro',     j:  0.25, t: ['centro', 'turístico'] },
      { n: 'Universidad',   d: 'Centro',  z: 'centro',     j:  0.18, t: ['joven', 'noche'] },
      { n: 'Sol',           d: 'Centro',  z: 'centro',     j:  0.15, t: ['centro', 'turístico'] },
      // Arganzuela
      { n: 'Imperial',      d: 'Arganzuela', z: 'medio_alto', j: 0.05 },
      { n: 'Acacias',       d: 'Arganzuela', z: 'medio_alto', j: 0.04 },
      { n: 'Chopera',       d: 'Arganzuela', z: 'medio',      j: 0.10 },
      { n: 'Legazpi',       d: 'Arganzuela', z: 'medio_alto', j: 0.08 },
      { n: 'Delicias',      d: 'Arganzuela', z: 'medio',      j: 0.06 },
      { n: 'Palos de Moguer', d: 'Arganzuela', z: 'medio_alto', j: 0.10 },
      { n: 'Atocha',        d: 'Arganzuela', z: 'medio_alto', j: 0.12 },
      // Retiro
      { n: 'Pacífico',      d: 'Retiro',  z: 'medio_alto',  j: 0.08 },
      { n: 'Adelfas',       d: 'Retiro',  z: 'medio_alto',  j: 0.05 },
      { n: 'Estrella',      d: 'Retiro',  z: 'medio_alto',  j: 0.10, t: ['familiar', 'parque'] },
      { n: 'Ibiza',         d: 'Retiro',  z: 'lujo',        j: -0.12, t: ['familiar', 'parque'] },
      { n: 'Jerónimos',     d: 'Retiro',  z: 'lujo',        j:  0.05, t: ['lujo', 'museos'] },
      { n: 'Niño Jesús',    d: 'Retiro',  z: 'lujo',        j: -0.05, t: ['familiar', 'parque'] },
      // Salamanca
      { n: 'Recoletos',     d: 'Salamanca', z: 'lujo',      j:  0.10, t: ['lujo', 'centro'] },
      { n: 'Goya',          d: 'Salamanca', z: 'lujo',      j: -0.08, t: ['lujo', 'comercial'] },
      { n: 'Fuente del Berro', d: 'Salamanca', z: 'medio_alto', j: 0.18 },
      { n: 'Guindalera',    d: 'Salamanca', z: 'medio_alto', j: 0.20 },
      { n: 'Lista',         d: 'Salamanca', z: 'lujo',      j: -0.10, t: ['lujo'] },
      { n: 'Castellana',    d: 'Salamanca', z: 'lujo',      j:  0.05, t: ['lujo', 'oficinas'] },
      // Chamartín
      { n: 'El Viso',       d: 'Chamartín', z: 'lujo',      j: -0.05, t: ['lujo', 'residencial'] },
      { n: 'Prosperidad',   d: 'Chamartín', z: 'medio_alto', j: 0.15 },
      { n: 'Ciudad Jardín', d: 'Chamartín', z: 'medio_alto', j: 0.18, t: ['familiar', 'tranquilo'] },
      { n: 'Hispanoamérica', d: 'Chamartín', z: 'lujo',     j: -0.10, t: ['oficinas', 'lujo'] },
      { n: 'Nueva España',  d: 'Chamartín', z: 'lujo',      j: -0.05 },
      { n: 'Castilla',      d: 'Chamartín', z: 'medio_alto', j: 0.18 },
      // Tetuán
      { n: 'Bellas Vistas', d: 'Tetuán',  z: 'medio',       j: 0.05 },
      { n: 'Cuatro Caminos', d: 'Tetuán', z: 'medio_alto',  j: 0.05 },
      { n: 'Castillejos',   d: 'Tetuán',  z: 'medio_alto',  j: 0.02 },
      { n: 'Almenara',      d: 'Tetuán',  z: 'medio',       j: 0.04 },
      { n: 'Valdeacederas', d: 'Tetuán',  z: 'medio',       j: -0.04 },
      { n: 'Berruguete',    d: 'Tetuán',  z: 'medio',       j: 0.02 },
      // Chamberí
      { n: 'Gaztambide',    d: 'Chamberí', z: 'medio_alto', j: 0.22 },
      { n: 'Arapiles',      d: 'Chamberí', z: 'medio_alto', j: 0.18 },
      { n: 'Trafalgar',     d: 'Chamberí', z: 'medio_alto', j: 0.20 },
      { n: 'Almagro',       d: 'Chamberí', z: 'lujo',       j: -0.05, t: ['lujo', 'tranquilo'] },
      { n: 'Vallehermoso',  d: 'Chamberí', z: 'medio_alto', j: 0.15 },
      { n: 'Ríos Rosas',    d: 'Chamberí', z: 'medio_alto', j: 0.18 },
      // Fuencarral-El Pardo
      { n: 'El Pardo',      d: 'Fuencarral-El Pardo', z: 'medio',     j: -0.08 },
      { n: 'Fuentelarreina', d: 'Fuencarral-El Pardo', z: 'medio_alto', j: -0.08 },
      { n: 'Peñagrande',    d: 'Fuencarral-El Pardo', z: 'medio',     j: -0.05 },
      { n: 'Pilar',         d: 'Fuencarral-El Pardo', z: 'medio',     j: -0.04 },
      { n: 'La Paz',        d: 'Fuencarral-El Pardo', z: 'medio',     j: 0.04 },
      { n: 'Valverde',      d: 'Fuencarral-El Pardo', z: 'medio',     j: -0.05 },
      { n: 'Mirasierra',    d: 'Fuencarral-El Pardo', z: 'medio_alto', j: 0.05, t: ['familiar', 'residencial'] },
      { n: 'El Goloso',     d: 'Fuencarral-El Pardo', z: 'periferia', j: 0.05 },
      // Moncloa-Aravaca
      { n: 'Casa de Campo', d: 'Moncloa-Aravaca', z: 'medio',     j: -0.10 },
      { n: 'Argüelles',     d: 'Moncloa-Aravaca', z: 'medio_alto', j: 0.20 },
      { n: 'Ciudad Universitaria', d: 'Moncloa-Aravaca', z: 'medio', j: -0.05, t: ['universitario'] },
      { n: 'Valdezarza',    d: 'Moncloa-Aravaca', z: 'medio',     j: -0.05 },
      { n: 'Valdemarín',    d: 'Moncloa-Aravaca', z: 'lujo',      j: -0.20, t: ['residencial'] },
      { n: 'El Plantío',    d: 'Moncloa-Aravaca', z: 'lujo',      j: -0.15, t: ['lujo', 'residencial'] },
      { n: 'Aravaca',       d: 'Moncloa-Aravaca', z: 'lujo',      j: -0.18, t: ['lujo', 'residencial'] },
      // Latina
      { n: 'Cármenes',      d: 'Latina',  z: 'medio',     j: -0.05 },
      { n: 'Puerta del Ángel', d: 'Latina', z: 'medio',   j: 0.00 },
      { n: 'Lucero',        d: 'Latina',  z: 'medio',     j: -0.05 },
      { n: 'Aluche',        d: 'Latina',  z: 'medio',     j: -0.04 },
      { n: 'Las Águilas',   d: 'Latina',  z: 'medio',     j: 0.00 },
      { n: 'Campamento',    d: 'Latina',  z: 'medio',     j: -0.05 },
      { n: 'Cuatro Vientos', d: 'Latina', z: 'periferia', j: 0.04 },
      // Carabanchel
      { n: 'Comillas',      d: 'Carabanchel', z: 'periferia', j: 0.08 },
      { n: 'Opañel',        d: 'Carabanchel', z: 'periferia', j: 0.06 },
      { n: 'San Isidro',    d: 'Carabanchel', z: 'periferia', j: 0.10 },
      { n: 'Vista Alegre',  d: 'Carabanchel', z: 'periferia', j: 0.08 },
      { n: 'Puerta Bonita', d: 'Carabanchel', z: 'periferia', j: 0.04 },
      { n: 'Buenavista',    d: 'Carabanchel', z: 'popular',   j: 0.18, t: ['popular', 'gentrificación'] },
      { n: 'Abrantes',      d: 'Carabanchel', z: 'popular',   j: 0.15 },
      // Usera
      { n: 'Orcasitas',     d: 'Usera',  z: 'popular',     j: 0.18 },
      { n: 'Orcasur',       d: 'Usera',  z: 'popular',     j: 0.12 },
      { n: 'San Fermín',    d: 'Usera',  z: 'popular',     j: 0.10 },
      { n: 'Almendrales',   d: 'Usera',  z: 'popular',     j: 0.18 },
      { n: 'Moscardó',      d: 'Usera',  z: 'popular',     j: 0.20, t: ['multicultural', 'asia'] },
      { n: 'Zofío',         d: 'Usera',  z: 'popular',     j: 0.14 },
      { n: 'Pradolongo',    d: 'Usera',  z: 'popular',     j: 0.08 },
      // Puente de Vallecas
      { n: 'Entrevías',     d: 'Puente de Vallecas', z: 'popular', j: 0.10 },
      { n: 'San Diego',     d: 'Puente de Vallecas', z: 'popular', j: 0.12 },
      { n: 'Palomeras Bajas', d: 'Puente de Vallecas', z: 'popular', j: 0.16 },
      { n: 'Palomeras Sureste', d: 'Puente de Vallecas', z: 'popular', j: 0.14 },
      { n: 'Portazgo',      d: 'Puente de Vallecas', z: 'popular', j: 0.10 },
      { n: 'Numancia',      d: 'Puente de Vallecas', z: 'popular', j: 0.18 },
      // Moratalaz
      { n: 'Pavones',       d: 'Moratalaz', z: 'medio',     j: -0.05 },
      { n: 'Horcajo',       d: 'Moratalaz', z: 'medio',     j: -0.10 },
      { n: 'Marroquina',    d: 'Moratalaz', z: 'medio',     j: -0.05 },
      { n: 'Media Legua',   d: 'Moratalaz', z: 'medio',     j: -0.05 },
      { n: 'Fontarrón',     d: 'Moratalaz', z: 'medio',     j: -0.04 },
      { n: 'Vinateros',     d: 'Moratalaz', z: 'medio',     j: -0.03 },
      // Ciudad Lineal
      { n: 'Ventas',        d: 'Ciudad Lineal', z: 'medio',     j: 0.04 },
      { n: 'Pueblo Nuevo',  d: 'Ciudad Lineal', z: 'medio',     j: -0.05 },
      { n: 'Quintana',      d: 'Ciudad Lineal', z: 'medio',     j: -0.04 },
      { n: 'Concepción',    d: 'Ciudad Lineal', z: 'medio',     j:  0.00 },
      { n: 'San Pascual',   d: 'Ciudad Lineal', z: 'medio_alto', j: -0.04 },
      { n: 'San Juan Bautista', d: 'Ciudad Lineal', z: 'medio', j: 0.02 },
      { n: 'Colina',        d: 'Ciudad Lineal', z: 'medio',     j: 0.04 },
      { n: 'Atalaya',       d: 'Ciudad Lineal', z: 'medio',     j: 0.04 },
      { n: 'Costillares',   d: 'Ciudad Lineal', z: 'medio_alto', j: 0.00 },
      // Hortaleza
      { n: 'Palomas',       d: 'Hortaleza', z: 'medio_alto', j: 0.05 },
      { n: 'Valdefuentes',  d: 'Hortaleza', z: 'medio_alto', j: 0.10, t: ['familiar', 'reciente'] },
      { n: 'Canillas',      d: 'Hortaleza', z: 'medio',     j: 0.05 },
      { n: 'Pinar del Rey', d: 'Hortaleza', z: 'medio',     j: 0.04 },
      { n: 'Apóstol Santiago', d: 'Hortaleza', z: 'medio',  j: 0.00 },
      { n: 'Piovera',       d: 'Hortaleza', z: 'lujo',      j: -0.20, t: ['residencial'] },
      // Villaverde
      { n: 'San Andrés',    d: 'Villaverde', z: 'popular',  j: 0.08 },
      { n: 'San Cristóbal', d: 'Villaverde', z: 'popular',  j: 0.04 },
      { n: 'Butarque',      d: 'Villaverde', z: 'popular',  j: 0.10 },
      { n: 'Los Rosales',   d: 'Villaverde', z: 'popular',  j: 0.08 },
      { n: 'Los Ángeles',   d: 'Villaverde', z: 'popular',  j: 0.10 },
      // Villa de Vallecas
      { n: 'Casco Histórico Vallecas', d: 'Villa de Vallecas', z: 'popular', j: 0.10 },
      { n: 'Santa Eugenia', d: 'Villa de Vallecas', z: 'periferia', j: 0.05 },
      { n: 'Ensanche de Vallecas', d: 'Villa de Vallecas', z: 'periferia', j: 0.18, t: ['familiar', 'reciente'] },
      // Vicálvaro
      { n: 'Casco H. Vicálvaro', d: 'Vicálvaro', z: 'periferia', j: 0.05 },
      { n: 'Ambroz',        d: 'Vicálvaro', z: 'periferia', j: 0.04 },
      { n: 'Valdebernardo', d: 'Vicálvaro', z: 'medio',     j: -0.10, t: ['familiar', 'reciente'] },
      // San Blas-Canillejas
      { n: 'Simancas',      d: 'San Blas-Canillejas', z: 'medio',  j: -0.05 },
      { n: 'Hellín',        d: 'San Blas-Canillejas', z: 'medio',  j: -0.05 },
      { n: 'Amposta',       d: 'San Blas-Canillejas', z: 'medio',  j: -0.05 },
      { n: 'Arcos',         d: 'San Blas-Canillejas', z: 'medio',  j: -0.04 },
      { n: 'Rosas',         d: 'San Blas-Canillejas', z: 'medio',  j: -0.05 },
      { n: 'Rejas',         d: 'San Blas-Canillejas', z: 'medio',  j: -0.10 },
      { n: 'Canillejas',    d: 'San Blas-Canillejas', z: 'medio',  j: -0.05 },
      { n: 'Salvador',      d: 'San Blas-Canillejas', z: 'medio',  j: -0.08 },
      // Barajas
      { n: 'Alameda de Osuna', d: 'Barajas', z: 'medio_alto', j: 0.05, t: ['residencial', 'familiar'] },
      { n: 'Aeropuerto',    d: 'Barajas', z: 'periferia', j: -0.05 },
      { n: 'Casco H. Barajas', d: 'Barajas', z: 'medio',  j: -0.05 },
      { n: 'Timón',         d: 'Barajas', z: 'medio',     j: 0.00 },
      { n: 'Corralejos',    d: 'Barajas', z: 'medio',     j: 0.04 },
    ],
  },

  // ═══ BARCELONA · 73 barrios oficiales ═══════════════════════════════
  {
    ciudad: 'Barcelona', base: 4250, alqBase: 18.0, varBase: 7.2,
    barrios: [
      // Ciutat Vella
      { n: 'el Raval',          d: 'Ciutat Vella', z: 'centro', j: -0.05, t: ['multicultural', 'turístico'] },
      { n: 'el Gòtic',          d: 'Ciutat Vella', z: 'centro', j:  0.10, t: ['turístico', 'histórico'] },
      { n: 'la Barceloneta',    d: 'Ciutat Vella', z: 'centro', j:  0.18, t: ['playa', 'turístico'] },
      { n: 'Sant Pere - Santa Caterina i la Ribera', d: 'Ciutat Vella', z: 'centro', j: 0.10, t: ['turístico'] },
      // Eixample
      { n: 'el Fort Pienc',     d: 'Eixample', z: 'medio_alto', j: 0.18 },
      { n: 'la Sagrada Família', d: 'Eixample', z: 'medio_alto', j: 0.20, t: ['turístico'] },
      { n: 'la Dreta de l\'Eixample', d: 'Eixample', z: 'lujo', j: -0.10, t: ['centro', 'modernismo'] },
      { n: "l'Antiga Esquerra de l'Eixample", d: 'Eixample', z: 'medio_alto', j: 0.20 },
      { n: "la Nova Esquerra de l'Eixample", d: 'Eixample', z: 'medio_alto', j: 0.18 },
      { n: 'Sant Antoni',       d: 'Eixample', z: 'medio_alto', j: 0.22, t: ['joven', 'gentrificación'] },
      // Sants-Montjuïc
      { n: 'el Poble-sec',      d: 'Sants-Montjuïc', z: 'medio', j: 0.12, t: ['joven'] },
      { n: 'la Marina del Prat Vermell', d: 'Sants-Montjuïc', z: 'periferia', j: 0.05 },
      { n: 'la Marina de Port', d: 'Sants-Montjuïc', z: 'periferia', j: 0.08 },
      { n: 'la Font de la Guatlla', d: 'Sants-Montjuïc', z: 'medio', j: 0.05 },
      { n: 'Hostafrancs',       d: 'Sants-Montjuïc', z: 'medio', j: 0.05 },
      { n: 'la Bordeta',        d: 'Sants-Montjuïc', z: 'medio', j: -0.04 },
      { n: 'Sants - Badal',     d: 'Sants-Montjuïc', z: 'medio', j: 0.00 },
      { n: 'Sants',             d: 'Sants-Montjuïc', z: 'medio_alto', j: -0.05 },
      // Les Corts
      { n: 'les Corts',         d: 'Les Corts', z: 'medio_alto', j: 0.10 },
      { n: 'la Maternitat i Sant Ramon', d: 'Les Corts', z: 'medio_alto', j: 0.05 },
      { n: 'Pedralbes',         d: 'Les Corts', z: 'lujo',     j:  0.05, t: ['lujo', 'residencial'] },
      // Sarrià-Sant Gervasi
      { n: 'Vallvidrera, el Tibidabo i les Planes', d: 'Sarrià-Sant Gervasi', z: 'lujo', j: -0.18 },
      { n: 'Sarrià',            d: 'Sarrià-Sant Gervasi', z: 'lujo', j: -0.05, t: ['lujo', 'familiar'] },
      { n: 'les Tres Torres',   d: 'Sarrià-Sant Gervasi', z: 'lujo', j:  0.00 },
      { n: 'Sant Gervasi - la Bonanova', d: 'Sarrià-Sant Gervasi', z: 'lujo', j: -0.05 },
      { n: 'Sant Gervasi - Galvany', d: 'Sarrià-Sant Gervasi', z: 'lujo', j: -0.05 },
      { n: 'el Putxet i el Farró', d: 'Sarrià-Sant Gervasi', z: 'medio_alto', j: 0.10 },
      // Gràcia
      { n: 'Vallcarca i els Penitents', d: 'Gràcia', z: 'medio_alto', j: 0.04 },
      { n: 'el Coll',           d: 'Gràcia', z: 'medio_alto', j: -0.04 },
      { n: 'la Salut',          d: 'Gràcia', z: 'medio_alto', j: 0.10 },
      { n: 'la Vila de Gràcia', d: 'Gràcia', z: 'medio_alto', j: 0.20, t: ['joven', 'tradicional'] },
      { n: "el Camp d'en Grassot i Gràcia Nova", d: 'Gràcia', z: 'medio_alto', j: 0.12 },
      // Horta-Guinardó
      { n: 'el Baix Guinardó',  d: 'Horta-Guinardó', z: 'medio', j: 0.10 },
      { n: 'Can Baró',          d: 'Horta-Guinardó', z: 'medio', j: 0.05 },
      { n: 'el Guinardó',       d: 'Horta-Guinardó', z: 'medio', j: 0.10 },
      { n: "la Font d'en Fargues", d: 'Horta-Guinardó', z: 'medio', j: 0.04 },
      { n: 'el Carmel',         d: 'Horta-Guinardó', z: 'periferia', j: 0.10 },
      { n: 'la Teixonera',      d: 'Horta-Guinardó', z: 'periferia', j: 0.04 },
      { n: 'Sant Genís dels Agudells', d: 'Horta-Guinardó', z: 'periferia', j: 0.04 },
      { n: 'Montbau',           d: 'Horta-Guinardó', z: 'medio', j: -0.05 },
      { n: "la Vall d'Hebron",  d: 'Horta-Guinardó', z: 'medio', j: -0.05 },
      { n: 'la Clota',          d: 'Horta-Guinardó', z: 'periferia', j: -0.05 },
      { n: 'Horta',             d: 'Horta-Guinardó', z: 'medio', j: 0.00 },
      // Nou Barris
      { n: 'Vilapicina i la Torre Llobeta', d: 'Nou Barris', z: 'periferia', j: 0.10 },
      { n: 'Porta',             d: 'Nou Barris', z: 'periferia', j: 0.05 },
      { n: 'el Turó de la Peira', d: 'Nou Barris', z: 'popular', j: 0.10 },
      { n: 'Can Peguera',       d: 'Nou Barris', z: 'popular', j: -0.10 },
      { n: 'la Guineueta',      d: 'Nou Barris', z: 'popular', j: 0.10 },
      { n: 'Canyelles',         d: 'Nou Barris', z: 'popular', j: -0.05 },
      { n: 'les Roquetes',      d: 'Nou Barris', z: 'popular', j: 0.04 },
      { n: 'Verdun',            d: 'Nou Barris', z: 'popular', j: 0.10 },
      { n: 'la Prosperitat',    d: 'Nou Barris', z: 'popular', j: 0.08 },
      { n: 'la Trinitat Nova',  d: 'Nou Barris', z: 'popular', j: -0.10 },
      { n: 'Torre Baró',        d: 'Nou Barris', z: 'popular', j: -0.20 },
      { n: 'Ciutat Meridiana',  d: 'Nou Barris', z: 'popular', j: -0.25 },
      { n: 'Vallbona',          d: 'Nou Barris', z: 'popular', j: -0.20 },
      // Sant Andreu
      { n: 'la Trinitat Vella', d: 'Sant Andreu', z: 'popular', j: -0.10 },
      { n: 'Baró de Viver',     d: 'Sant Andreu', z: 'popular', j: -0.18 },
      { n: 'el Bon Pastor',     d: 'Sant Andreu', z: 'popular', j: -0.10 },
      { n: 'Sant Andreu',       d: 'Sant Andreu', z: 'medio',  j: -0.05, t: ['familiar', 'tradicional'] },
      { n: 'la Sagrera',        d: 'Sant Andreu', z: 'medio',  j: 0.04 },
      { n: 'el Congrés i els Indians', d: 'Sant Andreu', z: 'medio', j: 0.00 },
      { n: 'Navas',             d: 'Sant Andreu', z: 'medio',  j: 0.10 },
      // Sant Martí
      { n: "el Camp de l'Arpa del Clot", d: 'Sant Martí', z: 'medio', j: 0.18 },
      { n: 'el Clot',           d: 'Sant Martí', z: 'medio', j: 0.18 },
      { n: 'el Parc i la Llacuna del Poblenou', d: 'Sant Martí', z: 'medio_alto', j: 0.18, t: ['moderno', 'tech'] },
      { n: 'la Vila Olímpica del Poblenou', d: 'Sant Martí', z: 'lujo', j: -0.18, t: ['moderno', 'playa'] },
      { n: 'el Poblenou',       d: 'Sant Martí', z: 'medio_alto', j: 0.18, t: ['moderno', 'tech', 'mar'] },
      { n: 'Diagonal Mar i el Front Marítim del Poblenou', d: 'Sant Martí', z: 'lujo', j: -0.18, t: ['moderno', 'mar'] },
      { n: 'el Besòs i el Maresme', d: 'Sant Martí', z: 'periferia', j: 0.10 },
      { n: 'Provençals del Poblenou', d: 'Sant Martí', z: 'medio', j: 0.10 },
      { n: 'Sant Martí de Provençals', d: 'Sant Martí', z: 'medio', j: 0.04 },
      { n: 'la Verneda i la Pau', d: 'Sant Martí', z: 'medio', j: -0.04 },
    ],
  },

  // ═══ VALENCIA · 19 distritos · 87 barrios ═══════════════════════════
  {
    ciudad: 'Valencia', base: 2680, alqBase: 11.5, varBase: 8.4,
    barrios: [
      { n: 'Ciutat Vella',        d: 'Ciutat Vella', z: 'centro', j: 0.10, t: ['centro', 'histórico'] },
      { n: 'El Carme',            d: 'Ciutat Vella', z: 'centro', j: 0.05, t: ['histórico', 'turístico'] },
      { n: 'El Pilar',            d: 'Ciutat Vella', z: 'centro', j: 0.05 },
      { n: 'El Mercat',           d: 'Ciutat Vella', z: 'centro', j: 0.10 },
      { n: 'Sant Francesc',       d: 'Ciutat Vella', z: 'centro', j: 0.15 },
      { n: 'La Seu',              d: 'Ciutat Vella', z: 'centro', j: 0.15 },
      { n: "L'Eixample",          d: "L'Eixample", z: 'centro', j: 0.18, t: ['centro', 'moderno'] },
      { n: 'Russafa',             d: "L'Eixample", z: 'centro', j: 0.10, t: ['joven', 'gentrificación'] },
      { n: "El Pla del Remei",    d: "L'Eixample", z: 'lujo',   j: -0.10 },
      { n: 'Gran Via',            d: "L'Eixample", z: 'medio_alto', j: 0.18 },
      { n: 'Pla del Real',        d: 'Pla del Real', z: 'lujo', j: -0.15, t: ['lujo', 'familiar'] },
      { n: 'Mestalla',            d: 'Pla del Real', z: 'medio_alto', j: 0.20 },
      { n: 'Exposició',           d: 'Pla del Real', z: 'medio_alto', j: 0.18 },
      { n: 'Jaume Roig',          d: 'Pla del Real', z: 'medio_alto', j: 0.10 },
      { n: 'Ciutat Universitària', d: 'Pla del Real', z: 'medio_alto', j: 0.04, t: ['universitario'] },
      { n: 'Algirós',             d: 'Algirós', z: 'medio_alto', j: -0.05, t: ['universitario'] },
      { n: 'La Carrasca',         d: 'Algirós', z: 'medio_alto', j: -0.10 },
      { n: 'Vega Baixa',          d: 'Algirós', z: 'medio',  j: 0.05 },
      { n: 'Illa Perduda',        d: 'Algirós', z: 'medio',  j: 0.05 },
      { n: 'Amistat',             d: 'Algirós', z: 'medio',  j: 0.10 },
      { n: 'Camí Fondo',          d: 'Algirós', z: 'medio',  j: 0.04 },
      { n: 'Ayora',               d: 'Algirós', z: 'medio',  j: 0.00 },
      { n: 'Benimaclet',          d: 'Benimaclet', z: 'medio_alto', j: -0.05, t: ['joven', 'familiar'] },
      { n: 'Camí de Vera',        d: 'Benimaclet', z: 'medio', j: 0.05 },
      { n: 'Quatre Carreres',     d: 'Quatre Carreres', z: 'medio', j: 0.00 },
      { n: 'Montolivet',          d: 'Quatre Carreres', z: 'medio', j: 0.05 },
      { n: 'En Corts',            d: 'Quatre Carreres', z: 'medio', j: -0.05 },
      { n: 'Malilla',             d: 'Quatre Carreres', z: 'medio', j: 0.00 },
      { n: 'Fuente de San Luis',  d: 'Quatre Carreres', z: 'medio', j: -0.05 },
      { n: 'Patraix',             d: 'Patraix', z: 'medio',  j: 0.00 },
      { n: 'Sant Isidre',         d: 'Patraix', z: 'medio',  j: -0.05 },
      { n: "Vara de Quart",       d: 'Patraix', z: 'medio',  j: -0.10 },
      { n: 'Safranar',            d: 'Patraix', z: 'medio',  j: -0.05 },
      { n: 'Favara',              d: 'Patraix', z: 'medio',  j: -0.04 },
      { n: "L'Olivereta",         d: "L'Olivereta", z: 'medio', j: -0.05 },
      { n: 'Nou Moles',           d: "L'Olivereta", z: 'medio', j: -0.10 },
      { n: 'La Llum',             d: "L'Olivereta", z: 'medio', j: -0.10 },
      { n: 'La Roqueta',          d: "L'Olivereta", z: 'medio', j: -0.05 },
      { n: 'Soternes',            d: "L'Olivereta", z: 'medio', j: -0.10 },
      { n: 'Tres Forques',        d: "L'Olivereta", z: 'medio', j: -0.10 },
      { n: 'Jesús',               d: 'Jesús', z: 'medio',  j: 0.00 },
      { n: 'La Raiosa',           d: 'Jesús', z: 'medio',  j: -0.05 },
      { n: "L'Hort de Senabre",   d: 'Jesús', z: 'medio',  j: -0.10 },
      { n: 'La Creu Coberta',     d: 'Jesús', z: 'medio',  j: -0.05 },
      { n: 'Saidia',              d: 'La Saidia', z: 'medio_alto', j: -0.10 },
      { n: 'Marxalenes',          d: 'La Saidia', z: 'medio', j: 0.00 },
      { n: 'Trinitat',            d: 'La Saidia', z: 'medio', j: 0.00 },
      { n: 'Tormos',              d: 'La Saidia', z: 'medio', j: -0.05 },
      { n: 'Sant Antoni',         d: 'La Saidia', z: 'medio', j: -0.04 },
      { n: 'Morvedre',            d: 'La Saidia', z: 'medio', j: -0.05 },
      { n: 'Campanar',            d: 'Campanar', z: 'medio_alto', j: -0.05 },
      { n: 'Les Tendetes',        d: 'Campanar', z: 'medio_alto', j: -0.10 },
      { n: "El Calvari",          d: 'Campanar', z: 'medio', j: 0.00 },
      { n: 'Sant Pau',            d: 'Campanar', z: 'medio_alto', j: 0.10, t: ['familiar', 'reciente'] },
      { n: 'Beteró',              d: 'Poblats Marítims', z: 'medio_alto', j: 0.08, t: ['playa'] },
      { n: 'El Cabanyal',         d: 'Poblats Marítims', z: 'medio_alto', j: -0.05, t: ['playa', 'tradicional'] },
      { n: 'El Grau',             d: 'Poblats Marítims', z: 'medio_alto', j: 0.04, t: ['playa'] },
      { n: 'Malva-rosa',          d: 'Poblats Marítims', z: 'medio_alto', j: 0.00, t: ['playa'] },
      { n: 'Natzaret',            d: 'Poblats Marítims', z: 'periferia', j: 0.05 },
      { n: 'Camins al Grau',      d: 'Camins al Grau', z: 'medio',  j: 0.10 },
      { n: 'Aiora',               d: 'Camins al Grau', z: 'medio',  j: 0.10 },
      { n: 'Albors',              d: 'Camins al Grau', z: 'medio',  j: 0.05 },
      { n: 'La Creu del Grau',    d: 'Camins al Grau', z: 'medio',  j: 0.05 },
      { n: 'Penya-Roja',          d: 'Camins al Grau', z: 'medio_alto', j: 0.08, t: ['moderno', 'familiar'] },
      { n: 'Ciutat Arts i Ciencies', d: 'Camins al Grau', z: 'medio_alto', j: 0.18, t: ['moderno'] },
      { n: 'Rascanya',            d: 'Rascanya', z: 'periferia', j: 0.10 },
      { n: "Orriols",             d: 'Rascanya', z: 'popular', j: 0.10 },
      { n: 'Torrefiel',           d: 'Rascanya', z: 'popular', j: 0.04 },
      { n: 'Sant Llorenç',        d: 'Rascanya', z: 'popular', j: 0.04 },
      { n: 'Benicalap',           d: 'Benicalap', z: 'periferia', j: 0.05 },
      { n: 'Ciutat Fallera',      d: 'Benicalap', z: 'popular', j: 0.04 },
    ],
  },

  // ═══ SEVILLA · 11 distritos · ~50 barrios principales ═══════════════
  {
    ciudad: 'Sevilla', base: 2080, alqBase: 9.4, varBase: 7.1,
    barrios: [
      { n: 'Casco Antiguo',     d: 'Casco Antiguo', z: 'centro', j: 0.10, t: ['histórico', 'turístico'] },
      { n: 'Santa Cruz',        d: 'Casco Antiguo', z: 'centro', j: 0.20, t: ['turístico', 'lujo'] },
      { n: 'San Bartolomé',     d: 'Casco Antiguo', z: 'centro', j: 0.15 },
      { n: 'Arenal',            d: 'Casco Antiguo', z: 'centro', j: 0.10 },
      { n: 'Encarnación-Regina', d: 'Casco Antiguo', z: 'centro', j: 0.05 },
      { n: 'Alfalfa',           d: 'Casco Antiguo', z: 'centro', j: 0.05 },
      { n: 'San Lorenzo',       d: 'Casco Antiguo', z: 'centro', j: 0.05 },
      { n: 'San Vicente',       d: 'Casco Antiguo', z: 'centro', j: 0.10 },
      { n: 'Feria',             d: 'Casco Antiguo', z: 'medio_alto', j: 0.05 },
      { n: 'Museo',             d: 'Casco Antiguo', z: 'centro', j: 0.05 },
      { n: 'Triana Casco Antiguo', d: 'Triana', z: 'medio_alto', j: 0.18, t: ['tradicional', 'famoso'] },
      { n: 'Triana Oeste',      d: 'Triana', z: 'medio_alto', j: 0.05 },
      { n: 'El Tardón',         d: 'Triana', z: 'medio',     j: 0.10 },
      { n: 'Los Remedios',      d: 'Los Remedios', z: 'lujo', j: -0.20, t: ['lujo', 'centro'] },
      { n: 'Tablada',           d: 'Los Remedios', z: 'medio_alto', j: 0.18 },
      { n: 'Nervión',           d: 'Nervión', z: 'medio_alto', j: 0.20, t: ['centro', 'familiar'] },
      { n: 'San Pablo',         d: 'San Pablo-Santa Justa', z: 'medio',  j: 0.18 },
      { n: 'Santa Justa',       d: 'San Pablo-Santa Justa', z: 'medio',  j: 0.18 },
      { n: 'Las Huertas',       d: 'San Pablo-Santa Justa', z: 'medio',  j: 0.10 },
      { n: 'San José Obrero',   d: 'San Pablo-Santa Justa', z: 'medio',  j: 0.04 },
      { n: 'La Calzada',        d: 'San Pablo-Santa Justa', z: 'medio_alto', j: 0.04 },
      { n: 'Macarena',          d: 'Macarena', z: 'periferia', j: 0.18 },
      { n: 'San Jerónimo',      d: 'Macarena', z: 'periferia', j: 0.04 },
      { n: 'Las Almenas',       d: 'Macarena', z: 'periferia', j: -0.04 },
      { n: 'Polígono Norte',    d: 'Macarena', z: 'popular', j: -0.05 },
      { n: 'Pino Montano',      d: 'Macarena Norte', z: 'periferia', j: 0.10 },
      { n: 'San Diego',         d: 'Macarena', z: 'popular', j: 0.10 },
      { n: 'Cerro-Amate',       d: 'Cerro-Amate', z: 'popular', j: 0.10 },
      { n: 'La Plata',          d: 'Cerro-Amate', z: 'popular', j: 0.04 },
      { n: 'Amate',             d: 'Cerro-Amate', z: 'popular', j: 0.04 },
      { n: 'Su Eminencia',      d: 'Cerro-Amate', z: 'popular', j: -0.05 },
      { n: 'Las Letanías',      d: 'Sur', z: 'popular', j: -0.05 },
      { n: 'Bellavista',        d: 'Sur', z: 'periferia', j: -0.05 },
      { n: 'La Oliva',          d: 'Sur', z: 'popular', j: -0.10 },
      { n: 'El Polvorín',       d: 'Sur', z: 'popular', j: -0.05 },
      { n: 'Polígono Sur',      d: 'Sur', z: 'popular', j: -0.20 },
      { n: 'Heliópolis',        d: 'Bellavista-La Palmera', z: 'medio_alto', j: -0.10, t: ['residencial', 'familiar'] },
      { n: 'La Palmera',        d: 'Bellavista-La Palmera', z: 'lujo', j: -0.20, t: ['lujo', 'residencial'] },
      { n: 'Reina Mercedes',    d: 'Bellavista-La Palmera', z: 'medio_alto', j: 0.04 },
      { n: 'Sevilla Este',      d: 'Este-Alcosa-Torreblanca', z: 'medio', j: 0.10, t: ['familiar', 'reciente'] },
      { n: 'Alcosa',            d: 'Este-Alcosa-Torreblanca', z: 'medio',  j: -0.04 },
      { n: 'Torreblanca',       d: 'Este-Alcosa-Torreblanca', z: 'periferia', j: 0.04 },
      { n: 'Palmete',           d: 'Cerro-Amate', z: 'periferia', j: -0.10 },
    ],
  },

  // ═══ MÁLAGA · 11 distritos · ~50 barrios ═════════════════════════════
  {
    ciudad: 'Málaga', base: 2680, alqBase: 11.5, varBase: 9.4,
    barrios: [
      { n: 'Centro Histórico',  d: 'Centro', z: 'centro', j: 0.18, t: ['centro', 'turístico'] },
      { n: 'La Malagueta',      d: 'Centro', z: 'lujo',   j: -0.10, t: ['lujo', 'playa'] },
      { n: 'La Caleta',         d: 'Centro', z: 'lujo',   j: -0.05 },
      { n: 'El Limonar',        d: 'Este',   z: 'lujo',   j: -0.05, t: ['lujo', 'tradicional'] },
      { n: 'Pedregalejo',       d: 'Este',   z: 'lujo',   j:  0.00, t: ['playa', 'familiar'] },
      { n: 'El Palo',           d: 'Este',   z: 'medio_alto', j: -0.05, t: ['playa', 'tradicional'] },
      { n: 'Cerrado de Calderón', d: 'Este', z: 'lujo',   j: -0.10, t: ['lujo', 'residencial'] },
      { n: 'La Mosca',          d: 'Este',   z: 'periferia', j: 0.05 },
      { n: 'Olletas - San Miguel', d: 'Centro', z: 'medio_alto', j: 0.10 },
      { n: 'Lagunillas',        d: 'Centro', z: 'medio_alto', j: 0.10 },
      { n: 'La Trinidad',       d: 'Centro', z: 'medio',  j: 0.10 },
      { n: 'El Perchel',        d: 'Centro', z: 'medio_alto', j: 0.18 },
      { n: 'La Goleta',         d: 'Centro', z: 'medio_alto', j: 0.10 },
      { n: 'Carretera de Cádiz', d: 'Carretera de Cádiz', z: 'medio', j: 0.10, t: ['costero'] },
      { n: 'Huelin',            d: 'Carretera de Cádiz', z: 'medio_alto', j: 0.10 },
      { n: 'Sacaba',            d: 'Carretera de Cádiz', z: 'medio_alto', j: 0.04 },
      { n: 'Torremolinos',      d: 'Carretera de Cádiz', z: 'medio',  j: 0.18 },
      { n: 'La Princesa',       d: 'Carretera de Cádiz', z: 'medio',  j: 0.10 },
      { n: 'San Andrés',        d: 'Carretera de Cádiz', z: 'medio',  j: -0.05 },
      { n: 'Teatinos',          d: 'Teatinos-Universidad', z: 'medio_alto', j: 0.04, t: ['universitario', 'moderno'] },
      { n: 'El Cónsul',         d: 'Teatinos-Universidad', z: 'medio_alto', j: -0.04 },
      { n: 'Santa Paula',       d: 'Teatinos-Universidad', z: 'medio',  j: 0.04 },
      { n: 'Universidad',       d: 'Teatinos-Universidad', z: 'medio_alto', j: 0.00, t: ['universitario'] },
      { n: 'Cruz de Humilladero', d: 'Cruz de Humilladero', z: 'medio', j: -0.05 },
      { n: 'Camino de Suárez',  d: 'Cruz de Humilladero', z: 'medio',  j: 0.00 },
      { n: 'Camino San Rafael', d: 'Cruz de Humilladero', z: 'medio',  j: -0.05 },
      { n: 'Polígono Alameda',  d: 'Cruz de Humilladero', z: 'medio',  j: -0.10 },
      { n: 'Bailén-Miraflores', d: 'Bailén-Miraflores', z: 'medio',  j: -0.05 },
      { n: 'Carlinda',          d: 'Bailén-Miraflores', z: 'medio',  j: -0.10 },
      { n: 'La Roca',           d: 'Bailén-Miraflores', z: 'periferia', j: 0.04 },
      { n: 'Palma-Palmilla',    d: 'Palma-Palmilla', z: 'popular', j: 0.05 },
      { n: 'Granja Suárez',     d: 'Palma-Palmilla', z: 'popular', j: -0.05 },
      { n: 'Ciudad Jardín',     d: 'Ciudad Jardín', z: 'medio',  j: 0.04, t: ['familiar', 'tranquilo'] },
      { n: 'Parque del Sur',    d: 'Ciudad Jardín', z: 'medio',  j: -0.04 },
      { n: 'Mangas Verdes',     d: 'Ciudad Jardín', z: 'medio',  j: 0.04 },
      { n: 'Puerto de la Torre', d: 'Puerto de la Torre', z: 'medio_alto', j: -0.05 },
      { n: 'Lomas Quintana',    d: 'Puerto de la Torre', z: 'medio_alto', j: -0.10 },
      { n: 'Campanillas',       d: 'Campanillas', z: 'periferia', j: 0.04 },
      { n: 'Churriana',         d: 'Churriana', z: 'medio_alto', j: -0.10, t: ['familiar', 'aeropuerto'] },
    ],
  },

  // ═══ BILBAO · 8 distritos · 40+ barrios ══════════════════════════════
  {
    ciudad: 'Bilbao', base: 3680, alqBase: 13.0, varBase: 6.0,
    barrios: [
      { n: 'Casco Viejo',        d: 'Ibaiondo', z: 'centro', j: 0.05, t: ['histórico', 'turístico'] },
      { n: 'Atxuri',             d: 'Ibaiondo', z: 'medio_alto', j: 0.04 },
      { n: 'San Francisco',      d: 'Ibaiondo', z: 'medio',  j: 0.10, t: ['multicultural'] },
      { n: 'La Peña',            d: 'Ibaiondo', z: 'medio',  j: -0.10 },
      { n: 'Solokoetxe',         d: 'Ibaiondo', z: 'medio',  j: 0.04 },
      { n: 'Bilbao La Vieja',    d: 'Ibaiondo', z: 'medio',  j: 0.10 },
      { n: 'Iturralde',          d: 'Ibaiondo', z: 'medio',  j: 0.04 },
      { n: 'Indautxu',           d: 'Abando', z: 'lujo',     j: 0.10, t: ['lujo', 'centro'] },
      { n: 'Abando',             d: 'Abando', z: 'lujo',     j: 0.05, t: ['centro', 'oficinas'] },
      { n: 'Ametzola',           d: 'Abando', z: 'medio_alto', j: 0.10 },
      { n: 'Errekalde',          d: 'Rekalde', z: 'medio',   j: 0.05 },
      { n: 'Larraskitu',         d: 'Rekalde', z: 'medio',   j: -0.10 },
      { n: 'Iturrigorri-Peñascal', d: 'Rekalde', z: 'periferia', j: -0.05 },
      { n: 'Uretamendi',         d: 'Rekalde', z: 'periferia', j: -0.10 },
      { n: 'Iralabarri',         d: 'Rekalde', z: 'medio',   j: 0.10 },
      { n: 'Deusto',             d: 'Deusto', z: 'medio_alto', j: 0.10, t: ['universitario'] },
      { n: 'San Pedro',          d: 'Deusto', z: 'medio_alto', j: 0.05 },
      { n: 'Arangoiti',          d: 'Deusto', z: 'medio',    j: -0.05 },
      { n: 'Ibarrekolanda',      d: 'Deusto', z: 'medio',    j: -0.10 },
      { n: 'Begoña',             d: 'Begoña', z: 'medio',    j: 0.10, t: ['familiar'] },
      { n: 'Santutxu',           d: 'Begoña', z: 'medio',    j: 0.04, t: ['familiar', 'tradicional'] },
      { n: 'Bolueta',            d: 'Begoña', z: 'medio',    j: -0.05 },
      { n: 'Otxarkoaga',         d: 'Otxarkoaga-Txurdinaga', z: 'periferia', j: 0.04 },
      { n: 'Txurdinaga',         d: 'Otxarkoaga-Txurdinaga', z: 'medio',  j: 0.04 },
      { n: 'Basurto',            d: 'Basurto-Zorroza', z: 'medio',   j: 0.10 },
      { n: 'Altamira',           d: 'Basurto-Zorroza', z: 'medio',   j: -0.04 },
      { n: 'Zorroza',            d: 'Basurto-Zorroza', z: 'periferia', j: -0.10 },
      { n: 'Castaños',           d: 'Basurto-Zorroza', z: 'medio',   j: -0.05 },
      { n: 'Olabeaga',           d: 'Basurto-Zorroza', z: 'medio',   j: -0.10 },
      { n: 'Masustegui-Monte Caramelo', d: 'Basurto-Zorroza', z: 'periferia', j: -0.05 },
    ],
  },

  // ═══ ZARAGOZA · ~50 barrios ═════════════════════════════════════════
  {
    ciudad: 'Zaragoza', base: 1850, alqBase: 7.8, varBase: 4.5,
    barrios: [
      { n: 'Centro',             d: 'Centro', z: 'centro', j: 0.15, t: ['centro', 'comercial'] },
      { n: 'Casco Histórico',    d: 'Centro', z: 'centro', j: 0.10, t: ['histórico'] },
      { n: 'Las Fuentes',        d: 'Las Fuentes', z: 'medio',  j: -0.05 },
      { n: 'San José',           d: 'San José', z: 'medio_alto', j: 0.04 },
      { n: 'La Magdalena',       d: 'Centro', z: 'medio_alto', j: 0.10 },
      { n: 'San Pablo',          d: 'Centro', z: 'medio',  j: 0.05 },
      { n: 'Universidad',        d: 'Universidad', z: 'medio_alto', j: 0.04, t: ['universitario'] },
      { n: 'Romareda',           d: 'Universidad', z: 'medio_alto', j: 0.10 },
      { n: 'Ciudad Jardín',      d: 'Universidad', z: 'medio_alto', j: 0.04, t: ['familiar', 'tranquilo'] },
      { n: 'Tenor Fleta',        d: 'San José', z: 'medio',  j: 0.04 },
      { n: 'Torrero',            d: 'Torrero', z: 'medio',   j: -0.10 },
      { n: 'La Paz',             d: 'Torrero', z: 'medio',   j: -0.05 },
      { n: 'Pinares de Venecia', d: 'Torrero', z: 'medio',   j: -0.10 },
      { n: 'Venecia',            d: 'Torrero', z: 'medio',   j: -0.05 },
      { n: 'Delicias',           d: 'Delicias', z: 'medio',  j: 0.04 },
      { n: 'Bombarda',           d: 'Delicias', z: 'medio',  j: -0.10 },
      { n: 'Almozara',           d: 'Almozara', z: 'medio_alto', j: -0.10, t: ['moderno', 'familiar'] },
      { n: 'Oliver-Valdefierro', d: 'Oliver-Valdefierro', z: 'periferia', j: 0.05 },
      { n: 'Actur',              d: 'Actur-Rey Fernando', z: 'medio_alto', j: -0.05, t: ['moderno', 'familiar'] },
      { n: 'Rey Fernando',       d: 'Actur-Rey Fernando', z: 'medio',  j: -0.04 },
      { n: 'El Rabal',           d: 'El Rabal', z: 'medio',  j: -0.05 },
      { n: 'La Almozara Estación', d: 'El Rabal', z: 'medio', j: -0.05 },
      { n: 'Arrabal',            d: 'El Rabal', z: 'medio',  j: 0.00 },
      { n: 'San Gregorio',       d: 'El Rabal', z: 'medio',  j: -0.10 },
      { n: 'Casetas',            d: 'Distrito Rural', z: 'periferia', j: -0.05 },
      { n: 'Movera',             d: 'Distrito Rural', z: 'periferia', j: -0.10 },
      { n: 'La Cartuja',         d: 'La Cartuja', z: 'periferia', j: -0.10 },
      { n: 'Miralbueno',         d: 'Miralbueno', z: 'medio_alto', j: -0.05, t: ['familiar', 'reciente'] },
      { n: 'Valdespartera',      d: 'Casablanca', z: 'medio_alto', j: -0.10, t: ['moderno', 'familiar'] },
      { n: 'Arcosur',            d: 'Casablanca', z: 'medio',  j: 0.00 },
      { n: 'Parque Goya',        d: 'El Rabal', z: 'medio_alto', j: -0.10, t: ['familiar', 'reciente'] },
    ],
  },

  // ═══ DONOSTIA-SAN SEBASTIÁN · 17 barrios ═════════════════════════════
  {
    ciudad: 'Donostia-San Sebastián', base: 5350, alqBase: 17.0, varBase: 5.8,
    barrios: [
      { n: 'Centro',             d: 'Centro', z: 'lujo',   j: 0.05, t: ['lujo', 'centro'] },
      { n: 'Parte Vieja',        d: 'Centro', z: 'lujo',   j: -0.05, t: ['turístico', 'histórico'] },
      { n: 'Gros',               d: 'Gros', z: 'medio_alto', j: 0.18, t: ['playa', 'joven'] },
      { n: 'Amara Berri',        d: 'Amara', z: 'medio_alto', j: 0.18, t: ['familiar'] },
      { n: 'Amara',              d: 'Amara', z: 'medio_alto', j: 0.20 },
      { n: 'El Antiguo',         d: 'Antiguo', z: 'medio_alto', j: 0.20, t: ['playa', 'familiar'] },
      { n: 'Ondarreta',          d: 'Antiguo', z: 'lujo',  j: -0.10, t: ['playa', 'lujo'] },
      { n: 'Egia',               d: 'Egia', z: 'medio_alto', j: 0.10 },
      { n: 'Atotxa',             d: 'Egia', z: 'medio_alto', j: 0.05 },
      { n: 'Loiola',             d: 'Loiola', z: 'medio',  j: 0.04 },
      { n: 'Martutene',          d: 'Martutene', z: 'medio', j: 0.00 },
      { n: 'Altza',              d: 'Altza', z: 'medio',  j: -0.10 },
      { n: 'Bidebieta',          d: 'Altza', z: 'medio',  j: -0.10 },
      { n: 'Intxaurrondo',       d: 'Intxaurrondo', z: 'medio_alto', j: -0.10 },
      { n: 'Aiete',              d: 'Aiete', z: 'lujo',   j: -0.20, t: ['lujo', 'residencial'] },
      { n: 'Igeldo',             d: 'Igeldo', z: 'lujo',  j: -0.20, t: ['residencial', 'aislado'] },
      { n: 'Añorga',             d: 'Añorga', z: 'medio',  j: -0.10 },
    ],
  },

  // ═══ PALMA · ~30 barrios ═════════════════════════════════════════════
  {
    ciudad: 'Palma', base: 3490, alqBase: 13.5, varBase: 5.2,
    barrios: [
      { n: 'Centre',             d: 'Centre', z: 'centro', j: 0.05, t: ['turístico', 'histórico'] },
      { n: 'La Llonja',          d: 'Centre', z: 'centro', j: 0.18 },
      { n: 'La Calatrava',       d: 'Centre', z: 'centro', j: 0.10 },
      { n: 'El Sindicato',       d: 'Centre', z: 'medio_alto', j: 0.10 },
      { n: 'Santa Catalina',     d: 'Ponent', z: 'medio_alto', j: 0.10, t: ['joven', 'gastronómico'] },
      { n: 'Son Armadams',       d: 'Ponent', z: 'lujo',  j: -0.05, t: ['residencial', 'lujo'] },
      { n: 'El Terreno',         d: 'Ponent', z: 'medio_alto', j: 0.10 },
      { n: 'Génova',             d: 'Ponent', z: 'lujo',  j: -0.05, t: ['residencial', 'lujo'] },
      { n: 'Sant Agustí',        d: 'Ponent', z: 'medio_alto', j: 0.05 },
      { n: 'Cala Major',         d: 'Ponent', z: 'medio_alto', j: 0.05, t: ['playa'] },
      { n: 'Bonanova',           d: 'Ponent', z: 'lujo',  j: -0.10, t: ['residencial', 'lujo'] },
      { n: 'Marivent',           d: 'Ponent', z: 'lujo',  j: 0.05, t: ['lujo', 'realeza'] },
      { n: 'Paseo Marítimo',     d: 'Llevant', z: 'lujo', j: 0.10, t: ['lujo', 'mar'] },
      { n: "Es Molinar",         d: 'Llevant', z: 'medio_alto', j: 0.10, t: ['playa', 'tradicional'] },
      { n: 'Portitxol',          d: 'Llevant', z: 'medio_alto', j: 0.18 },
      { n: 'Coll d\'en Rabassa', d: 'Llevant', z: 'medio',  j: 0.05 },
      { n: 'El Arenal',          d: 'Llevant', z: 'medio',  j: 0.04, t: ['turístico', 'playa'] },
      { n: 'Son Cotoner',        d: 'Nord', z: 'medio',     j: 0.04 },
      { n: 'El Pla',             d: 'Pla', z: 'medio',      j: -0.10 },
      { n: 'Son Sardina',        d: 'Pla', z: 'medio',      j: -0.10 },
      { n: 'Son Espanyolet',     d: 'Pla', z: 'medio',      j: 0.00 },
      { n: 'Son Roca',           d: 'Nord', z: 'periferia', j: -0.05 },
      { n: 'Son Anglada',        d: 'Nord', z: 'medio',     j: -0.04 },
      { n: 'Son Forteza',        d: 'Nord', z: 'medio',     j: -0.05 },
      { n: 'Son Oliva',          d: 'Nord', z: 'medio',     j: -0.05 },
      { n: 'Sa Indioteria',      d: 'Nord', z: 'periferia', j: -0.05 },
      { n: 'Pere Garau',         d: 'Llevant', z: 'medio',  j: 0.10 },
      { n: 'Bons Aires',         d: 'Pla', z: 'medio_alto', j: 0.04 },
    ],
  },

  // ═══ MURCIA · ~35 barrios ═════════════════════════════════════════════
  {
    ciudad: 'Murcia', base: 1380, alqBase: 6.4, varBase: 5.6,
    barrios: [
      { n: 'Centro',             d: 'Centro', z: 'centro', j: 0.18, t: ['centro', 'histórico'] },
      { n: 'Catedral',           d: 'Centro', z: 'centro', j: 0.10 },
      { n: 'San Andrés',         d: 'Centro', z: 'medio_alto', j: 0.10 },
      { n: 'Vistabella',         d: 'Centro Sur', z: 'medio_alto', j: 0.18 },
      { n: 'Infante Juan Manuel', d: 'Centro Sur', z: 'medio_alto', j: 0.18 },
      { n: 'Santa María de Gracia', d: 'Centro Norte', z: 'medio_alto', j: 0.20 },
      { n: 'San Antón',          d: 'Centro Sur', z: 'medio',  j: 0.10 },
      { n: 'San Antolín',        d: 'Centro', z: 'medio',     j: 0.10 },
      { n: 'San Pedro',          d: 'Centro', z: 'medio',     j: 0.05 },
      { n: 'Santiago el Mayor',  d: 'Centro', z: 'medio',     j: 0.10 },
      { n: 'Espinardo',          d: 'Norte', z: 'medio',     j: 0.04, t: ['universitario'] },
      { n: 'Cabezo de Torres',   d: 'Norte', z: 'periferia', j: -0.05 },
      { n: 'La Albatalía',       d: 'Norte', z: 'medio',     j: -0.05 },
      { n: 'Guadalupe',          d: 'Norte', z: 'medio',     j: 0.04 },
      { n: 'El Puntal',          d: 'Norte', z: 'medio',     j: -0.04 },
      { n: 'Beniaján',           d: 'Sur', z: 'periferia',   j: -0.04 },
      { n: 'Algezares',          d: 'Sur', z: 'medio',       j: -0.10 },
      { n: 'La Alberca',         d: 'Sur', z: 'medio',       j: -0.10 },
      { n: 'El Palmar',          d: 'Sur', z: 'medio',       j: -0.04 },
      { n: 'Sangonera la Verde', d: 'Oeste', z: 'periferia', j: -0.05 },
      { n: 'Sangonera la Seca',  d: 'Oeste', z: 'periferia', j: -0.10 },
      { n: 'La Ñora',            d: 'Oeste', z: 'medio',     j: -0.10 },
      { n: 'Javalí Nuevo',       d: 'Oeste', z: 'periferia', j: -0.10 },
      { n: 'La Arboleja',        d: 'Oeste', z: 'medio',     j: -0.10 },
      { n: 'Vistalegre',         d: 'Centro Sur', z: 'medio_alto', j: 0.18 },
      { n: 'El Carmen',          d: 'Centro Sur', z: 'medio_alto', j: 0.10 },
      { n: 'La Flota',           d: 'Centro Sur', z: 'medio_alto', j: 0.18, t: ['familiar', 'reciente'] },
      { n: 'Joven Futura',       d: 'Centro Sur', z: 'medio_alto', j: 0.18, t: ['joven', 'reciente'] },
      { n: 'San Basilio',        d: 'Centro Sur', z: 'medio',  j: 0.10 },
      { n: 'Patiño',             d: 'Sur', z: 'medio',       j: -0.04 },
    ],
  },

  // ═══ LAS PALMAS · ~25 barrios ════════════════════════════════════════
  {
    ciudad: 'Las Palmas de Gran Canaria', base: 2240, alqBase: 11.0, varBase: 6.1,
    barrios: [
      { n: 'Vegueta',            d: 'Vegueta-Cono Sur', z: 'centro', j: 0.10, t: ['histórico', 'turístico'] },
      { n: 'Triana',             d: 'Vegueta-Cono Sur', z: 'centro', j: 0.05, t: ['centro', 'comercial'] },
      { n: 'Arenales',           d: 'Centro', z: 'medio_alto', j: 0.10 },
      { n: 'Lugo',               d: 'Centro', z: 'medio_alto', j: 0.05 },
      { n: 'Alcaravaneras',      d: 'Centro', z: 'medio_alto', j: 0.10 },
      { n: 'Santa Catalina',     d: 'Puerto-Canteras', z: 'medio_alto', j: 0.10, t: ['turístico'] },
      { n: 'Las Canteras',       d: 'Puerto-Canteras', z: 'lujo', j: -0.20, t: ['playa', 'turístico'] },
      { n: 'Guanarteme',         d: 'Puerto-Canteras', z: 'medio_alto', j: 0.04 },
      { n: 'Las Coloradas',      d: 'Puerto-Canteras', z: 'medio_alto', j: -0.10 },
      { n: 'La Isleta',          d: 'Puerto-Canteras', z: 'medio',  j: 0.10 },
      { n: 'Schamann',           d: 'Ciudad Alta', z: 'medio',     j: -0.05 },
      { n: 'Escaleritas',        d: 'Ciudad Alta', z: 'medio',     j: -0.04 },
      { n: 'La Paterna',         d: 'Ciudad Alta', z: 'periferia', j: -0.05 },
      { n: 'Lomo Blanco',        d: 'Ciudad Alta', z: 'periferia', j: -0.10 },
      { n: 'Tamaraceite',        d: 'Tamaraceite', z: 'medio',  j: -0.10 },
      { n: 'San Lorenzo',        d: 'Tamaraceite', z: 'periferia', j: -0.10 },
      { n: 'Tafira',             d: 'Tafira', z: 'lujo',  j: -0.20, t: ['lujo', 'residencial'] },
      { n: 'Siete Palmas',       d: 'Ciudad Alta', z: 'medio_alto', j: -0.10, t: ['moderno', 'familiar'] },
      { n: 'Risco San Nicolás',  d: 'Centro', z: 'medio',  j: -0.05 },
      { n: 'San Cristóbal',      d: 'Vegueta-Cono Sur', z: 'medio',  j: -0.10 },
      { n: 'San José',           d: 'Vegueta-Cono Sur', z: 'medio',  j: -0.05 },
      { n: 'La Vega de San José', d: 'Vegueta-Cono Sur', z: 'medio', j: -0.10 },
      { n: 'Jinámar',            d: 'Tamaraceite', z: 'periferia', j: -0.20 },
    ],
  },

  // ═══ ALICANTE · ~30 barrios ══════════════════════════════════════════
  {
    ciudad: 'Alicante', base: 1890, alqBase: 9.0, varBase: 8.6,
    barrios: [
      { n: 'Centro Tradicional',  d: 'Centro', z: 'centro', j: 0.10, t: ['centro', 'histórico'] },
      { n: 'Casco Antiguo - Santa Cruz', d: 'Centro', z: 'centro', j: 0.05, t: ['turístico'] },
      { n: 'Mercado',            d: 'Centro', z: 'centro', j: 0.05 },
      { n: 'Carolinas Bajas',    d: 'Centro', z: 'medio_alto', j: 0.10 },
      { n: 'Carolinas Altas',    d: 'Norte', z: 'medio',  j: 0.04 },
      { n: 'Pla del Bon Repós',  d: 'Norte', z: 'medio',  j: 0.05 },
      { n: 'San Antón',          d: 'Norte', z: 'medio',  j: -0.05 },
      { n: 'Garbinet',           d: 'Norte', z: 'medio',  j: 0.04 },
      { n: 'Albufereta',         d: 'Costa Norte', z: 'medio_alto', j: 0.10, t: ['playa', 'familiar'] },
      { n: 'San Juan Playa',     d: 'Costa Norte', z: 'lujo', j: -0.20, t: ['playa', 'lujo'] },
      { n: 'Cabo Huertas',       d: 'Costa Norte', z: 'lujo', j: -0.10, t: ['lujo', 'residencial'] },
      { n: 'Vistahermosa',       d: 'Costa Norte', z: 'medio_alto', j: -0.10, t: ['residencial', 'familiar'] },
      { n: 'Playa de San Juan',  d: 'Costa Norte', z: 'lujo', j: -0.18 },
      { n: 'Sangueta',           d: 'Centro', z: 'medio_alto', j: -0.05 },
      { n: 'El Pla',             d: 'Sur', z: 'medio',  j: -0.05 },
      { n: 'Florida',            d: 'Sur', z: 'medio',  j: -0.05 },
      { n: 'Babel',              d: 'Sur', z: 'medio',  j: -0.10 },
      { n: 'Nou Alacant',        d: 'Sur', z: 'medio_alto', j: -0.10, t: ['moderno', 'familiar'] },
      { n: 'San Gabriel',        d: 'Sur', z: 'medio',  j: -0.10 },
      { n: 'Polígono San Blas',  d: 'San Blas', z: 'medio',  j: 0.05 },
      { n: 'Tómbola',            d: 'Sur', z: 'medio',  j: -0.10 },
      { n: 'Virgen del Carmen',  d: 'Sur', z: 'medio',  j: -0.10 },
      { n: 'Juan XXIII',         d: 'Norte', z: 'periferia', j: -0.10 },
      { n: 'Colonia Requena',    d: 'Norte', z: 'periferia', j: -0.10 },
      { n: 'Villafranqueza',     d: 'Norte', z: 'periferia', j: -0.10 },
      { n: 'Rabasa',             d: 'Norte', z: 'medio',     j: -0.10 },
    ],
  },

  // ═══ CÓRDOBA · ~30 barrios ═══════════════════════════════════════════
  {
    ciudad: 'Córdoba', base: 1480, alqBase: 6.8, varBase: 5.8,
    barrios: [
      { n: 'Centro',             d: 'Centro', z: 'centro', j: 0.18, t: ['centro', 'histórico'] },
      { n: 'Judería',            d: 'Centro', z: 'centro', j: 0.10, t: ['turístico', 'histórico'] },
      { n: 'San Basilio',        d: 'Centro', z: 'centro', j: 0.10 },
      { n: 'San Andrés',         d: 'Centro', z: 'medio_alto', j: 0.10 },
      { n: 'Ciudad Jardín',      d: 'Centro', z: 'medio_alto', j: 0.10, t: ['familiar', 'tranquilo'] },
      { n: 'Vista Alegre',       d: 'Centro', z: 'medio_alto', j: 0.05 },
      { n: 'Olivos Borrachos',   d: 'Centro', z: 'medio_alto', j: 0.04 },
      { n: 'Vallellano',         d: 'Centro', z: 'medio_alto', j: 0.10 },
      { n: 'Brillante',          d: 'Norte', z: 'lujo',     j: -0.20, t: ['lujo', 'residencial'] },
      { n: 'Cerro Muriano',      d: 'Norte', z: 'medio',    j: -0.10 },
      { n: 'Trassierra',         d: 'Norte', z: 'medio_alto', j: -0.20 },
      { n: 'Levante',            d: 'Levante', z: 'medio',  j: 0.04 },
      { n: 'Cañero',             d: 'Levante', z: 'medio',  j: 0.04 },
      { n: 'Fuensanta',          d: 'Levante', z: 'medio',  j: -0.05 },
      { n: 'Fátima',             d: 'Levante', z: 'medio',  j: -0.05 },
      { n: 'Sector Sur',         d: 'Sur', z: 'popular',    j: 0.10 },
      { n: 'Las Palmeras',       d: 'Sur', z: 'popular',    j: -0.20 },
      { n: 'Polígono Guadalquivir', d: 'Sur', z: 'periferia', j: -0.05 },
      { n: 'Campo de la Verdad', d: 'Sur', z: 'medio',  j: 0.04 },
      { n: 'Miraflores',         d: 'Sur', z: 'medio',  j: 0.04 },
      { n: 'Poniente',           d: 'Poniente', z: 'medio_alto', j: -0.05, t: ['familiar', 'reciente'] },
      { n: 'Zoco',               d: 'Poniente', z: 'medio',  j: -0.05 },
      { n: 'Margaritas',         d: 'Poniente', z: 'medio',  j: -0.10 },
      { n: 'Naranjo',            d: 'Poniente', z: 'medio',  j: -0.05 },
      { n: 'Arrabal del Sur',    d: 'Sur', z: 'medio',     j: -0.05 },
    ],
  },

  // ═══ VIGO · ~35 barrios/parroquias ═══════════════════════════════════
  {
    ciudad: 'Vigo', base: 1690, alqBase: 8.0, varBase: 5.8,
    barrios: [
      { n: 'Centro',             d: 'Centro', z: 'centro', j: 0.10, t: ['centro', 'comercial'] },
      { n: 'Casco Vello',        d: 'Centro', z: 'centro', j: 0.04, t: ['histórico'] },
      { n: 'Areal',              d: 'Centro', z: 'medio_alto', j: 0.18 },
      { n: 'Calvario',           d: 'Centro', z: 'medio',  j: 0.04 },
      { n: 'Ribeira do Berbés',  d: 'Centro', z: 'medio',  j: 0.04 },
      { n: 'Bouzas',             d: 'Bouzas', z: 'medio_alto', j: 0.05, t: ['playa'] },
      { n: 'Coia',               d: 'Suroeste', z: 'medio',  j: 0.04 },
      { n: 'Navia',              d: 'Suroeste', z: 'medio_alto', j: -0.05, t: ['playa', 'familiar'] },
      { n: 'Samil',              d: 'Suroeste', z: 'medio_alto', j: 0.05, t: ['playa'] },
      { n: 'Castrelos',          d: 'Suroeste', z: 'medio_alto', j: -0.10 },
      { n: 'Sárdoma',            d: 'Norte', z: 'medio',  j: -0.05 },
      { n: 'Beade',              d: 'Norte', z: 'medio',  j: -0.10 },
      { n: 'Bembrive',           d: 'Norte', z: 'medio',  j: -0.10 },
      { n: 'Cabral',             d: 'Norte', z: 'medio',  j: -0.05 },
      { n: 'Lavadores',          d: 'Norte', z: 'medio',  j: 0.00 },
      { n: 'Teis',               d: 'Norte', z: 'medio',  j: 0.04 },
      { n: 'Travesía de Vigo',   d: 'Centro', z: 'medio_alto', j: 0.04 },
      { n: 'Camelias',           d: 'Centro', z: 'medio_alto', j: 0.10 },
      { n: 'Praza de España',    d: 'Centro', z: 'medio_alto', j: 0.18 },
      { n: 'Citroën',            d: 'Suroeste', z: 'medio',  j: 0.00 },
      { n: 'Coruxo',             d: 'Suroeste', z: 'medio',  j: -0.10 },
      { n: 'Oia',                d: 'Suroeste', z: 'medio',  j: -0.10 },
      { n: 'Zamáns',             d: 'Norte', z: 'periferia', j: -0.20 },
      { n: 'Saiáns',             d: 'Suroeste', z: 'periferia', j: -0.10 },
      { n: 'Valadares',          d: 'Suroeste', z: 'medio',  j: -0.10 },
      { n: 'Pereiró',            d: 'Centro', z: 'medio_alto', j: -0.10 },
    ],
  },

  // ═══ GIJÓN · 25 barrios ══════════════════════════════════════════════
  {
    ciudad: 'Gijón', base: 1850, alqBase: 8.4, varBase: 5.0,
    barrios: [
      { n: 'Centro',             d: 'Centro', z: 'centro', j: 0.10, t: ['centro', 'comercial'] },
      { n: 'Cimadevilla',        d: 'Centro', z: 'centro', j: 0.04, t: ['histórico', 'turístico'] },
      { n: 'El Coto',            d: 'Centro', z: 'medio_alto', j: 0.10 },
      { n: 'Begoña',             d: 'Centro', z: 'medio_alto', j: 0.10 },
      { n: 'Arena',              d: 'Centro', z: 'medio_alto', j: 0.18, t: ['playa', 'familiar'] },
      { n: 'Pumarín',            d: 'Centro', z: 'medio',  j: 0.04 },
      { n: 'El Bibio',           d: 'Centro', z: 'medio_alto', j: 0.10 },
      { n: 'La Calzada',         d: 'Oeste', z: 'medio',  j: 0.00 },
      { n: 'Natahoyo',           d: 'Oeste', z: 'medio',  j: 0.00 },
      { n: 'El Llano',           d: 'Centro', z: 'medio',  j: 0.04 },
      { n: 'La Arena',           d: 'Centro', z: 'medio_alto', j: 0.10 },
      { n: 'Somió',              d: 'Este', z: 'lujo',   j: -0.18, t: ['lujo', 'residencial'] },
      { n: 'Cabueñes',           d: 'Este', z: 'medio_alto', j: -0.10 },
      { n: 'Castiello Bernueces', d: 'Este', z: 'medio',  j: -0.10 },
      { n: 'Viesques',           d: 'Sur', z: 'medio_alto', j: -0.10, t: ['universitario'] },
      { n: 'Roces',              d: 'Sur', z: 'medio',  j: 0.00 },
      { n: 'Nuevo Roces',        d: 'Sur', z: 'medio_alto', j: -0.10, t: ['familiar', 'reciente'] },
      { n: 'Tremañes',           d: 'Oeste', z: 'medio',  j: -0.10 },
      { n: 'El Polígono',        d: 'Oeste', z: 'medio',  j: -0.10 },
      { n: 'La Camocha',         d: 'Sur', z: 'periferia', j: -0.10 },
      { n: 'Ceares',             d: 'Sur', z: 'medio',  j: -0.05 },
      { n: 'Contrueces',         d: 'Sur', z: 'medio',  j: -0.05 },
      { n: 'Vega',               d: 'Sur', z: 'medio',  j: -0.05 },
      { n: 'Santa Bárbara',      d: 'Centro', z: 'medio',  j: -0.05 },
    ],
  },

  // ═══ A CORUÑA · 30 barrios ═══════════════════════════════════════════
  {
    ciudad: 'A Coruña', base: 2080, alqBase: 9.6, varBase: 5.6,
    barrios: [
      { n: 'Cidade Vella',       d: 'Centro', z: 'centro', j: 0.10, t: ['histórico'] },
      { n: 'Pescadería',         d: 'Centro', z: 'centro', j: 0.10, t: ['centro'] },
      { n: 'Ensanche',           d: 'Centro', z: 'medio_alto', j: 0.20 },
      { n: 'Juan Flórez',        d: 'Centro', z: 'medio_alto', j: 0.18 },
      { n: 'Cuatro Caminos',     d: 'Centro', z: 'medio_alto', j: 0.10 },
      { n: 'Os Mallos',          d: 'Centro', z: 'medio',  j: 0.04 },
      { n: 'Sagrada Familia',    d: 'Centro', z: 'medio_alto', j: 0.04 },
      { n: 'Riazor',             d: 'Costa', z: 'lujo',   j: -0.20, t: ['playa', 'lujo'] },
      { n: 'San Roque',          d: 'Costa', z: 'medio_alto', j: 0.05 },
      { n: 'Adormideras',        d: 'Costa', z: 'medio_alto', j: 0.04 },
      { n: 'Zalaeta',            d: 'Costa', z: 'medio_alto', j: 0.10 },
      { n: 'Monelos',            d: 'Sur', z: 'medio',     j: 0.00 },
      { n: 'Eirís',              d: 'Sur', z: 'medio',     j: 0.04 },
      { n: 'Os Castros',         d: 'Sur', z: 'medio_alto', j: 0.04 },
      { n: 'Matogrande',         d: 'Sur', z: 'medio_alto', j: -0.10, t: ['familiar', 'reciente'] },
      { n: 'Elviña',             d: 'Sur', z: 'medio',     j: -0.05, t: ['universitario'] },
      { n: 'Mesoiro',            d: 'Sur', z: 'medio',     j: -0.10 },
      { n: 'Agra do Orzán',      d: 'Centro', z: 'medio',  j: -0.05 },
      { n: 'Labañou',            d: 'Costa', z: 'medio_alto', j: 0.00 },
      { n: 'Birloque',           d: 'Sur', z: 'periferia', j: -0.10 },
      { n: 'A Silva',            d: 'Sur', z: 'periferia', j: -0.10 },
      { n: 'San Pedro de Visma', d: 'Costa', z: 'medio_alto', j: -0.10 },
      { n: 'Monte Alto',         d: 'Costa', z: 'medio_alto', j: 0.05 },
      { n: 'Atochas-Monelos',    d: 'Sur', z: 'medio',  j: -0.05 },
      { n: 'Castiñeiras',        d: 'Sur', z: 'periferia', j: -0.10 },
    ],
  },

  // ═══ GRANADA · 22 barrios ════════════════════════════════════════════
  {
    ciudad: 'Granada', base: 1850, alqBase: 8.6, varBase: 6.4,
    barrios: [
      { n: 'Centro',             d: 'Centro', z: 'centro', j: 0.20, t: ['centro', 'histórico'] },
      { n: 'Albaicín',           d: 'Albaicín', z: 'centro', j: 0.10, t: ['turístico', 'histórico'] },
      { n: 'Realejo',            d: 'Centro', z: 'centro', j: 0.10, t: ['turístico'] },
      { n: 'Sacromonte',         d: 'Albaicín', z: 'medio_alto', j: -0.05, t: ['turístico'] },
      { n: 'Beiro',              d: 'Beiro', z: 'medio_alto', j: 0.10 },
      { n: 'San Lázaro',         d: 'Beiro', z: 'medio',  j: 0.04 },
      { n: 'San Francisco',      d: 'Centro', z: 'medio_alto', j: 0.10 },
      { n: 'Fígares',            d: 'Genil', z: 'medio_alto', j: 0.10 },
      { n: 'Bola de Oro',        d: 'Genil', z: 'lujo',   j: -0.20 },
      { n: 'Cervantes',          d: 'Genil', z: 'medio_alto', j: 0.10 },
      { n: 'Camino de Ronda',    d: 'Ronda', z: 'medio_alto', j: 0.10 },
      { n: 'Pajaritos',          d: 'Ronda', z: 'medio',  j: 0.04 },
      { n: 'Triunfo',            d: 'Centro', z: 'medio_alto', j: 0.10 },
      { n: 'Zaidín',             d: 'Zaidín', z: 'medio',  j: 0.10 },
      { n: 'Vergeles',           d: 'Zaidín', z: 'medio',  j: 0.04 },
      { n: 'Cerrillo de Maracena', d: 'Beiro', z: 'medio',  j: -0.05 },
      { n: 'Almanjáyar',         d: 'Norte', z: 'periferia', j: 0.10 },
      { n: 'Casería de Montijo', d: 'Norte', z: 'periferia', j: -0.10 },
      { n: 'Albayda',            d: 'Norte', z: 'periferia', j: -0.10 },
      { n: 'La Chana',           d: 'Beiro', z: 'medio',  j: 0.04 },
      { n: 'Bobadilla',          d: 'Norte', z: 'periferia', j: -0.10 },
    ],
  },

  // ═══ VITORIA-GASTEIZ · 30 barrios ═══════════════════════════════════
  {
    ciudad: 'Vitoria-Gasteiz', base: 2480, alqBase: 9.8, varBase: 5.4,
    barrios: [
      { n: 'Casco Viejo',        d: 'Casco Medieval', z: 'centro', j: 0.05, t: ['histórico'] },
      { n: 'Ensanche',           d: 'Centro', z: 'medio_alto', j: 0.20, t: ['centro'] },
      { n: 'Lovaina',            d: 'Centro', z: 'medio_alto', j: 0.10 },
      { n: 'Coronación',         d: 'Centro', z: 'medio_alto', j: 0.10 },
      { n: 'Aranbizkarra',       d: 'Centro', z: 'medio',  j: 0.10 },
      { n: 'Adurtza',            d: 'Sur', z: 'medio',     j: 0.00 },
      { n: 'San Cristóbal',      d: 'Sur', z: 'medio',     j: -0.04 },
      { n: 'Ariznabarra',        d: 'Sur', z: 'medio',     j: -0.05 },
      { n: 'Santa Lucía',        d: 'Sur', z: 'medio_alto', j: -0.10 },
      { n: 'San Martín',         d: 'Sur', z: 'medio_alto', j: -0.05 },
      { n: 'Mendizorroza',       d: 'Sur', z: 'medio_alto', j: 0.04 },
      { n: 'El Pilar',           d: 'Sur', z: 'medio_alto', j: 0.04 },
      { n: 'Zaramaga',           d: 'Norte', z: 'medio',  j: -0.05 },
      { n: 'Sansomendi',         d: 'Norte', z: 'medio',  j: 0.05 },
      { n: 'Lakua',              d: 'Norte', z: 'medio_alto', j: -0.10, t: ['moderno', 'familiar'] },
      { n: 'Salburua',           d: 'Este', z: 'medio_alto', j: -0.05, t: ['moderno', 'familiar'] },
      { n: 'Zabalgana',          d: 'Oeste', z: 'medio_alto', j: -0.10, t: ['moderno', 'familiar'] },
      { n: 'Aranzabela',         d: 'Centro', z: 'medio_alto', j: 0.04 },
      { n: 'Judimendi',          d: 'Este', z: 'medio',  j: -0.05 },
      { n: 'Arana',              d: 'Este', z: 'medio',  j: -0.05 },
      { n: 'Errekaleor',         d: 'Este', z: 'periferia', j: -0.20 },
      { n: 'Olarizu',            d: 'Sur', z: 'medio_alto', j: -0.10, t: ['lujo', 'residencial'] },
      { n: 'Anglo Vasco',        d: 'Centro', z: 'medio_alto', j: 0.10 },
      { n: 'Desamparadas',       d: 'Centro', z: 'medio',  j: 0.10 },
      { n: 'Aretxabaleta',       d: 'Sur', z: 'medio_alto', j: -0.20, t: ['lujo', 'residencial'] },
    ],
  },

  // ═══ CIUDADES SECUNDARIAS · ~10-20 barrios cada una ═════════════════
  // Pamplona · 14 barrios
  {
    ciudad: 'Pamplona', base: 2380, alqBase: 9.8, varBase: 5.0,
    barrios: [
      { n: 'Casco Antiguo',      d: 'Casco Antiguo', z: 'centro', j: 0.10, t: ['histórico'] },
      { n: 'Ensanche',           d: 'Ensanche', z: 'lujo',   j: -0.15, t: ['centro', 'lujo'] },
      { n: 'Iturrama',           d: 'Iturrama', z: 'medio_alto', j: 0.18 },
      { n: 'San Juan',           d: 'San Juan', z: 'medio_alto', j: 0.10, t: ['familiar'] },
      { n: 'Milagrosa',          d: 'Milagrosa', z: 'medio',  j: 0.10 },
      { n: 'Echavacoiz',         d: 'Echavacoiz', z: 'medio',  j: -0.05 },
      { n: 'Etxabakoitz',        d: 'Echavacoiz', z: 'medio',  j: -0.10 },
      { n: 'San Jorge',          d: 'San Jorge', z: 'medio',  j: 0.04 },
      { n: 'Rochapea',           d: 'Rochapea', z: 'medio',  j: 0.04 },
      { n: 'Azpilagaña',         d: 'Azpilagaña', z: 'medio_alto', j: -0.05 },
      { n: 'Mendebaldea',        d: 'Mendebaldea', z: 'medio_alto', j: -0.10, t: ['familiar', 'reciente'] },
      { n: 'Buztintxuri',        d: 'Buztintxuri', z: 'medio',  j: -0.10 },
      { n: 'Lezkairu',           d: 'Lezkairu', z: 'medio_alto', j: -0.10, t: ['moderno', 'familiar'] },
      { n: 'Mendillorri',        d: 'Mendillorri', z: 'medio_alto', j: -0.05 },
    ],
  },

  // Valladolid · ~25 barrios
  {
    ciudad: 'Valladolid', base: 1480, alqBase: 6.8, varBase: 4.0,
    barrios: [
      { n: 'Centro',             d: 'Centro', z: 'centro', j: 0.20, t: ['centro', 'histórico'] },
      { n: 'San Pablo',          d: 'Centro', z: 'medio_alto', j: 0.10 },
      { n: 'San Miguel y el Rosario', d: 'Centro', z: 'medio_alto', j: 0.04 },
      { n: 'Vadillos',           d: 'Centro', z: 'medio_alto', j: 0.04 },
      { n: 'Hospital',           d: 'Centro', z: 'medio',  j: 0.04 },
      { n: 'Pajarillos',         d: 'Pajarillos', z: 'medio',  j: -0.10 },
      { n: 'Pilarica',           d: 'Pajarillos', z: 'medio',  j: -0.05 },
      { n: 'San Andrés',         d: 'Pajarillos', z: 'medio',  j: -0.04 },
      { n: 'Belén',              d: 'Pajarillos', z: 'medio',  j: -0.10 },
      { n: 'La Victoria',        d: 'Pilarica-Victoria', z: 'medio', j: 0.04 },
      { n: 'Huerta del Rey',     d: 'Huerta del Rey', z: 'medio_alto', j: -0.05, t: ['familiar', 'tranquilo'] },
      { n: 'Parquesol',          d: 'Parquesol', z: 'medio_alto', j: -0.10, t: ['familiar', 'reciente'] },
      { n: 'Villa del Prado',    d: 'Parquesol', z: 'medio_alto', j: -0.10 },
      { n: 'Arturo Eyries',      d: 'Sur', z: 'medio',  j: -0.10 },
      { n: 'Rondilla',           d: 'Norte', z: 'medio',  j: 0.04 },
      { n: 'Caamaño',            d: 'Norte', z: 'medio',  j: -0.10 },
      { n: 'Delicias',           d: 'Sur', z: 'medio',  j: -0.05 },
      { n: 'Las Flores',         d: 'Sur', z: 'medio',  j: -0.10 },
      { n: 'San Pedro Regalado', d: 'Sur', z: 'medio',  j: 0.04 },
      { n: 'Girón',              d: 'Norte', z: 'medio_alto', j: 0.04 },
      { n: 'Zona Sur',           d: 'Sur', z: 'medio',  j: -0.05 },
      { n: 'Polígono Argales',   d: 'Sur', z: 'periferia', j: -0.20 },
      { n: 'Las Villas',         d: 'Norte', z: 'medio',  j: -0.05 },
    ],
  },

  // Oviedo · 25 barrios
  {
    ciudad: 'Oviedo', base: 1690, alqBase: 7.8, varBase: 4.2,
    barrios: [
      { n: 'Centro',             d: 'Centro', z: 'centro', j: 0.18, t: ['centro', 'histórico'] },
      { n: 'Ciudad Naranco',     d: 'Naranco', z: 'medio_alto', j: 0.10 },
      { n: 'San Lázaro',         d: 'Centro', z: 'medio_alto', j: 0.10 },
      { n: 'La Tenderina',       d: 'Tenderina', z: 'medio',  j: 0.00 },
      { n: 'Pumarín',            d: 'Pumarín', z: 'medio',  j: 0.05 },
      { n: 'Buenavista',         d: 'Buenavista', z: 'medio_alto', j: 0.10, t: ['familiar', 'tranquilo'] },
      { n: 'El Cristo',          d: 'Buenavista', z: 'medio_alto', j: 0.10, t: ['universitario'] },
      { n: 'Las Campas',         d: 'Buenavista', z: 'medio_alto', j: -0.05 },
      { n: 'Ventanielles',       d: 'Pumarín', z: 'medio',  j: -0.05 },
      { n: 'Otero',              d: 'Naranco', z: 'medio_alto', j: -0.05, t: ['familiar', 'tranquilo'] },
      { n: 'Vetusta',            d: 'Naranco', z: 'medio_alto', j: -0.05 },
      { n: 'Campomanes',         d: 'Centro', z: 'medio_alto', j: 0.10 },
      { n: 'Vallobín',           d: 'Vallobín', z: 'medio',  j: -0.05 },
      { n: 'Villafría',          d: 'Tenderina', z: 'medio',  j: -0.10 },
      { n: 'Trubia',             d: 'Trubia', z: 'periferia', j: -0.20 },
      { n: 'San Claudio',        d: 'San Claudio', z: 'medio',  j: -0.20 },
      { n: 'Olloniego',          d: 'Olloniego', z: 'periferia', j: -0.20 },
      { n: 'Colloto',            d: 'Colloto', z: 'medio',  j: -0.10 },
      { n: 'La Corredoria',      d: 'Corredoria', z: 'medio',  j: -0.10, t: ['familiar', 'reciente'] },
      { n: 'Las Caldas',         d: 'Las Caldas', z: 'medio_alto', j: -0.20 },
      { n: 'Montecerrao',        d: 'Buenavista', z: 'lujo',  j: -0.20, t: ['lujo', 'residencial'] },
      { n: 'Olivares',           d: 'Centro', z: 'medio_alto', j: -0.10 },
    ],
  },

  // Pequeñas pero significativas (~10-15 barrios cada una)
  ...['Burgos:1380:6.4:4.1','Salamanca:1380:6.4:4.2','Logroño:1380:6.0:3.8','Pontevedra:1690:7.6:5.8',
 'Lleida:1380:6.0:5.0','Tarragona:2150:9.0:6.0','Castellón de la Plana:1350:6.2:6.4','Cádiz:1750:8.4:7.2',
 'Jerez de la Frontera:1280:5.8:6.4','León:1180:5.6:3.4','Almería:1450:6.8:6.8','Huelva:1410:6.4:5.4',
 'Lugo:1290:5.6:4.1','Santa Cruz de Tenerife:2080:9.6:6.2','Cartagena:1420:6.6:6.0','Albacete:1080:5.0:3.2',
 'Ourense:1180:5.4:4.0','Badajoz:950:4.8:2.9','Ávila:1180:5.4:4.0','Segovia:1490:6.8:4.4',
 'Cáceres:920:4.6:2.6','Zamora:990:4.8:2.8','Cuenca:980:4.6:2.9','Soria:1080:5.0:3.0',
 'Teruel:950:4.6:2.4','Toledo:1320:6.2:4.5','Guadalajara:1490:6.8:4.8','Huesca:1390:6.4:4.6',
 'Mérida:1050:5.0:3.5','Marbella:3850:14.0:7.8','Mataró:2680:11.0:6.4','Sabadell:2480:10.4:6.0',
 'Terrassa:2350:10.0:6.0',"L'Hospitalet de Llobregat:3120:13.0:6.8",'Móstoles:2380:10.0:5.8',
 'Alcalá de Henares:2180:9.6:5.4','Fuenlabrada:2280:9.8:5.6','Leganés:2380:10.2:5.8',
 'Getafe:2680:11.0:6.0','Algeciras:1290:6.0:5.4','Cornellà de Llobregat:2980:12.5:6.4',
 'Badalona:2840:12.0:6.4','Santa Coloma de Gramenet:2580:11.0:6.2','Reus:1850:8.0:5.8',
 'Manresa:1780:7.6:5.0','Girona:2680:11.0:6.6','Vila-real:1450:6.4:5.6','Elda:1080:5.0:5.4',
 'Elche:1480:6.8:7.4','Torrejón de Ardoz:2280:9.8:5.6','Alcorcón:2580:10.8:5.8',
 'Parla:2080:8.8:5.4','Las Rozas:3680:13.5:6.4','Pozuelo de Alarcón:4580:15.0:6.0',
 'Majadahonda:3580:13.0:5.8','San Sebastián de los Reyes:2680:11.0:5.8','Santander:2380:10.5:5.6',
 'Torrelavega:1480:6.8:4.5','Lorca:1080:5.0:4.8','Alcoy:1080:5.0:4.6','Manacor:2380:9.8:5.4',
 'Ibiza:5680:18.0:7.5','Ferrol:1280:5.8:4.0','Avilés:1380:6.2:4.4','Mieres:850:4.0:2.8',
 'Langreo:880:4.2:2.8','Telde:1850:8.0:5.8','San Cristóbal de La Laguna:1850:8.0:5.6',
 'Arrecife:1490:6.8:5.4','Roquetas de Mar:1350:6.0:6.4','Vélez-Málaga:1480:6.4:7.4',
 'Estepona:2680:10.0:7.2','Fuengirola:2480:9.8:7.4','Mijas:2380:9.6:7.6','Benidorm:2280:10.0:6.8',
 'Torrevieja:1380:6.4:6.4','Orihuela:1180:5.6:5.8','Gandía:1480:7.0:6.4','Sagunto:1280:5.8:5.6'].map(line => {
    const [c, base, alq, v] = line.split(':')
    const baseN = +base, alqN = +alq, varN = +v
    return {
      ciudad: c, base: baseN, alqBase: alqN, varBase: varN,
      barrios: [
        { n: 'Centro', z: 'centro' as Zona, j: 0.10, t: ['centro'] },
        { n: 'Casco Antiguo', z: 'centro' as Zona, j: 0.05, t: ['histórico'] },
        { n: 'Ensanche', z: 'medio_alto' as Zona, j: 0.10 },
        { n: 'Norte', z: 'medio' as Zona, j: 0.04 },
        { n: 'Sur', z: 'medio' as Zona, j: -0.05 },
        { n: 'Este', z: 'medio' as Zona, j: 0.00 },
        { n: 'Oeste', z: 'medio' as Zona, j: 0.00 },
        { n: 'Polígono Industrial', z: 'periferia' as Zona, j: -0.10 },
        { n: 'Zona Residencial', z: 'medio_alto' as Zona, j: -0.05, t: ['familiar', 'reciente'] },
        { n: 'Periferia', z: 'periferia' as Zona, j: -0.05 },
      ],
    } as CiudadDef
  }),
]

// ─── Exports ────────────────────────────────────────────────────────────
export const TODOS_LOS_BARRIOS: Barrio[] = CIUDADES.flatMap(c =>
  c.barrios.map(b => deriveBarrio(c, b)),
)

export const CIUDADES_DISPONIBLES: string[] = Array.from(
  new Set(CIUDADES.map(c => c.ciudad)),
).sort((a, b) => a.localeCompare(b, 'es'))
