from __future__ import annotations


def _initiative(
    id: str,
    title: str,
    type: str,
    submitter_party: str,
    submitter_actors: list[str],
    submitted_date: str,
    current_status: str,
    summary: str,
    key_articles: list[str],
    expected_impact: str,
    voting_history: list[dict],
    affected_demographics: list[str],
    opposition_arguments: list[str],
    support_arguments: list[str],
    citations: list[str],
) -> dict:
    return {
        "id": id,
        "title": title,
        "type": type,
        "submitter_party": submitter_party,
        "submitter_actors": submitter_actors,
        "submitted_date": submitted_date,
        "current_status": current_status,
        "summary": summary,
        "key_articles": key_articles,
        "expected_impact": expected_impact,
        "voting_history": voting_history,
        "affected_demographics": affected_demographics,
        "opposition_arguments": opposition_arguments,
        "support_arguments": support_arguments,
        "citations": citations,
    }


LEGISLATIVE_INITIATIVES: list[dict] = [
    _initiative(
        "leg_vivienda_2023", "Ley 12/2023 por el Derecho a la Vivienda", "Ley",
        "psoe", ["pedro_sanchez", "maria_jesus_montero"], "2022-02-01", "Aprobada",
        "Establece marco estatal de derecho a vivienda con zonas tensionadas, índice de referencia, y limitaciones a desahucios. Prevé colaboración con autonomías para aplicación. Dotación pública para vivienda asequible.",
        ["Art.16: zonas tensionadas", "Art.17: índice precio referencia", "Art.18: limitaciones precio alquiler"],
        "Aplicación efectiva sólo en Cataluña, declarado constitucional por TC en 2025",
        [{"date": "2023-04-27", "result": "176 sí / 167 no", "stage": "Pleno Congreso"}],
        ["jovenes 25-35", "familias monoparentales", "inquilinos urbanos"],
        ["Intervencionismo destruye oferta", "Inseguridad jurídica para propietarios", "Invade competencias autonómicas"],
        ["Acceso a vivienda derecho constitucional", "Frenar especulación urbana", "Protección colectivos vulnerables"],
        ["BOE 25/05/2023", "STC 79/2025"],
    ),
    _initiative(
        "leg_memoria_2022", "Ley 20/2022 de Memoria Democrática", "Ley",
        "psoe", ["pedro_sanchez", "felix_bolanos"], "2021-09-15", "Aprobada",
        "Reconocimiento víctimas franquismo, eliminación simbología, declaración nulidad consejos guerra. Crea fiscalía memoria democrática. Introduce contenido obligatorio en currículo educativo.",
        ["Art.6: ilegitimidad régimen", "Art.34: simbología", "Art.55: educación"],
        "Implementación lenta por resistencias autonómicas; cementerios y fosas con avance gradual",
        [{"date": "2022-10-19", "result": "173 sí / 159 no / 14 abst", "stage": "Pleno Congreso"}],
        ["familias víctimas franquismo", "estudiantes ESO/Bach"],
        ["Reabre heridas cerradas", "Sectarismo histórico", "Revisión Transición"],
        ["Reparación a víctimas", "Memoria como base democracia", "Cumplir estándares internacionales"],
        ["BOE 21/10/2022"],
    ),
    _initiative(
        "leg_amnistia_2024", "Ley Orgánica 1/2024 de Amnistía Catalana", "Ley Orgánica",
        "psoe", ["pedro_sanchez", "felix_bolanos"], "2023-11-13", "Aprobada",
        "Amnistía a personas implicadas en proceso independentista catalán entre 2012 y 2023. Excluye delitos de terrorismo, traición o vulneraciones graves de derechos humanos. Incluye procedimientos administrativos y penales.",
        ["Art.1: ámbito objetivo", "Art.2: exclusiones", "Art.4: efectos retroactivos"],
        "Aplicación parcial; Puigdemont pendiente; aval TC junio 2025 con matices",
        [{"date": "2024-01-30", "result": "171 sí / 179 no", "stage": "Pleno Congreso (rechazo inicial)"},
         {"date": "2024-05-30", "result": "177 sí / 172 no", "stage": "Pleno Congreso (aprobación)"}],
        ["políticos catalanes", "funcionarios Generalitat", "manifestantes 1-O"],
        ["Inconstitucionalidad", "Privilegio penal", "Capitulación frente independentismo"],
        ["Convivencia social", "Desjudicialización conflicto", "Estabilidad institucional"],
        ["BOE 11/06/2024", "STC 2025/06"],
    ),
    _initiative(
        "leg_trans_2023", "Ley 4/2023 para la Igualdad Real y Efectiva de las Personas Trans", "Ley",
        "podemos", ["irene_montero", "ione_belarra"], "2022-06-27", "Aprobada",
        "Reconoce autodeterminación de género desde 16 años con aval médico. Garantiza despatologización trans. Prohibe terapias de conversión. Refuerza derechos LGTBI globales.",
        ["Art.43: rectificación registral", "Art.17: terapias conversión", "Art.59: protección menores"],
        "Aplicación inmediata; polémica por casos cambios oportunistas",
        [{"date": "2023-02-16", "result": "188 sí / 150 no / 7 abst", "stage": "Pleno Congreso"}],
        ["personas trans", "menores trans", "colectivos LGTBI"],
        ["Borrado de las mujeres", "Riesgo menores sin acompañamiento", "Inseguridad jurídica deportiva"],
        ["Derecho a identidad", "Reducción suicidio personas trans", "Equiparación estándares europeos"],
        ["BOE 28/02/2023"],
    ),
    _initiative(
        "leg_reforma_laboral_2021", "RDL 32/2021 Reforma Laboral", "Real Decreto-ley",
        "psoe", ["yolanda_diaz", "pedro_sanchez"], "2021-12-28", "Aprobada",
        "Reforma laboral fruto del diálogo social CEOE-CCOO-UGT. Limita contratación temporal, recupera ultraactividad de convenios y prevalencia sectorial. Modifica ERTE. Recupera elementos derogados en 2012.",
        ["Art.15: contratación temporal", "Art.84: ultraactividad", "Art.86: prevalencia sectorial"],
        "Reducción histórica temporalidad al 16%; éxito reconocido OCDE",
        [{"date": "2022-02-03", "result": "175 sí / 174 no", "stage": "Convalidación Congreso (error voto Casero)"}],
        ["trabajadores temporales", "empleados sectores estacionales"],
        ["Freno a flexibilidad", "Aumento costes empresas", "Riesgo destrucción empleo"],
        ["Reducción precariedad", "Prestigio internacional", "Acuerdo de los agentes sociales"],
        ["BOE 30/12/2021"],
    ),
    _initiative(
        "leg_bienestar_animal_2023", "Ley 7/2023 de Protección de los Derechos y el Bienestar de los Animales", "Ley",
        "podemos", ["ione_belarra"], "2022-02-18", "Aprobada",
        "Marco estatal de protección animal con prohibición de sacrificio cero, registro nacional de animales, regulación de venta y tenencia. Excluye finalmente perros caza por enmienda PSOE.",
        ["Art.27: sacrificio cero", "Art.34: tenencia responsable", "Art.45: registros"],
        "Aplicación parcial; tensiones por exclusión perros caza",
        [{"date": "2023-03-09", "result": "174 sí / 167 no / 5 abst", "stage": "Pleno Congreso"}],
        ["propietarios animales compañía", "asociaciones protectoras", "cazadores"],
        ["Burocratización", "Costes administrativos", "Atenta tradiciones rurales"],
        ["Bienestar animal moderno", "Estándares europeos", "Reducción abandono"],
        ["BOE 29/03/2023"],
    ),
    _initiative(
        "leg_proteccion_embarazadas", "Ley 1/2023 de Protección a Mujeres Embarazadas", "Ley Orgánica",
        "psoe", ["pedro_sanchez", "irene_montero"], "2022-09-15", "Aprobada",
        "Refuerza derechos en interrupción del embarazo, elimina obligación reflexión 3 días, garantiza IVE en sanidad pública, protege contra acoso ante clínicas. Despenaliza aborto a 16-17 años sin permiso parental.",
        ["Art.17: IVE en pública", "Art.13: 16-17 años", "Art.172.bis Código Penal: acoso clínicas"],
        "Aplicación efectiva en sanidad pública; persisten dificultades en algunas autonomías",
        [{"date": "2023-02-16", "result": "185 sí / 154 no", "stage": "Pleno Congreso"}],
        ["mujeres en edad fértil", "menores 16-17", "personal sanitario"],
        ["Atenta protección no nacido", "Rompe consensos previos", "Eliminación reflexión"],
        ["Derecho efectivo a IVE", "Reducción peregrinaje", "Estándares OMS"],
        ["BOE 01/03/2023"],
    ),
    _initiative(
        "leg_familias_2024", "Ley de Familias", "Ley",
        "sumar", ["ione_belarra", "yolanda_diaz"], "2023-09-01", "Tramitación",
        "Reconoce diversidad familiar, amplía permisos parentales, protege familias monomarentales. Equipara familia numerosa de 3 hijos con monoparental de 2. Crea registro estatal y mejora prestaciones.",
        ["Art.4: tipología familiar", "Art.10: permisos", "Art.18: prestaciones monoparentales"],
        "Bloqueada en tramitación por reforma intensa enmiendas",
        [{"date": "2024-02-22", "result": "166 sí / 175 no", "stage": "Toma en consideración (rechazo)"}],
        ["familias monoparentales", "familias homosexuales", "padres y madres"],
        ["Coste presupuestario", "Privilegios injustificados", "Burocracia adicional"],
        ["Diversidad familiar real", "Equiparación europea", "Apoyo monoparentales"],
        ["BOCG 12/09/2023"],
    ),
    _initiative(
        "leg_codigo_penal_2022", "LO 14/2022 Reforma Código Penal (sedición y malversación)", "Ley Orgánica",
        "psoe", ["felix_bolanos", "pedro_sanchez"], "2022-11-11", "Aprobada",
        "Suprime delito de sedición sustituido por desórdenes públicos agravados. Modifica malversación distinguiendo enriquecimiento personal. Reforma transposición directiva UE.",
        ["Art.557: desórdenes públicos", "Art.432: malversación"],
        "Permitió reducción condenas líderes procés; tensión judicial",
        [{"date": "2022-12-22", "result": "184 sí / 64 no / 89 abst", "stage": "Pleno Congreso"}],
        ["líderes procés condenados", "funcionarios públicos"],
        ["Privilegio para condenados procés", "Desprotección frente disturbios", "Erosión Estado de Derecho"],
        ["Homologación europea", "Distinguir tipos malversación", "Modernización penal"],
        ["BOE 23/12/2022"],
    ),
    _initiative(
        "leg_solo_si_si_2022", "LO 10/2022 de Garantía Integral Libertad Sexual", "Ley Orgánica",
        "podemos", ["irene_montero"], "2021-07-06", "Aprobada",
        "Refunde delitos sexuales basándolos en consentimiento, elimina distinción agresión-abuso. Refuerza protección víctimas, baja edad consentimiento sexual a 16. Conocida como ley solo sí es sí.",
        ["Art.178: agresión sexual unificada", "Art.181: agresión a menores", "Art.183: edad consentimiento"],
        "Reducciones imprevistas; reforma técnica abril 2023",
        [{"date": "2022-08-25", "result": "205 sí / 141 no", "stage": "Pleno Congreso"},
         {"date": "2023-04-18", "result": "234 sí / 120 no", "stage": "Reforma técnica"}],
        ["víctimas violencia sexual", "condenados agresión sexual"],
        ["Rebajas de pena masivas", "Diseño técnico defectuoso", "Inseguridad jurídica"],
        ["Centra consentimiento", "Estándar Estambul", "Refuerzo víctimas"],
        ["BOE 07/09/2022", "BOE 27/04/2023"],
    ),
    _initiative(
        "leg_eutanasia_2021", "LO 3/2021 Reguladora de la Eutanasia", "Ley Orgánica",
        "psoe", ["pedro_sanchez"], "2020-02-01", "Aprobada",
        "Reconoce derecho a la prestación de ayuda para morir como nuevo derecho individual. Establece requisitos médicos, ámbito SNS y comisión de garantía y evaluación.",
        ["Art.5: requisitos persona solicitante", "Art.8: procedimiento médico", "Art.17: comisión evaluación"],
        "Aplicación efectiva; ~1.000 prestaciones anuales",
        [{"date": "2021-03-18", "result": "202 sí / 141 no / 2 abst", "stage": "Pleno Congreso"}],
        ["enfermos terminales", "enfermos crónicos invalidantes"],
        ["Devalúa vida humana", "Pendiente desarrollo cuidados paliativos", "Riesgo abuso"],
        ["Autonomía individual", "Final digno", "Estándares Bélgica/Países Bajos"],
        ["BOE 25/03/2021"],
    ),
    _initiative(
        "leg_lomloe_2020", "LO 3/2020 LOMLOE Ley Educación", "Ley Orgánica",
        "psoe", ["pedro_sanchez"], "2020-03-04", "Aprobada",
        "Reforma sistema educativo para compensar la LOMCE: refuerza inclusión, reduce concertada, refuerza educación pública, lengua propia cooficial. Genera oposición masiva PP y VOX.",
        ["Art.84: criterios admisión", "Art.110: educación inclusiva", "Disp. final 4ª: lengua cooficial"],
        "Implementación gradual con resistencia desde gobiernos PP",
        [{"date": "2020-12-23", "result": "177 sí / 148 no / 17 abst", "stage": "Pleno Congreso"}],
        ["alumnado escolar", "personal docente", "familias"],
        ["Adoctrinamiento", "Desprecio español", "Exclusión concertada"],
        ["Modernización educación", "Equidad", "Cooperación lenguas oficiales"],
        ["BOE 30/12/2020"],
    ),
    _initiative(
        "leg_reforma_pensiones_2023", "RDL 2/2023 Reforma Sistema Pensiones (segunda fase)", "Real Decreto-ley",
        "psoe", ["pedro_sanchez", "yolanda_diaz", "jose_luis_escriva"], "2023-03-16", "Aprobada",
        "Refuerza ingresos del sistema con MEI y destopado bases máximas. Adapta cotizaciones a duración carreras. Establece cláusula de salvaguarda.",
        ["Art.4: MEI", "Art.6: destopado", "Disp.final 7ª: revisión 2050"],
        "Sistema sostenible hasta 2050 según AIReF",
        [{"date": "2023-03-30", "result": "179 sí / 162 no", "stage": "Convalidación Congreso"}],
        ["pensionistas presentes", "trabajadores futuros", "rentas altas"],
        ["Aumenta carga contributiva", "Insostenible largo plazo", "Penaliza salarios altos"],
        ["Mantiene poder adquisitivo", "Justicia intergeneracional", "Validación AIReF"],
        ["BOE 17/03/2023"],
    ),
    _initiative(
        "leg_cambio_climatico_2021", "Ley 7/2021 de Cambio Climático y Transición Energética", "Ley",
        "psoe", ["pedro_sanchez", "teresa_ribera"], "2020-05-19", "Aprobada",
        "Marco legal para neutralidad climática 2050. Objetivo 23% reducción emisiones 2030. Cierre minería carbón. Plan energía y clima vinculante. Movilidad cero emisiones 2040.",
        ["Art.3: objetivos 2030/2050", "Art.14: movilidad", "Art.27: financiación"],
        "Marco fundamental UE; cumple Paris",
        [{"date": "2021-04-08", "result": "246 sí / 8 no / 95 abst", "stage": "Pleno Congreso"}],
        ["sector energético", "industria intensiva", "movilidad"],
        ["Coste industrial", "Excesiva ambición", "Burocratización energía"],
        ["Cumplimiento Paris", "Liderazgo verde España", "Inversión renovables"],
        ["BOE 21/05/2021"],
    ),
    _initiative(
        "leg_minimo_vital_2020", "RDL 20/2020 Ingreso Mínimo Vital", "Real Decreto-ley",
        "psoe", ["pedro_sanchez", "ione_belarra"], "2020-05-29", "Aprobada",
        "Crea prestación no contributiva estatal para hogares en situación pobreza. Cobertura prevista 850.000 hogares. Reconocimiento por SS estatal.",
        ["Art.1: garantía ingreso mínimo", "Art.7: requisitos", "Art.20: complemento infancia"],
        "Cobertura efectiva 50% objetivo según AIReF",
        [{"date": "2020-06-10", "result": "297 sí / 0 no / 52 abst", "stage": "Convalidación Congreso"}],
        ["hogares pobreza severa", "familias monomarentales"],
        ["Lentitud burocrática", "Riesgo dependencia", "Cobertura insuficiente"],
        ["Suelo digno mínimo", "Reducción pobreza infantil", "Convergencia europea"],
        ["BOE 01/06/2020"],
    ),
    _initiative(
        "leg_smi_2025", "RD SMI 2025: 1184€ x 14 pagas", "Real Decreto",
        "psoe", ["yolanda_diaz", "pedro_sanchez"], "2025-01-15", "Aprobada",
        "Sube SMI a 1184€ x 14 pagas (+4,4%) tras subidas anteriores. Acuerdo con sindicatos sin patronal. Acumulado SMI 2018-2025: +60%.",
        ["Art.1: cuantía mensual", "Art.2: ámbito aplicación"],
        "1.150€ promedio salarial mínimo; cumple compromiso 60% mediana",
        [{"date": "2025-02-04", "result": "Aprobación Consejo Ministros", "stage": "Real Decreto"}],
        ["trabajadores menores ingresos", "empleadas hogar", "agricultura"],
        ["Destrucción empleo joven", "Coste pequeñas empresas", "Inflacionario"],
        ["Salario digno", "Reducir desigualdad", "Estándares europeos"],
        ["BOE 05/02/2025"],
    ),
    _initiative(
        "leg_extranjeria_2025", "Reforma Reglamento Extranjería 2025", "Real Decreto",
        "psoe", ["felix_bolanos", "pedro_sanchez"], "2024-11-19", "Aprobada",
        "Regularización extraordinaria con arraigo socio-formativo. Refuerza vías legales migración. Marco para distribución solidaria menores no acompañados Canarias.",
        ["Art.124: arraigo formativo", "Art.187: distribución menores"],
        "Regularización 300.000 personas estimadas; tensión Vox sale gobiernos",
        [{"date": "2024-11-26", "result": "Aprobación Consejo Ministros", "stage": "RD"}],
        ["migrantes en situación irregular", "menores no acompañados", "comunidad canaria"],
        ["Efecto llamada", "Inmigración descontrolada", "Carga autonómica"],
        ["Regularización solidaria", "Cumplimiento marco UE", "Cohesión social"],
        ["BOE 27/11/2024"],
    ),
    _initiative(
        "leg_fiscal_2022", "Ley 38/2022 Impuestos extraordinarios banca y energéticas", "Ley",
        "psoe", ["maria_jesus_montero", "pedro_sanchez"], "2022-07-28", "Aprobada",
        "Crea gravámenes temporales (luego prorrogados) sobre beneficios extraordinarios banca (4,8%) y energéticas (1,2% facturación). Recaudación destinada a medidas anti-inflación.",
        ["Art.1: gravamen energéticas", "Art.2: gravamen banca", "Disp. final: prórroga"],
        "Recaudación ~3.000M€/año; impugnaciones judiciales pendientes",
        [{"date": "2022-12-15", "result": "180 sí / 154 no / 14 abst", "stage": "Pleno Congreso"}],
        ["clientes banca", "consumidores energía", "accionistas grandes corporativos"],
        ["Inseguridad jurídica", "Recaída final consumidor", "Impuesto confiscatorio"],
        ["Justicia fiscal", "Aporte beneficios extraordinarios", "Financiar medidas escudo social"],
        ["BOE 28/12/2022"],
    ),
    _initiative(
        "leg_anuncio_canarias", "Reforma Ley Extranjería 2025 (menores Canarias)", "Ley",
        "psoe", ["fernando_clavijo", "felix_bolanos"], "2025-01-15", "Aprobada",
        "Modifica artículo 35 LO 4/2000 para distribuir solidariamente menores no acompañados entre todas las CCAA. Aprobación con votos PP+PSOE+CC sin Vox y con polémica.",
        ["Art.35: redistribución obligatoria"],
        "Distribución 4.500 menores entre CCAA; tensión judicial PP autonómico",
        [{"date": "2025-03-25", "result": "182 sí / 150 no / 16 abst", "stage": "Pleno Congreso"}],
        ["menores no acompañados", "comunidad canaria"],
        ["Efecto llamada", "Imposición autonómica", "Carga asimétrica"],
        ["Solidaridad territorial", "Drama humanitario", "Reparación crónica"],
        ["BOE 02/04/2025"],
    ),
    _initiative(
        "leg_violencia_genero_2024", "Pacto Estado Violencia Género: Renovación 2024", "Acuerdo Cortes",
        "psoe", ["pedro_sanchez", "monica_garcia"], "2024-09-15", "Aprobada",
        "Renovación quinquenal del Pacto con 462 medidas y partida 1.500M€. Refuerza atención psicosocial y crea red de centros 24h. Apoyo todos los grupos salvo VOX.",
        ["Medida 23: refuerzo psicosocial", "Medida 47: centros crisis 24h", "Medida 132: violencia digital"],
        "Implementación efectiva con presupuesto incrementado 30%",
        [{"date": "2024-11-25", "result": "324 sí / 33 no", "stage": "Pleno Congreso"}],
        ["mujeres víctimas violencia", "menores en hogares violentos", "personal asistencial"],
        ["Estigmatización hombres", "Sesgo ideológico", "Coste injustificado"],
        ["Consenso democrático", "Datos respaldan necesidad", "Cumplimiento Estambul"],
        ["BOCG 28/11/2024"],
    ),
    _initiative(
        "leg_subida_pensiones_2024", "RDL 8/2023 Subida pensiones IPC 2024", "Real Decreto-ley",
        "psoe", ["pedro_sanchez", "maria_jesus_montero"], "2023-12-19", "Aprobada",
        "Subida pensiones contributivas 3,8% IPC 2024 y mínimas 6,9%. Mantiene poder adquisitivo pensionistas. Coste anual 4.500M€.",
        ["Art.45: revalorización", "Art.46: pensiones mínimas"],
        "Aplicación inmediata enero 2024",
        [{"date": "2024-01-10", "result": "178 sí / 172 no", "stage": "Convalidación Congreso"}],
        ["pensionistas", "viudas/os", "discapacitados"],
        ["Coste insostenible", "Inflación añadida", "Penaliza generaciones futuras"],
        ["Compromiso pensionistas", "Cláusula constitucional", "Justicia social"],
        ["BOE 28/12/2023"],
    ),
    _initiative(
        "leg_canon_digital_2025", "Ley Servicios Digitales y IA", "Ley",
        "sumar", ["ernest_urtasun", "yolanda_diaz"], "2024-06-18", "Tramitación",
        "Adapta Ley Servicios Digitales europea y AI Act. Crea AESIA (agencia supervisión IA). Marco transparencia algoritmos públicos. Regula modelos generales.",
        ["Art.34: AESIA", "Art.45: transparencia algorítmica", "Art.62: sandbox regulatorio"],
        "Tramitación con apoyo amplio salvo VOX y dudas PP",
        [{"date": "2025-04-15", "result": "230 sí / 60 abst / 30 no", "stage": "Toma consideración"}],
        ["empresas tecnológicas", "usuarios redes sociales", "investigadores IA"],
        ["Burocratización", "Pérdida competitividad", "Inseguridad sector"],
        ["Cumplimiento DSA y AI Act", "Liderazgo regulación", "Protección derechos"],
        ["BOCG 25/06/2024"],
    ),
    _initiative(
        "leg_consumo_2024", "Ley Reducción Empaques y Plásticos", "Ley",
        "sumar", ["ernest_urtasun"], "2024-04-15", "Tramitación",
        "Obligación reducir 50% plásticos no reutilizables 2030. Sistema Devolución Depósito y Retorno. Tasa específica embalajes. Excepciones para PYMES.",
        ["Art.7: SDDR", "Art.10: tasa embalajes"],
        "Bloqueo industrial en tramitación",
        [{"date": "2024-09-10", "result": "Comisión sin acuerdo", "stage": "Comisión Transición Ecológica"}],
        ["consumidores", "industria envases", "comercio retail"],
        ["Coste ciudadano", "Inflación productos", "Inviable PYMES"],
        ["Reducción residuos", "Estándar UE", "Innovación verde"],
        ["BOCG 20/04/2024"],
    ),
    _initiative(
        "leg_jornada_laboral_2025", "Ley Reducción Jornada Laboral 37,5h", "Ley",
        "sumar", ["yolanda_diaz"], "2024-12-20", "Rechazada",
        "Reduce jornada laboral ordinaria de 40 a 37,5 horas semanales sin reducción salarial. Plazo 18 meses adaptación. Régimen sancionador refuerza control horario.",
        ["Art.1: jornada 37,5h", "Art.34 ET reformado"],
        "Rechazada por Junts; Yolanda Díaz volverá a presentar",
        [{"date": "2025-09-10", "result": "171 sí / 178 no", "stage": "Pleno Congreso (rechazo)"}],
        ["asalariados sector privado", "PYMES", "empresas servicios"],
        ["Coste empresas inasumible", "Destrucción empleo", "Productividad caerá"],
        ["Conciliación familiar", "Tendencia europea", "Sin coste salarial"],
        ["BOCG 27/12/2024"],
    ),
    _initiative(
        "leg_gestion_dana", "Ley Reconstrucción DANA Valencia", "Ley",
        "psoe", ["pedro_sanchez", "maria_jesus_montero"], "2024-11-15", "Aprobada",
        "Plan reconstrucción tras DANA 29-O. 16.600M€ ayudas directas, agrícolas, infraestructura. Coordinación con Generalitat Valenciana pese a tensión política.",
        ["Art.5: ayudas directas afectados", "Art.18: reconstrucción infraestructura", "Art.34: agrícola"],
        "Aplicación con tensiones competenciales con Generalitat",
        [{"date": "2024-12-19", "result": "330 sí / 1 no / 18 abst", "stage": "Pleno Congreso"}],
        ["afectados DANA", "agricultores Valencia", "comerciantes Paiporta"],
        ["Insuficiente y tarde", "Tensión competencial", "Falta plan estructural"],
        ["Solidaridad territorial", "Reconstrucción urgente", "Consenso amplio"],
        ["BOE 27/12/2024"],
    ),
    _initiative(
        "leg_financiacion_catalana", "RDL 6/2024 Financiación singular Catalunya", "Real Decreto-ley",
        "psoe", ["maria_jesus_montero", "pedro_sanchez"], "2024-07-25", "Tramitación",
        "Establece modelo de financiación singular para Cataluña con cesión cobro IRPF a Agencia Tributaria Catalana. Compensación al Estado por servicios. Compromiso acuerdo PSOE-ERC.",
        ["Art.7: cesión IRPF", "Art.15: compensación"],
        "Bloqueo en Cortes por oposición PP/VOX y dudas internas PSOE",
        [{"date": "2024-09-22", "result": "Sin votación final", "stage": "Comisión Hacienda"}],
        ["contribuyentes Cataluña", "Agencia Tributaria", "resto autonomías"],
        ["Privilegio territorial", "Ruptura solidaridad", "Cupo encubierto"],
        ["Reconocimiento singularidad", "Compromiso investidura", "Eficiencia administrativa"],
        ["BOCG 30/07/2024"],
    ),
    _initiative(
        "leg_fiscal_progresiva_2025", "Ley Reforma Fiscal Progresiva 2025", "Ley",
        "psoe", ["maria_jesus_montero"], "2024-09-15", "Tramitación",
        "Sube tipos IRPF rentas altas (>200.000€), refuerza grandes fortunas y consolida impuesto extraordinario banca/energéticas. Reduce IVA productos básicos.",
        ["Art.66: tipos IRPF altos", "Art.78: gran fortuna", "Art.96: IVA básicos"],
        "En tramitación con dudas Junts",
        [{"date": "2025-01-30", "result": "Tramitación Comisión", "stage": "Comisión Hacienda"}],
        ["rentas altas", "grandes fortunas", "consumidores básicos"],
        ["Confiscatorio", "Fuga fiscal", "Burocratización"],
        ["Justicia fiscal", "Reducción desigualdad", "Reforzar servicios públicos"],
        ["BOCG 22/09/2024"],
    ),
    _initiative(
        "leg_movilidad_sostenible", "Ley Movilidad Sostenible 2024", "Ley",
        "psoe", ["yolanda_diaz", "raquel_sanchez"], "2023-09-22", "Aprobada",
        "Marco básico transporte sostenible. Subvenciones VEH eléctrico. Obligación ZBE poblaciones >50.000. Refuerza cercanías. Plan inversiones 5.000M€.",
        ["Art.14: ZBE obligatorias", "Art.27: subvenciones eléctrico", "Art.45: ferrocarril"],
        "Implementación con resistencia ZBE en gobiernos PP",
        [{"date": "2024-04-23", "result": "184 sí / 168 no", "stage": "Pleno Congreso"}],
        ["conductores urbanos", "industria automoción", "usuarios cercanías"],
        ["Coste familias", "Pérdida competitividad", "ZBE injustas"],
        ["Cumplimiento UE", "Salud pública", "Cambio modal"],
        ["BOE 27/04/2024"],
    ),
    _initiative(
        "leg_proteccion_periodistas", "Ley Protección Periodistas y SLAPP", "Ley",
        "sumar", ["ernest_urtasun"], "2025-02-10", "Tramitación",
        "Transpone directiva UE anti-SLAPP. Protección informadores frente a demandas abusivas. Estatuto profesional periodista. Garantía secreto profesional reforzado.",
        ["Art.5: SLAPP", "Art.18: secreto profesional", "Art.32: estatuto"],
        "En fase enmiendas; apoyo progresista",
        [{"date": "2025-04-15", "result": "Toma en consideración 220 sí / 130 no", "stage": "Pleno Congreso"}],
        ["periodistas", "informadores freelance", "medios independientes"],
        ["Privilegio para activistas", "Inseguridad jurídica empresas", "Restringe derecho honor"],
        ["Cumplimiento UE", "Defensa libertad información", "Protección democrática"],
        ["BOCG 18/02/2025"],
    ),
    _initiative(
        "leg_reforma_judicial_2024", "LO Reforma CGPJ y Estatuto Magistratura", "Ley Orgánica",
        "psoe", ["felix_bolanos"], "2024-06-25", "Aprobada",
        "Renueva CGPJ tras 5 años bloqueo. Refuerza independencia. Cambia sistema elección con cuotas profesionales. Acuerdo histórico PP-PSOE julio 2024.",
        ["Art.566 LOPJ: composición", "Art.577: incompatibilidades"],
        "Renovación efectiva CGPJ junio 2024",
        [{"date": "2024-06-20", "result": "279 sí / 69 no", "stage": "Pleno Congreso"}],
        ["jueces y magistrados", "operadores jurídicos"],
        ["Politización CGPJ", "Reparto cuotas inadecuado"],
        ["Desbloqueo institucional", "Independencia judicial", "Cumplimiento UE"],
        ["BOE 26/06/2024"],
    ),
    _initiative(
        "leg_comercio_electronico_2024", "Ley Modernización Comercio Electrónico", "Ley",
        "psoe", ["yolanda_diaz"], "2024-03-15", "Aprobada",
        "Refuerza derechos consumidor en e-commerce. Plazo desistimiento 30 días. Garantías productos refurbished. Sanciones plataformas.",
        ["Art.71: desistimiento", "Art.122: refurbished"],
        "Aplicación normalizada",
        [{"date": "2024-09-25", "result": "289 sí / 50 abst", "stage": "Pleno Congreso"}],
        ["consumidores online", "PYMES e-commerce", "plataformas"],
        ["Burocratización", "Coste empresas pequeñas"],
        ["Refuerzo consumidor", "Cumplimiento UE", "Modernización"],
        ["BOE 03/10/2024"],
    ),
    _initiative(
        "leg_renta_basica_universal", "PNL Renta Básica Universal", "Proposición no de Ley",
        "podemos", ["ione_belarra"], "2024-09-10", "Rechazada",
        "Insta al Gobierno a estudiar viabilidad RBU como política pública complementaria al IMV. Iniciativa simbólica.",
        ["Único punto: encargo estudio AIReF"],
        "Rechazada por amplia mayoría",
        [{"date": "2024-11-12", "result": "12 sí / 320 no / 17 abst", "stage": "Pleno Congreso"}],
        ["población general", "colectivos pobreza"],
        ["Inviable presupuestaria", "Desincentivo trabajo", "Utopía"],
        ["Lucha pobreza", "Modernización Estado bienestar"],
        ["BOCG 12/09/2024"],
    ),
    _initiative(
        "leg_anuncio_isla_palma", "Ley Reconstrucción La Palma", "Ley",
        "psoe", ["pedro_sanchez", "fernando_clavijo"], "2022-01-25", "Aprobada",
        "Plan reconstrucción tras erupción Cumbre Vieja. 1.200M€ ayudas directas, agrícolas, viviendas. Coordinación con Cabildo Palma.",
        ["Art.5: ayudas directas", "Art.18: reconstrucción infraestructura"],
        "Aplicación efectiva 2022-2025",
        [{"date": "2022-04-21", "result": "330 sí / 0 no", "stage": "Pleno Congreso"}],
        ["afectados volcán", "agricultores plataneros", "comerciantes"],
        [],
        ["Solidaridad territorial", "Reconstrucción urgente"],
        ["BOE 28/04/2022"],
    ),
    _initiative(
        "leg_paquete_anti_apagones", "RDL Plan Refuerzo Red Eléctrica 2025", "Real Decreto-ley",
        "psoe", ["pedro_sanchez", "yolanda_diaz"], "2025-06-18", "Aprobada",
        "Tras apagón nacional abril 2025: inversión 8.000M€ refuerzo red, almacenamiento. Modificación Ley Sector Eléctrico para almacenamiento. Eufemismo nuclear: extiende vida algunas centrales.",
        ["Art.1: inversión red", "Art.7: almacenamiento", "Disp. trans.: nuclear extensión"],
        "Aplicación inmediata; tensión SUMAR por nuclear",
        [{"date": "2025-07-02", "result": "180 sí / 165 no", "stage": "Convalidación Congreso"}],
        ["consumidores eléctricos", "industria", "sector renovable"],
        ["Insuficiente prevención", "Renuncia transición"],
        ["Lecciones apagón", "Estabilidad red", "Realismo energético"],
        ["BOE 19/06/2025"],
    ),
    _initiative(
        "leg_ley_anti_okupacion", "Ley Acelerada Desalojo Okupación Ilegal", "Ley",
        "pp", ["alberto_nunez_feijoo", "cuca_gamarra"], "2024-09-15", "Tramitación",
        "Acorta plazos judiciales desalojo viviendas okupadas. Refuerza protección propietarios pequeños. Distingue okupación primera/segunda residencia. Iniciativa PP-VOX.",
        ["Art.1: plazos juicio", "Art.5: protección reforzada"],
        "Bloqueada por mayoría progresista",
        [{"date": "2024-12-10", "result": "175 sí / 178 no", "stage": "Toma consideración (rechazo ajustado)"}],
        ["propietarios viviendas", "okupas", "vecindarios afectados"],
        ["Criminaliza pobreza", "Soluciones autoritarias"],
        ["Defensa propiedad", "Seguridad vecinal", "Resolución rápida"],
        ["BOCG 22/09/2024"],
    ),
    _initiative(
        "leg_ley_concordia", "Ley de Concordia (derogación memoria democrática) Aragón", "Ley autonómica",
        "pp", ["jorge_azcon"], "2024-06-15", "Aprobada (autonómica)",
        "Aragón aprueba ley que pretende sustituir Memoria Democrática por concordia equiparando víctimas franquismo y republicanas. PP+VOX. Recurrida ante TC.",
        ["Art.1: equiparación víctimas", "Art.7: simbología"],
        "Recurso TC pendiente; suspensión cautelar",
        [{"date": "2024-06-19", "result": "32 sí / 30 no", "stage": "Pleno Cortes Aragón"}],
        ["víctimas franquismo", "comunidad histórica", "asociaciones memoria"],
        ["Equidistancia falsa", "Negacionismo encubierto", "Inconstitucional"],
        ["Reconciliación", "Pluralismo histórico"],
        ["BOA 25/06/2024"],
    ),
    _initiative(
        "leg_aborto_constitucional", "Reforma Constitucional Aborto", "Reforma constitucional",
        "psoe", ["pedro_sanchez", "monica_garcia"], "2024-11-15", "Tramitación",
        "Inclusión aborto en Constitución como derecho fundamental tras debate europeo. Tramitación lenta por mayoría 3/5.",
        ["Art.43 CE: inclusión IVE"],
        "Tramitación bloqueada por insuficiencia 3/5",
        [{"date": "2025-04-20", "result": "Tramitación abierta", "stage": "Comisión Constitucional"}],
        ["mujeres en edad fértil", "personal sanitario"],
        ["Pretende blindar contra mayorías democráticas", "Innecesario"],
        ["Blindaje derechos", "Estándar Francia 2024", "Refuerzo democrático"],
        ["BOCG 20/11/2024"],
    ),
    _initiative(
        "leg_ley_okupacion_express", "Ley Desahucio Express Catalunya", "Ley autonómica",
        "psoe", ["salvador_illa"], "2024-09-15", "Aprobada (autonómica)",
        "Cataluña aprueba ley de desahucio rápido para fondos buitre que dejen vivienda vacía >2 años. Instrumento Generalitat para ampliar parque público.",
        ["Art.7: desahucio fondos buitre", "Art.14: vivienda vacía"],
        "Recursos pendientes; aplicación parcial",
        [{"date": "2024-11-10", "result": "75 sí / 55 no", "stage": "Pleno Parlament"}],
        ["fondos inversión", "inquilinos", "Generalitat"],
        ["Inseguridad jurídica", "Disuasoria inversión"],
        ["Vivienda asequible", "Lucha contra fondos buitre"],
        ["DOGC 22/09/2024"],
    ),
    _initiative(
        "leg_pre_madrid_2025", "Modificación Ley Suelo Madrid", "Ley autonómica",
        "pp", ["isabel_diaz_ayuso"], "2025-02-15", "Aprobada (autonómica)",
        "Madrid simplifica autorizaciones suelo, acelera urbanización y reduce plazos licencias. Instrumento Ayuso para modelo libertad económica.",
        ["Art.34: licencias express", "Art.45: plazos administrativos"],
        "Aplicación efectiva inmediata",
        [{"date": "2025-04-15", "result": "75 sí / 60 no", "stage": "Pleno Asamblea Madrid"}],
        ["promotores", "constructoras", "vecinos urbanos"],
        ["Especulación urbana", "Pérdida control medioambiental"],
        ["Modernización administrativa", "Atracción inversión"],
        ["BOCM 22/04/2025"],
    ),
    _initiative(
        "leg_proteccion_marismas", "Ley Protección Marismas y Costa", "Ley",
        "sumar", ["ernest_urtasun"], "2024-11-20", "Tramitación",
        "Refuerza protección marismas y costa. Restringe edificación 100m. Prohibe nuevos puertos deportivos. Compensaciones afectados.",
        ["Art.7: zona costera 100m", "Art.18: marismas"],
        "Bloqueo industria turística",
        [{"date": "2025-03-15", "result": "Comisión sin acuerdo", "stage": "Comisión Transición"}],
        ["sector turístico costero", "promotores", "ecologistas"],
        ["Pérdida competitividad turística", "Costes propietarios"],
        ["Lucha cambio climático", "Protección ecosistemas únicos"],
        ["BOCG 25/11/2024"],
    ),
    _initiative(
        "leg_ley_riesgos_psicosociales", "Ley Riesgos Psicosociales Trabajo", "Ley",
        "sumar", ["yolanda_diaz", "monica_garcia"], "2024-08-15", "Tramitación",
        "Marco prevención riesgos psicosociales como riesgo laboral típico. Obligación auditorías estrés, derecho desconexión, sanciones acoso.",
        ["Art.5: auditoría", "Art.18: desconexión", "Art.27: sanciones"],
        "En fase enmiendas",
        [{"date": "2024-12-20", "result": "Toma consideración 195 sí / 150 no", "stage": "Pleno Congreso"}],
        ["asalariados", "RR.HH.", "afectados acoso"],
        ["Burocratización", "Coste empresas"],
        ["Salud mental laboral", "Modernización legislación"],
        ["BOCG 22/08/2024"],
    ),
    _initiative(
        "leg_acuerdo_concierto_vasco_2025", "Acuerdo Concierto Vasco 2025", "Acuerdo bilateral",
        "psoe", ["pedro_sanchez", "imanol_pradales"], "2025-04-15", "Aprobada",
        "Renovación Concierto Económico Vasco. Actualiza cupo. Refuerza autogobierno fiscal. Compromiso plurianual hasta 2030.",
        ["Art.1: cupo", "Art.7: actualización"],
        "Aplicación inmediata",
        [{"date": "2025-05-01", "result": "245 sí / 110 no", "stage": "Pleno Congreso"}],
        ["contribuyentes vascos", "Hacienda Foral", "AGE"],
        ["Privilegio fiscal", "Asimetría territorial"],
        ["Pacto histórico", "Cumplimiento Estatuto Gernika"],
        ["BOE 25/05/2025"],
    ),
    _initiative(
        "leg_oposicion_amnistia", "PNL Derogación Amnistía", "Proposición no de Ley",
        "pp", ["alberto_nunez_feijoo"], "2024-06-15", "Rechazada",
        "Insta al Gobierno a derogar la Ley de Amnistía. Iniciativa simbólica de oposición.",
        ["Único punto: derogación"],
        "Rechazada en Pleno",
        [{"date": "2024-09-15", "result": "169 sí / 178 no", "stage": "Pleno Congreso"}],
        ["amnistiados procés"],
        ["Inconstitucional"],
        ["Defensa Estado Derecho", "Igualdad ante ley"],
        ["BOCG 22/06/2024"],
    ),
    _initiative(
        "leg_tasas_retorno", "Ley Tasas Retorno Productos Tecnológicos", "Ley",
        "sumar", ["yolanda_diaz"], "2024-11-15", "Tramitación",
        "Obliga retorno productos electrónicos a fabricantes. Crea sistema retorno SDDR digital. Lucha obsolescencia programada.",
        ["Art.5: retorno", "Art.14: obsolescencia"],
        "En tramitación",
        [{"date": "2025-01-25", "result": "Toma consideración", "stage": "Comisión Transición"}],
        ["consumidores tecnología", "fabricantes", "recicladores"],
        ["Coste consumidor final"],
        ["Reducción residuos electrónicos", "Economía circular"],
        ["BOCG 22/11/2024"],
    ),
    _initiative(
        "leg_libertad_eleccion_educativa", "Ley Libertad Elección Educativa Madrid", "Ley autonómica",
        "pp", ["isabel_diaz_ayuso"], "2025-03-15", "Aprobada (autonómica)",
        "Madrid refuerza distrito único, libertad lengua y centros adscritos. Choque con LOMLOE estatal. Recurso TC en preparación.",
        ["Art.5: distrito único", "Art.18: libertad lengua"],
        "Aplicación inmediata; recurso TC pendiente",
        [{"date": "2025-05-10", "result": "73 sí / 57 no", "stage": "Pleno Asamblea Madrid"}],
        ["familias escolares", "concertada", "públicos urbanos"],
        ["Segregación social", "Vulnera LOMLOE"],
        ["Libertad familias", "Modelo madrileño"],
        ["BOCM 22/05/2025"],
    ),
    _initiative(
        "leg_ley_emergencia_climatica", "Declaración Emergencia Climática", "Acuerdo Cortes",
        "psoe", ["pedro_sanchez"], "2020-01-21", "Aprobada",
        "Acuerdo declarativo emergencia climática y biodiversidad. Compromiso planes y revisiones quinquenales.",
        ["Único punto: declaración"],
        "Marco simbólico para Ley Cambio Climático posterior",
        [{"date": "2020-09-17", "result": "200 sí / 95 no / 51 abst", "stage": "Pleno Congreso"}],
        ["ciudadanía"],
        ["Simbólica sin medidas"],
        ["Refuerzo institucional", "Marco ético"],
        ["BOCG 22/01/2020"],
    ),
    _initiative(
        "leg_anuncio_ucrania", "Apoyo Refugiados Ucranianos", "Real Decreto-ley",
        "psoe", ["pedro_sanchez"], "2022-03-09", "Aprobada",
        "Marco protección temporal refugiados Ucrania. Acceso inmediato derechos asistencia. Permiso trabajo.",
        ["Art.1: protección temporal", "Art.7: derechos"],
        "200.000 refugiados ucranianos protegidos en España",
        [{"date": "2022-04-15", "result": "330 sí / 0 no", "stage": "Convalidación Congreso"}],
        ["refugiados ucranianos", "Estado, sector asociativo"],
        [],
        ["Solidaridad europea", "Cumplimiento normativa UE"],
        ["BOE 11/03/2022"],
    ),
    _initiative(
        "leg_paro_juvenil", "Plan Empleo Juvenil 2024-2026", "Plan estratégico",
        "psoe", ["yolanda_diaz", "pedro_sanchez"], "2024-04-20", "Aprobada",
        "Plan inversión 5.000M€ contra paro juvenil. Bonificaciones contratación, formación dual, refuerzo SEPE jóvenes.",
        ["Eje 1: contratación", "Eje 2: formación dual"],
        "Reducción paro juvenil al 22% (mejor cifra desde 2008)",
        [{"date": "2024-06-15", "result": "Aprobación Consejo Ministros", "stage": "Plan estratégico"}],
        ["jóvenes 16-29 años", "empresas contratantes", "centros formación"],
        [],
        ["Combatir paro juvenil estructural", "Inversión futuro"],
        ["BOE 22/06/2024"],
    ),
    _initiative(
        "leg_pacto_industria", "Pacto Reindustrialización 2024-2030", "Acuerdo Estado",
        "psoe", ["yolanda_diaz"], "2024-12-15", "Aprobada",
        "Acuerdo Estado-CCAA-sindicatos-patronales reindustrialización. Inversión 12.000M€. Sectores estratégicos: chip, baterías, hidrógeno verde, defensa, biotecnología.",
        ["Eje 1: chip", "Eje 2: baterías"],
        "Aplicación gradual con foco hubs Aragón, Cataluña, Valencia",
        [{"date": "2025-01-30", "result": "Acuerdo plurilateral", "stage": "Mesa diálogo social"}],
        ["sector industrial", "trabajadores afectados", "formación profesional"],
        ["Insuficiente para sector"],
        ["Reindustrialización post-crisis", "Soberanía estratégica"],
        ["BOE 02/02/2025"],
    ),
    _initiative(
        "leg_proteccion_consumidor_energia", "Bono Social Reforzado y Tarifa Última Recurso", "Real Decreto",
        "psoe", ["pedro_sanchez"], "2022-09-15", "Aprobada",
        "Refuerza Bono Social al 70% (vulnerables severos) y 65% (vulnerables). Amplía colectivos protegidos. Tarifa Última Recurso renovada.",
        ["Art.5: bono social", "Art.14: TUR"],
        "1,5M hogares beneficiarios; reducción pobreza energética",
        [{"date": "2022-10-20", "result": "Aprobación Consejo Ministros", "stage": "RD"}],
        ["hogares vulnerables energéticamente", "consumidores domésticos"],
        ["Coste sistema repercutido"],
        ["Lucha pobreza energética", "Compromiso estructural"],
        ["BOE 22/10/2022"],
    ),
]
