from __future__ import annotations

HISTORICAL_NARRATIVES: list[dict] = [
    {
        "id": "narr_vivienda",
        "frame_label": "Crisis de la vivienda",
        "period_start": "2018-01-01",
        "period_end": "2026-05-01",
        "central_claim": "El acceso a la vivienda en alquiler y compra se ha vuelto inviable para clases medias y jóvenes en grandes ciudades.",
        "peak_intensity": 92,
        "lifecycle": "peak",
        "promoting_actors": ["yolanda_diaz", "ione_belarra", "ada_colau", "ernest_urtasun"],
        "opposing_actors": ["isabel_diaz_ayuso", "alberto_nunez_feijoo"],
        "key_events": [
            {"date": "2019-03-05", "description": "Decreto medidas urgentes vivienda"},
            {"date": "2020-12-01", "description": "Manifestaciones por subida alquileres"},
            {"date": "2023-04-27", "description": "Aprobación Ley Estatal por el Derecho a la Vivienda"},
            {"date": "2024-04-13", "description": "Manifestación masiva Madrid contra precios alquiler"},
            {"date": "2024-09-21", "description": "Movimiento Sindicato Inquilinas huelga alquileres"},
            {"date": "2025-04-05", "description": "Aplicación zonas tensionadas en Cataluña"},
            {"date": "2025-11-23", "description": "Tribunal Constitucional avala Ley Vivienda"},
        ],
        "outcomes": ["Ley aprobada pero aplicada solo en Cataluña; tensión territorial", "Surgimiento sindicato de inquilinas como actor clave"],
        "current_status": "Tema dominante en agenda política y mediática",
        "related_narratives": ["narr_inflacion", "narr_brecha_territorial"],
        "influence_score": 95,
    },
    {
        "id": "narr_memoria",
        "frame_label": "Memoria histórica y democrática",
        "period_start": "2018-09-01",
        "period_end": "2026-05-01",
        "central_claim": "La democracia española debe completar reparación a víctimas del franquismo y reformular símbolos públicos heredados.",
        "peak_intensity": 78,
        "lifecycle": "decline",
        "promoting_actors": ["pedro_sanchez", "felix_bolanos", "ernest_urtasun"],
        "opposing_actors": ["santiago_abascal", "alberto_nunez_feijoo", "jose_maria_aznar"],
        "key_events": [
            {"date": "2019-10-24", "description": "Exhumación de Franco del Valle de los Caídos"},
            {"date": "2020-09-15", "description": "Anuncio Ley Memoria Democrática"},
            {"date": "2022-10-19", "description": "Aprobación Ley Memoria Democrática"},
            {"date": "2023-03-21", "description": "Decreto retirada simbología franquista"},
            {"date": "2024-11-20", "description": "Aniversario muerte Franco con tensiones"},
            {"date": "2025-03-15", "description": "Apertura fosas Cuelgamuros para identificación ADN"},
        ],
        "outcomes": ["Ley aprobada pero implementación lenta", "Polarización en torno al tema"],
        "current_status": "Recurrente como wedge issue en aniversarios",
        "related_narratives": ["narr_lawfare", "narr_amnistia"],
        "influence_score": 70,
    },
    {
        "id": "narr_independentismo",
        "frame_label": "Independentismo catalán",
        "period_start": "2018-01-01",
        "period_end": "2026-05-01",
        "central_claim": "Cataluña tiene derecho a decidir su futuro político, posiblemente como Estado independiente.",
        "peak_intensity": 95,
        "lifecycle": "decline",
        "promoting_actors": ["carles_puigdemont", "oriol_junqueras", "pere_aragones", "gabriel_rufian"],
        "opposing_actors": ["santiago_abascal", "salvador_illa", "alberto_nunez_feijoo"],
        "key_events": [
            {"date": "2017-10-01", "description": "Referéndum 1-O"},
            {"date": "2017-10-27", "description": "DUI y aplicación 155"},
            {"date": "2019-10-14", "description": "Sentencia procés"},
            {"date": "2021-06-22", "description": "Indultos del Gobierno"},
            {"date": "2024-05-12", "description": "Elecciones catalanas: PSC mayoritario"},
            {"date": "2024-08-08", "description": "Investidura Salvador Illa"},
            {"date": "2024-08-08", "description": "Regreso Puigdemont y huida"},
        ],
        "outcomes": ["Pérdida hegemonía independentista", "PSC vuelve a la Generalitat"],
        "current_status": "En decadencia, pero latente",
        "related_narratives": ["narr_amnistia", "narr_brecha_territorial"],
        "influence_score": 75,
    },
    {
        "id": "narr_pactos_pp_vox",
        "frame_label": "Pactos PP-VOX en autonomías",
        "period_start": "2019-01-01",
        "period_end": "2026-05-01",
        "central_claim": "El PP normaliza la coalición con la extrema derecha en gobiernos autonómicos y municipales.",
        "peak_intensity": 88,
        "lifecycle": "peak",
        "promoting_actors": ["pedro_sanchez", "yolanda_diaz"],
        "opposing_actors": ["alberto_nunez_feijoo", "santiago_abascal"],
        "key_events": [
            {"date": "2019-01-16", "description": "Andalucía: PP+Cs+VOX (apoyo externo)"},
            {"date": "2022-04-10", "description": "Castilla y León: coalición PP-VOX"},
            {"date": "2023-07-19", "description": "Comunidad Valenciana: gobierno PP-VOX (Mazón)"},
            {"date": "2023-07-12", "description": "Aragón, Baleares, Murcia, Extremadura: PP con VOX"},
            {"date": "2024-07-10", "description": "VOX rompe gobiernos por inmigración"},
        ],
        "outcomes": ["Vox sale de todos los gobiernos autonómicos", "PP gobierna en solitario tras ruptura"],
        "current_status": "Latente, posibles nuevos pactos tras 27M2027",
        "related_narratives": ["narr_inmigracion"],
        "influence_score": 82,
    },
    {
        "id": "narr_amnistia",
        "frame_label": "Ley de Amnistía 2024",
        "period_start": "2023-08-01",
        "period_end": "2026-05-01",
        "central_claim": "La amnistía a los implicados en el procés es un instrumento de convivencia o un fraude constitucional según la posición.",
        "peak_intensity": 96,
        "lifecycle": "decline",
        "promoting_actors": ["pedro_sanchez", "felix_bolanos", "carles_puigdemont", "oriol_junqueras"],
        "opposing_actors": ["alberto_nunez_feijoo", "santiago_abascal", "felipe_gonzalez", "jose_maria_aznar"],
        "key_events": [
            {"date": "2023-11-09", "description": "Anuncio del acuerdo PSOE-Junts"},
            {"date": "2023-11-18", "description": "Manifestación masiva contra amnistía Madrid"},
            {"date": "2024-05-30", "description": "Aprobación Ley de Amnistía"},
            {"date": "2024-06-11", "description": "Recurso del PP ante TC"},
            {"date": "2024-08-08", "description": "Aplicación parcial / Puigdemont y huida"},
            {"date": "2025-06-26", "description": "TC avala Ley de Amnistía con matices"},
        ],
        "outcomes": ["Tribunal Constitucional avala con matices", "Crisis de Estado evitada por escaso margen"],
        "current_status": "Efecto político residual aún relevante",
        "related_narratives": ["narr_independentismo", "narr_lawfare", "narr_acuerdo_investidura_2023"],
        "influence_score": 90,
    },
    {
        "id": "narr_ley_trans",
        "frame_label": "Ley Trans y autodeterminación de género",
        "period_start": "2021-06-01",
        "period_end": "2024-12-31",
        "central_claim": "La autodeterminación de género es un derecho humano básico o una amenaza al feminismo según la posición.",
        "peak_intensity": 80,
        "lifecycle": "dormant",
        "promoting_actors": ["irene_montero", "ione_belarra", "monica_garcia"],
        "opposing_actors": ["santiago_abascal", "rocio_monasterio", "alberto_nunez_feijoo"],
        "key_events": [
            {"date": "2021-06-29", "description": "Aprobación borrador Ministerio Igualdad"},
            {"date": "2022-12-22", "description": "Aprobación en Consejo de Ministros"},
            {"date": "2023-02-16", "description": "Aprobación Ley Trans en Cortes"},
            {"date": "2023-09-15", "description": "Casos polémicos cambios registrales"},
        ],
        "outcomes": ["Aprobada con división interna PSOE", "Polémica con 'rebajas de pena' del solo sí es sí"],
        "current_status": "Latente, sin reforma pendiente",
        "related_narratives": ["narr_solo_si", "narr_pacto_estado_violencia"],
        "influence_score": 60,
    },
    {
        "id": "narr_reforma_laboral",
        "frame_label": "Reforma laboral 2021",
        "period_start": "2021-12-01",
        "period_end": "2023-12-31",
        "central_claim": "La reforma laboral del Gobierno de coalición ha logrado reducir temporalidad sin destruir empleo.",
        "peak_intensity": 65,
        "lifecycle": "dormant",
        "promoting_actors": ["yolanda_diaz", "pedro_sanchez", "patxi_lopez"],
        "opposing_actors": ["alberto_nunez_feijoo", "santiago_abascal"],
        "key_events": [
            {"date": "2021-12-23", "description": "Acuerdo CEOE-CCOO-UGT"},
            {"date": "2022-02-03", "description": "Aprobación en Congreso por error de voto"},
            {"date": "2023-07-10", "description": "OCDE valida la reforma laboral"},
        ],
        "outcomes": ["Reducción contratación temporal a mínimos históricos", "Validación internacional"],
        "current_status": "Capital político consolidado",
        "related_narratives": ["narr_reforma_laboral", "narr_inflacion"],
        "influence_score": 60,
    },
    {
        "id": "narr_imv",
        "frame_label": "Ingreso Mínimo Vital",
        "period_start": "2020-05-01",
        "period_end": "2026-05-01",
        "central_claim": "El IMV ha protegido a colectivos vulnerables pero adolece de problemas de cobertura efectiva.",
        "peak_intensity": 55,
        "lifecycle": "dormant",
        "promoting_actors": ["pedro_sanchez", "ione_belarra"],
        "opposing_actors": ["santiago_abascal", "alberto_nunez_feijoo"],
        "key_events": [
            {"date": "2020-05-29", "description": "Aprobación Real Decreto Ley"},
            {"date": "2022-11-15", "description": "Inclusión complemento ayuda infancia"},
            {"date": "2024-01-15", "description": "Informe AIReF: cobertura 50% objetivo"},
        ],
        "outcomes": ["Implementado con baja tasa de aceptación inicial", "Mejora gradual cobertura"],
        "current_status": "Estructural, debate técnico",
        "related_narratives": ["narr_imv", "narr_brecha_territorial"],
        "influence_score": 45,
    },
    {
        "id": "narr_tasa_tobin",
        "frame_label": "Impuesto a transacciones financieras (Tasa Tobin)",
        "period_start": "2020-10-01",
        "period_end": "2024-12-31",
        "central_claim": "Las grandes corporaciones financieras deben aportar más al sostenimiento del Estado.",
        "peak_intensity": 40,
        "lifecycle": "dormant",
        "promoting_actors": ["pedro_sanchez", "maria_jesus_montero", "yolanda_diaz"],
        "opposing_actors": ["alberto_nunez_feijoo", "esteban_gonzalez_pons"],
        "key_events": [
            {"date": "2020-10-15", "description": "Aprobación impuesto"},
            {"date": "2021-01-16", "description": "Entrada en vigor"},
            {"date": "2023-12-19", "description": "Prórroga indefinida impuestos extraordinarios banca y energéticas"},
        ],
        "outcomes": ["Implementado con menor recaudación esperada", "Prorrogado impuesto extraordinario"],
        "current_status": "Consolidado",
        "related_narratives": ["narr_inflacion"],
        "influence_score": 35,
    },
    {
        "id": "narr_covid",
        "frame_label": "Gestión COVID-19",
        "period_start": "2020-03-01",
        "period_end": "2022-12-31",
        "central_claim": "La gestión gubernamental de la pandemia fue insuficiente o adecuada según el espectro político.",
        "peak_intensity": 100,
        "lifecycle": "dormant",
        "promoting_actors": ["pedro_sanchez", "salvador_illa"],
        "opposing_actors": ["isabel_diaz_ayuso", "santiago_abascal", "pablo_casado"],
        "key_events": [
            {"date": "2020-03-14", "description": "Estado de Alarma"},
            {"date": "2020-04-15", "description": "Pico hospitalizaciones primera ola"},
            {"date": "2021-05-09", "description": "Fin Estado Alarma"},
            {"date": "2021-12-15", "description": "Vacunación al 80% mayores 12 años"},
        ],
        "outcomes": ["Vacunación masiva exitosa", "Polarización gestión sanitaria"],
        "current_status": "Cerrada, tema marginal",
        "related_narratives": ["narr_vacunacion"],
        "influence_score": 30,
    },
    {
        "id": "narr_vacunacion",
        "frame_label": "Vacunación masiva",
        "period_start": "2020-12-01",
        "period_end": "2022-06-30",
        "central_claim": "España logró una de las mayores tasas de vacunación de Europa demostrando capacidad técnica del SNS.",
        "peak_intensity": 75,
        "lifecycle": "dormant",
        "promoting_actors": ["pedro_sanchez", "monica_garcia"],
        "opposing_actors": ["santiago_abascal"],
        "key_events": [
            {"date": "2020-12-27", "description": "Primera vacunación Araceli"},
            {"date": "2021-04-09", "description": "Polémica vacunación cargos públicos"},
            {"date": "2021-08-30", "description": "70% pauta completa"},
        ],
        "outcomes": ["Éxito pauta vacunal", "Plataforma capital político breve"],
        "current_status": "Cerrada",
        "related_narratives": ["narr_covid"],
        "influence_score": 25,
    },
    {
        "id": "narr_transicion_energetica",
        "frame_label": "Transición energética",
        "period_start": "2020-01-01",
        "period_end": "2026-05-01",
        "central_claim": "España puede liderar transición verde aprovechando renovables solares y eólicas, pero a costa industria intensiva.",
        "peak_intensity": 70,
        "lifecycle": "peak",
        "promoting_actors": ["yolanda_diaz", "ernest_urtasun", "monica_garcia"],
        "opposing_actors": ["santiago_abascal", "jorge_buxade"],
        "key_events": [
            {"date": "2021-05-21", "description": "Ley Cambio Climático"},
            {"date": "2023-07-21", "description": "Plan Nacional Integrado Energía y Clima"},
            {"date": "2024-12-15", "description": "Subasta hidrógeno verde"},
            {"date": "2025-04-28", "description": "Apagón nacional 2025"},
        ],
        "outcomes": ["España líder solar UE", "Tensiones industriales"],
        "current_status": "Activo, con debate post-apagón",
        "related_narratives": ["narr_apagon", "narr_precio_energia"],
        "influence_score": 78,
    },
    {
        "id": "narr_precio_energia",
        "frame_label": "Crisis precio energía 2022",
        "period_start": "2021-09-01",
        "period_end": "2024-06-30",
        "central_claim": "El sistema marginalista dispara facturas por encima del costo real, exigiendo intervención pública.",
        "peak_intensity": 90,
        "lifecycle": "dormant",
        "promoting_actors": ["pedro_sanchez", "yolanda_diaz", "ione_belarra"],
        "opposing_actors": ["alberto_nunez_feijoo"],
        "key_events": [
            {"date": "2021-09-14", "description": "Bono social ampliado"},
            {"date": "2022-06-15", "description": "Excepción ibérica precio gas"},
            {"date": "2022-09-08", "description": "Plan ahorro energético"},
            {"date": "2023-12-19", "description": "Prórroga IVA reducido luz y gas"},
        ],
        "outcomes": ["Excepción ibérica como modelo UE", "Estabilización precios 2024"],
        "current_status": "Cerrada con normalización",
        "related_narratives": ["narr_inflacion"],
        "influence_score": 65,
    },
    {
        "id": "narr_inflacion",
        "frame_label": "Inflación 2022-2023",
        "period_start": "2022-01-01",
        "period_end": "2024-06-30",
        "central_claim": "La pérdida de poder adquisitivo erosiona ingresos reales pese a recuperación nominal.",
        "peak_intensity": 92,
        "lifecycle": "dormant",
        "promoting_actors": ["pedro_sanchez", "yolanda_diaz", "alberto_nunez_feijoo"],
        "opposing_actors": [],
        "key_events": [
            {"date": "2022-07-01", "description": "Pico IPC 10,8% interanual"},
            {"date": "2022-09-14", "description": "Bonificación 20 céntimos gasolina"},
            {"date": "2023-12-31", "description": "IPC fin año 3,1%"},
        ],
        "outcomes": ["Subida pensiones por IPC", "Erosión salarios reales"],
        "current_status": "Latente, recuperación parcial 2024-2026",
        "related_narratives": ["narr_precio_energia", "narr_vivienda"],
        "influence_score": 80,
    },
    {
        "id": "narr_sequia",
        "frame_label": "Sequía e infraestructura hídrica",
        "period_start": "2022-06-01",
        "period_end": "2025-09-30",
        "central_claim": "España afronta sequía estructural agravada por cambio climático y mala planificación hídrica.",
        "peak_intensity": 75,
        "lifecycle": "decline",
        "promoting_actors": ["alberto_nunez_feijoo", "carlos_mazon", "juanma_moreno"],
        "opposing_actors": ["pedro_sanchez", "ernest_urtasun"],
        "key_events": [
            {"date": "2022-08-01", "description": "Restricciones agua Andalucía"},
            {"date": "2023-04-01", "description": "Cataluña fase emergencia hídrica"},
            {"date": "2024-04-19", "description": "Lluvias y desactivación emergencia"},
            {"date": "2025-08-15", "description": "Nueva emergencia hídrica Levante"},
        ],
        "outcomes": ["Inversión histórica desalación", "Conflicto trasvase Tajo-Segura"],
        "current_status": "Latente con picos estacionales",
        "related_narratives": ["narr_dana_valencia", "narr_brecha_territorial"],
        "influence_score": 65,
    },
    {
        "id": "narr_inmigracion",
        "frame_label": "Inmigración y fronteras",
        "period_start": "2018-06-01",
        "period_end": "2026-05-01",
        "central_claim": "España debe gestionar flujos migratorios con visión humanitaria o cierre fronterizo según posición.",
        "peak_intensity": 88,
        "lifecycle": "peak",
        "promoting_actors": ["pedro_sanchez", "fernando_clavijo", "felix_bolanos"],
        "opposing_actors": ["santiago_abascal", "rocio_monasterio", "jorge_buxade"],
        "key_events": [
            {"date": "2018-08-01", "description": "Aquarius llega a Valencia"},
            {"date": "2020-11-15", "description": "Crisis Canarias y muelle Arguineguín"},
            {"date": "2024-08-15", "description": "Ola migratoria Canarias récord"},
            {"date": "2025-03-15", "description": "Reforma Ley Extranjería"},
            {"date": "2025-07-12", "description": "Vox abandona gobiernos autonómicos por menores"},
        ],
        "outcomes": ["Reforma Extranjería con consenso PP-PSOE", "Vox refuerza discurso identitario"],
        "current_status": "Tema dominante en debate público",
        "related_narratives": ["narr_pactos_pp_vox", "narr_inmigracion"],
        "influence_score": 92,
    },
    {
        "id": "narr_corrupcion_koldo",
        "frame_label": "Casos corrupción (Koldo, Begoña, hermano Sánchez)",
        "period_start": "2024-02-01",
        "period_end": "2026-05-01",
        "central_claim": "Casos de presunta corrupción del entorno PSOE erosionan credibilidad del Gobierno.",
        "peak_intensity": 90,
        "lifecycle": "peak",
        "promoting_actors": ["alberto_nunez_feijoo", "cuca_gamarra", "santiago_abascal"],
        "opposing_actors": ["pedro_sanchez", "felix_bolanos"],
        "key_events": [
            {"date": "2024-02-21", "description": "Detención Koldo García (ex asesor Ábalos)"},
            {"date": "2024-04-24", "description": "Carta a la ciudadanía Sánchez (5 días reflexión)"},
            {"date": "2024-04-29", "description": "Sánchez decide continuar"},
            {"date": "2024-09-05", "description": "Imputación Begoña Gómez"},
            {"date": "2025-02-10", "description": "Imputación David Sánchez"},
            {"date": "2025-10-15", "description": "Investigación parlamentaria caso Koldo"},
        ],
        "outcomes": ["Erosión credibilidad", "Polarización extrema mediática"],
        "current_status": "Activo y dominante",
        "related_narratives": ["narr_lawfare", "narr_amnistia"],
        "influence_score": 95,
    },
    {
        "id": "narr_lawfare",
        "frame_label": "Lawfare contra el Gobierno",
        "period_start": "2023-11-01",
        "period_end": "2026-05-01",
        "central_claim": "Sectores judiciales y mediáticos coordinados buscan tumbar al Gobierno con causas instrumentalizadas.",
        "peak_intensity": 80,
        "lifecycle": "peak",
        "promoting_actors": ["pedro_sanchez", "felix_bolanos", "ernest_urtasun"],
        "opposing_actors": ["alberto_nunez_feijoo", "isabel_diaz_ayuso"],
        "key_events": [
            {"date": "2024-04-24", "description": "Carta Sánchez por causa Begoña Gómez"},
            {"date": "2024-12-10", "description": "Comisión investigación lawfare Congreso"},
            {"date": "2025-06-05", "description": "Sentencia exculpatoria juez Peinado"},
        ],
        "outcomes": ["Polarización extrema en justicia", "Reforma CGPJ pendiente"],
        "current_status": "Activo, marco interpretativo dominante PSOE",
        "related_narratives": ["narr_corrupcion_koldo", "narr_amnistia"],
        "influence_score": 75,
    },
    {
        "id": "narr_pegasus",
        "frame_label": "Espionaje Pegasus",
        "period_start": "2022-04-01",
        "period_end": "2024-06-30",
        "central_claim": "El espionaje masivo del Estado contra políticos catalanes y vascos es una crisis democrática.",
        "peak_intensity": 75,
        "lifecycle": "dormant",
        "promoting_actors": ["oriol_junqueras", "pere_aragones", "mertxe_aizpurua"],
        "opposing_actors": ["pedro_sanchez", "felix_bolanos"],
        "key_events": [
            {"date": "2022-04-18", "description": "Citizen Lab: 65 espionajes catalanes"},
            {"date": "2022-05-02", "description": "Espionaje a Sánchez y Robles"},
            {"date": "2022-05-10", "description": "Cese directora CNI Paz Esteban"},
        ],
        "outcomes": ["Investigación parlamentaria sin sanciones efectivas", "Tensión con independentismo"],
        "current_status": "Inactivo",
        "related_narratives": ["narr_independentismo"],
        "influence_score": 50,
    },
    {
        "id": "narr_rey_emerito",
        "frame_label": "Caso Rey Emérito Juan Carlos I",
        "period_start": "2020-08-01",
        "period_end": "2024-12-31",
        "central_claim": "La conducta financiera del Rey Emérito ha erosionado la institución y exige rendición de cuentas.",
        "peak_intensity": 80,
        "lifecycle": "dormant",
        "promoting_actors": ["yolanda_diaz", "ione_belarra", "irene_montero", "gabriel_rufian"],
        "opposing_actors": ["jose_maria_aznar", "pedro_sanchez"],
        "key_events": [
            {"date": "2020-08-03", "description": "Salida Juan Carlos I a Abu Dhabi"},
            {"date": "2022-03-02", "description": "Archivo causas Tribunal Supremo"},
            {"date": "2022-05-19", "description": "Visita relámpago Sanxenxo"},
            {"date": "2024-11-21", "description": "Memorias 'Reconciliación'"},
        ],
        "outcomes": ["Distanciamiento institucional Felipe VI", "Causas archivadas"],
        "current_status": "Latente",
        "related_narratives": ["narr_monarquia"],
        "influence_score": 55,
    },
    {
        "id": "narr_monarquia",
        "frame_label": "Monarquía vs República",
        "period_start": "2018-01-01",
        "period_end": "2026-05-01",
        "central_claim": "España debe reformular o abolir la jefatura de Estado hereditaria por una elegida.",
        "peak_intensity": 60,
        "lifecycle": "decline",
        "promoting_actors": ["yolanda_diaz", "ione_belarra", "irene_montero", "gabriel_rufian"],
        "opposing_actors": ["pedro_sanchez", "alberto_nunez_feijoo", "santiago_abascal"],
        "key_events": [
            {"date": "2014-06-19", "description": "Abdicación Juan Carlos I"},
            {"date": "2020-03-15", "description": "Casa Real renuncia herencia"},
            {"date": "2024-10-31", "description": "Princesa Leonor jura Constitución"},
            {"date": "2025-06-19", "description": "10 aniversario Felipe VI"},
        ],
        "outcomes": ["Estabilidad Felipe VI", "Republicanismo minoritario"],
        "current_status": "Latente, sin reforma constitucional viable",
        "related_narratives": ["narr_rey_emerito"],
        "influence_score": 45,
    },
    {
        "id": "narr_indultos",
        "frame_label": "Indultos a líderes del procés",
        "period_start": "2021-04-01",
        "period_end": "2022-06-30",
        "central_claim": "Los indultos son un acto de magnanimidad estatal o un fraude a sentencia firme según posición.",
        "peak_intensity": 78,
        "lifecycle": "dormant",
        "promoting_actors": ["pedro_sanchez", "felix_bolanos"],
        "opposing_actors": ["pablo_casado", "alberto_nunez_feijoo", "santiago_abascal"],
        "key_events": [
            {"date": "2021-06-22", "description": "Indultos parciales aprobados"},
            {"date": "2021-07-14", "description": "Manifestación contra indultos"},
            {"date": "2022-03-24", "description": "Anulación sentencia TC parcial"},
        ],
        "outcomes": ["Apertura mesa de diálogo", "Polarización persistente"],
        "current_status": "Cerrada, sustituida por amnistía",
        "related_narratives": ["narr_amnistia", "narr_independentismo"],
        "influence_score": 55,
    },
    {
        "id": "narr_mesa_dialogo",
        "frame_label": "Mesa de diálogo Cataluña",
        "period_start": "2020-09-01",
        "period_end": "2024-08-08",
        "central_claim": "El diálogo institucional entre el Gobierno y la Generalitat es vía solución al conflicto territorial.",
        "peak_intensity": 60,
        "lifecycle": "dormant",
        "promoting_actors": ["pedro_sanchez", "pere_aragones", "salvador_illa"],
        "opposing_actors": ["alberto_nunez_feijoo", "santiago_abascal"],
        "key_events": [
            {"date": "2020-09-10", "description": "Acuerdo creación mesa"},
            {"date": "2022-07-27", "description": "Reforma Código Penal sedición"},
            {"date": "2023-12-19", "description": "Acuerdo financiación catalana"},
        ],
        "outcomes": ["Reformas penales reales", "Creación marco de diálogo permanente"],
        "current_status": "Cerrada por victoria PSC",
        "related_narratives": ["narr_independentismo", "narr_amnistia"],
        "influence_score": 50,
    },
    {
        "id": "narr_pacto_estado_violencia",
        "frame_label": "Pacto de Estado contra violencia de género",
        "period_start": "2017-09-01",
        "period_end": "2026-05-01",
        "central_claim": "La violencia machista exige consenso transversal y refuerzo presupuestario continuado.",
        "peak_intensity": 70,
        "lifecycle": "peak",
        "promoting_actors": ["pedro_sanchez", "yolanda_diaz", "monica_garcia", "irene_montero"],
        "opposing_actors": ["santiago_abascal", "rocio_monasterio"],
        "key_events": [
            {"date": "2017-09-28", "description": "Aprobación Pacto"},
            {"date": "2022-12-22", "description": "Renovación con ampliación 2027"},
            {"date": "2024-11-25", "description": "Manifestación 25N global"},
            {"date": "2025-09-15", "description": "Ampliación recursos psicosociales"},
        ],
        "outcomes": ["Consenso amplio salvo VOX", "Reforzamiento normativo"],
        "current_status": "Activo, debate sobre eficacia",
        "related_narratives": ["narr_solo_si", "narr_pacto_estado_violencia"],
        "influence_score": 75,
    },
    {
        "id": "narr_acuerdo_investidura_2023",
        "frame_label": "Acuerdo PSOE-Junts investidura 2023",
        "period_start": "2023-11-01",
        "period_end": "2026-05-01",
        "central_claim": "El acuerdo PSOE-Junts es bisagra de gobernabilidad o capitulación según posición.",
        "peak_intensity": 95,
        "lifecycle": "decline",
        "promoting_actors": ["pedro_sanchez", "felix_bolanos", "carles_puigdemont"],
        "opposing_actors": ["alberto_nunez_feijoo", "santiago_abascal", "felipe_gonzalez"],
        "key_events": [
            {"date": "2023-11-09", "description": "Acuerdo Bruselas PSOE-Junts"},
            {"date": "2023-11-16", "description": "Investidura Sánchez"},
            {"date": "2024-07-15", "description": "Junts vota contra senda déficit"},
            {"date": "2024-10-28", "description": "Crisis Junts: rotura presupuestos"},
            {"date": "2025-07-08", "description": "Junts retira apoyos parlamentarios"},
        ],
        "outcomes": ["Gobierno débil con apoyos volátiles", "Tensiones internas constantes"],
        "current_status": "Crítico, riesgo elecciones anticipadas",
        "related_narratives": ["narr_amnistia", "narr_acuerdo_investidura_2023"],
        "influence_score": 88,
    },
    {
        "id": "narr_coalicion_progresista",
        "frame_label": "Coalición progresista PSOE-Sumar",
        "period_start": "2023-11-01",
        "period_end": "2026-05-01",
        "central_claim": "El gobierno de coalición es la primera vez en democracia y muestra modelo posible o imposible según mirada.",
        "peak_intensity": 80,
        "lifecycle": "decline",
        "promoting_actors": ["pedro_sanchez", "yolanda_diaz", "ernest_urtasun", "monica_garcia"],
        "opposing_actors": ["alberto_nunez_feijoo", "santiago_abascal", "ione_belarra"],
        "key_events": [
            {"date": "2020-01-13", "description": "Primera coalición Sánchez-Iglesias"},
            {"date": "2023-11-16", "description": "Coalición Sánchez-Díaz"},
            {"date": "2024-06-09", "description": "Crisis Sumar tras europeas"},
            {"date": "2024-10-24", "description": "Dimisión Errejón"},
            {"date": "2025-03-23", "description": "Asamblea Sumar reorganización"},
        ],
        "outcomes": ["Reformas históricas (laboral, vivienda)", "Erosión Sumar mediática"],
        "current_status": "En crisis interna SUMAR, pero gobierno mantenido",
        "related_narratives": ["narr_acuerdo_investidura_2023", "narr_reforma_laboral"],
        "influence_score": 80,
    },
    {
        "id": "narr_dana_valencia",
        "frame_label": "DANA Valencia octubre 2024",
        "period_start": "2024-10-29",
        "period_end": "2026-05-01",
        "central_claim": "La gestión deficiente de la DANA y la respuesta tardía revelan fallos institucionales graves.",
        "peak_intensity": 100,
        "lifecycle": "peak",
        "promoting_actors": ["pedro_sanchez", "yolanda_diaz", "vicent_marza"],
        "opposing_actors": ["carlos_mazon", "alberto_nunez_feijoo"],
        "key_events": [
            {"date": "2024-10-29", "description": "Avenida lluvias DANA: 220+ víctimas"},
            {"date": "2024-10-31", "description": "Visita reyes y políticos: incidentes Paiporta"},
            {"date": "2024-11-09", "description": "Manifestación 100.000 contra Mazón"},
            {"date": "2025-04-29", "description": "Comisión investigación CV"},
            {"date": "2025-09-15", "description": "Imputación cargos Generalitat"},
        ],
        "outcomes": ["Crisis Mazón con peticiones masivas dimisión", "Investigación judicial"],
        "current_status": "Activo y muy intenso",
        "related_narratives": ["narr_sequia", "narr_pactos_pp_vox"],
        "influence_score": 98,
    },
    {
        "id": "narr_brecha_territorial",
        "frame_label": "Brecha territorial y financiación",
        "period_start": "2018-01-01",
        "period_end": "2026-05-01",
        "central_claim": "El modelo de financiación autonómica genera desequilibrios entre regiones que erosionan cohesión.",
        "peak_intensity": 70,
        "lifecycle": "peak",
        "promoting_actors": ["juanma_moreno", "alfonso_rueda", "andoni_ortuzar"],
        "opposing_actors": ["pedro_sanchez", "maria_jesus_montero"],
        "key_events": [
            {"date": "2021-12-20", "description": "Reforma fiscal autonómica"},
            {"date": "2023-12-19", "description": "Acuerdo financiación catalana singular"},
            {"date": "2024-07-15", "description": "Conferencia presidentes financiación"},
            {"date": "2025-05-01", "description": "Pacto País Vasco-Estado nuevo concierto"},
        ],
        "outcomes": ["Modelo en revisión continua", "Tensión Cataluña-resto"],
        "current_status": "Estructural, recurrente",
        "related_narratives": ["narr_amnistia", "narr_independentismo"],
        "influence_score": 70,
    },
    {
        "id": "narr_solo_si",
        "frame_label": "Ley solo sí es sí",
        "period_start": "2022-08-01",
        "period_end": "2024-06-30",
        "central_claim": "La reforma de delitos sexuales era necesaria pero generó rebajas de pena imprevistas.",
        "peak_intensity": 88,
        "lifecycle": "dormant",
        "promoting_actors": ["irene_montero", "ione_belarra"],
        "opposing_actors": ["alberto_nunez_feijoo", "santiago_abascal", "rocio_monasterio"],
        "key_events": [
            {"date": "2022-08-25", "description": "Aprobación Ley"},
            {"date": "2023-04-18", "description": "Reforma técnica"},
            {"date": "2024-02-15", "description": "Datos consolidados rebajas"},
        ],
        "outcomes": ["Aprobada con reforma técnica", "Erosión política Igualdad"],
        "current_status": "Cerrada, debate marginal",
        "related_narratives": ["narr_ley_trans", "narr_pacto_estado_violencia"],
        "influence_score": 65,
    },
    {
        "id": "narr_apagon",
        "frame_label": "Apagón nacional abril 2025",
        "period_start": "2025-04-28",
        "period_end": "2026-05-01",
        "central_claim": "El apagón eléctrico nacional revela debilidades del sistema y el debate sobre transición energética.",
        "peak_intensity": 95,
        "lifecycle": "decline",
        "promoting_actors": ["pedro_sanchez", "yolanda_diaz"],
        "opposing_actors": ["alberto_nunez_feijoo", "santiago_abascal", "isabel_diaz_ayuso"],
        "key_events": [
            {"date": "2025-04-28", "description": "Apagón eléctrico peninsular durante 12 horas"},
            {"date": "2025-04-29", "description": "Restablecimiento gradual servicio"},
            {"date": "2025-06-15", "description": "Informe técnico ENTSO-E"},
            {"date": "2025-09-01", "description": "Plan refuerzo red"},
        ],
        "outcomes": ["Inversión histórica en red", "Debate sobre nuclear"],
        "current_status": "En decadencia tras informe técnico",
        "related_narratives": ["narr_transicion_energetica"],
        "influence_score": 75,
    },
]
