from __future__ import annotations

PARTIES: list[dict] = [
    {
        "id": "psoe",
        "name": "Partido Socialista Obrero Español",
        "short_name": "PSOE",
        "founded_year": 1879,
        "color": "#E30613",
        "ideology": ["socialdemocracia", "progresismo", "europeismo", "centroizquierda"],
        "current_leader_id": "pedro_sanchez",
        "secretary_general": "Pedro Sánchez",
        "vice_secretaries": ["María Jesús Montero", "Pilar Alegría"],
        "congress_seats": 121,
        "senate_seats": 72,
        "european_seats": 20,
        "regional_governments": ["Asturias", "Castilla-La Mancha", "Navarra"],
        "municipal_strongholds": ["Sevilla", "Barcelona", "A Coruña"],
        "affiliated_youth_org": "Juventudes Socialistas de España",
        "last_congress_date": "2024-11-30",
        "polling_average_30d": 30.4,
        "polling_trend": "stable",
        "key_alliances": ["sumar", "erc", "pnv", "bildu", "bng"],
        "historical_results": {2008: 169, 2011: 110, 2015: 90, 2016: 85, 2019: 123, "2019_nov": 120, 2023: 121},
        "notable_internal_factions": ["sanchismo", "felipismo", "renovadores"],
        "primary_constituencies": ["Andalucía", "Extremadura", "Asturias", "Castilla-La Mancha"],
        "weakness_constituencies": ["Madrid", "País Vasco urbano", "Cataluña"],
        "key_dates_calendar": ["41 Congreso Federal 2024-11-30"],
        "ideological_position": {"economic_axis": -3, "social_axis": -5},
    },
    {
        "id": "pp",
        "name": "Partido Popular",
        "short_name": "PP",
        "founded_year": 1989,
        "color": "#0056A8",
        "ideology": ["conservadurismo", "liberalismo economico", "democracia cristiana", "centroderecha"],
        "current_leader_id": "alberto_nunez_feijoo",
        "secretary_general": "Cuca Gamarra",
        "vice_secretaries": ["Borja Sémper", "Esteban González Pons", "Elías Bendodo"],
        "congress_seats": 137,
        "senate_seats": 120,
        "european_seats": 22,
        "regional_governments": ["Andalucía", "Galicia", "Madrid", "Murcia", "Castilla y León", "Aragón", "Comunidad Valenciana", "Baleares", "La Rioja", "Cantabria", "Extremadura"],
        "municipal_strongholds": ["Madrid", "Málaga", "Zaragoza"],
        "affiliated_youth_org": "Nuevas Generaciones del PP",
        "last_congress_date": "2022-04-02",
        "polling_average_30d": 33.8,
        "polling_trend": "rising",
        "key_alliances": ["vox", "upn", "cc"],
        "historical_results": {2008: 154, 2011: 186, 2015: 123, 2016: 137, 2019: 66, "2019_nov": 89, 2023: 137},
        "notable_internal_factions": ["aznaristas", "marianistas", "ayusistas", "feijooistas"],
        "primary_constituencies": ["Madrid", "Galicia", "Castilla y León", "Murcia"],
        "weakness_constituencies": ["Cataluña", "País Vasco", "Andalucía rural"],
        "key_dates_calendar": ["20 Congreso Nacional 2022-04-02"],
        "ideological_position": {"economic_axis": 5, "social_axis": 3},
    },
    {
        "id": "vox",
        "name": "Vox",
        "short_name": "VOX",
        "founded_year": 2013,
        "color": "#5AC035",
        "ideology": ["derecha radical", "nacionalismo español", "conservadurismo social", "euroescepticismo"],
        "current_leader_id": "santiago_abascal",
        "secretary_general": "Ignacio Garriga",
        "vice_secretaries": ["Jorge Buxadé", "Javier Ortega Smith"],
        "congress_seats": 33,
        "senate_seats": 4,
        "european_seats": 6,
        "regional_governments": [],
        "municipal_strongholds": ["Murcia", "Toledo"],
        "affiliated_youth_org": "Revuelta",
        "last_congress_date": "2024-07-21",
        "polling_average_30d": 14.2,
        "polling_trend": "rising",
        "key_alliances": ["pp"],
        "historical_results": {2019: 24, "2019_nov": 52, 2023: 33},
        "notable_internal_factions": ["abascalistas", "macarenistas (escindidos)"],
        "primary_constituencies": ["Murcia", "Andalucía rural", "Castilla y León"],
        "weakness_constituencies": ["País Vasco", "Cataluña", "Galicia"],
        "key_dates_calendar": ["IV Asamblea Nacional 2024-07-21"],
        "ideological_position": {"economic_axis": 4, "social_axis": 8},
    },
    {
        "id": "sumar",
        "name": "Sumar",
        "short_name": "SUMAR",
        "founded_year": 2023,
        "color": "#E5007D",
        "ideology": ["izquierda", "ecologismo", "feminismo", "progresismo", "republicanismo"],
        "current_leader_id": "yolanda_diaz",
        "secretary_general": "Lara Hernández",
        "vice_secretaries": ["Ernest Urtasun", "Mónica García"],
        "congress_seats": 27,
        "senate_seats": 1,
        "european_seats": 3,
        "regional_governments": [],
        "municipal_strongholds": ["Barcelona (compartido)"],
        "affiliated_youth_org": "Juventudes Sumar",
        "last_congress_date": "2025-03-23",
        "polling_average_30d": 4.6,
        "polling_trend": "declining",
        "key_alliances": ["psoe", "iu", "comuns"],
        "historical_results": {2023: 31},
        "notable_internal_factions": ["IU", "Comunes", "Más Madrid", "Compromís", "Verdes Equo"],
        "primary_constituencies": ["Madrid urbano", "Barcelona", "Valencia"],
        "weakness_constituencies": ["zonas rurales", "Andalucía oriental"],
        "key_dates_calendar": ["Asamblea fundacional 2025-03-23"],
        "ideological_position": {"economic_axis": -7, "social_axis": -8},
    },
    {
        "id": "podemos",
        "name": "Podemos",
        "short_name": "PODEMOS",
        "founded_year": 2014,
        "color": "#6A2E70",
        "ideology": ["izquierda", "populismo de izquierda", "republicanismo", "feminismo"],
        "current_leader_id": "ione_belarra",
        "secretary_general": "Ione Belarra",
        "vice_secretaries": ["Irene Montero", "Pablo Fernández"],
        "congress_seats": 4,
        "senate_seats": 0,
        "european_seats": 2,
        "regional_governments": [],
        "municipal_strongholds": [],
        "affiliated_youth_org": "Juventudes Podemos",
        "last_congress_date": "2024-11-23",
        "polling_average_30d": 3.5,
        "polling_trend": "stable",
        "key_alliances": [],
        "historical_results": {2015: 69, 2016: 71, 2019: 35, "2019_nov": 26, 2023: 4},
        "notable_internal_factions": ["pablistas", "errejonistas (escindidos)", "anticapitalistas"],
        "primary_constituencies": ["Madrid urbano", "Asturias"],
        "weakness_constituencies": ["resto del Estado"],
        "key_dates_calendar": ["IV Asamblea Ciudadana 2024-11-23"],
        "ideological_position": {"economic_axis": -8, "social_axis": -7},
    },
    {
        "id": "erc",
        "name": "Esquerra Republicana de Catalunya",
        "short_name": "ERC",
        "founded_year": 1931,
        "color": "#FFB232",
        "ideology": ["independentismo catalan", "republicanismo", "socialdemocracia", "ecologismo"],
        "current_leader_id": "oriol_junqueras",
        "secretary_general": "Elisenda Alamany",
        "vice_secretaries": ["Raquel Sans", "Isaac Albert"],
        "congress_seats": 7,
        "senate_seats": 6,
        "european_seats": 1,
        "regional_governments": [],
        "municipal_strongholds": ["Tarragona", "Lleida", "Girona"],
        "affiliated_youth_org": "JERC",
        "last_congress_date": "2024-11-30",
        "polling_average_30d": 6.8,
        "polling_trend": "declining",
        "key_alliances": ["psoe (legislatura)", "bng", "bildu"],
        "historical_results": {2015: 9, 2016: 9, 2019: 15, "2019_nov": 13, 2023: 7},
        "notable_internal_factions": ["junquerismo", "rovirismo (escindido)", "Foc Nou"],
        "primary_constituencies": ["Cataluña interior", "Girona", "Lleida"],
        "weakness_constituencies": ["resto del Estado"],
        "key_dates_calendar": ["Congrés Nacional 2024-11-30"],
        "ideological_position": {"economic_axis": -3, "social_axis": -6},
    },
    {
        "id": "junts",
        "name": "Junts per Catalunya",
        "short_name": "JUNTS",
        "founded_year": 2020,
        "color": "#5AB6E4",
        "ideology": ["independentismo catalan", "liberalismo", "centroderecha catalanista"],
        "current_leader_id": "carles_puigdemont",
        "secretary_general": "Jordi Turull",
        "vice_secretaries": ["Míriam Nogueras", "Josep Rius"],
        "congress_seats": 7,
        "senate_seats": 2,
        "european_seats": 1,
        "regional_governments": [],
        "municipal_strongholds": ["Vic", "Manresa", "Igualada"],
        "affiliated_youth_org": "Jovent Republicà (afín)",
        "last_congress_date": "2024-06-30",
        "polling_average_30d": 4.1,
        "polling_trend": "stable",
        "key_alliances": ["psoe (investidura)"],
        "historical_results": {2019: 8, "2019_nov": 8, 2023: 7},
        "notable_internal_factions": ["puigdemontistas", "pragmaticos"],
        "primary_constituencies": ["Cataluña interior", "Girona"],
        "weakness_constituencies": ["resto del Estado"],
        "key_dates_calendar": ["Congrés 2024-06-30"],
        "ideological_position": {"economic_axis": 3, "social_axis": -2},
    },
    {
        "id": "pnv",
        "name": "Partido Nacionalista Vasco",
        "short_name": "PNV",
        "founded_year": 1895,
        "color": "#0E823A",
        "ideology": ["nacionalismo vasco", "democracia cristiana", "centro"],
        "current_leader_id": "andoni_ortuzar",
        "secretary_general": "Andoni Ortuzar",
        "vice_secretaries": ["Itxaso Atutxa", "Joseba Aguirretxea"],
        "congress_seats": 5,
        "senate_seats": 4,
        "european_seats": 1,
        "regional_governments": ["País Vasco"],
        "municipal_strongholds": ["Bilbao", "Vitoria", "Donostia"],
        "affiliated_youth_org": "EGI",
        "last_congress_date": "2025-01-25",
        "polling_average_30d": 1.4,
        "polling_trend": "stable",
        "key_alliances": ["psoe (legislatura)", "psoe-euskadi (gobierno vasco)"],
        "historical_results": {2015: 6, 2016: 5, 2019: 6, "2019_nov": 7, 2023: 5},
        "notable_internal_factions": ["urkullistas", "ortuzaristas"],
        "primary_constituencies": ["País Vasco"],
        "weakness_constituencies": ["resto del Estado"],
        "key_dates_calendar": ["Asamblea Nacional 2025-01-25"],
        "ideological_position": {"economic_axis": 1, "social_axis": -1},
    },
    {
        "id": "bildu",
        "name": "Euskal Herria Bildu",
        "short_name": "EH BILDU",
        "founded_year": 2012,
        "color": "#A8D03B",
        "ideology": ["independentismo vasco", "izquierda abertzale", "socialismo"],
        "current_leader_id": "arnaldo_otegi",
        "secretary_general": "Arnaldo Otegi",
        "vice_secretaries": ["Mertxe Aizpurua", "Pello Otxandiano"],
        "congress_seats": 6,
        "senate_seats": 1,
        "european_seats": 1,
        "regional_governments": [],
        "municipal_strongholds": ["Pamplona", "Tafalla"],
        "affiliated_youth_org": "Ernai",
        "last_congress_date": "2024-03-09",
        "polling_average_30d": 1.6,
        "polling_trend": "rising",
        "key_alliances": ["psoe (legislatura)", "erc", "bng"],
        "historical_results": {2015: 2, 2016: 2, 2019: 4, "2019_nov": 5, 2023: 6},
        "notable_internal_factions": ["sortu", "alternatiba", "eusko alkartasuna"],
        "primary_constituencies": ["País Vasco", "Navarra"],
        "weakness_constituencies": ["resto del Estado"],
        "key_dates_calendar": ["Congreso 2024-03-09"],
        "ideological_position": {"economic_axis": -6, "social_axis": -6},
    },
    {
        "id": "bng",
        "name": "Bloque Nacionalista Galego",
        "short_name": "BNG",
        "founded_year": 1982,
        "color": "#75B2DD",
        "ideology": ["nacionalismo galego", "izquierda", "socialismo"],
        "current_leader_id": "ana_ponton",
        "secretary_general": "Ana Pontón",
        "vice_secretaries": ["Néstor Rego", "Goretti Sanmartín"],
        "congress_seats": 1,
        "senate_seats": 0,
        "european_seats": 0,
        "regional_governments": [],
        "municipal_strongholds": ["Santiago de Compostela", "Pontevedra"],
        "affiliated_youth_org": "Galiza Nova",
        "last_congress_date": "2024-04-13",
        "polling_average_30d": 1.0,
        "polling_trend": "rising",
        "key_alliances": ["psoe (legislatura)", "erc", "bildu"],
        "historical_results": {2015: 0, 2016: 0, 2019: 1, "2019_nov": 1, 2023: 1},
        "notable_internal_factions": ["UPG", "Asambleas Abertas", "MGS"],
        "primary_constituencies": ["Galicia"],
        "weakness_constituencies": ["resto del Estado"],
        "key_dates_calendar": ["XVIII Asemblea Nacional 2024-04-13"],
        "ideological_position": {"economic_axis": -6, "social_axis": -5},
    },
    {
        "id": "cc",
        "name": "Coalición Canaria",
        "short_name": "CC",
        "founded_year": 1993,
        "color": "#FFD700",
        "ideology": ["nacionalismo canario", "centro", "regionalismo"],
        "current_leader_id": "fernando_clavijo",
        "secretary_general": "Fernando Clavijo",
        "vice_secretaries": ["Pablo Rodríguez", "Rosa Dávila"],
        "congress_seats": 1,
        "senate_seats": 0,
        "european_seats": 0,
        "regional_governments": ["Canarias"],
        "municipal_strongholds": ["La Laguna", "Tenerife"],
        "affiliated_youth_org": "Juventudes Canaristas",
        "last_congress_date": "2024-06-22",
        "polling_average_30d": 0.7,
        "polling_trend": "stable",
        "key_alliances": ["pp", "asg"],
        "historical_results": {2015: 1, 2016: 1, 2019: 2, "2019_nov": 2, 2023: 1},
        "notable_internal_factions": ["clavijistas", "tinerfeños", "majoreros"],
        "primary_constituencies": ["Canarias"],
        "weakness_constituencies": ["resto del Estado"],
        "key_dates_calendar": ["Congreso Nacional 2024-06-22"],
        "ideological_position": {"economic_axis": 2, "social_axis": 0},
    },
    {
        "id": "upn",
        "name": "Unión del Pueblo Navarro",
        "short_name": "UPN",
        "founded_year": 1979,
        "color": "#0080C0",
        "ideology": ["regionalismo navarro", "constitucionalismo", "centroderecha"],
        "current_leader_id": "javier_esparza",
        "secretary_general": "Javier Esparza",
        "vice_secretaries": ["Sergio Sayas", "Yolanda Ibáñez"],
        "congress_seats": 1,
        "senate_seats": 0,
        "european_seats": 0,
        "regional_governments": [],
        "municipal_strongholds": ["Pamplona (compartido)", "Tudela"],
        "affiliated_youth_org": "Nuevas Generaciones UPN",
        "last_congress_date": "2024-09-28",
        "polling_average_30d": 0.5,
        "polling_trend": "stable",
        "key_alliances": ["pp"],
        "historical_results": {2015: 2, 2016: 2, 2019: 2, "2019_nov": 2, 2023: 1},
        "notable_internal_factions": ["esparcistas", "sanzistas (escindidos)"],
        "primary_constituencies": ["Navarra"],
        "weakness_constituencies": ["resto del Estado"],
        "key_dates_calendar": ["XV Congreso 2024-09-28"],
        "ideological_position": {"economic_axis": 4, "social_axis": 3},
    },
]
