from __future__ import annotations

ACTORS: list[dict] = [
    {
        "id": "pedro_sanchez",
        "name": "Pedro Sánchez",
        "full_name": "Pedro Sánchez Pérez-Castejón",
        "party": "psoe",
        "current_role": "Presidente del Gobierno de España",
        "previous_roles": ["Diputado por Madrid", "Secretario General PSOE", "Profesor universitario"],
        "age": 53,
        "region": "Madrid",
        "biography": "Economista y político español, líder del PSOE desde 2017 tras ganar las primarias internas. Presidente del Gobierno desde 2018, primero por moción de censura y posteriormente tras las elecciones de 2019 y 2023. Defensor de un giro progresista en política social y de la coalición con SUMAR. Su gestión ha estado marcada por la pandemia, la guerra de Ucrania y la ley de amnistía.",
        "key_positions": ["Defensa de la coalición progresista", "Ley de amnistía como herramienta de convivencia", "Refuerzo del Estado del bienestar", "Europeismo activo", "Memoria democrática"],
        "media_exposure": 98,
        "public_approval": -12,
        "trajectory": "stable",
        "social_handles": {"twitter": "@sanchezcastejon", "instagram": "@sanchezcastejon"},
        "key_dates": [{"date": "1972-02-29", "event": "Nacimiento"}, {"date": "2014-07-26", "event": "Elegido secretario general PSOE"}, {"date": "2018-06-01", "event": "Investidura tras moción de censura"}, {"date": "2023-11-16", "event": "Investidura segunda legislatura"}],
        "notable_quotes": ["No es no", "Manual de resistencia", "Hemos llegado para quedarnos"],
        "conflicts_of_interest": ["Caso Begoña Gómez (cónyuge)", "Caso David Sánchez (hermano)"],
        "allies": ["maria_jesus_montero", "felix_bolanos", "yolanda_diaz", "patxi_lopez"],
        "rivals": ["alberto_nunez_feijoo", "santiago_abascal", "isabel_diaz_ayuso"],
    },
    {
        "id": "yolanda_diaz",
        "name": "Yolanda Díaz",
        "full_name": "Yolanda Díaz Pérez",
        "party": "sumar",
        "current_role": "Vicepresidenta segunda y Ministra de Trabajo",
        "previous_roles": ["Diputada por A Coruña", "Coordinadora de Esquerda Unida Galicia", "Abogada laboralista"],
        "age": 53,
        "region": "Galicia",
        "biography": "Abogada laboralista gallega, líder de Sumar desde su fundación en 2023. Ministra de Trabajo desde 2020, impulsora de la reforma laboral y de la subida del SMI. Construyó un proyecto político post-Podemos con vocación de aglutinar el espacio a la izquierda del PSOE. Su capital político se erosionó tras los malos resultados europeos y autonómicos.",
        "key_positions": ["Reducción jornada laboral 37,5 horas", "Subida del SMI", "Derechos laborales reforzados", "Republicanismo", "Feminismo institucional"],
        "media_exposure": 78,
        "public_approval": -5,
        "trajectory": "declining",
        "social_handles": {"twitter": "@Yolanda_Diaz_", "instagram": "@yolandadiazsumar"},
        "key_dates": [{"date": "1971-05-06", "event": "Nacimiento en Fene"}, {"date": "2020-01-13", "event": "Ministra de Trabajo"}, {"date": "2023-04-02", "event": "Lanzamiento Sumar"}],
        "notable_quotes": ["Sumar es la nueva gramática del cambio", "El trabajo digno es la columna del país", "No somos rehenes de nadie"],
        "conflicts_of_interest": [],
        "allies": ["pedro_sanchez", "monica_garcia", "ernest_urtasun"],
        "rivals": ["ione_belarra", "alberto_nunez_feijoo", "santiago_abascal"],
    },
    {
        "id": "alberto_nunez_feijoo",
        "name": "Alberto Núñez Feijóo",
        "full_name": "Alberto Núñez Feijóo",
        "party": "pp",
        "current_role": "Líder de la oposición y senador por designación autonómica",
        "previous_roles": ["Presidente de la Xunta de Galicia (2009-2022)", "Secretario General de Sanidad", "Presidente del PP de Galicia"],
        "age": 64,
        "region": "Galicia",
        "biography": "Político y abogado gallego, presidente nacional del PP desde abril de 2022. Cuatro veces presidente de la Xunta con mayoría absoluta. Asumió el liderazgo del PP tras la crisis interna que apartó a Pablo Casado. Ganó las generales de 2023 en escaños pero fue incapaz de articular una mayoría de investidura. Estilo institucional moderado en contraste con figuras más confrontacionales del partido.",
        "key_positions": ["Bajada de impuestos", "Pacto de Estado por el agua", "Derogación de la ley de amnistía", "Reforma educativa", "Constitucionalismo"],
        "media_exposure": 88,
        "public_approval": -8,
        "trajectory": "stable",
        "social_handles": {"twitter": "@NunezFeijoo", "instagram": "@nunezfeijoo"},
        "key_dates": [{"date": "1961-09-10", "event": "Nacimiento"}, {"date": "2009-04-18", "event": "Investidura Xunta"}, {"date": "2022-04-02", "event": "Presidente del PP"}],
        "notable_quotes": ["Galicia es mi escuela", "España necesita un cambio sereno", "No vale todo en política"],
        "conflicts_of_interest": ["Polémica fotos con Marcial Dorado"],
        "allies": ["cuca_gamarra", "borja_semper", "esteban_gonzalez_pons", "juanma_moreno"],
        "rivals": ["pedro_sanchez", "santiago_abascal", "isabel_diaz_ayuso"],
    },
    {
        "id": "santiago_abascal",
        "name": "Santiago Abascal",
        "full_name": "Santiago Abascal Conde",
        "party": "vox",
        "current_role": "Presidente de Vox y diputado por Madrid",
        "previous_roles": ["Concejal del PP en Llodio", "Diputado autonómico Vasco", "Director de la Fundación DENAES"],
        "age": 49,
        "region": "País Vasco",
        "biography": "Político vasco fundador de Vox en 2013 tras abandonar el PP. Lidera el partido desde 2014 y lo ha llevado al Congreso, parlamento europeo y gobiernos autonómicos en coalición con el PP. Su perfil combina nacionalismo español, oposición frontal al independentismo y conservadurismo cultural. Mantiene relaciones internacionales con la derecha radical europea y latinoamericana.",
        "key_positions": ["Ilegalización partidos independentistas", "Suspensión Schengen", "Defensa de la familia tradicional", "Oposición al consenso climático", "Recentralización del Estado"],
        "media_exposure": 84,
        "public_approval": -22,
        "trajectory": "rising",
        "social_handles": {"twitter": "@Santi_ABASCAL", "instagram": "@santi_abascal"},
        "key_dates": [{"date": "1976-04-14", "event": "Nacimiento"}, {"date": "2013-12-17", "event": "Fundación Vox"}, {"date": "2019-04-28", "event": "Entrada al Congreso"}],
        "notable_quotes": ["Hacer España grande otra vez", "Reconquista democrática", "No nos representan"],
        "conflicts_of_interest": ["Escolta privada financiada por NIF Foundation"],
        "allies": ["jorge_buxade", "rocio_monasterio"],
        "rivals": ["pedro_sanchez", "yolanda_diaz", "alberto_nunez_feijoo", "carles_puigdemont"],
    },
    {
        "id": "isabel_diaz_ayuso",
        "name": "Isabel Díaz Ayuso",
        "full_name": "Isabel Natividad Díaz Ayuso",
        "party": "pp",
        "current_role": "Presidenta de la Comunidad de Madrid",
        "previous_roles": ["Diputada autonómica Madrid", "Viceconsejera de Presidencia", "Periodista"],
        "age": 46,
        "region": "Madrid",
        "biography": "Política madrileña, presidenta de la Comunidad de Madrid desde 2019 y reelegida con mayoría absoluta en 2023. Símbolo de un PP confrontacional con el gobierno central, defensora de bajada de impuestos y del modelo de libertad económica madrileño. Su perfil ha generado tensiones internas con la dirección nacional del PP. Implicada en la polémica de su pareja Alberto González Amador.",
        "key_positions": ["Bajada de impuestos en Madrid", "Libertad de elección educativa y sanitaria", "Oposición al gobierno central", "Defensa del español", "Hispanidad"],
        "media_exposure": 92,
        "public_approval": 4,
        "trajectory": "rising",
        "social_handles": {"twitter": "@IdiazAyuso", "instagram": "@isabel.diazayuso"},
        "key_dates": [{"date": "1978-10-17", "event": "Nacimiento"}, {"date": "2019-08-19", "event": "Investidura presidenta CM"}, {"date": "2023-05-28", "event": "Mayoría absoluta"}],
        "notable_quotes": ["Comunismo o libertad", "Me dejan en paz", "Madrid es la frontera"],
        "conflicts_of_interest": ["Caso González Amador (pareja)", "Caso ático Plaza España"],
        "allies": ["miguel_angel_rodriguez", "esperanza_aguirre"],
        "rivals": ["pedro_sanchez", "alberto_nunez_feijoo", "monica_garcia"],
    },
    {
        "id": "carles_puigdemont",
        "name": "Carles Puigdemont",
        "full_name": "Carles Puigdemont i Casamajó",
        "party": "junts",
        "current_role": "Presidente Junts per Catalunya, eurodiputado",
        "previous_roles": ["President de la Generalitat (2016-2017)", "Alcalde de Girona", "Periodista"],
        "age": 62,
        "region": "Cataluña",
        "biography": "Político catalán que lideró el referéndum del 1-O y la declaración de independencia de 2017. Huyó a Bélgica para evitar la justicia española y desde allí ha mantenido el liderazgo de Junts. Su rol fue decisivo en la investidura de Sánchez de 2023 a cambio de la ley de amnistía. Regresó a España en 2024 tras la aplicación parcial de la amnistía.",
        "key_positions": ["Independencia de Cataluña", "Amnistía total para presos del proces", "Negociación bilateral Estado-Generalitat", "Lengua catalana en la UE", "Republicanismo catalán"],
        "media_exposure": 75,
        "public_approval": -28,
        "trajectory": "declining",
        "social_handles": {"twitter": "@KRLS", "instagram": "@krlspuigdemont"},
        "key_dates": [{"date": "1962-12-29", "event": "Nacimiento"}, {"date": "2016-01-12", "event": "Investidura president"}, {"date": "2017-10-27", "event": "DUI"}, {"date": "2017-10-30", "event": "Huida a Bélgica"}],
        "notable_quotes": ["Hem guanyat", "La república catalana", "No renunciem"],
        "conflicts_of_interest": ["Procesado por desobediencia y malversación"],
        "allies": ["jordi_turull (sin perfil)", "miriam_nogueras (sin perfil)"],
        "rivals": ["pedro_sanchez", "alberto_nunez_feijoo", "salvador_illa", "santiago_abascal"],
    },
    {
        "id": "oriol_junqueras",
        "name": "Oriol Junqueras",
        "full_name": "Oriol Junqueras i Vies",
        "party": "erc",
        "current_role": "Presidente de ERC",
        "previous_roles": ["Vicepresident de la Generalitat (2016-2017)", "Eurodiputado", "Profesor de historia económica"],
        "age": 56,
        "region": "Cataluña",
        "biography": "Historiador económico y político catalán, líder de ERC desde 2011. Vicepresident con Puigdemont durante el proces, condenado a 13 años por sedición y malversación, indultado en 2021. Reconstruyó ERC desde la cárcel y mantuvo una línea de pragmatismo dentro del independentismo. Perdió la presidencia tras los malos resultados de las catalanas 2024.",
        "key_positions": ["Independencia de Cataluña vía referéndum", "Diálogo con el Estado", "Republicanismo", "Justicia social", "Ecologismo"],
        "media_exposure": 65,
        "public_approval": -18,
        "trajectory": "stable",
        "social_handles": {"twitter": "@junqueras", "instagram": "@oriol_junqueras"},
        "key_dates": [{"date": "1969-04-11", "event": "Nacimiento"}, {"date": "2011-09-17", "event": "Presidente ERC"}, {"date": "2019-10-14", "event": "Sentencia 13 años"}, {"date": "2021-06-22", "event": "Indulto"}],
        "notable_quotes": ["Ho tornarem a fer", "Llibertat presos polítics", "República catalana"],
        "conflicts_of_interest": ["Inhabilitado hasta 2031"],
        "allies": ["pere_aragones", "gabriel_rufian"],
        "rivals": ["carles_puigdemont", "salvador_illa", "alberto_nunez_feijoo"],
    },
    {
        "id": "pablo_iglesias",
        "name": "Pablo Iglesias",
        "full_name": "Pablo Iglesias Turrión",
        "party": "podemos",
        "current_role": "Politólogo, comentarista y profesor",
        "previous_roles": ["Vicepresidente segundo del Gobierno (2020-2021)", "Líder de Podemos (2014-2021)", "Eurodiputado"],
        "age": 47,
        "region": "Madrid",
        "biography": "Politólogo madrileño, fundador de Podemos en 2014 tras el 15M y exvicepresidente del Gobierno. Abandonó la política institucional en 2021 tras la derrota en las autonómicas madrileñas frente a Ayuso. Mantiene influencia mediática con su programa La Base y como ideólogo del espacio. Mantiene tensión con Sumar y especialmente con Yolanda Díaz.",
        "key_positions": ["Republicanismo", "Reforma constitucional", "Crítica a la oligarquía mediática", "Memoria democrática", "Soberanía energética"],
        "media_exposure": 80,
        "public_approval": -32,
        "trajectory": "stable",
        "social_handles": {"twitter": "@PabloIglesias", "instagram": "@iglesiasturrion"},
        "key_dates": [{"date": "1978-10-17", "event": "Nacimiento"}, {"date": "2014-01-17", "event": "Lanzamiento Podemos"}, {"date": "2020-01-13", "event": "Vicepresidente"}, {"date": "2021-05-04", "event": "Adiós política"}],
        "notable_quotes": ["Sí se puede", "Asalto a los cielos", "La casta"],
        "conflicts_of_interest": ["Caso Niñera (sobreseído)"],
        "allies": ["ione_belarra", "irene_montero"],
        "rivals": ["yolanda_diaz", "isabel_diaz_ayuso", "alberto_nunez_feijoo"],
    },
    {
        "id": "ione_belarra",
        "name": "Ione Belarra",
        "full_name": "Ione Belarra Urteaga",
        "party": "podemos",
        "current_role": "Secretaria General de Podemos, diputada por Navarra",
        "previous_roles": ["Ministra de Derechos Sociales (2021-2023)", "Secretaria de Estado Agenda 2030"],
        "age": 36,
        "region": "Navarra",
        "biography": "Politóloga navarra, secretaria general de Podemos desde 2021 tras la salida de Iglesias. Ministra durante la primera legislatura de coalición, impulsora de la ley de Vivienda y la Ley de Familias. Lidera la línea de máxima ruptura con Sumar y la confrontación frontal con la OTAN y con Israel.",
        "key_positions": ["Ruptura con la OTAN", "Sanciones a Israel", "Defensa Ley Vivienda", "Renta básica", "Prohibición de fondos buitre"],
        "media_exposure": 68,
        "public_approval": -28,
        "trajectory": "declining",
        "social_handles": {"twitter": "@ionebelarra", "instagram": "@ionebelarra"},
        "key_dates": [{"date": "1987-09-25", "event": "Nacimiento Pamplona"}, {"date": "2021-06-13", "event": "Secretaria general Podemos"}],
        "notable_quotes": ["Genocidio en Gaza", "Frente patriótico oligárquico", "Resistir contra el ruido mediático"],
        "conflicts_of_interest": [],
        "allies": ["irene_montero", "pablo_iglesias"],
        "rivals": ["yolanda_diaz", "pedro_sanchez", "alberto_nunez_feijoo"],
    },
    {
        "id": "cuca_gamarra",
        "name": "Cuca Gamarra",
        "full_name": "María del Carmen Gamarra Ruiz-Clavijo",
        "party": "pp",
        "current_role": "Secretaria General del PP, diputada por La Rioja",
        "previous_roles": ["Alcaldesa de Logroño (2011-2019)", "Portavoz PP en el Congreso"],
        "age": 50,
        "region": "La Rioja",
        "biography": "Abogada riojana, secretaria general del PP desde 2022. Persona de máxima confianza de Feijóo en la dirección nacional. Su perfil moderado contrasta con sectores más duros del partido. Ha sido la voz institucional del PP en la oposición durante la legislatura.",
        "key_positions": ["Reforma fiscal con bajada de impuestos", "Pacto de Estado por el agua", "Derogación ley amnistía", "Reforma educativa con asignaturas obligatorias", "Modernización administración"],
        "media_exposure": 60,
        "public_approval": -10,
        "trajectory": "stable",
        "social_handles": {"twitter": "@cucagamarra", "instagram": "@cucagamarra"},
        "key_dates": [{"date": "1974-08-13", "event": "Nacimiento"}, {"date": "2011-06-11", "event": "Alcaldesa Logroño"}, {"date": "2022-04-02", "event": "Secretaria general PP"}],
        "notable_quotes": ["España necesita serenidad", "El PP es el dique frente al sanchismo", "Volver a la moderación"],
        "conflicts_of_interest": [],
        "allies": ["alberto_nunez_feijoo", "borja_semper", "esteban_gonzalez_pons"],
        "rivals": ["pedro_sanchez", "santiago_abascal", "maria_jesus_montero"],
    },
    {
        "id": "maria_jesus_montero",
        "name": "María Jesús Montero",
        "full_name": "María Jesús Montero Cuadrado",
        "party": "psoe",
        "current_role": "Vicepresidenta primera y Ministra de Hacienda",
        "previous_roles": ["Consejera de Hacienda Junta de Andalucía (2013-2018)", "Diputada"],
        "age": 58,
        "region": "Andalucía",
        "biography": "Médica y política sevillana, ministra de Hacienda desde 2018 y vicepresidenta primera desde 2024. Vicesecretaria general del PSOE y candidata a la Junta de Andalucía. Diseñó el sistema de transferencias autonómicas y los presupuestos durante toda la era Sánchez. Su carácter directo la convierte en habitual antagonista en el Congreso.",
        "key_positions": ["Reforma fiscal progresiva", "Defensa modelo autonómico solidario", "Impuesto a banca y eléctricas", "Subida pensiones IPC", "Lucha contra paraísos fiscales"],
        "media_exposure": 70,
        "public_approval": -8,
        "trajectory": "stable",
        "social_handles": {"twitter": "@MJMonteroCuadra", "instagram": "@mjmonterocuadrado"},
        "key_dates": [{"date": "1966-12-09", "event": "Nacimiento Sevilla"}, {"date": "2018-06-07", "event": "Ministra Hacienda"}, {"date": "2024-12-03", "event": "Candidata Junta Andalucía"}],
        "notable_quotes": ["Quien tenga más, que aporte más", "Andalucía no es de nadie, es de todos", "Hablar con datos"],
        "conflicts_of_interest": [],
        "allies": ["pedro_sanchez", "felix_bolanos", "patxi_lopez", "juan_espadas"],
        "rivals": ["juanma_moreno", "alberto_nunez_feijoo", "cuca_gamarra"],
    },
    {
        "id": "felix_bolanos",
        "name": "Félix Bolaños",
        "full_name": "Félix Bolaños García",
        "party": "psoe",
        "current_role": "Ministro de la Presidencia, Justicia y Relaciones con las Cortes",
        "previous_roles": ["Secretario General de la Presidencia", "Abogado del Estado"],
        "age": 49,
        "region": "Madrid",
        "biography": "Abogado del Estado y político madrileño, ministro desde 2021 y mano derecha de Sánchez en la negociación parlamentaria. Pieza clave en la investidura de 2023 y el acuerdo con Junts y ERC. Conduce las relaciones con el CGPJ y la reforma del poder judicial.",
        "key_positions": ["Reforma del CGPJ", "Defensa amnistía", "Memoria democrática", "Reforma pacto de Estado contra violencia género", "Coordinación Cortes-Gobierno"],
        "media_exposure": 72,
        "public_approval": -10,
        "trajectory": "stable",
        "social_handles": {"twitter": "@bolanos_psoe", "instagram": "@felixbolanos"},
        "key_dates": [{"date": "1975-12-10", "event": "Nacimiento Madrid"}, {"date": "2021-07-12", "event": "Ministro"}],
        "notable_quotes": ["La amnistía es un instrumento de convivencia", "España es plural por construcción", "El diálogo siempre"],
        "conflicts_of_interest": [],
        "allies": ["pedro_sanchez", "maria_jesus_montero", "patxi_lopez"],
        "rivals": ["alberto_nunez_feijoo", "santiago_abascal", "isabel_diaz_ayuso"],
    },
    {
        "id": "patxi_lopez",
        "name": "Patxi López",
        "full_name": "Francisco Javier López Álvarez",
        "party": "psoe",
        "current_role": "Portavoz del PSOE en el Congreso",
        "previous_roles": ["Lehendakari del País Vasco (2009-2012)", "Presidente del Congreso (2016)", "Secretario de Política Federal PSOE"],
        "age": 65,
        "region": "País Vasco",
        "biography": "Político vasco, único lehendakari no nacionalista de la historia del País Vasco. Hombre de máxima confianza de Sánchez, portavoz parlamentario y figura clave en la mediación interna del PSOE. Su perfil dialogante lo convierte en interlocutor con todos los grupos.",
        "key_positions": ["Diálogo institucional", "Memoria democrática", "Modelo federalista", "Pacto educativo", "Convivencia plural"],
        "media_exposure": 58,
        "public_approval": -6,
        "trajectory": "stable",
        "social_handles": {"twitter": "@patxilopez", "instagram": "@patxilopezpsoe"},
        "key_dates": [{"date": "1959-10-03", "event": "Nacimiento Portugalete"}, {"date": "2009-05-07", "event": "Lehendakari"}, {"date": "2016-01-13", "event": "Presidente Congreso"}],
        "notable_quotes": ["España es la suma de identidades", "El diálogo desactiva el odio", "PSOE es socialdemocracia útil"],
        "conflicts_of_interest": [],
        "allies": ["pedro_sanchez", "felix_bolanos", "maria_jesus_montero"],
        "rivals": ["alberto_nunez_feijoo", "santiago_abascal", "ione_belarra"],
    },
    {
        "id": "esperanza_aguirre",
        "name": "Esperanza Aguirre",
        "full_name": "Esperanza Aguirre y Gil de Biedma",
        "party": "pp",
        "current_role": "Presidenta honorífica del PP de Madrid (retirada institucional)",
        "previous_roles": ["Presidenta de la Comunidad de Madrid (2003-2012)", "Ministra de Educación", "Presidenta del Senado"],
        "age": 73,
        "region": "Madrid",
        "biography": "Aristócrata y política madrileña, figura emblemática del PP de finales de los 2000. Tres veces presidenta de la Comunidad de Madrid. Dimitió en 2016 por el caso Púnica y se retiró tras imputaciones por la financiación irregular del PP madrileño. Mantiene voz en redes y como referente del ala liberal-conservadora.",
        "key_positions": ["Liberalismo económico", "Privatización servicios públicos", "Constitucionalismo radical", "Anticomunismo", "Defensa monarquía parlamentaria"],
        "media_exposure": 50,
        "public_approval": -25,
        "trajectory": "declining",
        "social_handles": {"twitter": "@EsperanzAguirre", "instagram": ""},
        "key_dates": [{"date": "1952-01-03", "event": "Nacimiento Madrid"}, {"date": "2003-11-21", "event": "Presidenta Comunidad de Madrid"}, {"date": "2016-04-25", "event": "Dimisión por Púnica"}],
        "notable_quotes": ["Yo lo dije", "Madrid es España y España es Madrid", "El liberalismo es libertad"],
        "conflicts_of_interest": ["Caso Púnica (imputada)", "Caso Lezo"],
        "allies": ["isabel_diaz_ayuso", "miguel_angel_rodriguez"],
        "rivals": ["pedro_sanchez", "ione_belarra", "yolanda_diaz"],
    },
    {
        "id": "pablo_casado",
        "name": "Pablo Casado",
        "full_name": "Pablo Casado Blanco",
        "party": "pp",
        "current_role": "Sin cargo público, sector privado",
        "previous_roles": ["Presidente del PP (2018-2022)", "Diputado por Ávila", "Vicesecretario de Comunicación PP"],
        "age": 44,
        "region": "Castilla y León",
        "biography": "Abogado y político castellano, presidió el PP entre 2018 y 2022 cuando fue defenestrado por el enfrentamiento con Ayuso por el caso de su hermano. Defensor de un PP más ideológico y menos contemporizador. Tras dejar la política activa se incorporó al sector privado en consultoría internacional.",
        "key_positions": ["Liberalismo económico", "Constitucionalismo", "Patriotismo español", "Ortodoxia popular europea", "Pacto Atlántico"],
        "media_exposure": 30,
        "public_approval": -20,
        "trajectory": "declining",
        "social_handles": {"twitter": "@pablocasado_", "instagram": "@pablocasadob"},
        "key_dates": [{"date": "1981-02-01", "event": "Nacimiento Palencia"}, {"date": "2018-07-21", "event": "Presidente del PP"}, {"date": "2022-04-02", "event": "Salida tras Genova vs Ayuso"}],
        "notable_quotes": ["España suma", "El PP es la casa común del centroderecha", "Política sin trincheras"],
        "conflicts_of_interest": [],
        "allies": ["jose_maria_aznar"],
        "rivals": ["isabel_diaz_ayuso", "pedro_sanchez", "santiago_abascal"],
    },
    {
        "id": "jose_maria_aznar",
        "name": "José María Aznar",
        "full_name": "José María Aznar López",
        "party": "pp",
        "current_role": "Presidente de FAES, expresidente del Gobierno",
        "previous_roles": ["Presidente del Gobierno (1996-2004)", "Presidente del PP (1990-2003)", "Presidente Junta de Castilla y León"],
        "age": 73,
        "region": "Madrid",
        "biography": "Político e inspector de Hacienda, dos veces presidente del Gobierno con mayoría absoluta en su segunda legislatura. Su mandato estuvo marcado por la apertura económica, la entrada al euro y la guerra de Irak. Desde su retirada lidera FAES como think tank ideológico del PP. Voz crítica con la línea más moderada del actual PP.",
        "key_positions": ["Atlantismo", "Liberalismo económico", "Defensa de la unidad nacional", "Memoria de la Transición", "OTAN-EEUU como ejes"],
        "media_exposure": 55,
        "public_approval": -30,
        "trajectory": "stable",
        "social_handles": {"twitter": "@JMAznar", "instagram": ""},
        "key_dates": [{"date": "1953-02-25", "event": "Nacimiento Madrid"}, {"date": "1996-05-04", "event": "Investidura"}, {"date": "2000-04-26", "event": "Mayoría absoluta"}, {"date": "2004-04-17", "event": "Salida tras 11M"}],
        "notable_quotes": ["España va bien", "Que se jodan", "Yo nunca tuve una crisis"],
        "conflicts_of_interest": ["Caso Gürtel (testimonio)", "Iraq weapons of mass destruction"],
        "allies": ["pablo_casado", "isabel_diaz_ayuso"],
        "rivals": ["pedro_sanchez", "felipe_gonzalez (rivalidad histórica)"],
    },
    {
        "id": "felipe_gonzalez",
        "name": "Felipe González",
        "full_name": "Felipe González Márquez",
        "party": "psoe",
        "current_role": "Expresidente del Gobierno, comentarista",
        "previous_roles": ["Presidente del Gobierno (1982-1996)", "Secretario General PSOE (1974-1997)"],
        "age": 83,
        "region": "Andalucía",
        "biography": "Abogado sevillano, líder histórico del PSOE durante la Transición y presidente del Gobierno cuatro legislaturas. Modernizó España, ingresó en la CEE y la OTAN. Su mandato terminó marcado por los GAL y los casos de corrupción. Desde su retirada mantiene una voz crítica con el sanchismo y el rumbo del PSOE actual.",
        "key_positions": ["Atlantismo", "Modernización europea", "Estado de bienestar moderno", "Constitucionalismo", "Crítica a alianzas con independentistas"],
        "media_exposure": 50,
        "public_approval": -8,
        "trajectory": "stable",
        "social_handles": {"twitter": "", "instagram": ""},
        "key_dates": [{"date": "1942-03-05", "event": "Nacimiento Sevilla"}, {"date": "1982-10-28", "event": "Mayoría absoluta histórica"}, {"date": "1986-03-12", "event": "Referéndum OTAN"}],
        "notable_quotes": ["Cien años de honradez", "El que se mueva no sale en la foto", "Por el cambio"],
        "conflicts_of_interest": ["Caso GAL (no imputado)", "Asesoramientos privados"],
        "allies": ["alfonso_guerra (histórico)"],
        "rivals": ["jose_maria_aznar", "pedro_sanchez (público)"],
    },
    {
        "id": "mariano_rajoy",
        "name": "Mariano Rajoy",
        "full_name": "Mariano Rajoy Brey",
        "party": "pp",
        "current_role": "Expresidente del Gobierno, registrador de la propiedad",
        "previous_roles": ["Presidente del Gobierno (2011-2018)", "Presidente PP (2004-2018)", "Vicepresidente del Gobierno"],
        "age": 70,
        "region": "Galicia",
        "biography": "Registrador y político gallego, presidente del Gobierno desde 2011 hasta su salida tras la primera moción de censura de la democracia. Su mandato estuvo marcado por la crisis económica, la corrupción del PP en el caso Gürtel y la aplicación del 155 en Cataluña. Tras la política se reincorporó a su plaza de registrador.",
        "key_positions": ["Estabilidad institucional", "Reforma laboral 2012", "Aplicación 155 Cataluña", "Austeridad fiscal", "Constitucionalismo"],
        "media_exposure": 35,
        "public_approval": -15,
        "trajectory": "stable",
        "social_handles": {"twitter": "@marianorajoy", "instagram": "@mariano_rajoy"},
        "key_dates": [{"date": "1955-03-27", "event": "Nacimiento Santiago"}, {"date": "2011-12-21", "event": "Investidura"}, {"date": "2018-06-01", "event": "Moción censura"}],
        "notable_quotes": ["España es una gran nación", "Las cosas no son como son sino como deben ser", "Cuanto peor, mejor para todos"],
        "conflicts_of_interest": ["Caso Gürtel (testigo)"],
        "allies": ["alberto_nunez_feijoo"],
        "rivals": ["pedro_sanchez"],
    },
    {
        "id": "salvador_illa",
        "name": "Salvador Illa",
        "full_name": "Salvador Illa Roca",
        "party": "psoe",
        "current_role": "President de la Generalitat de Catalunya",
        "previous_roles": ["Ministro de Sanidad (2020-2021)", "Líder del PSC", "Alcalde de La Roca del Vallès"],
        "age": 59,
        "region": "Cataluña",
        "biography": "Filósofo y político catalán, líder del PSC, ministro de Sanidad durante la pandemia. Ganó las elecciones catalanas de 2024 y fue investido president, rompiendo más de una década de hegemonía independentista. Su perfil tecnocrático y dialogante busca tender puentes con todos los sectores.",
        "key_positions": ["Catalanismo no independentista", "Diálogo Estado-Generalitat", "Modernización servicios públicos", "Reindustrialización Cataluña", "Lengua catalana protegida"],
        "media_exposure": 75,
        "public_approval": 8,
        "trajectory": "rising",
        "social_handles": {"twitter": "@salvadorilla", "instagram": "@salvadorilla"},
        "key_dates": [{"date": "1966-05-25", "event": "Nacimiento La Roca"}, {"date": "2020-01-13", "event": "Ministro Sanidad"}, {"date": "2024-05-12", "event": "Victoria 12M"}, {"date": "2024-08-08", "event": "Investidura president"}],
        "notable_quotes": ["Catalunya és el meu país", "Servir abans que parlar", "Reconnectar Catalunya"],
        "conflicts_of_interest": [],
        "allies": ["pedro_sanchez", "felix_bolanos", "patxi_lopez"],
        "rivals": ["carles_puigdemont", "oriol_junqueras", "alberto_nunez_feijoo"],
    },
    {
        "id": "pere_aragones",
        "name": "Pere Aragonès",
        "full_name": "Pere Aragonès i Garcia",
        "party": "erc",
        "current_role": "Expresident de la Generalitat (retirado)",
        "previous_roles": ["President de la Generalitat (2021-2024)", "Vicepresident", "Conseller d'Economia"],
        "age": 42,
        "region": "Cataluña",
        "biography": "Economista y abogado catalán, president de la Generalitat entre 2021 y 2024. Lideró la mesa de diálogo con el Estado y los indultos del proces. Tras su derrota en las elecciones del 12M anunció su retirada de la política activa. Apostó por una vía pragmática del independentismo basada en el consenso.",
        "key_positions": ["Diálogo Estado-Generalitat", "Acuerdo de claridad", "Republicanismo", "Justicia social", "Lengua catalana"],
        "media_exposure": 45,
        "public_approval": -12,
        "trajectory": "declining",
        "social_handles": {"twitter": "@perearagones", "instagram": "@perearagonesgarcia"},
        "key_dates": [{"date": "1982-11-16", "event": "Nacimiento Pineda"}, {"date": "2021-05-21", "event": "Investidura"}, {"date": "2024-05-12", "event": "Derrota 12M"}],
        "notable_quotes": ["L'acord de claredat", "Desjudicialitzar el conflicte", "Independència és pau social"],
        "conflicts_of_interest": [],
        "allies": ["oriol_junqueras", "gabriel_rufian"],
        "rivals": ["carles_puigdemont", "salvador_illa", "alberto_nunez_feijoo"],
    },
    {
        "id": "andoni_ortuzar",
        "name": "Andoni Ortuzar",
        "full_name": "Andoni Ortuzar Arruabarrena",
        "party": "pnv",
        "current_role": "Presidente del EBB del PNV",
        "previous_roles": ["Director General de EITB", "Presidente del BBB del PNV"],
        "age": 63,
        "region": "País Vasco",
        "biography": "Periodista y político vasco, presidente del Euzkadi Buru Batzar (máximo órgano del PNV) desde 2013. Pieza clave en la política española como interlocutor habitual con todos los gobiernos centrales. Defiende el modelo concertado vasco y la profundización del autogobierno.",
        "key_positions": ["Profundización del autogobierno vasco", "Defensa del concierto económico", "Plurinacionalidad de España", "Estabilidad institucional", "Diálogo permanente"],
        "media_exposure": 50,
        "public_approval": 5,
        "trajectory": "stable",
        "social_handles": {"twitter": "@andoniortuzar", "instagram": ""},
        "key_dates": [{"date": "1962-08-21", "event": "Nacimiento Bilbao"}, {"date": "2013-02-02", "event": "Presidente EBB"}],
        "notable_quotes": ["Euskadi necesita estabilidad", "El autogobierno es proyecto", "Sin nosotros no hay mayoría"],
        "conflicts_of_interest": [],
        "allies": ["aitor_esteban", "imanol_pradales"],
        "rivals": ["santiago_abascal", "alberto_nunez_feijoo"],
    },
    {
        "id": "aitor_esteban",
        "name": "Aitor Esteban",
        "full_name": "Aitor Esteban Bravo",
        "party": "pnv",
        "current_role": "Portavoz del PNV en el Congreso",
        "previous_roles": ["Diputado por Bizkaia (2004-presente)", "Profesor universitario"],
        "age": 62,
        "region": "País Vasco",
        "biography": "Filólogo y político vasco, portavoz del PNV en el Congreso desde 2004 con interrupciones. Considerado uno de los mejores oradores parlamentarios. Pieza clave en las negociaciones de presupuestos e investiduras desde Aznar hasta Sánchez. Su estilo combina ironía, rigor y pragmatismo nacionalista.",
        "key_positions": ["Pragmatismo nacionalista", "Defensa pactos institucionales", "Profundización autogobierno", "Crítica al populismo", "Europeismo"],
        "media_exposure": 55,
        "public_approval": 0,
        "trajectory": "stable",
        "social_handles": {"twitter": "@AitorEsteban", "instagram": ""},
        "key_dates": [{"date": "1962-09-22", "event": "Nacimiento Bilbao"}, {"date": "2004-04-02", "event": "Diputado"}],
        "notable_quotes": ["No vamos a invadir nada", "Nuestro voto tiene precio: el autogobierno", "Discutamos sin gritarnos"],
        "conflicts_of_interest": [],
        "allies": ["andoni_ortuzar", "imanol_pradales"],
        "rivals": ["santiago_abascal", "mertxe_aizpurua"],
    },
    {
        "id": "mertxe_aizpurua",
        "name": "Mertxe Aizpurua",
        "full_name": "Mertxe Aizpurua Arsuaga",
        "party": "bildu",
        "current_role": "Portavoz EH Bildu en el Congreso",
        "previous_roles": ["Periodista en Egin y Gara", "Diputada por Gipuzkoa"],
        "age": 63,
        "region": "País Vasco",
        "biography": "Periodista y política vasca, portavoz de EH Bildu en el Congreso desde 2019. Antigua redactora jefa de Gara, simboliza el desarrollo de la izquierda abertzale tras el final de ETA. Su trayectoria ha sido cuestionada por sus opiniones históricas sobre ETA pero también ha jugado un papel en la integración institucional.",
        "key_positions": ["Independencia vasca y Navarra", "Memoria histórica antifranquista", "Reparación todas las víctimas", "Derecho a decidir", "Justicia social"],
        "media_exposure": 50,
        "public_approval": -25,
        "trajectory": "rising",
        "social_handles": {"twitter": "@mertxeaizpurua", "instagram": ""},
        "key_dates": [{"date": "1962-02-13", "event": "Nacimiento Hernani"}, {"date": "2019-04-28", "event": "Diputada"}],
        "notable_quotes": ["Euskal Herria libre", "Conquistar derechos sociales", "No nos van a callar"],
        "conflicts_of_interest": ["Pasado en prensa pro-ETA"],
        "allies": ["arnaldo_otegi", "pello_otxandiano"],
        "rivals": ["andoni_ortuzar", "santiago_abascal"],
    },
    {
        "id": "nestor_rego",
        "name": "Néstor Rego",
        "full_name": "Néstor Rego Candamil",
        "party": "bng",
        "current_role": "Diputado del BNG en el Congreso",
        "previous_roles": ["Profesor de literatura gallega", "Diputado autonómico Galicia"],
        "age": 64,
        "region": "Galicia",
        "biography": "Filólogo y político gallego, único diputado del BNG en el Congreso. Voz solitaria pero clave en las negociaciones de investidura y presupuestos. Defiende activamente la lengua gallega y los intereses pesqueros e industriales de Galicia.",
        "key_positions": ["Soberanía nacional gallega", "Defensa del gallego", "Reindustrialización Galicia", "Sector pesquero protegido", "Justicia climática"],
        "media_exposure": 35,
        "public_approval": 2,
        "trajectory": "rising",
        "social_handles": {"twitter": "@nestor_rego", "instagram": ""},
        "key_dates": [{"date": "1961-04-23", "event": "Nacimiento Vimianzo"}, {"date": "2019-11-10", "event": "Diputado Congreso"}],
        "notable_quotes": ["Galiza primeiro", "Os intereses galegos non se negocian", "Soberanía xa"],
        "conflicts_of_interest": [],
        "allies": ["ana_ponton", "oriol_junqueras"],
        "rivals": ["alberto_nunez_feijoo", "santiago_abascal"],
    },
    {
        "id": "alberto_rodriguez",
        "name": "Alberto Rodríguez",
        "full_name": "Alberto Rodríguez Rodríguez",
        "party": "podemos",
        "current_role": "Activista, fuera de cargo institucional",
        "previous_roles": ["Diputado por Tenerife (2016-2021)", "Sindicalista"],
        "age": 43,
        "region": "Canarias",
        "biography": "Sindicalista canario y exdiputado de Podemos. Fue privado de su acta tras condena por desorden público en 2021, decisión polémica que reabrió el debate sobre los aforamientos. Mantiene presencia mediática como activista por causas sociales y canarias. Crítico con la deriva del espacio.",
        "key_positions": ["Justicia laboral", "Soberanía energética Canarias", "Desmilitarización OTAN", "Fin del aforamiento", "Solidaridad migrante"],
        "media_exposure": 25,
        "public_approval": -15,
        "trajectory": "declining",
        "social_handles": {"twitter": "@AlbertoRdgz_R", "instagram": "@albertordgzr"},
        "key_dates": [{"date": "1981-09-24", "event": "Nacimiento Tenerife"}, {"date": "2021-10-25", "event": "Pérdida acta"}],
        "notable_quotes": ["Canarias no es un parque temático", "El sistema me robó el acta", "Ni un paso atrás"],
        "conflicts_of_interest": ["Condenado por desorden público"],
        "allies": ["ione_belarra", "irene_montero"],
        "rivals": ["fernando_clavijo", "yolanda_diaz"],
    },
    {
        "id": "inigo_errejon",
        "name": "Iñigo Errejón",
        "full_name": "Iñigo Errejón Galván",
        "party": "sumar",
        "current_role": "Sin cargo público (dimitió 2024)",
        "previous_roles": ["Portavoz Sumar Congreso", "Líder Más País", "Cofundador Podemos"],
        "age": 41,
        "region": "Madrid",
        "biography": "Politólogo madrileño, cofundador de Podemos junto a Iglesias y posteriormente fundador de Más País. Fue portavoz de Sumar en el Congreso hasta su dimisión en octubre de 2024 tras denuncias de violencia machista. Su salida supuso un golpe simbólico para el espacio progresista. Investigación judicial abierta.",
        "key_positions": ["Verde nuevo trato", "Reforma democrática", "Salud mental como prioridad", "Feminismo (cuestionado)", "Republicanismo"],
        "media_exposure": 65,
        "public_approval": -45,
        "trajectory": "declining",
        "social_handles": {"twitter": "@ierrejon", "instagram": "@ierrejon"},
        "key_dates": [{"date": "1983-12-14", "event": "Nacimiento Madrid"}, {"date": "2014-01-17", "event": "Cofundación Podemos"}, {"date": "2019-01-17", "event": "Salida Más País"}, {"date": "2024-10-24", "event": "Dimisión por denuncias"}],
        "notable_quotes": ["Construir hegemonía", "Salud mental, urgencia política", "Pido perdón"],
        "conflicts_of_interest": ["Investigación violencia machista 2024"],
        "allies": [],
        "rivals": ["pablo_iglesias", "ione_belarra", "yolanda_diaz"],
    },
    {
        "id": "monica_garcia",
        "name": "Mónica García",
        "full_name": "Mónica García Gómez",
        "party": "sumar",
        "current_role": "Ministra de Sanidad",
        "previous_roles": ["Líder Más Madrid Asamblea (2021-2024)", "Médica anestesista"],
        "age": 50,
        "region": "Madrid",
        "biography": "Médica anestesista madrileña, ministra de Sanidad desde 2023. Lideró Más Madrid en la asamblea durante la presidencia de Ayuso, siendo voz crítica de la gestión sanitaria pandemica. Encarna el ala profesional y técnica de Sumar.",
        "key_positions": ["Refuerzo sanidad pública", "Lucha contra privatización", "Salud mental política de Estado", "Ley clases magistrales", "Atención primaria reforzada"],
        "media_exposure": 65,
        "public_approval": 5,
        "trajectory": "stable",
        "social_handles": {"twitter": "@Monica_Garcia_G", "instagram": "@monicagarciamasmadrid"},
        "key_dates": [{"date": "1974-08-12", "event": "Nacimiento Madrid"}, {"date": "2023-11-21", "event": "Ministra Sanidad"}],
        "notable_quotes": ["La sanidad pública no se vende", "Hagamos política con bata", "El sistema se rompe por arriba"],
        "conflicts_of_interest": [],
        "allies": ["yolanda_diaz", "ernest_urtasun"],
        "rivals": ["isabel_diaz_ayuso", "alberto_nunez_feijoo"],
    },
    {
        "id": "rocio_monasterio",
        "name": "Rocío Monasterio",
        "full_name": "Rocío Monasterio San Martín",
        "party": "vox",
        "current_role": "Diputada autonómica Madrid",
        "previous_roles": ["Líder Vox Madrid (2018-presente)", "Arquitecta"],
        "age": 51,
        "region": "Madrid",
        "biography": "Arquitecta cubano-española, líder de Vox en la Comunidad de Madrid. Cara visible del partido en el discurso anti-okupación, anti-inmigración y conservador social. Mantiene tensión política frecuente con Ayuso pese a compartir espacio ideológico.",
        "key_positions": ["Mano dura okupación", "Cierre fronteras", "Defensa familia tradicional", "Eliminación aborto a demanda", "Recentralización Estado"],
        "media_exposure": 60,
        "public_approval": -30,
        "trajectory": "stable",
        "social_handles": {"twitter": "@monasterioR", "instagram": "@rociomonasteriovox"},
        "key_dates": [{"date": "1974-04-27", "event": "Nacimiento La Habana"}, {"date": "2019-05-26", "event": "Diputada autonómica"}],
        "notable_quotes": ["Defensa fronteras es defensa España", "El globalismo nos arrasa", "Madrid no es Caracas"],
        "conflicts_of_interest": ["Polémica licencias urbanísticas"],
        "allies": ["santiago_abascal", "jorge_buxade"],
        "rivals": ["pedro_sanchez", "yolanda_diaz", "monica_garcia"],
    },
    {
        "id": "macarena_olona",
        "name": "Macarena Olona",
        "full_name": "Macarena Olona Choclán",
        "party": "vox",
        "current_role": "Sin cargo institucional, comentarista",
        "previous_roles": ["Diputada por Granada VOX (2019-2022)", "Candidata a Junta Andalucía 2022", "Abogada del Estado"],
        "age": 46,
        "region": "Andalucía",
        "biography": "Abogada del Estado y política, fue una de las voces más reconocibles de Vox hasta su salida en 2022 por motivos de salud y discrepancias internas. Candidata a la Junta de Andalucía en 2022. Tras su ruptura con Vox ha mantenido proyectos políticos efímeros y presencia mediática como crítica del partido.",
        "key_positions": ["Constitucionalismo radical", "Soberanía nacional", "Lucha contra trama mafiosa Estado", "Patriotismo cristiano", "Estado fuerte"],
        "media_exposure": 35,
        "public_approval": -35,
        "trajectory": "declining",
        "social_handles": {"twitter": "@MacarenaOlona", "instagram": "@macarenaolonaoficial"},
        "key_dates": [{"date": "1979-04-06", "event": "Nacimiento Alicante"}, {"date": "2019-04-28", "event": "Diputada"}, {"date": "2022-07-22", "event": "Salida de VOX"}],
        "notable_quotes": ["España no se rinde", "Soy patriota antes que política", "Han querido callarme"],
        "conflicts_of_interest": [],
        "allies": [],
        "rivals": ["santiago_abascal", "rocio_monasterio", "pedro_sanchez"],
    },
    {
        "id": "javier_maroto",
        "name": "Javier Maroto",
        "full_name": "Javier Maroto Aranzábal",
        "party": "pp",
        "current_role": "Senador por designación autonómica",
        "previous_roles": ["Vicesecretario General PP (2015-2022)", "Alcalde de Vitoria (2011-2015)", "Portavoz PP Senado"],
        "age": 52,
        "region": "País Vasco",
        "biography": "Político vasco, vicesecretario general del PP durante la era Casado y portavoz en el Senado. Actor visible en la batalla parlamentaria desde la mayoría absoluta del PP en la cámara alta. Referente del ala socialliberal del partido.",
        "key_positions": ["Pacto contra okupación", "Defensa autonomías", "Bilingüismo cooficial", "Liberalismo económico", "Constitucionalismo"],
        "media_exposure": 40,
        "public_approval": -10,
        "trajectory": "stable",
        "social_handles": {"twitter": "@JavierMaroto", "instagram": "@javiermaroto"},
        "key_dates": [{"date": "1972-12-09", "event": "Nacimiento Vitoria"}, {"date": "2011-06-11", "event": "Alcalde Vitoria"}],
        "notable_quotes": ["España necesita normalidad", "El PP es pluralidad", "Hablemos con respeto"],
        "conflicts_of_interest": [],
        "allies": ["alberto_nunez_feijoo", "cuca_gamarra"],
        "rivals": ["andoni_ortuzar", "pedro_sanchez"],
    },
    {
        "id": "borja_semper",
        "name": "Borja Sémper",
        "full_name": "Borja Sémper Pascual",
        "party": "pp",
        "current_role": "Portavoz Nacional del PP",
        "previous_roles": ["Presidente PP Gipuzkoa", "Diputado autonómico País Vasco"],
        "age": 47,
        "region": "País Vasco",
        "biography": "Político vasco, portavoz nacional del PP desde 2022. Vivió bajo escolta por amenazas de ETA. Su perfil dialogante y profundamente vasquista contrasta con sectores más confrontacionales. Voz pública del partido en debates mediáticos.",
        "key_positions": ["Vasquismo constitucional", "Pacto educativo", "Crítica al populismo", "Igualdad como valor liberal", "Memoria víctimas terrorismo"],
        "media_exposure": 55,
        "public_approval": 0,
        "trajectory": "rising",
        "social_handles": {"twitter": "@borjasemper", "instagram": "@borja.semper"},
        "key_dates": [{"date": "1976-10-16", "event": "Nacimiento Donostia"}, {"date": "2022-04-02", "event": "Portavoz nacional"}],
        "notable_quotes": ["Vasco y español", "Política con dignidad", "El centro no es tibieza"],
        "conflicts_of_interest": [],
        "allies": ["alberto_nunez_feijoo", "cuca_gamarra", "esteban_gonzalez_pons"],
        "rivals": ["santiago_abascal", "ione_belarra"],
    },
    {
        "id": "esteban_gonzalez_pons",
        "name": "Esteban González Pons",
        "full_name": "Esteban González Pons",
        "party": "pp",
        "current_role": "Vicesecretario Institucional del PP, eurodiputado",
        "previous_roles": ["Portavoz PP Eurocámara", "Diputado por Valencia"],
        "age": 60,
        "region": "Comunidad Valenciana",
        "biography": "Abogado y político valenciano, una de las figuras más experimentadas del PP en el ámbito europeo. Vicepresidente del Grupo Popular Europeo durante años. Ha asumido la vicesecretaría institucional con Feijóo, gestionando relaciones con instituciones del Estado.",
        "key_positions": ["Europeismo popular", "Constitucionalismo", "Defensa CGPJ", "Mediterraneo como prioridad", "Diálogo institucional"],
        "media_exposure": 45,
        "public_approval": -8,
        "trajectory": "stable",
        "social_handles": {"twitter": "@gonzalezpons", "instagram": "@gonzalezponspp"},
        "key_dates": [{"date": "1964-11-25", "event": "Nacimiento Valencia"}, {"date": "2014-07-01", "event": "Eurodiputado"}],
        "notable_quotes": ["Europa es la solución", "Sin instituciones no hay democracia", "El PP es Estado"],
        "conflicts_of_interest": [],
        "allies": ["alberto_nunez_feijoo", "cuca_gamarra", "borja_semper"],
        "rivals": ["pedro_sanchez", "santiago_abascal"],
    },
    {
        "id": "juan_espadas",
        "name": "Juan Espadas",
        "full_name": "Juan Espadas Cejas",
        "party": "psoe",
        "current_role": "Líder PSOE-A en el Senado",
        "previous_roles": ["Secretario general PSOE-A (2021-2025)", "Alcalde de Sevilla (2015-2021)"],
        "age": 58,
        "region": "Andalucía",
        "biography": "Ingeniero y político sevillano, lideró el PSOE-A entre 2021 y 2025 tras suceder a Susana Díaz. Sufrió la mayor derrota histórica del PSOE-A frente a Juanma Moreno en 2022. Ha dejado paso a María Jesús Montero como nueva candidata. Mantiene un papel relevante en el Senado.",
        "key_positions": ["Defensa servicios públicos", "Empleo verde", "Red Andalucía conectada", "Lucha despoblación", "Memoria democrática andaluza"],
        "media_exposure": 35,
        "public_approval": -12,
        "trajectory": "declining",
        "social_handles": {"twitter": "@juanespadasc", "instagram": "@juanespadasc"},
        "key_dates": [{"date": "1966-04-28", "event": "Nacimiento Sevilla"}, {"date": "2015-06-13", "event": "Alcalde Sevilla"}, {"date": "2022-06-19", "event": "Derrota Junta"}],
        "notable_quotes": ["Andalucía merece más", "El PSOE-A se reconstruye", "Servicios públicos primero"],
        "conflicts_of_interest": [],
        "allies": ["maria_jesus_montero", "pedro_sanchez"],
        "rivals": ["juanma_moreno", "alberto_nunez_feijoo"],
    },
    {
        "id": "juanma_moreno",
        "name": "Juanma Moreno",
        "full_name": "Juan Manuel Moreno Bonilla",
        "party": "pp",
        "current_role": "Presidente de la Junta de Andalucía",
        "previous_roles": ["Secretario de Estado de Servicios Sociales", "Presidente PP-A"],
        "age": 54,
        "region": "Andalucía",
        "biography": "Político malagueño, presidente de la Junta de Andalucía desde 2019 y reelegido con mayoría absoluta histórica en 2022. Su gestión, marcada por una imagen moderada y cercana, rompió 36 años de hegemonía socialista en Andalucía. Modelo de gobernanza que el PP nacional intenta replicar.",
        "key_positions": ["Bajada de impuestos en Andalucía", "Modernización servicios públicos", "Pacto del agua", "Inversión sanitaria", "Proximidad institucional"],
        "media_exposure": 65,
        "public_approval": 12,
        "trajectory": "rising",
        "social_handles": {"twitter": "@JuanMa_Moreno", "instagram": "@juanma_moreno_pp"},
        "key_dates": [{"date": "1970-05-01", "event": "Nacimiento Barcelona"}, {"date": "2019-01-16", "event": "Presidente Junta"}, {"date": "2022-06-19", "event": "Mayoría absoluta"}],
        "notable_quotes": ["Andalucía está de moda", "Gobernar para todos", "Centrismo útil"],
        "conflicts_of_interest": [],
        "allies": ["alberto_nunez_feijoo", "cuca_gamarra"],
        "rivals": ["maria_jesus_montero", "pedro_sanchez", "santiago_abascal"],
    },
    {
        "id": "carlos_mazon",
        "name": "Carlos Mazón",
        "full_name": "Carlos Mazón Guixot",
        "party": "pp",
        "current_role": "Presidente de la Generalitat Valenciana",
        "previous_roles": ["Presidente Diputación Alicante", "Líder PP-CV"],
        "age": 51,
        "region": "Comunidad Valenciana",
        "biography": "Abogado y político alicantino, presidente de la Generalitat Valenciana desde 2023 en coalición con Vox. Su gestión de la DANA de octubre de 2024 ha sido objeto de fuertes críticas y movilizaciones ciudadanas, con peticiones de dimisión. Investigación judicial abierta sobre la cadena de mando.",
        "key_positions": ["Trasvase Tajo-Segura", "Cooficialidad valenciano-castellano", "Bajada impuestos", "Apoyo agroindustria", "Pactos con Vox"],
        "media_exposure": 75,
        "public_approval": -42,
        "trajectory": "declining",
        "social_handles": {"twitter": "@carlos_mazon_", "instagram": "@carlosmazonpp"},
        "key_dates": [{"date": "1974-04-13", "event": "Nacimiento Alicante"}, {"date": "2023-07-19", "event": "Investidura"}, {"date": "2024-10-29", "event": "DANA Valencia"}],
        "notable_quotes": ["Cumplir y resistir", "Levantemos Valencia juntos", "Asumiré responsabilidades"],
        "conflicts_of_interest": ["DANA Valencia: investigación judicial", "Comida Cucú"],
        "allies": ["alberto_nunez_feijoo", "santiago_abascal"],
        "rivals": ["ximo_puig", "pedro_sanchez", "vicent_marza"],
    },
    {
        "id": "ximo_puig",
        "name": "Ximo Puig",
        "full_name": "Joaquín Francisco Puig Ferrer",
        "party": "psoe",
        "current_role": "Embajador permanente OCDE",
        "previous_roles": ["President de la Generalitat Valenciana (2015-2023)", "Líder PSPV-PSOE"],
        "age": 64,
        "region": "Comunidad Valenciana",
        "biography": "Periodista y político valenciano, expresident de la Generalitat Valenciana durante dos legislaturas en el Botànic. Tras su derrota en 2023 fue designado embajador permanente ante la OCDE. Su modelo de coalición tripartita es referente en el espacio progresista.",
        "key_positions": ["Botànic como modelo coalicional", "Refuerzo valenciano lengua", "Reindustrialización", "Política mediterránea", "Federalismo cooperativo"],
        "media_exposure": 30,
        "public_approval": -5,
        "trajectory": "stable",
        "social_handles": {"twitter": "@ximopuig", "instagram": "@ximopuig"},
        "key_dates": [{"date": "1959-09-21", "event": "Nacimiento Morella"}, {"date": "2015-06-29", "event": "Investidura"}, {"date": "2023-06-15", "event": "Salida Generalitat"}],
        "notable_quotes": ["Botànic és model", "El País Valencià necessita pont", "Diáleg és progrés"],
        "conflicts_of_interest": [],
        "allies": ["pedro_sanchez", "vicent_marza"],
        "rivals": ["carlos_mazon", "alberto_nunez_feijoo"],
    },
    {
        "id": "marga_prohens",
        "name": "Marga Prohens",
        "full_name": "Margalida Prohens Rigo",
        "party": "pp",
        "current_role": "Presidenta del Govern Balear",
        "previous_roles": ["Diputada autonómica Baleares", "Líder PP Baleares"],
        "age": 42,
        "region": "Baleares",
        "biography": "Filóloga y política mallorquina, presidenta del Govern Balear desde 2023 en gobierno PP con apoyo externo de Vox. Representa la nueva generación femenina del PP territorial. Su gestión está marcada por el debate de la masificación turística y la vivienda.",
        "key_positions": ["Gestión turística sostenible", "Vivienda asequible", "Cooficialidad catalán-castellano", "Apoyo agroganadería", "Defensa modelo balear"],
        "media_exposure": 45,
        "public_approval": 5,
        "trajectory": "rising",
        "social_handles": {"twitter": "@MargaProhens", "instagram": "@margaprohens"},
        "key_dates": [{"date": "1982-08-21", "event": "Nacimiento Felanitx"}, {"date": "2023-07-06", "event": "Investidura"}],
        "notable_quotes": ["Balears no es ven", "Turisme amb límits", "Servir des de la proximitat"],
        "conflicts_of_interest": [],
        "allies": ["alberto_nunez_feijoo", "cuca_gamarra"],
        "rivals": ["pedro_sanchez", "yolanda_diaz"],
    },
    {
        "id": "fernando_clavijo",
        "name": "Fernando Clavijo",
        "full_name": "Fernando Clavijo Batlle",
        "party": "cc",
        "current_role": "Presidente del Gobierno de Canarias",
        "previous_roles": ["Presidente Gobierno de Canarias (2015-2019)", "Alcalde de La Laguna", "Senador"],
        "age": 53,
        "region": "Canarias",
        "biography": "Empresario y político tinerfeño, presidente del Gobierno de Canarias por segunda vez desde 2023 en coalición con PP. Su gestión está marcada por la crisis migratoria y la repatriación de menores no acompañados. Voz visible del nacionalismo canario en el debate territorial.",
        "key_positions": ["REF y agenda canaria", "Gestión solidaria migración", "Soberanía energética isleña", "Lucha despoblamiento rural", "Bilingüismo institucional"],
        "media_exposure": 40,
        "public_approval": 3,
        "trajectory": "stable",
        "social_handles": {"twitter": "@FdoClavijoB", "instagram": "@fclavijob"},
        "key_dates": [{"date": "1971-08-15", "event": "Nacimiento Tenerife"}, {"date": "2015-07-09", "event": "Primera presidencia"}, {"date": "2023-07-12", "event": "Segunda presidencia"}],
        "notable_quotes": ["Canarias no puede sola", "El REF es supervivencia", "Solidaridad migrante"],
        "conflicts_of_interest": ["Caso Grúas (sobreseído)"],
        "allies": ["alberto_nunez_feijoo", "andoni_ortuzar"],
        "rivals": ["pedro_sanchez", "santiago_abascal"],
    },
    {
        "id": "vicent_marza",
        "name": "Vicent Marzà",
        "full_name": "Vicent Marzà Ibáñez",
        "party": "sumar",
        "current_role": "Diputado por Compromís en el Congreso",
        "previous_roles": ["Conseller d'Educació, Cultura i Esport (2015-2023)", "Activista cultural"],
        "age": 39,
        "region": "Comunidad Valenciana",
        "biography": "Filólogo y político castellonense, fue conseller en el Botànic durante 8 años. Diputado de Compromís dentro del grupo Sumar en el Congreso. Voz visible del valencianismo progresista. Crítico con el plurilingüismo recortado por el actual gobierno PP-Vox de Mazón.",
        "key_positions": ["Defensa lengua valenciana", "Educación pública valencianista", "Inversión cultural", "Memoria democrática", "Territorialidad equitativa"],
        "media_exposure": 30,
        "public_approval": 0,
        "trajectory": "stable",
        "social_handles": {"twitter": "@vicentmarza", "instagram": "@vicentmarza"},
        "key_dates": [{"date": "1985-12-14", "event": "Nacimiento Castelló"}, {"date": "2015-06-29", "event": "Conseller"}, {"date": "2023-07-23", "event": "Diputado Congreso"}],
        "notable_quotes": ["El valencià és vida", "Cultura accessible", "El Botànic continua"],
        "conflicts_of_interest": [],
        "allies": ["yolanda_diaz", "ximo_puig"],
        "rivals": ["carlos_mazon", "santiago_abascal"],
    },
    {
        "id": "gabriel_rufian",
        "name": "Gabriel Rufián",
        "full_name": "Gabriel Rufián Romero",
        "party": "erc",
        "current_role": "Portavoz ERC en el Congreso",
        "previous_roles": ["Diputado por Barcelona (2016-presente)"],
        "age": 42,
        "region": "Cataluña",
        "biography": "Politólogo nacido en Santa Coloma de Gramanet, voz mediática habitual de ERC en Madrid desde 2016. Sus intervenciones en el Congreso lo han convertido en uno de los oradores más virales. Defensor de un independentismo sociolingüísticamente plural y federalista.",
        "key_positions": ["Independencia con base social", "Defensa lenguas cooficiales en Madrid", "Justicia social como vía soberanía", "Crítica a la corrupción", "Memoria republicana"],
        "media_exposure": 75,
        "public_approval": -22,
        "trajectory": "stable",
        "social_handles": {"twitter": "@gabrielrufian", "instagram": "@gabrielrufian"},
        "key_dates": [{"date": "1982-10-14", "event": "Nacimiento Sant Cugat"}, {"date": "2016-01-13", "event": "Diputado"}],
        "notable_quotes": ["No estamos en Cuenca", "Volar puentes con educación", "Republicano y obrero"],
        "conflicts_of_interest": [],
        "allies": ["oriol_junqueras", "pere_aragones"],
        "rivals": ["carles_puigdemont", "santiago_abascal", "alberto_nunez_feijoo"],
    },
    {
        "id": "ana_ponton",
        "name": "Ana Pontón",
        "full_name": "Ana Pontón Mondelo",
        "party": "bng",
        "current_role": "Portavoz nacional del BNG, líder de la oposición Galicia",
        "previous_roles": ["Diputada Parlamento Galicia (2003-presente)"],
        "age": 47,
        "region": "Galicia",
        "biography": "Politóloga y política gallega, portavoz nacional del BNG desde 2016 ha conseguido revitalizar el partido. En las gallegas de 2024 logró el mejor resultado histórico del BNG con 25 escaños, asentándose como líder de la oposición. Voz feminista y soberanista referente.",
        "key_positions": ["Soberanía gallega", "Defensa lengua gallega", "Justicia climática", "Igualdad efectiva", "Reindustrialización con criterios sociales"],
        "media_exposure": 50,
        "public_approval": 8,
        "trajectory": "rising",
        "social_handles": {"twitter": "@ponton_ana", "instagram": "@anapontonbng"},
        "key_dates": [{"date": "1977-09-11", "event": "Nacimiento Sarria"}, {"date": "2016-02-21", "event": "Portavoz BNG"}, {"date": "2024-02-18", "event": "25 escaños histórico"}],
        "notable_quotes": ["Galiza, sempre", "A patria son as persoas", "Outra Galiza é posible"],
        "conflicts_of_interest": [],
        "allies": ["nestor_rego", "yolanda_diaz"],
        "rivals": ["alfonso_rueda", "alberto_nunez_feijoo"],
    },
    {
        "id": "alfonso_rueda",
        "name": "Alfonso Rueda",
        "full_name": "Alfonso Rueda Valenzuela",
        "party": "pp",
        "current_role": "Presidente da Xunta de Galicia",
        "previous_roles": ["Vicepresidente Xunta (2009-2022)", "Presidente Diputación Pontevedra"],
        "age": 56,
        "region": "Galicia",
        "biography": "Abogado y político pontevedrés, presidente de la Xunta desde 2022 tras la salida de Feijóo. Reválido la mayoría absoluta del PP gallego en 2024, siendo el único barón regional con esa fortaleza. Su perfil es continuidad institucional del feijooismo gallego.",
        "key_positions": ["Continuidad gestión feijooista", "Lucha despoblamiento rural Galicia", "Defensa lengua gallega cooficial", "Modernización servicios", "Hidrógeno verde y eólica marina"],
        "media_exposure": 45,
        "public_approval": 8,
        "trajectory": "stable",
        "social_handles": {"twitter": "@AlfonsoRuedaGal", "instagram": "@alfonsoruedavalenzuela"},
        "key_dates": [{"date": "1968-09-30", "event": "Nacimiento Pontevedra"}, {"date": "2022-05-14", "event": "Presidente Xunta"}, {"date": "2024-02-18", "event": "Mayoría absoluta"}],
        "notable_quotes": ["Galicia, valor seguro", "Servir desde la cercanía", "Estabilidade é progreso"],
        "conflicts_of_interest": [],
        "allies": ["alberto_nunez_feijoo"],
        "rivals": ["ana_ponton", "pedro_sanchez"],
    },
    {
        "id": "imanol_pradales",
        "name": "Imanol Pradales",
        "full_name": "Imanol Pradales Gil",
        "party": "pnv",
        "current_role": "Lehendakari del País Vasco",
        "previous_roles": ["Diputado foral Bizkaia", "Profesor universitario"],
        "age": 49,
        "region": "País Vasco",
        "biography": "Sociólogo y político vasco, lehendakari desde junio de 2024. Sustituyó a Iñigo Urkullu tras ganar las elecciones vascas de abril 2024. Lidera un gobierno de coalición PNV-PSE. Su perfil es de gestión técnica con énfasis en transición energética y industrial.",
        "key_positions": ["Profundización autogobierno", "Transición energética industrial", "Vivienda como derecho", "Defensa concierto económico", "Plurinacionalidad operativa"],
        "media_exposure": 50,
        "public_approval": 12,
        "trajectory": "rising",
        "social_handles": {"twitter": "@ipradales", "instagram": "@imanolpradalespnv"},
        "key_dates": [{"date": "1975-10-13", "event": "Nacimiento Santurtzi"}, {"date": "2024-06-22", "event": "Investidura lehendakari"}],
        "notable_quotes": ["Euskadi mira al futuro", "Industria y autogobierno", "Pacto largo, paz larga"],
        "conflicts_of_interest": [],
        "allies": ["andoni_ortuzar", "aitor_esteban"],
        "rivals": ["pello_otxandiano", "santiago_abascal"],
    },
    {
        "id": "pello_otxandiano",
        "name": "Pello Otxandiano",
        "full_name": "Pello Otxandiano Etxebarria",
        "party": "bildu",
        "current_role": "Líder EH Bildu Parlamento Vasco",
        "previous_roles": ["Investigador en política industrial", "Coordinador EH Bildu"],
        "age": 41,
        "region": "País Vasco",
        "biography": "Ingeniero y político vasco, candidato a lehendakari por EH Bildu en 2024. Liderazgo generacional que ha consolidado a la izquierda abertzale como segunda fuerza con 27 escaños. Su perfil técnico contrasta con los liderazgos clásicos de EH Bildu.",
        "key_positions": ["Independencia con justicia social", "Reindustrialización verde", "Vivienda como derecho", "Memoria todas las víctimas", "Soberanía energética"],
        "media_exposure": 50,
        "public_approval": 0,
        "trajectory": "rising",
        "social_handles": {"twitter": "@pellootxandiano", "instagram": "@pellootxandiano"},
        "key_dates": [{"date": "1983-04-13", "event": "Nacimiento Bilbao"}, {"date": "2024-04-21", "event": "Líder oposición vasca"}],
        "notable_quotes": ["Euskadi merece valentía", "Industria, lengua, soberanía", "Hablamos de futuro"],
        "conflicts_of_interest": [],
        "allies": ["arnaldo_otegi", "mertxe_aizpurua"],
        "rivals": ["imanol_pradales", "andoni_ortuzar", "santiago_abascal"],
    },
    {
        "id": "arnaldo_otegi",
        "name": "Arnaldo Otegi",
        "full_name": "Arnaldo Otegi Mondragón",
        "party": "bildu",
        "current_role": "Coordinador general EH Bildu",
        "previous_roles": ["Líder Sortu", "Diputado Parlamento Vasco", "Líder Batasuna (ilegalizado)"],
        "age": 67,
        "region": "País Vasco",
        "biography": "Líder histórico de la izquierda abertzale, condenado por militancia en ETA en los años 80 e indultado. Tras su salida de prisión en 2016 ha liderado la transformación pública de EH Bildu hacia la integración institucional. Figura controvertida pero clave en la pacificación vasca.",
        "key_positions": ["Independencia vía democrática", "Reparación todas las víctimas (incluida ETA)", "Justicia social", "Plurinacionalidad", "Memoria simétrica polémica"],
        "media_exposure": 60,
        "public_approval": -35,
        "trajectory": "stable",
        "social_handles": {"twitter": "@ArnaldoOtegi", "instagram": ""},
        "key_dates": [{"date": "1958-07-06", "event": "Nacimiento Elgoibar"}, {"date": "2009-10-13", "event": "Detención"}, {"date": "2016-03-01", "event": "Salida prisión"}],
        "notable_quotes": ["No habrá vuelta atrás", "Construimos república vasca", "Reparación a todas las víctimas"],
        "conflicts_of_interest": ["Condenas pasadas terrorismo"],
        "allies": ["mertxe_aizpurua", "pello_otxandiano"],
        "rivals": ["alberto_nunez_feijoo", "santiago_abascal", "andoni_ortuzar"],
    },
    {
        "id": "irene_montero",
        "name": "Irene Montero",
        "full_name": "Irene María Montero Gil",
        "party": "podemos",
        "current_role": "Eurodiputada Podemos",
        "previous_roles": ["Ministra de Igualdad (2020-2023)", "Portavoz Podemos Congreso"],
        "age": 37,
        "region": "Madrid",
        "biography": "Psicóloga y política madrileña, ministra de Igualdad en la primera coalición progresista. Impulsora de la ley del solo sí es sí, ley trans, y leyes feministas. Tras la salida del gobierno se incorporó al parlamento europeo. Símbolo del feminismo radical y a la vez de la polémica por las reducciones de condena.",
        "key_positions": ["Ley solo sí es sí (autocrítica)", "Ley trans", "Feminismo radical", "Anti racismo institucional", "Reducción jornada laboral"],
        "media_exposure": 70,
        "public_approval": -32,
        "trajectory": "stable",
        "social_handles": {"twitter": "@IreneMontero", "instagram": "@irenemonteropodemos"},
        "key_dates": [{"date": "1988-02-13", "event": "Nacimiento Madrid"}, {"date": "2020-01-13", "event": "Ministra Igualdad"}, {"date": "2024-06-09", "event": "Eurodiputada"}],
        "notable_quotes": ["Hermana yo sí te creo", "Es ley feminista", "Habrá pelea"],
        "conflicts_of_interest": [],
        "allies": ["ione_belarra", "pablo_iglesias"],
        "rivals": ["yolanda_diaz", "isabel_diaz_ayuso", "alberto_nunez_feijoo"],
    },
    {
        "id": "ernest_urtasun",
        "name": "Ernest Urtasun",
        "full_name": "Ernest Urtasun Domènech",
        "party": "sumar",
        "current_role": "Ministro de Cultura, Portavoz de Sumar",
        "previous_roles": ["Eurodiputado por Catalunya en Comú", "Portavoz Verdes Europeos"],
        "age": 42,
        "region": "Cataluña",
        "biography": "Economista catalán, ministro de Cultura desde 2023 y portavoz de Sumar. Vinculado históricamente a Iniciativa per Catalunya Verds y a los Verdes Europeos. Su gestión ha estado marcada por la polémica de revisar contenidos coloniales en museos públicos.",
        "key_positions": ["Revisión memoria colonial museos", "Cultura accesible", "Defensa industria audiovisual", "Lengua catalana en plataformas", "Democratización política cultural"],
        "media_exposure": 50,
        "public_approval": -10,
        "trajectory": "stable",
        "social_handles": {"twitter": "@ernesturtasun", "instagram": "@ernesturtasun"},
        "key_dates": [{"date": "1982-04-26", "event": "Nacimiento Barcelona"}, {"date": "2023-11-21", "event": "Ministro Cultura"}],
        "notable_quotes": ["Cultura como derecho", "Sin memoria no hay futuro", "Política valiente"],
        "conflicts_of_interest": [],
        "allies": ["yolanda_diaz", "monica_garcia"],
        "rivals": ["santiago_abascal", "isabel_diaz_ayuso"],
    },
    {
        "id": "miguel_angel_rodriguez",
        "name": "Miguel Ángel Rodríguez",
        "full_name": "Miguel Ángel Rodríguez Bajón",
        "party": "pp",
        "current_role": "Jefe de Gabinete de Isabel Díaz Ayuso",
        "previous_roles": ["Secretario de Estado de Comunicación con Aznar", "Asesor de comunicación"],
        "age": 64,
        "region": "Madrid",
        "biography": "Periodista y asesor político, jefe de gabinete de Ayuso desde 2019 y arquitecto de su comunicación. Veterano del PP desde la era Aznar. Su nombre ha aparecido en la polémica del caso González Amador por filtraciones a medios contra el fiscal general.",
        "key_positions": ["Comunicación política agresiva", "Estrategia narrativa de marca", "Defensa Ayuso", "Crítica feroz al gobierno", "Madrid como polo identitario"],
        "media_exposure": 45,
        "public_approval": -25,
        "trajectory": "stable",
        "social_handles": {"twitter": "@MARodriguezB", "instagram": ""},
        "key_dates": [{"date": "1960-10-05", "event": "Nacimiento Madrid"}, {"date": "2019-08-19", "event": "Jefe Gabinete CM"}],
        "notable_quotes": ["Comunicación es batalla", "Verdad y veracidad", "Son ataques personales"],
        "conflicts_of_interest": ["Investigación filtraciones a medios"],
        "allies": ["isabel_diaz_ayuso", "jose_maria_aznar"],
        "rivals": ["pedro_sanchez", "felix_bolanos"],
    },
    {
        "id": "jorge_buxade",
        "name": "Jorge Buxadé",
        "full_name": "Jorge Buxadé Villalba",
        "party": "vox",
        "current_role": "Vicepresidente Acción Política Vox, eurodiputado",
        "previous_roles": ["Abogado del Estado", "Líder Vox eurocámara"],
        "age": 49,
        "region": "Cataluña",
        "biography": "Abogado del Estado catalán, número dos efectivo de Vox. Líder ideológico del partido y del grupo Patriots for Europe en la Eurocámara. Voz dura del partido en el discurso anti-élites, anti-Pacto Verde y anti-inmigración. Tensiones internas con la línea más institucional.",
        "key_positions": ["Salida de la Agenda 2030", "Cierre fronteras y Schengen", "Reforma judicial", "Nacionalismo español", "Anti-globalismo"],
        "media_exposure": 55,
        "public_approval": -28,
        "trajectory": "rising",
        "social_handles": {"twitter": "@Jorgebuxade", "instagram": "@jorgebuxade"},
        "key_dates": [{"date": "1976-04-13", "event": "Nacimiento Barcelona"}, {"date": "2019-04-28", "event": "Diputado Vox"}, {"date": "2024-06-09", "event": "Eurodiputado"}],
        "notable_quotes": ["Reconquista política", "Globalismo es tiranía", "España viva"],
        "conflicts_of_interest": [],
        "allies": ["santiago_abascal", "rocio_monasterio"],
        "rivals": ["pedro_sanchez", "yolanda_diaz", "carles_puigdemont"],
    },
]
